Repository esphome/esphome-docs, pull requests merged in 2020-10, with the labels that each got.

#784 Remove bh7150 API reference
  components/sensor/bh1750.rst
Labels: Hacktoberfest, current

#786 Add 2.13in-ttgo-b73 to list of waveshare models
  components/display/waveshare_epaper.rst
Labels: Hacktoberfest, current

#787 Typo: connedted -> connected
  cookbook/h801.rst
Labels: Hacktoberfest, current

#785 Update edit URL on Sonoff Basic page
  devices/sonoff_basic.rst
Labels: Hacktoberfest, current

#783 Update Sonoff Mini
  devices/sonoff.rst
Labels: Hacktoberfest, current

#788 Set correct link to ESPColor struct
  components/light/index.rst
Labels: Hacktoberfest, current

#761 Add battery_level note for xiaomi_hhccjcy01
  components/sensor/xiaomi_ble.rst
Labels: current, has-parent

#789 Corrected the example pin mapping to GPIO mapping.
  devices/nodemcu_esp8266.rst
Labels: Hacktoberfest, current

#782 Add time.has_time documentation
  components/time.rst
  guides/automations.rst
Labels: has-parent, next, parent-merged

#802 Fix links, moved to gists
  cookbook/arduino_port_extender.rst
Labels: current

#795 Update wifi.rst
  components/wifi.rst
Labels: Hacktoberfest, current

#792 BME680 default address is 0x76
  components/sensor/bme680.rst
Labels: Hacktoberfest, current

#791 Individual BMXXXXX sensor configs are optional
  components/sensor/bme280.rst
  components/sensor/bme680.rst
  components/sensor/bmp085.rst
  components/sensor/bmp280.rst
Labels: Hacktoberfest, current

#811 Correct pull-up value
  components/sensor/dallas.rst
Labels: current

#817 1.15.3
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#821 add battery sensor for lywsd02
  components/sensor/xiaomi_ble.rst
Labels: Hacktoberfest, has-parent, next

#815 Small typo fixes for Sonoff T1 UK 3 Gang
  devices/images/sonoff_t1_uk_3g_backplate_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_touchpads_v1.1.jpg
  devices/sonoff_t1_uk_3gang_v1.1.rst
Labels: Hacktoberfest, current

#451 Added tmp102 Temperature sensor docs
  components/sensor/images/tmp102-full.jpg
  components/sensor/tmp102.rst
  images/tmp102.jpg
  index.rst
Labels: has-parent, integration: tmp102, next

#691 Add documentation for MCP9808 sensor
  components/sensor/images/mcp9808-full.jpg
  components/sensor/mcp9808.rst
  images/mcp9808.jpg
  index.rst
Labels: integration: mcp9808

#810 add rc522 docs
  components/binary_sensor/images/rc522-full.jpg
  components/binary_sensor/rc522.rst
  images/rc522.jpg
  index.rst
Labels: Hacktoberfest, has-parent, next

#798 Update PN532 docs to add I2C
  components/binary_sensor/pn532.rst
Labels: Hacktoberfest, has-parent, next
