Repository esphome/esphome-docs, pull requests merged in 2020-09, with the labels that each got.

#748 Update diy.rst
  guides/diy.rst
Labels: current

#734 Add carrier_frequency for IR device example
  components/remote_transmitter.rst
Labels: current

#749 Added Arlec Grid Connect Smart Plug
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
Labels: current

#756 Adds Tuya Climate temperature multiplier
  components/climate/tuya.rst
Labels: has-parent, next

#762 1.15.1
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  components/climate/tuya.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#760 Update diy.rst
  guides/diy.rst
Labels: next

#757 Update index.rst
  components/sensor/index.rst
Labels: current

#765 add custom uart id usage
  components/uart.rst
Labels: current, integration: uart

#763 Add docs for homeassistant.tag_scanned action
  components/api.rst
  components/binary_sensor/pn532.rst
  components/binary_sensor/rdm6300.rst
Labels: has-parent, next

#776 1.15.2
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  components/api.rst
  components/binary_sensor/pn532.rst
  components/binary_sensor/rdm6300.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
Labels: current, has-parent

#767 Mention CODEOWNERS magic symbol
  guides/contributing.rst
Labels: current

#747 using docker image to build esphome-docs locally
  guides/contributing.rst
Labels: current

#740 Add missing doc for rc_switch event
  components/remote_receiver.rst
Labels: current, has-parent

#752 Remove unneeded parameters
  components/esp32_ble_tracker.rst
Labels: current

#743 Enable color_interlock for the Teckin SB50 example
  cookbook/teckin_sb50.rst
Labels: current, has-parent

#754 clarify esp8266_restore_from_flash with restore_value
  guides/automations.rst
Labels: current

#732 Update mirabella-genio-bulb.rst
  cookbook/mirabella-genio-bulb.rst
Labels: current

#772 Fix APDS9960 datasheet link
  components/sensor/apds9960.rst
Labels: current

#771 Update uart.rst
  components/uart.rst
Labels: current

#773 Update index.rst
  components/display/index.rst
Labels: current

#726 update Max7219 digit with reverse option
  components/display/max7219digit.rst
Labels: has-parent, next

#769 HM3301 - Change type to calculation_type
  components/sensor/hm3301.rst
Labels: current

#781 Update diy.rst
  guides/diy.rst
Labels: current

#780 Update docker architectures in getting started
  guides/getting_started_command_line.rst
Labels: current
