Repository esphome/esphome-docs, pull requests merged in 2020-12, with the labels that each got.

#859 Update docs for Configurable OTA Safe Mode
  components/ota.rst
Labels: has-parent, next

#863 Update ethernet.rst
  components/ethernet.rst
Labels: current

#868 Documentation for tuya ignore_mcu_update_on_datapoints setting
  components/tuya.rst
Labels: has-parent, next

#864 scd30: Document temperature_offset setting
  components/sensor/scd30.rst
Labels: has-parent

#870 Ili9341 doc update
  changelog/v1.15.0.rst
  components/display/ili9341.rst
  components/display/images/ili9341-full.jpg
  images/ili9341.jpg
  index.rst
Labels: next

#613 MCP23S08-Docs
  components/mcp23Sxx.rst
  index.rst
Labels: has-parent, integration: mcp23Sxx

#883 Update max31856.rst
  components/sensor/max31856.rst
Labels: current

#881 Fix one of the commens in code block
  custom/custom_component.rst
Labels: current

#873 Update wifi.rst
  components/wifi.rst
Labels: current

#857 Update mirabella-genio-bulb.rst
  cookbook/mirabella-genio-bulb.rst
Labels: current

#878 Update teckin sb50 entry as they cannot be flashed anymore
  cookbook/teckin_sb50.rst
Labels: current

#860 Change all instances of travis to github actions
  guides/contributing.rst
Labels: current

#843 Improve obtaining bind key
  components/sensor/xiaomi_ble.rst
Labels: current

#770 Add clarification about "update_interval" to SDS011 sensor documentation
  components/sensor/sds011.rst
Labels: current

#805 Cookbook: Light Strip
  cookbook/images/infostrip-detail.jpg
  cookbook/images/infostrip-lights-ui.png
  cookbook/infostrip.rst
Labels: Hacktoberfest, current

#851 Add troubleshooting help with light partition
  components/light/partition.rst
Labels: current

#524 Update bang_bang.rst
  components/climate/bang_bang.rst
Labels: integration: bang_bang

#606 Fixed docs to match xiaomi rename
  components/esp32_ble_tracker.rst
Labels: integration: esp32_ble_tracker

#573 add another example without MQTT
  components/binary_sensor/pn532.rst
Labels: integration: pn532

#688 Show example of calling HA script
  components/api.rst
Labels: integration: api

#689 Update pulse_counter.rst
  components/sensor/pulse_counter.rst
Labels: integration: pulse_counter

#658 More descriptive information for noobs
  components/stepper/index.rst
Labels: integration: stepper

#885 esp32_dac.rst - Add light component to example
  components/output/esp32_dac.rst
Labels: current

#887 Update ethernet.rst
  components/ethernet.rst
Labels: current

#856 Adding gif animation docs
  components/display/index.rst
Labels: has-parent, next

#888 Update diy.rst
  guides/diy.rst
Labels: current

#891 Update diy.rst
  guides/diy.rst
Labels: current

#893 Update sim800l.rst
  components/sim800l.rst
Labels: current

#741 docs: necessary registration of node in HA
  components/sensor/homeassistant.rst
Labels: current

#759 display: st7789v: Set GPIO0 as INPUT_PULLUP
  components/display/st7789v.rst
Labels: current

#753 clarify VCC, wrt #1452
  components/sensor/adc.rst
Labels: current

#809 Update docs about MQTT lambdas
  components/mqtt.rst
Labels: Hacktoberfest, current

#816 Add manual for Sonoff T3 EU 3 Gang
  devices/images/sonoff_t3_eu_3g_back_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_backplate_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_plate_off_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_touchpads_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_uart_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_v1.0.jpg
  devices/sonoff.rst
  devices/sonoff_t3_eu_3gang_v1.0.rst
  devices/sonoff_t3_eu_3gang_v1.0.yaml
  images/sonoff_t3_eu_3g_v1.0.jpg
  index.rst
Labels: Hacktoberfest, current

#819 Add get_setup_priority() to Custom sensor docs
  components/sensor/custom.rst
Labels: Hacktoberfest, current

#867 Change on_message topics into a yaml list for deep_sleep docs
  components/deep_sleep.rst
Labels: current

#872 Update pzem Example configuration entry (bad stop bit)
  components/sensor/pzemac.rst
Labels: current, has-parent

#892 Update sonof_basic.rst - incorrect example
  devices/sonoff_basic.rst
Labels: current, in-progress

#895 Update apds9960.rst
  components/sensor/apds9960.rst
Labels: current

#823 Canbus + MCP2515
  components/canbus.rst
  components/images/canbus_mcp2515_resistor.png
  components/images/canbus_mcp2515_txs0108e.png
  images/canbus.svg
  index.rst
Labels: has-parent, next

#875 Add SSD1327 display docs
  components/display/images/ssd1327-full.jpg
  components/display/ssd1325.rst
  components/display/ssd1327.rst
  images/ssd1327.jpg
  index.rst
Labels: has-parent, next

#869 Add SSD1322 doc
  components/display/images/ssd1322-full.jpg
  components/display/ssd1322.rst
  images/ssd1322.jpg
  index.rst
Labels: has-parent, next
