Repository esphome/esphome-docs, pull requests merged in 2020-07, with the labels that each got.

#693 Add script modes and timers
  guides/automations.rst
Labels: has-parent, parent-merged

#706 Partially Revert make SPI CS pin optional
  components/binary_sensor/pn532.rst
  components/display/max7219.rst
  components/display/ssd1306.rst
  components/display/ssd1325.rst
  components/display/waveshare_epaper.rst
  components/sensor/atm90e32.rst
  components/sensor/max31855.rst
  components/sensor/max6675.rst
  components/spi.rst
Labels: integration: atm90e32, integration: max31855, integration: max6675, integration: max7219, integration: pn532, integration: spi, integration: ssd1306, integration: ssd1325, integration: waveshare_epaper

#700 add buzzer rtttl docs
  components/images/buzzer.jpg
  components/rtttl.rst
  images/buzzer.jpg
  index.rst
Labels: integration: rtttl, parent-merged

#710 fix merge: climate devices moved to climate-ir
  index.rst
Labels: next

#709 Revert "Dallas autosetup (#551)"
  components/sensor/dallas.rst
Labels: has-parent, in-progress, next

#667 Update bang_bang doc, changelog fix
  changelog/v1.15.0.rst
  components/climate/bang_bang.rst
  components/climate/thermostat.rst
Labels: integration: bang_bang, integration: thermostat

#713 New prometheus configuration
  components/prometheus.rst
  components/web_server.rst
  images/prometheus.svg
  index.rst
  svg2png/prometheus.png
Labels: has-parent, next

#714 ESP8266 change recommended framework version to 2.7.2
  components/esphome.rst
Labels: has-parent, next

#716 Fix old screenshots
  guides/getting_started_hassio.rst
  guides/images/dashboard.png
  guides/images/hassio_interface.png
  guides/images/hassio_start.png
Labels: next

#715 Add tuya platforms to changelog table
  changelog/v1.15.0.rst
Labels: next

#717 1.15.0b2
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  components/esphome.rst
  conf.py
  guides/getting_started_hassio.rst
  guides/images/dashboard.png
  guides/images/hassio_interface.png
  guides/images/hassio_start.png
Labels: beta, has-parent

#718 Include new v1.15 components from diff
  changelog/v1.15.0.rst
Labels: next

#720 Added hint that not the subsensor id is meant.
  components/sensor/tx20.rst
Labels: current

#722 1.15.0b3
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  components/sensor/tx20.rst
  conf.py
Labels: beta, has-parent

#719 Add hyphen to supported name characters
  components/esphome.rst
  components/sensor/tx20.rst
Labels: has-parent, next

#721 Update docs for community Hass.io add-ons
  guides/faq.rst
  guides/getting_started_hassio.rst
  guides/images/hassio_addon.png
  guides/images/hassio_repo.png
Labels: current
