Repository esphome/esphome-docs, pull requests merged in 2020-08, with the labels that each got.

#730 add image type
  components/display/index.rst
Labels: has-parent, next

#736 Update diy.rst
  guides/diy.rst
Labels: current

#735 Add a note about setting dns in manual ip mode
  components/time.rst
Labels: current

#737 Change example ota id
  components/ota.rst
Labels: current

#744 1.15.0b4
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  components/display/index.rst
  components/ota.rst
  components/time.rst
  conf.py
  cookbook/bme280_environment.rst
  guides/diy.rst
  guides/faq.rst
  guides/getting_started_hassio.rst
  guides/images/hassio_addon.png
  guides/images/hassio_repo.png
Labels: beta, has-parent

#746 Light triggers referenced in the "automation" guide.
  guides/automations.rst
Labels: next
