Repository esphome/esphome-docs, pull requests merged in 2021-04, with the labels that each got.

#1079 Add documentation for the display.is_displaying_page condition
  components/display/index.rst
  guides/automations.rst
Labels: has-parent, next

#793 Add BME680 BSEC docs
  components/sensor/bme680_bsec.rst
  components/sensor/images/bme680-bsec-ui.png
  index.rst
Labels: Hacktoberfest, has-parent, next

#1086 Adds docs for the b-parasite soil moisture sensor
  components/sensor/b_parasite.rst
  components/sensor/images/b_parasite.jpg
  images/b_parasite.jpg
  index.rst
Labels: has-parent, next

#985 sgp40
  components/sensor/images/sgp40.jpg
  components/sensor/sgp40.rst
  cookbook/iaq_board.rst
  images/sgp40.jpg
  index.rst
Labels: has-parent, next

#1094 Updating docs for the gps component.
  components/gps.rst
Labels: has-parent, next

#1106 Update diy.rst
  guides/diy.rst
Labels: current

#1113 Make changelog banner dismissable
  _static/custom.css
  _templates/layout.html
Labels: current

#1109 Correct typo: "between between" -> "between"
  components/i2c.rst
Labels: current

#1115 Update canbus.rst
  components/canbus.rst
Labels: current

#1114 Update diy.rst
  guides/diy.rst
Labels: current

#1111 update name_add_mac_suffix use dash
  components/esphome.rst
Labels: has-parent, next

#1067 Add 'pulse' effect doc
  components/light/index.rst
Labels: has-parent, next

#1002 Add docs for SHT4X
  components/sensor/images/sht4x-full.jpg
  components/sensor/sht4x.rst
  images/sht4x.jpg
  index.rst
Labels: has-parent, next

#1120 Add Atm90e32 energy docs
  components/sensor/atm90e32.rst
Labels: has-parent, next

#835 Add Grow fingerprint reader docs
  components/fingerprint_grow.rst
  components/images/r307-full.jpg
  components/images/r503-full.jpg
  images/fingerprint.svg
  index.rst
Labels: has-parent, next

#846 Documentation for TOF10120 support
  components/images/tof10120.jpg
  components/sensor/images/tof10120-full.jpg
  components/sensor/images/tof10120-ui.png
  components/sensor/tof10120.rst
  images/tof10120.jpg
  index.rst
Labels: has-parent, next
