Repository esphome/esphome-docs, pull requests merged in 2021-11, with the labels that each got.

#1584 Add restore_mode to rotary_encoder sensor
  components/sensor/rotary_encoder.rst
Labels: has-parent, next

#1568 ili9341: document auto_clear_enabled flag
  components/display/ili9341.rst
  components/display/index.rst
Labels: has-parent, next

#1591 Convert pin mode examples to new format
  components/binary_sensor/gpio.rst
  components/climate/ir_climate.rst
  components/display/st7789v.rst
  components/mcp230xx.rst
  components/mcp23Sxx.rst
  components/output/ac_dimmer.rst
  components/pcf8574.rst
  components/remote_receiver.rst
  components/sx1509.rst
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
  cookbook/esw01-eu.rst
  cookbook/ilonda-wifi-smart-fish-feeder.rst
  cookbook/sonoff-basic-light-switch.rst
  cookbook/sonoff-dual-light-switch.rst
  cookbook/sonoff-fishpond-pump.rst
  cookbook/sonoff-t1-3.rst
  devices/sonoff_4ch.rst
  devices/sonoff_4ch.yaml
  devices/sonoff_basic.rst
  devices/sonoff_s20.rst
  devices/sonoff_s20.yaml
  devices/sonoff_t1_uk_3gang_v1.1.rst
  devices/sonoff_t1_uk_3gang_v1.1.yaml
  devices/sonoff_t3_eu_3gang_v1.0.rst
  devices/sonoff_t3_eu_3gang_v1.0.yaml
  devices/teckin.yaml
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
Labels: current

#1575 [remote_receiver] Correct actual default for "filter" (50us instead of 10us)
  components/remote_receiver.rst
Labels: current

#1573 Add missing link from Tuya MCU to Tuya Sensor
  components/tuya.rst
Labels: current

#1557 Fix number of MAC bytes appended to name
  components/esphome.rst
Labels: current

#1583 Add entity_category docs
  components/binary_sensor/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/esp32_camera.rst
  components/fan/index.rst
  components/light/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text_sensor/index.rst
Labels: has-parent, next

#1595 Add `esp32_camera_web_server:` usage docs
  components/esp32_camera_web_server.rst
  index.rst
Labels: has-parent, next

#1563 Add Pronto protocol
  components/remote_transmitter.rst
Labels: has-parent, next

#1601 Update project example yaml
  guides/creators.rst
Labels: current

#1589 Docs for CAP1188 Capacitive Touch Sensor
  components/binary_sensor/cap1188.rst
  components/binary_sensor/images/cap1188-full.jpg
  images/cap1188.jpg
  index.rst
Labels: has-parent, next

#1592 [ADC] Reference new "raw output" option + clarify voltage ranges
  components/sensor/adc.rst
Labels: has-parent, next

#1602 Update max7219digit.rst
  components/display/max7219digit.rst
Labels: has-parent, next

#1598 Add `web_server` component's `ota` parameter
  components/web_server.rst
Labels: wrong-base-branch, has-parent, next

#1525 Improv serial docs
  components/captive_portal.rst
  components/esp32_improv.rst
  components/improv_serial.rst
  guides/creators.rst
  index.rst
Labels: has-parent, next

#1604 Docs for repeat action
  guides/automations.rst
Labels: has-parent, next

#1605 2021.11.0b1
  Doxygen
  Makefile
  _static/changelog-2021.11.0.png
  _static/version
  changelog/2021.11.0.rst
  changelog/index.rst
  components/binary_sensor/cap1188.rst
  components/binary_sensor/images/cap1188-full.jpg
  components/binary_sensor/index.rst
  components/captive_portal.rst
  components/climate/index.rst
  components/cover/index.rst
  components/display/ili9341.rst
  components/display/index.rst
  components/display/max7219digit.rst
  components/esp32_camera.rst
  components/esp32_camera_web_server.rst
  components/esp32_improv.rst
  components/external_components.rst
  components/fan/index.rst
  components/improv_serial.rst
  components/light/index.rst
  components/mqtt.rst
  components/number/index.rst
  components/remote_transmitter.rst
  components/select/index.rst
  components/sensor/adc.rst
  components/sensor/cse7761.rst
  components/sensor/index.rst
  components/sensor/rotary_encoder.rst
  components/sensor/ruuvitag.rst
  components/sensor/tcs34725.rst
  components/sensor/xiaomi_ble.rst
  components/switch/index.rst
  components/text_sensor/index.rst
  components/web_server.rst
  conf.py
  devices/sonoff.rst
  guides/automations.rst
  guides/creators.rst
  guides/supporters.rst
  images/cap1188.jpg
  images/cse7761.svg
  index.rst
  svg2png/cse7761.png
Labels: beta

#1536 Add documentation for the UART debugger
  components/uart.rst
Labels: has-parent, next

#1606 2021.11.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  components/uart.rst
  conf.py
Labels: beta

#1611 2021.11.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1576 Add strapping pin information to FAQ
  guides/faq.rst
Labels: has-parent, current

#1615 components/sensors/pmsx003.rst: add config options for the PMS5003S
  components/sensor/pmsx003.rst
Labels: has-parent, next

#1614 Add new on_state trigger info
  components/climate/index.rst
Labels: has-parent, next

#1100 Update dallas.rst
  components/sensor/dallas.rst
Labels: stale, in-progress, current

#1597 fixed example code in custom light output documentation
  components/light/custom.rst
Labels: current

#1607 Gree i feel
  components/climate/ir_climate.rst
Labels: has-parent, next

#1619 2021.11.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  components/light/custom.rst
  components/sensor/dallas.rst
  conf.py
  guides/faq.rst
  guides/supporters.rst
Labels: beta

#1620 2021.11.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
Labels: beta

#1610 Document mqtt.discovery_unique_id_generator option
  components/mqtt.rst
Labels: has-parent, next

#1624 2021.11.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1625 2021.11.0b7
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
Labels: beta

#1626 2021.11.0b8
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
Labels: beta

#1621 Adding supported midea AC vendor
  components/climate/midea.rst
Labels: current

#1609 Add diy floor heating controller
  guides/diy.rst
Labels: current

#1417 Add BLE Binary Output Docs
  components/output/ble_client.rst
  index.rst
Labels: stale, has-parent, next

#1628 2021.11.0
  Doxygen
  Makefile
  _static/changelog-2021.11.0.png
  _static/version
  changelog/2021.11.0.rst
  changelog/images/configuration-url.png
  changelog/index.rst
  components/binary_sensor/cap1188.rst
  components/binary_sensor/images/cap1188-full.jpg
  components/binary_sensor/index.rst
  components/captive_portal.rst
  components/climate/index.rst
  components/cover/index.rst
  components/display/ili9341.rst
  components/display/index.rst
  components/display/max7219digit.rst
  components/esp32_camera.rst
  components/esp32_camera_web_server.rst
  components/esp32_improv.rst
  components/external_components.rst
  components/fan/index.rst
  components/improv_serial.rst
  components/light/index.rst
  components/mqtt.rst
  components/number/index.rst
  components/remote_transmitter.rst
  components/select/index.rst
  components/sensor/adc.rst
  components/sensor/cse7761.rst
  components/sensor/index.rst
  components/sensor/rotary_encoder.rst
  components/sensor/ruuvitag.rst
  components/sensor/tcs34725.rst
  components/sensor/xiaomi_ble.rst
  components/switch/index.rst
  components/text_sensor/index.rst
  components/uart.rst
  components/web_server.rst
  conf.py
  devices/sonoff.rst
  guides/automations.rst
  guides/creators.rst
  guides/supporters.rst
  images/cap1188.jpg
  images/cse7761.svg
  index.rst
  svg2png/cse7761.png
Labels: current

#1629 2021.11.1
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1630 dsmr add tariff
  components/sensor/dsmr.rst
Labels: has-parent, current

#1640 Update uart.rst
  components/uart.rst
Labels: current

#1643 Incorporate note about changes in ESP32 ADC
  components/sensor/adc.rst
Labels: current

#1618 Added note about nec protocol fix
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1644 Update custom.rst
  components/climate/custom.rst
Labels: current

#1647 Small spelling fix
  components/sensor/max6675.rst
Labels: current

#1596 Extend DSMR docs with request_pin and request_interval options
  components/sensor/dsmr.rst
  components/sensor/images/dsmr-request-pin-circuit-example.png
Labels: has-parent, next, integration: dsmr

#1635 CAP1188 - Correction - allow_multiple_touches to boolean value
  components/binary_sensor/cap1188.rst
Labels: current

#1638 Light Component now shows effect: none to cancel effects
  components/light/index.rst
Labels: current

#1646 Add sdp800 to sdp3x documentation
  components/sensor/sdp3x.rst
  index.rst
Labels: has-parent, next

#1651 Rename Amber to Yellow
  changelog/2021.9.0.rst
Labels: current

#1594 Add documentation for dsmr max_telegram_length
  components/sensor/dsmr.rst
Labels: has-parent, next

#1642 Update uart debugger docs with new minimal config option
  components/uart.rst
Labels: has-parent, next

#1654 Fix minor typos
  components/display/index.rst
Labels: current

#1652 Mark "variant" as required for `neopixelbus`
  components/light/neopixelbus.rst
Labels: has-parent, current

#1633 wifi: remove mdns option
  components/wifi.rst
Labels: current

#1658 Document new-style NeoPixelBus methods
  components/light/neopixelbus.rst
Labels: has-parent, current

#1655 Added Precise Elevation Calculation
  components/sun.rst
Labels: current

#1660 Change default build path
  components/esphome.rst
Labels: has-parent, current

#1661 Expand documentation on libraries option
  components/esphome.rst
Labels: current

#1663 Document that node name can be max 31 characters
  components/esphome.rst
Labels: current

#1662 mDNS component documentation
  components/mdns.rst
  images/radio-tower.svg
  index.rst
Labels: current

#1665 2021.11.2
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1632 Add map filter for text sensors
  components/text_sensor/index.rst
Labels: has-parent, next

#1666 Fix mDNS icon
  components/mdns.rst
Labels: next

#1656 total_daily_energy: add restore option
  components/sensor/total_daily_energy.rst
Labels: has-parent, next

#1667 Also run CI on PR edited event
  .github/workflows/lint.yml
Labels: current

#1668 Remove accidentally inserted backticks
  components/sun.rst
Labels: current

#1669 Cancel previous workflows for PRs and branches
  .github/workflows/lint.yml
Labels: current

#1590 document modbus fp32 datatype
  components/binary_sensor/modbus_controller.rst
  components/modbus_controller.rst
  components/number/modbus_controller.rst
  components/output/modbus_controller.rst
  components/sensor/modbus_controller.rst
  components/switch/modbus_controller.rst
  components/text_sensor/modbus_controller.rst
Labels: has-parent, next

#1673 2021.11.3
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1674 Add documentation for esp-idf ignore_efuse_mac_crc option
  components/esp32.rst
Labels: has-parent, current

#1678 2021.11.4
  Doxygen
  Makefile
  _static/version
  changelog/2021.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1680 Require that Made for ESPHome projects are adoptable
  guides/made_for_esphome.rst
Labels: current

#1675 add more see also
  components/modbus.rst
Labels: current

#1670 Add note about hlw8012 BL0937 SEL pin
  components/sensor/hlw8012.rst
Labels: current

#742 Added tip about gamma in Color Correction section
  components/light/rgb.rst
  components/light/rgbw.rst
  components/light/rgbww.rst
Labels: current

#1682 Update sharing example to match new repo
  guides/creators.rst
Labels: current

#1650 Improve dsmr telegram timeouts
  components/sensor/dsmr.rst
Labels: has-parent, next

#1572 Add 'include_internal' option to web_server
  components/web_server.rst
Labels: has-parent, next

#1684 Tuya automation and text sensor support
  components/text_sensor/tuya.rst
  components/tuya.rst
  index.rst
Labels: has-parent, next

#1681 Create docs for Button core, restart, template
  components/button/index.rst
  components/button/restart.rst
  components/button/template.rst
  components/index.rst
  components/switch/restart.rst
  index.rst
Labels: has-parent, next

#1686 Update device-class links to point to ha dev docs
  components/binary_sensor/index.rst
  components/sensor/index.rst
Labels: current

#1679 cse7766: add energy sensor
  components/sensor/cse7766.rst
Labels: has-parent, next

#1672 Describe unit_of_measurement for number component
  components/number/index.rst
Labels: has-parent, next

#1685 Button/device class
  components/button/index.rst
Labels: has-parent, next

#1689 Add doc for number mode
  components/number/index.rst
Labels: has-parent, next
