Repository esphome/esphome-docs, pull requests merged in 2021-05, with the labels that each got.

#702 Ble client docs
  components/ble_client.rst
  components/sensor/ble_sensor.rst
  components/switch/ble.rst
  cookbook/ble_itag.rst
  cookbook/images/esp32_ble_itag.png
  guides/contributing.rst
  images/esp32_ble_itag.jpg
  index.rst
Labels: has-parent, integration: ble_client, integration: ble_sensor, next

#1122 Update email addresses
  CODE_OF_CONDUCT.md
  misc/privacy.rst
Labels: current

#1080 Add speed_count to tuya fan
  components/fan/tuya.rst
Labels: has-parent, next

#1131 Fix mcp3008 reference
  components/sensor/mcp3008.rst
Labels: next

#1132 Fixed typo in 1.17.0 changelogs
  changelog/v1.17.0.rst
Labels: current

#1135 Add note about hyperion classic udp port
  components/light/index.rst
Labels: has-parent, next

#877 Document Tuya fan direction datapoint
  components/fan/tuya.rst
Labels: has-parent, next

#1125 Change wifi signal strength unit to dBm
  components/sensor/images/wifi_signal-ui.png
  components/sensor/wifi_signal.rst
Labels: has-parent, next

#1136 1.17.1
  Doxygen
  Makefile
  _static/version
  changelog/v1.17.0.rst
  components/sensor/xiaomi_ble.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1137 Fix abundant apostrophes
  guides/automations.rst
Labels: current

#1061 Add output part to binary light example
  components/light/binary.rst
Labels: current

#1148 1.17.2
  Doxygen
  Makefile
  _static/version
  changelog/v1.17.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1144 Fixed datasheet link for RC522
  components/binary_sensor/rc522.rst
Labels: current

#1150 1.18.0b1
  Doxygen
  Makefile
  _static/version
  changelog/index.rst
  changelog/v1.18.0.rst
  components/ble_client.rst
  components/display/index.rst
  components/esphome.rst
  components/ethernet.rst
  components/external_components.rst
  components/fan/tuya.rst
  components/fingerprint_grow.rst
  components/gps.rst
  components/i2c.rst
  components/images/r307-full.jpg
  components/images/r503-full.jpg
  components/images/tca9548a.jpg
  components/images/tof10120.jpg
  components/light/index.rst
  components/sensor/atm90e32.rst
  components/sensor/b_parasite.rst
  components/sensor/ble_sensor.rst
  components/sensor/bme680_bsec.rst
  components/sensor/images/b_parasite.jpg
  components/sensor/images/bme680-bsec-ui.png
  components/sensor/images/sgp40.jpg
  components/sensor/images/sht4x-full.jpg
  components/sensor/images/tof10120-full.jpg
  components/sensor/images/tof10120-ui.png
  components/sensor/images/wifi_signal-ui.png
  components/sensor/mcp3008.rst
  components/sensor/sgp40.rst
  components/sensor/sht4x.rst
  components/sensor/tof10120.rst
  components/sensor/wifi_signal.rst
  components/switch/ble.rst
  components/tca9548a.rst
  components/wifi.rst
  conf.py
  cookbook/ble_itag.rst
  cookbook/iaq_board.rst
  cookbook/images/esp32_ble_itag.png
  guides/automations.rst
  guides/contributing.rst
  guides/faq.rst
  guides/supporters.rst
  images/b_parasite.jpg
  images/esp32_ble_itag.jpg
  images/external_components.svg
  images/fingerprint.svg
  images/sgp40.jpg
  images/sht4x.jpg
  images/tca9548a.jpg
  images/tof10120.jpg
  index.rst
Labels: beta, has-parent

#1037 Added receive for Fujitsu ACs
  components/climate/ir_climate.rst
Labels: current, has-parent

#1072 Update allowed characters for node names
  components/esphome.rst
Labels: has-parent, next

#1089 Update pulse_counter.rst
  components/sensor/pulse_counter.rst
Labels: current

#1149 Remove deprecated board_flash_mode from configuration example
  guides/configuration-types.rst
Labels: current

#1152 Update deep_sleep.rst
  components/deep_sleep.rst
Labels: current

#1143 Utalize pip3 for commands
  guides/faq.rst
Labels: current

#1103 FAQ page: Converting from "I" to "we" wording
  guides/faq.rst
Labels: current

#1057 thermostat min/max temperature clarification
  components/climate/thermostat.rst
Labels: current

#1033 Added compatibility notes
  components/display/waveshare_epaper.rst
Labels: current

#1050 add font to usage example
  components/display/waveshare_epaper.rst
Labels: current, in-progress

#1155 Fix missed merge conflict
  components/light/index.rst
Labels: next

#1156 Sample codeblock has incorrect variables
  components/display/st7735.rst
Labels: current

#1157 Replaced set_password with new_password
  components/fingerprint_grow.rst
Labels: next

#1161 Add past changelogs to current
  changelog/v1.16.0.rst
  changelog/v1.17.0.rst
Labels: current

#1162 1.18.0b2
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  changelog/v1.17.0.rst
  changelog/v1.18.0.rst
  components/binary_sensor/rc522.rst
  components/climate/ir_climate.rst
  components/climate/thermostat.rst
  components/deep_sleep.rst
  components/display/st7735.rst
  components/display/waveshare_epaper.rst
  components/esphome.rst
  components/fingerprint_grow.rst
  components/light/index.rst
  components/sensor/cse7766.rst
  components/sensor/hlw8012.rst
  components/sensor/pulse_counter.rst
  components/wifi.rst
  conf.py
  cookbook/power_meter.rst
  guides/configuration-types.rst
  guides/faq.rst
  guides/supporters.rst
Labels: beta, has-parent

#1158 Fix docs for inkplate
  changelog/v1.16.0.rst
  components/display/Inkplate.rst
  components/display/images/Inkplate.jpg
  components/display/images/inkplate.jpg
  components/display/images/inkplate6.jpg
  components/display/inkplate6.rst
  images/inkplate6.jpg
  index.rst
Labels: current, in-progress

#1163 Fixed wrong link in i2c_id
  components/binary_sensor/pn532.rst
Labels: current

#1133 Explain where to upload .ttf font files
  components/display/index.rst
Labels: current

#1127 Add sm2135 component
  components/output/sm2135.rst
  images/sm2135.svg
  index.rst
Labels: has-parent, next

#1164 1.18.0b3
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  changelog/v1.18.0.rst
  components/binary_sensor/pn532.rst
  components/display/Inkplate.rst
  components/display/images/Inkplate.jpg
  components/display/images/inkplate.jpg
  components/display/images/inkplate6.jpg
  components/display/index.rst
  components/display/inkplate6.rst
  components/output/sm2135.rst
  conf.py
  guides/supporters.rst
  images/inkplate6.jpg
  images/sm2135.svg
  index.rst
Labels: beta, has-parent

#1165 Some clarification added to external components.
  components/external_components.rst
Labels: next

#1129 Add new disconnect reasons to the FAQ.
  guides/faq.rst
Labels: current, has-parent

#1093 Add the documentation for the autorepeat filter
  components/binary_sensor/index.rst
Labels: has-parent, next

#1147 pulse-meter/set-total-pulses-action
  components/sensor/pulse_meter.rst
Labels: has-parent, next

#1169 format-fixes
  components/ble_client.rst
  components/climate/tuya.rst
  components/display/waveshare_epaper.rst
  components/esphome.rst
  components/fan/tuya.rst
  components/fingerprint_grow.rst
  components/output/sm2135.rst
  components/sensor/bh1750.rst
  components/sensor/ble_client.rst
  components/sensor/bme680_bsec.rst
  components/sensor/sht4x.rst
  components/switch/ble_client.rst
  cookbook/ble_itag.rst
  index.rst
Labels: next

#1170 updates for v0.14.0 schema style
  schema_doc.py
Labels: next

#1159 Add attribute support to Home Assistant sensors
  components/binary_sensor/homeassistant.rst
  components/sensor/homeassistant.rst
  components/text_sensor/homeassistant.rst
Labels: has-parent, next

#1015 Add XPT2046 touch screen controller documentation
  components/binary_sensor/images/xpt2046-full.jpg
  components/binary_sensor/xpt2046.rst
  images/xpt2046.jpg
  index.rst
Labels: has-parent, next

#1178 1.18.0b4
  Doxygen
  Makefile
  _static/version
  changelog/v1.18.0.rst
  components/external_components.rst
  conf.py
  guides/faq.rst
  guides/supporters.rst
Labels: beta, has-parent

#1172 Update max frequency
  components/output/pca9685.rst
Labels: current

#1175 Update Arduino SDK versions
  components/esphome.rst
Labels: has-parent, next

#1168 Update web-api id component
  web-api/index.rst
Labels: current

#1179 Fix docker build failure
  Dockerfile
Labels: current

#1177 Update ifan02 example with new fan speed options
  cookbook/ifan02.rst
Labels: current, has-parent

#1176 Document missing use_address in Ethernet component
  components/ethernet.rst
Labels: current

#1173 Lambda over multiple lines. |- added
  cookbook/bme280_environment.rst
Labels: current

#1171 changed LG example to existing, working code
  components/remote_transmitter.rst
Labels: current

#1121 GPIO Switch: simplify Momentary Switch example
  components/switch/gpio.rst
Labels: current

#583 Added warning: GPIOs are LIVE in power measurement devices
  components/sensor/ade7953.rst
  components/sensor/cse7766.rst
  components/sensor/hlw8012.rst
  devices/sonoff.rst
Labels: current, integration: ade7953, integration: cse7766, integration: hlw8012

#915 Add on_tag_removed documentation to pn532.rst
  components/binary_sensor/pn532.rst
Labels: has-parent, next

#1181 1.18.0
  Doxygen
  Makefile
  _static/changelog-1.18.0.png
  _static/version
  changelog/index.rst
  changelog/v1.18.0.rst
  components/ble_client.rst
  components/display/index.rst
  components/esphome.rst
  components/ethernet.rst
  components/external_components.rst
  components/fan/tuya.rst
  components/fingerprint_grow.rst
  components/gps.rst
  components/i2c.rst
  components/images/r307-full.jpg
  components/images/r503-full.jpg
  components/images/tca9548a.jpg
  components/images/tof10120.jpg
  components/light/index.rst
  components/output/sm2135.rst
  components/sensor/atm90e32.rst
  components/sensor/b_parasite.rst
  components/sensor/ble_sensor.rst
  components/sensor/bme680_bsec.rst
  components/sensor/images/b_parasite.jpg
  components/sensor/images/bme680-bsec-ui.png
  components/sensor/images/sgp40.jpg
  components/sensor/images/sht4x-full.jpg
  components/sensor/images/tof10120-full.jpg
  components/sensor/images/tof10120-ui.png
  components/sensor/images/wifi_signal-ui.png
  components/sensor/mcp3008.rst
  components/sensor/sgp40.rst
  components/sensor/sht4x.rst
  components/sensor/tof10120.rst
  components/sensor/wifi_signal.rst
  components/switch/ble.rst
  components/tca9548a.rst
  components/wifi.rst
  conf.py
  cookbook/ble_itag.rst
  cookbook/iaq_board.rst
  cookbook/images/esp32_ble_itag.png
  guides/automations.rst
  guides/contributing.rst
  guides/faq.rst
  guides/supporters.rst
  images/b_parasite.jpg
  images/esp32_ble_itag.jpg
  images/external_components.svg
  images/fingerprint.svg
  images/sgp40.jpg
  images/sht4x.jpg
  images/sm2135.svg
  images/tca9548a.jpg
  images/tof10120.jpg
  index.rst
Labels: current, has-parent

#1116 Add triggers fan.on_turn_on / fan.on_turn_off
  components/fan/index.rst
Labels: has-parent, next

#1182 [b-parasite] Fix doc typo on "battery"
  components/sensor/b_parasite.rst
Labels: current

#1184 Fixed Sensirion typo
  components/sensor/scd30.rst
  components/sensor/sgp30.rst
  components/sensor/sgp40.rst
  components/sensor/sht3xd.rst
  components/sensor/shtcx.rst
  components/sensor/sps30.rst
  components/sensor/sts3x.rst
Labels: current

#1112 Add extra margin at the bottom to avoid overlap with Changelog banner
  _static/custom.css
Labels: current

#1092 feat: ESP32-EVB ethernet configuration example
  components/ethernet.rst
Labels: current

#1187 Fix spelling/capitalizing mistakes in ESPHome
  components/display/pcd8544.rst
  components/esphome.rst
  components/sensor/as3935.rst
  components/stepper/index.rst
  cookbook/display_time_temp_oled.rst
  cookbook/leak-detector-m5stickC.rst
  guides/diy.rst
Labels: current

#1186 Replace Hass.io with Home Assistant
  components/display/index.rst
  components/sensor/homeassistant.rst
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
  cookbook/mirabella-genio-bulb.rst
  cookbook/zemismart-rgbw-downlights.rst
  devices/sonoff_4ch.rst
  devices/sonoff_s20.rst
  devices/sonoff_t1_uk_3gang_v1.1.rst
  guides/faq.rst
  guides/getting_started_command_line.rst
  guides/migrate_espeasy.rst
  guides/migrate_espurna.rst
  guides/migrate_sonoff_tasmota.rst
Labels: current

#943 Update adc.rst
  components/sensor/adc.rst
Labels: current

#1194 Update diy.rst
  guides/diy.rst
Labels: current

#1190 Lights & GPIO Switch inverted restore mode
  components/light/index.rst
  components/switch/gpio.rst
Labels: has-parent, next

#1198 Update due to new version 1.18.0
  components/sensor/bh1750.rst
Labels: current

#1196 Fix ble_client YAML syntax
  components/ble_client.rst
Labels: current

#1191 Update sonoff_basic.rst
  devices/sonoff_basic.rst
Labels: current

#903 added E-LOG pin on PCB version 2.1
  devices/sonoff_s20.rst
Labels: current

#1200 Fix off to on
  components/fan/index.rst
Labels: current

#1199 Update Web address link for Nextion Editor
  components/display/nextion.rst
Labels: current

#1207 Added bottom segment to digit 9
  components/display/images/max7219/seg73.svg
Labels: has-parent, next

#745 Add support for sdm_meter energy devices
  components/modbus.rst
  components/sensor/images/sdm220m-full.png
  components/sensor/sdm_meter.rst
  images/sdm220m.png
  index.rst
Labels: has-parent, next

#944 CS5460A
  components/sensor/cs5460a.rst
  guides/automations.rst
  images/cs5460a.png
  index.rst
Labels: has-parent, next

#1192 Drop 128x160 ESP-32 camera resolution support
  components/esp32_camera.rst
Labels: has-parent, next

#1193 rf_bridge: add new actions
  components/rf_bridge.rst
Labels: current, has-parent
