Repository esphome/esphome-docs, pull requests merged in 2021-12, with the labels that each got.

#1683 Add Git credential config docs
  components/external_components.rst
Labels: has-parent, next

#1692 Expand uart invert feature to ESP8266
  components/uart.rst
Labels: has-parent, next

#1687 Support setting manual_ip under networks option
  components/wifi.rst
Labels: has-parent, next

#1695 2021.12.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2021.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1698 fix max7219digit scroll mode
  components/display/max7219digit.rst
Labels: current

#1696 Make Table of Contents scrollable
  _static/custom.css
Labels: current

#1699 add missing documentation for pm_size
  components/sensor/sps30.rst
Labels: has-parent, current

#1579 Add FAQ entry on testing PRs with external components
  guides/faq.rst
Labels: current

#1705 Deep Sleep: ESP32 per-reason run duration
  components/deep_sleep.rst
Labels: has-parent, next

#1704 2021.12.0b3
  Doxygen
  Makefile
  _static/custom.css
  _static/version
  changelog/2021.12.0.rst
  components/display/max7219digit.rst
  components/sensor/sps30.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1707 fixed time reference link
  components/sun.rst
Labels: current

#1706 Add some sign that the link is to the API
  components/text_sensor/custom.rst
Labels: current

#1710 Fix indentation of ESP-IDF example
  components/esp32.rst
Labels: current

#1713 use_write_multiple for modbus_controller number and output
  components/number/modbus_controller.rst
  components/output/modbus_controller.rst
Labels: has-parent, next

#1717 2021.12.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2021.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1700 Add light on_state trigger
  components/light/index.rst
Labels: has-parent, next

#952 Add reset_duration option for Waveshare
  components/display/waveshare_epaper.rst
Labels: stale, has-parent, next

#1719 Make button entities work on webserver
  _static/webserver-v1.js
  _static/webserver-v1.min.js
Labels: current

#1715 Quantile filter
  components/sensor/index.rst
Labels: has-parent, next

#1711 ESP32 Cam AEC config
  components/esp32_camera.rst
Labels: has-parent, next

#1723 2021.12.1
  Doxygen
  Makefile
  _static/version
  changelog/2021.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1722 Update status_led.rst
  components/light/status_led.rst
Labels: current

#1731 `slow_pwm` not TODO for a long time
  components/climate/pid.rst
Labels: current

#1716 Correct error in ST7789V TFT example
  components/display/st7789v.rst
Labels: current

#1729 Removed register_type
  components/number/modbus_controller.rst
Labels: has-parent, current

#1732 Add docs from growatt modbus sensor
  components/sensor/growatt_solar.rst
  components/sensor/images/growatt.jpg
  images/growatt.jpg
  index.rst
Labels: has-parent, next

#1634 Tuya number doc
  components/number/tuya.rst
  index.rst
Labels: has-parent, next

#1703 Document inversion option for the tm1637
  components/display/tm1637.rst
Labels: has-parent, next

#1737 Add netlify badge in sidebar
  _templates/contact.html
Labels: current

#1725 Add shutdown&safe mode button
  components/button/images/safemode-ui.png
  components/button/images/shutdown-ui.png
  components/button/safe_mode.rst
  components/button/shutdown.rst
Labels: has-parent, next

#1739 2021.12.2
  Doxygen
  Makefile
  _static/version
  changelog/2021.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1736 Update esphome.rst
  components/esphome.rst
Labels: current

#1735 Fix documentation for MQTT client's subscribe method.
  components/mqtt.rst
Labels: current

#1742 Change netlify badge to link to match others
  _templates/contact.html
Labels: current

#1743 Add model and wording for inkplate 10 support
  components/display/inkplate6.rst
  index.rst
Labels: has-parent, next

#1558 Add EntityBase properties to ESP32 Camera
  components/esp32_camera.rst
Labels: stale, has-parent, next

#1744 Use generic GPIO pins in MHZ19 example
  components/sensor/mhz19.rst
Labels: current

#1556 Add reference to MHO-C401 custom firmware
  components/sensor/xiaomi_ble.rst
Labels: current

#1648 Add output pin definition to hbridge fan example configuration
  components/fan/hbridge.rst
Labels: current

#1761 2021.12.3
  Doxygen
  Makefile
  _static/version
  changelog/2021.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1649 INA260 Current and Power Sensor support
  components/sensor/images/ina260-full.png
  components/sensor/ina260.rst
  images/ina260.jpg
  index.rst
Labels: has-parent, next
