Repository esphome/esphome-docs, pull requests merged in 2021-06, with the labels that each got.

#871 teleinfo: update documentation since sensor/text_sensor move.
  components/sensor/images/teleinfo-historical.jpg
  components/sensor/teleinfo.rst
Labels: has-parent, next

#920 Add documentation for Xiaomi CGDK2
  components/sensor/images/xiaomi_cgdk2.jpg
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1210 Add optional lambda to ble_sensor for raw data parsing
  components/sensor/ble_client.rst
Labels: has-parent, next

#1108 BME680 BSEC: Document per sensor T/P/H sample rate overrides
  components/sensor/bme680_bsec.rst
Labels: has-parent, next

#1211 Document Tuya light color temperature options
  components/light/tuya.rst
Labels: has-parent, next

#1065 Document new Tuya climate config options
  components/climate/tuya.rst
Labels: has-parent, next

#1209 Update Sonoff 4CH docs
  devices/sonoff_4ch.rst
Labels: current

#1212 Add dfplayer volume up/down actions
  components/dfplayer.rst
Labels: has-parent, next

#1201 Add support for Sensor state class
  components/sensor/index.rst
Labels: has-parent, next

#1063 Add docs for climate presets
  components/climate/index.rst
  components/climate/midea_ac.rst
Labels: has-parent, next

#1217 Correct yaml indentation for dfplayer.play
  components/dfplayer.rst
Labels: current

#1222 Just a couple of Typos corrected :)
  components/light/index.rst
Labels: current

#1183 CLI user experience improvements updated docs
  components/mqtt.rst
  guides/cli.rst
  guides/faq.rst
  guides/getting_started_command_line.rst
Labels: has-parent, next

#1203 Add docs for Improv and new BLE base/server
  components/esp32_ble.rst
  components/esp32_improv.rst
  components/esphome.rst
  images/improv-social.png
  images/improv.svg
  index.rst
Labels: has-parent, next

#1224 Add docs for project information
  components/esphome.rst
Labels: has-parent, next

#1225 Add example config to project information
  components/esphome.rst
Labels: next

#1205 Add 1.54v2 epaper model
  components/display/waveshare_epaper.rst
  devices/images/sonoff_t1_uk_3g_backplate_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_touchpads_v1.1.jpg
Labels: has-parent, next

#1231 1.19.0b2
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  components/display/waveshare_epaper.rst
  conf.py
  devices/images/sonoff_t1_uk_3g_backplate_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_touchpads_v1.1.jpg
  guides/supporters.rst
Labels: beta, has-parent

#1234 Split BLE/server docs
  components/esp32_ble.rst
  components/esp32_ble_server.rst
  components/esp32_improv.rst
Labels: has-parent, next

#1233 Update dashboard guide
  guides/getting_started_hassio.rst
  guides/images/dashboard.png
  guides/images/hassio_addons_section.png
  guides/images/hassio_repo.png
Labels: has-parent, next

#1236 1.19.0b3
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  components/esp32_ble.rst
  components/esp32_ble_server.rst
  components/esp32_improv.rst
  components/sensor/ads1115.rst
  conf.py
  guides/getting_started_hassio.rst
  guides/images/dashboard.png
  guides/images/hassio_addons_section.png
  guides/images/hassio_repo.png
  guides/supporters.rst
Labels: beta, has-parent

#1219 Document reversed option for light partitions
  components/light/partition.rst
Labels: has-parent, next

#1238 Update diy.rst
  guides/diy.rst
Labels: current

#1239 Fixed indentation of example
  guides/automations.rst
Labels: current

#1241 Add creator page
  guides/creators.rst
  index.rst
Labels: next

#1243 1.19.0b4
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  components/light/partition.rst
  conf.py
  guides/automations.rst
  guides/creators.rst
  guides/diy.rst
  guides/supporters.rst
  index.rst
Labels: beta, has-parent

#1244 1.19.0b5
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
Labels: beta, has-parent

#1242 Restyle top and guide section
  _static/custom.css
  _templates/contact.html
  conf.py
  images/hero.png
  images/index.rst
  images/shield-discord.svg
  images/shield-github.svg
  images/shield-twitter.svg
  index.rst
Labels: current

#1245 1.19.0b6
  Doxygen
  Makefile
  _static/custom.css
  _static/version
  _templates/contact.html
  changelog/v1.19.0.rst
  conf.py
  images/hero.png
  images/index.rst
  images/shield-discord.svg
  images/shield-github.svg
  images/shield-twitter.svg
  index.rst
Labels: beta, has-parent

#1247 Add devcontainer
  .devcontainer/devcontainer.json
Labels: current

#1249 Fallback to the beta branch if ref is missing
  Makefile
Labels: current

#1252 Turn guide cards around
  _static/custom.css
  index.rst
Labels: current

#1253 Remove min width from body for mobile
  _static/custom.css
Labels: current

#1254 Remove hover animation from guide card
  _static/custom.css
Labels: current

#1255 1.19.0b7
  .devcontainer/devcontainer.json
  Doxygen
  Makefile
  _static/custom.css
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: beta, has-parent

#1256 Add section on the CLI changes and the breaking change there
  changelog/v1.19.0.rst
Labels: current

#1258 YAML fix - characteristic_uuid
  cookbook/ble_itag.rst
Labels: current

#1260 1.19.1
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1259 Doc update for variable bit width for Samsung protocol enhancement
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1262 Change set_supports_auto_mode for custom climate
  components/climate/custom.rst
Labels: current, has-parent

#1264 Add link to generic Display Component
  components/display/st7735.rst
Labels: current

#1265 Remove extra comma from xpt2046.rst
  components/binary_sensor/xpt2046.rst
Labels: current, has-parent

#1267 1.19.2
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1266 Fix ‘follow’ typo in contact.html
  _templates/contact.html
Labels: current

#1269 1.19.3
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1270 Replace AUTO with HEAT_COOL
  components/climate/index.rst
Labels: current

#1261 Update diy.rst
  guides/diy.rst
Labels: current

#1246 Override document title for index
  _templates/layout.html
Labels: current

#1271 1.19.4
  Doxygen
  Makefile
  _static/version
  changelog/v1.19.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1276 Update fingerprint_grow.rst
  components/fingerprint_grow.rst
Labels: current

#1279 Climate component for Ballu air conditioners with remote model YKR-K/002E
  components/climate/ir_climate.rst
Labels: has-parent, next

#1280 switch argument order
  guides/getting_started_command_line.rst
Labels: current

#1281 Fix duplicated paragraph
  components/remote_transmitter.rst
Labels: current

#1285 Update climate code block types
  components/climate/index.rst
Labels: current

#1286 Replace cover word in template switch doc
  components/switch/template.rst
Labels: current
