Repository esphome/esphome-docs, pull requests merged in 2021-09, with the labels that each got.

#1436 Fan is on is off conditions
  components/fan/index.rst
  guides/automations.rst
Labels: has-parent, next

#1441 Improve template number/select documentation
  components/number/template.rst
  components/select/template.rst
Labels: current

#1431 Add docs for git packages
  guides/configuration-types.rst
Labels: has-parent, next

#1442 Remove last_reset_type
  components/sensor/index.rst
Labels: has-parent, next

#1448 Initial Made for ESPHome page and logos
  _static/made-for-esphome-black-on-transparent.png
  _static/made-for-esphome-black-on-white.png
  _static/made-for-esphome-white-on-black.png
  _static/made-for-esphome-white-on-transparent.png
  guides/made_for_esphome.rst
  index.rst
Labels: current

#1450 Fix remote receiver api links
  components/remote_receiver.rst
Labels: current

#1451 Add svg images for Made for ESPHome
  _static/made-for-esphome-black-on-transparent.svg
  _static/made-for-esphome-black-on-white.svg
  _static/made-for-esphome-white-on-black.svg
  _static/made-for-esphome-white-on-transparent.svg
  guides/made_for_esphome.rst
Labels: current

#1447 Add docs for new fan trigger: on_speed_set
  components/fan/index.rst
Labels: has-parent, next

#1444 Template sensor publish updates
  components/sensor/template.rst
  components/text_sensor/template.rst
Labels: has-parent, next

#1356 Midea support v2
  components/climate/midea.rst
  components/climate/midea_ac.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  index.rst
Labels: has-parent, next

#1336 ccs811: docs for version sensor
  components/sensor/ccs811.rst
Labels: has-parent, next

#1454 Document api encryption
  components/api.rst
Labels: has-parent, next

#1423 pm1006: document changes in esphome PR 2214
  components/sensor/pm1006.rst
Labels: has-parent, next

#1455 Fix LED letter casing
  components/light/status_led.rst
  components/status_led.rst
Labels: current

#1456 2021.9.0b1
  Doxygen
  Makefile
  _static/changelog-2021.9.0.png
  _static/version
  changelog/2021.9.0.rst
  changelog/index.rst
  components/api.rst
  components/binary_sensor/ble_presence.rst
  components/climate/midea.rst
  components/climate/midea_ac.rst
  components/display/images/st7920-full.jpg
  components/display/st7789v.rst
  components/display/st7920.rst
  components/esp32_ble_beacon.rst
  components/fan/hbridge.rst
  components/fan/images/L298N_module.jpg
  components/fan/index.rst
  components/light/index.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/airthings_ble.rst
  components/sensor/ccs811.rst
  components/sensor/images/airthings_wave_plus.jpg
  components/sensor/index.rst
  components/sensor/pm1006.rst
  components/sensor/template.rst
  components/sensor/total_daily_energy.rst
  components/text_sensor/template.rst
  conf.py
  guides/automations.rst
  guides/configuration-types.rst
  guides/supporters.rst
  images/airthings_logo.png
  images/st7920.jpg
  index.rst
Labels: beta

#1452 Fix static homepage title
  _templates/layout.html
  index.rst
Labels: current

#1459 2021.9.0b2
  Doxygen
  Makefile
  _static/version
  _templates/layout.html
  changelog/2021.9.0.rst
  conf.py
  guides/configuration-types.rst
  guides/supporters.rst
  index.rst
Labels: beta

#1465 Add support for color_temperature_invert on tuya lights
  components/light/tuya.rst
Labels: has-parent, next

#1445 Expose select on Frontend `web_server:`
  Makefile
  _static/webserver-v1.js
  _static/webserver-v1.min.js
Labels: has-parent, next

#1469 2021.9.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2021.9.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1464 Update BMP280 device description
  index.rst
Labels: current

#1460 Fix typo in dsmr docs
  components/sensor/dsmr.rst
Labels: current

#1461 fix and update h-bridge fan documentation
  components/fan/hbridge.rst
Labels: next

#1467 Update mhz19.rst
  components/sensor/mhz19.rst
Labels: current

#1440 correct the meaning of the sentence
  components/sensor/as3935.rst
Labels: current

#1438 Link update
  components/pipsolar.rst
Labels: current

#1430 Move SCD30 into air quality
  index.rst
Labels: current

#1425 SGP40: Small correction to the example
  components/sensor/sgp40.rst
Labels: current

#1439 Misc documentation updates
  components/fan/index.rst
  components/switch/index.rst
Labels: current

#1369 Update cookbook for ESP32 Water Leak Detector
  cookbook/leak-detector-m5stickC.rst
Labels: current

#1278 Display: Add example how to use color
  components/display/index.rst
Labels: current

#1188 Clarify that includes option does not only accept headers
  components/esphome.rst
Labels: current

#1432 MQTT is no longer required for ESPhome to work
  components/mqtt.rst
Labels: next

#1405 Update tsl2591.rst
  components/sensor/tsl2591.rst
Labels: current

#1384 Added current calibration section for gain_pga = 4X
  components/sensor/atm90e32.rst
Labels: current

#1342 Fix AS3935 I²C address documentation
  components/sensor/as3935.rst
Labels: current

#1126 added 10kHz value
  components/i2c.rst
Labels: current

#1064 Update ssd1351.rst
  components/display/ssd1351.rst
Labels: current

#1473 2021.9.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2021.9.0.rst
  components/display/index.rst
  components/display/ssd1351.rst
  components/esphome.rst
  components/fan/index.rst
  components/i2c.rst
  components/pipsolar.rst
  components/sensor/as3935.rst
  components/sensor/atm90e32.rst
  components/sensor/dsmr.rst
  components/sensor/mhz19.rst
  components/sensor/sgp40.rst
  components/sensor/tsl2591.rst
  components/switch/index.rst
  conf.py
  cookbook/leak-detector-m5stickC.rst
  guides/supporters.rst
  index.rst
Labels: beta

#1474 Update adc.rst
  components/sensor/adc.rst
Labels: current

#1472 correct typo
  components/esp32_ble_tracker.rst
Labels: current

#1475 dsmr-updates
  components/sensor/dsmr.rst
Labels: has-parent, next

#1476 2021.9.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2021.9.0.rst
  components/esp32_ble_tracker.rst
  components/sensor/adc.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1215 Tuya climate: Documentation for direct relay state
  components/climate/tuya.rst
Labels: has-parent, next

#1478 2021.9.0
  Doxygen
  Makefile
  _static/changelog-2021.9.0.png
  _static/version
  changelog/2021.9.0.rst
  changelog/index.rst
  components/api.rst
  components/binary_sensor/ble_presence.rst
  components/climate/midea.rst
  components/climate/midea_ac.rst
  components/display/images/st7920-full.jpg
  components/display/st7789v.rst
  components/display/st7920.rst
  components/esp32_ble_beacon.rst
  components/fan/hbridge.rst
  components/fan/images/L298N_module.jpg
  components/fan/index.rst
  components/light/index.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/airthings_ble.rst
  components/sensor/ccs811.rst
  components/sensor/images/airthings_wave_plus.jpg
  components/sensor/index.rst
  components/sensor/pm1006.rst
  components/sensor/template.rst
  components/sensor/total_daily_energy.rst
  components/text_sensor/template.rst
  conf.py
  guides/automations.rst
  guides/configuration-types.rst
  guides/supporters.rst
  images/airthings_logo.png
  images/st7920.jpg
  index.rst
Labels: current

#1480 Fix documentation for some st7735 params
  components/display/st7735.rst
Labels: current

#1477 Document syntax used to override library source
  components/esphome.rst
Labels: has-parent, current

#1463 Fix cover lambda docs
  components/cover/index.rst
Labels: current

#1435 missing merge symbol before file include
  guides/configuration-types.rst
Labels: current

#1484 Add line about sensor filter processing order
  components/sensor/index.rst
Labels: current

#1443 Add information about `esp8266_disable_ssl_support:`
  components/http_request.rst
Labels: has-parent, next

#1216 Tuya climate component: Add documentation for eco mode
  components/climate/tuya.rst
Labels: has-parent, next

#1485 rf_bridge: Move portisch actions under Portisch header
  components/rf_bridge.rst
Labels: current

#1486 2021.9.1
  Doxygen
  Makefile
  _static/version
  changelog/2021.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1358 Added new graphing feature
  components/display/images/graph_dualtrace.png
  components/display/images/graph_screen.png
  components/display/index.rst
Labels: has-parent, next

#1479 Added documentation for st7735 invert_colors
  components/display/st7735.rst
Labels: has-parent, next

#1483 Add documentation for deep-sleep wakeup from esp32 touch sensor event
  components/binary_sensor/esp32_touch.rst
  components/deep_sleep.rst
Labels: has-parent, next

#1453 Documentation for non-addressable lights in light partitions
  components/light/partition.rst
Labels: has-parent, next

#1490 add = to default glyph list
  components/display/index.rst
Labels: has-parent, next

#1390 Add documentation for Daly BMS Component
  components/sensor/daly_bms.rst
  components/sensor/images/daly_bms_example.png
  components/sensor/images/daly_bms_pinout.png
  images/daly_bms.png
  index.rst
Labels: has-parent, next

#1458 Combine xiaomi_miscale and xiaomi_miscale2
  components/sensor/images/xiaomi_miscale.jpg
  components/sensor/images/xiaomi_miscale2.jpg
  components/sensor/xiaomi_miscale.rst
  components/sensor/xiaomi_miscale2.rst
  images/xiaomi_miscale1&2.jpg
  index.rst
Labels: has-parent, next

#979 Add docs for LTR390
  components/sensor/images/ltr390-full.jpg
  components/sensor/ltr390.rst
  images/ltr390.jpg
Labels: has-parent, next

#1206 Document support for Waveshare 7.5in "version C" bichromatic e-paper display
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#1273 Add ESP-EYE config for esp32_camera component
  components/esp32_camera.rst
Labels: current

#1214 additional speed level topics for speed fan
  components/fan/index.rst
Labels: has-parent, next

#1054 Adding docs to new scan results text sensor.
  components/text_sensor/wifi_info.rst
Labels: has-parent, next

#1237 Add SSD1305 support and few new options to SSD1306 integration
  components/display/ssd1306.rst
Labels: has-parent, next

#1492 Updates b-parasite docs with light sensor information
  components/sensor/b_parasite.rst
  index.rst
Labels: has-parent, next

#1488 Add support for rgb support on tuya lights
  components/light/tuya.rst
Labels: has-parent, next

#1482 fan.cycle_speed docs
  components/fan/index.rst
Labels: has-parent, next

#1388 Modbus controller docs
  components/binary_sensor/modbus_controller.rst
  components/fan/hbridge.rst
  components/modbus.rst
  components/modbus_controller.rst
  components/number/modbus_controller.rst
  components/output/modbus_controller.rst
  components/sensor/modbus_controller.rst
  components/switch/modbus_controller.rst
  components/text_sensor/modbus_controller.rst
  cookbook/images/tracer-an.jpg
  cookbook/tracer-an.rst
  images/esp32-modbus.jpg
  images/modbus.png
  images/rs485.jpg
  images/tracer-an.jpg
  index.rst
Labels: has-parent, next

#905 Current based cover
  components/cover/current_based.rst
  components/cover/images/shelly2.5.png
  index.rst
Labels: has-parent, next

#1189 Add cover toggle support
  components/cover/index.rst
Labels: has-parent, next

#1496 2021.9.2
  Doxygen
  Makefile
  _static/version
  changelog/2021.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1499 Add links to security advisory and commit
  changelog/2021.9.0.rst
Labels: current

#1429 Add docs for SCD4X
  components/sensor/images/scd4x.jpg
  components/sensor/scd4x.rst
  images/scd4x.jpg
  index.rst
Labels: has-parent, next

#1495 Support for HSV color on Tuya light
  components/light/tuya.rst
Labels: has-parent, next

#1500 Fix typo
  components/sensor/xiaomi_ble.rst
Labels: current

#1466 Add documentation for new Tuya cover component
  components/cover/tuya.rst
  index.rst
Labels: has-parent, next

#1497 text sensor filter documentation
  components/text_sensor/index.rst
Labels: has-parent, next
