Repository esphome/esphome-docs, pull requests merged in 2021-02, with the labels that each got.

#976 1.16.0b7
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/sensor/scd30.rst
  conf.py
  guides/supporters.rst
Labels: beta, has-parent

#980 1.16.0b8
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  conf.py
  guides/supporters.rst
Labels: beta, has-parent

#657 Adding documentation for Inkbird IBS-TH1 Mini sensor
  components/sensor/images/inkbird_isbth1_mini-full.jpg
  components/sensor/images/inkbird_isbth1_mini-ui.png
  components/sensor/images/inkbird_isbth1_mini.png
  components/sensor/inkbird_ibsth1_mini.rst
  images/inkbird_isbth1_mini.jpg
  index.rst
Labels: integration: inkbird_ibsth1_mini

#889 Add MCP4725 docs
  components/output/mcp4725.rst
  images/mcp4725.jpg
  index.rst
Labels: has-parent, next

#989 Fix format consistency
  components/binary_sensor/mpr121.rst
  components/canbus.rst
  components/climate/tuya.rst
  components/ethernet.rst
  components/fan/speed.rst
  components/fan/tuya.rst
  components/light/index.rst
  components/mcp23Sxx.rst
  components/mqtt.rst
  components/output/template.rst
  components/remote_transmitter.rst
  components/sensor/as3935.rst
  components/sx1509.rst
  components/wifi.rst
Labels: next

#707 Added Energy sensor to hlw8012
  components/sensor/hlw8012.rst
Labels: has-parent, next

#728 MCP230xx open drain interrupt pins
  components/mcp230xx.rst
Labels: has-parent, next

#992 Fix API Reference link for display buffer
  cookbook/display_time_temp_oled.rst
Labels: current

#974 Fix humidity typo
  components/sensor/scd30.rst
Labels: current

#942 Update waveshare_epaper.rst
  components/display/waveshare_epaper.rst
Labels: current

#991 Fix st7735 yaml example
  components/display/st7735.rst
Labels: current

#1001 1.16.1
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/mcp230xx.rst
  components/sensor/hlw8012.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1000 ST7735 Changed configuration items to snake_case
  components/display/st7735.rst
Labels: has-parent, next

#1004 Incomplete sentence
  components/deep_sleep.rst
Labels: current

#996 Add doc for device_class attribute of sensor
  components/sensor/index.rst
Labels: has-parent, next

#995 Add sleep duration to enter deep sleep action
  components/deep_sleep.rst
Labels: has-parent, next

#1008 Make explicit examples for splitting and joining using partitions
  components/light/partition.rst
Labels: current

#1013 Title for Connecting your device to Home Assistant
  guides/getting_started_hassio.rst
Labels: current

#1010 Added documentation for Waveshare 2.90inch V2 e-ink display
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#983 Add reverse_enable for max7219
  components/display/max7219.rst
Labels: has-parent, next

#1022 1.16.2
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/display/max7219.rst
  components/display/waveshare_epaper.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1020 Update esp32_camera.rst
  components/esp32_camera.rst
Labels: current

#1019 Add another project to diy.rst
  guides/diy.rst
Labels: current

#1018 Update esphome-configs URL
  guides/diy.rst
Labels: current

#1011 Icon is ignored by HA when device class is set
  components/sensor/index.rst
Labels: has-parent, next

#1006 Update pid.rst
  components/climate/pid.rst
Labels: current

#975 Mention that Hyperion.NG works with E1.31
  components/light/index.rst
Labels: current

#1021 Add docs for Xiaomi Miscale v1 and v2
  components/sensor/images/xiaomi_miscale.jpg
  components/sensor/images/xiaomi_miscale2.jpg
  components/sensor/xiaomi_miscale.rst
  components/sensor/xiaomi_miscale2.rst
  images/xiaomi_miscale.jpg
  images/xiaomi_miscale2.jpg
  index.rst
Labels: has-parent, next

#1029 Add missing closing parenthesis in example
  components/display/st7789v.rst
Labels: current

#1026 Update Inkplate.rst
  components/display/Inkplate.rst
Labels: current

#1025 typo in st7735 model number
  components/display/st7735.rst
Labels: current

#1017 Fix mcp23sXX id config
  components/mcp23Sxx.rst
Labels: current, integration: mcp23Sxx

#1007 Update bme680.rst
  components/sensor/bme680.rst
Labels: current

#1027 Sim800l dial
  components/sim800l.rst
Labels: has-parent, next

#679 Update vl53l0x docs
  changelog/v1.14.0.rst
  components/sensor/images/vl53l0x.png
  components/sensor/vl53l0x.rst
  images/vl53l0x.png
  images/vl53l0x.svg
  index.rst
Labels: integration: vl53l0x

#986 Document recurring data in uart switch
  components/switch/uart.rst
Labels: has-parent, next

#904 Added remote samsung36 protocol docs
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, wrong-base-branch

#947 Add IWOOLE Table Lamp cookbook entry
  cookbook/images/iwoole_rgbw_table_lamp.png
  cookbook/images/iwoole_rgbw_table_lamp_connections_bottom.jpg
  cookbook/images/iwoole_rgbw_table_lamp_connections_top.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_1.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_2.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_3.jpg
  cookbook/images/iwoole_rgbw_table_lamp_wires_bottom.jpg
  cookbook/images/iwoole_rgbw_table_lamp_wires_top.jpg
  cookbook/iwoole_rgbw_table_lamp.rst
  images/iwoole_rgbw_table_lamp.png
  index.rst
Labels: current

#1031 Update uart.rst example to read all available characters
  components/text_sensor/uart.rst
Labels: current
