Repository esphome/esphome-docs, pull requests merged in 2021-08, with the labels that each got.

#1355 Add note about uart parity on 1.21.0 and above
  components/uart.rst
Labels: has-parent, next

#1343 Select docs
  components/index.rst
  components/select/index.rst
  components/select/template.rst
  index.rst
Labels: has-parent, next

#1357 FloatOutput: Documenting zero_means_zero
  components/output/index.rst
Labels: has-parent, next

#1339 Thermostat enhancements doc updates
  components/climate/thermostat.rst
Labels: has-parent, next, parent-merged

#1359 correct wrong example parameter
  components/display/st7735.rst
Labels: current

#1353 Adding references to other already existing tuya components
  components/tuya.rst
Labels: current

#1352 Improve documentation with information about modbus_id variable
  components/sensor/pzemac.rst
Labels: current

#1055 Add support for Waveshare E-Paper 4.2" B V2
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#1085 added min_save_interval to total_daily_energy and integration to keep wear on memory low
  components/sensor/integration.rst
  components/sensor/total_daily_energy.rst
Labels: has-parent, next

#1363 Fix range parameters for light.addressable_set
  components/light/index.rst
Labels: current

#1340 A few format consistency issues
  components/binary_sensor/nextion.rst
  components/light/tuya.rst
  components/sensor/havells_solar.rst
  components/sensor/nextion.rst
  components/sensor/teleinfo.rst
  components/text_sensor/nextion.rst
  index.rst
Labels: current

#1365 1.20.4
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1367 Add device_class to example config.
  cookbook/temt6000.rst
Labels: current

#1373 Update hero image
  images/hero.png
Labels: current

#1350 Documentation for hitachi_ac424
  components/climate/ir_climate.rst
Labels: has-parent, next

#1368 Anova fahrenheit support
  components/climate/anova.rst
Labels: has-parent, next

#1376 Fix Template Switch Lamda Example
  components/switch/template.rst
Labels: current

#1296 Update Toshiba doc for new Toshiba AC IR protocol
  components/climate/ir_climate.rst
Labels: has-parent, next

#1362 Add Dish Network protocol to remote receiver/transmitter
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1361 Add config option docs for disabled_by_default
  components/binary_sensor/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/esp32_camera.rst
  components/fan/index.rst
  components/light/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text_sensor/index.rst
Labels: has-parent, next

#1347 Docs - Split sensors into categories
  changelog/v1.14.0.rst
  components/sensor/images/pzem-ac.png
  components/sensor/images/pzem-dc.png
  components/sensor/pzemac.rst
  components/sensor/pzemdc.rst
  github.py
  guides/contributing.rst
  images/pzem-ac.png
  images/pzem-dc.png
  images/pzemac.svg
  images/pzemdc.svg
  index.rst
Labels: next

#1091 CGPR1 documentation
  components/sensor/images/xiaomi_cgpr1.png
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1354 Add status_led light platform
  components/light/status_led.rst
  components/status_led.rst
  index.rst
Labels: has-parent, next

#1360 Thermostat enhancements 2 doc update
  components/climate/thermostat.rst
Labels: has-parent, next

#973 Add docs and images for PMSA003i
  components/sensor/images/pmsa003i-full.jpg
  components/sensor/pmsa003i.rst
  images/pmsa003i.jpg
  index.rst
Labels: has-parent, next, parent-merged

#1370 document support for TSL2591
  components/sensor/images/tsl2591-ui.jpg
  components/sensor/images/tsl2591.jpg
  components/sensor/tsl2591.rst
  images/tsl2591.jpg
  index.rst
Labels: has-parent, next, parent-merged

#1377 Number Template: Clarify how to get value in set_action
  components/number/template.rst
Labels: current

#1372 Add note about RS485 converter
  components/sensor/sdm_meter.rst
Labels: current

#1378 Update automations.rst
  guides/automations.rst
Labels: current

#1366 Add FAQ advising against underscores in hostnames.
  guides/faq.rst
Labels: has-parent, current

#1364 Add dsmr component
  components/sensor/dsmr.rst
  images/dsmr.svg
  index.rst
Labels: has-parent, next, parent-merged

#1084 Feature pipsolar anh
  components/images/pipsolar.jpg
  components/pipsolar.rst
  images/pipsolar.jpg
  index.rst
Labels: has-parent, next

#1348 Add documentation for deassert_rts_dtr option
  components/logger.rst
Labels: has-parent, next

#1134 Am43 component docs
  components/cover/am43.rst
  components/cover/images/am43.jpg
  components/sensor/am43.rst
  components/sensor/images/am43.jpg
  images/am43.jpg
  index.rst
Labels: has-parent, next

#1277 Support for the DKE screen version of LilyGo-TTGO-T5 V2.3
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#1333 Add docs for sdp3x component
  components/sensor/images/sdp31.jpg
  components/sensor/sdp3x.rst
  images/sdp31.jpg
  index.rst
Labels: has-parent, next, parent-merged

#1220 components/display/waveshare_epaper: b74 variant
  components/display/waveshare_epaper.rst
Labels: has-parent, next, parent-merged

#1102 pmsx003: add config options for extra sensor data points
  components/sensor/pmsx003.rst
Labels: has-parent, next, parent-merged

#1389 Add Toshiba AC doc
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, parent-merged

#1387 Update v1.20.0.rst
  changelog/v1.20.0.rst
Labels: current

#1385 Update total_daily_energy.rst
  components/sensor/total_daily_energy.rst
Labels: current

#1392 1.21.0b2
  Doxygen
  Makefile
  _static/changelog-1.21.0.png
  _static/version
  changelog/v1.20.0.rst
  changelog/v1.21.0.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/total_daily_energy.rst
  conf.py
  guides/supporters.rst
Labels: has-parent, beta

#1328 Color mode documentation
  components/light/custom.rst
  components/light/cwww.rst
  components/light/hbridge.rst
  components/light/index.rst
  components/light/neopixelbus.rst
  components/light/rgbw.rst
  components/light/rgbww.rst
  components/light/tuya.rst
Labels: has-parent, next

#1393 Add method option to the total daily energy sensor
  components/sensor/total_daily_energy.rst
Labels: has-parent, next

#1397 Change state to position in cover docs
  components/cover/index.rst
Labels: current

#1396 Clarify some color temperature settings
  components/light/color_temperature.rst
  components/light/cwww.rst
  components/light/rgbct.rst
  components/light/rgbww.rst
Labels: next

#1394 Sort sensors & sensor categories alphabetically
  index.rst
Labels: next

#1398 1.21.0b3
  Doxygen
  Makefile
  _static/version
  changelog/v1.21.0.rst
  components/cover/index.rst
  components/light/color_temperature.rst
  components/light/custom.rst
  components/light/cwww.rst
  components/light/hbridge.rst
  components/light/index.rst
  components/light/neopixelbus.rst
  components/light/rgbct.rst
  components/light/rgbw.rst
  components/light/rgbww.rst
  components/light/tuya.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: has-parent, beta

#1402 Fix change banner
  _templates/layout.html
Labels: current

#1403 Update hero image to fix typos
  images/hero.png
Labels: current

#1382 Fix on-boot
  components/esphome.rst
  components/mqtt.rst
Labels: has-parent, current

#1409 Update thermostat example yaml
  components/climate/thermostat.rst
Labels: current

#1410 Fixing 404 link in DIY Examples
  guides/diy.rst
Labels: current

#1413 Fix log message for select docs
  components/select/index.rst
Labels: current

#1414 fix-bump-version
  script/bump-version.py
Labels: next

#1415 2021.8.1
  Doxygen
  Makefile
  _static/version
  changelog/2021.8.0.rst
  conf.py
  guides/supporters.rst
  script/bump-version.py
Labels: current

#1406 ST7789V: Document that backlight_pin is now optional
  components/display/st7789v.rst
Labels: has-parent, next

#1418 Remove custom uart text sensor from table
  index.rst
Labels: current

#1416 Update Nextion Editor URL
  components/display/nextion.rst
Labels: current

#1412 Update devices documentation
  components/esphome.rst
  devices/esp32.rst
  devices/esp8266.rst
  devices/nodemcu_esp8266.rst
  devices/sonoff.rst
  devices/sonoff_basic.rst
Labels: current

#1391 Update diy.rst
  guides/diy.rst
Labels: current

#1419 Fix CO2 spelling inconsistency
  index.rst
Labels: current

#1422 2021.8.2
  Doxygen
  Makefile
  _static/version
  changelog/2021.8.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1426 Add missing word
  components/sensor/ade7953.rst
  components/sensor/pzem004t.rst
  components/sensor/pzemac.rst
  components/sensor/pzemdc.rst
Labels: current

#1427 Fixed hrefs
  components/esphome.rst
Labels: current

#1424 Fix waveshare default update_interval to 1s
  components/display/waveshare_epaper.rst
Labels: current

#1433 Document fan hbridge component
  components/fan/hbridge.rst
  components/fan/images/L298N_module.jpg
  index.rst
Labels: has-parent, next

#1081 docs: Add airthings wave plus docs
  components/sensor/airthings_ble.rst
  components/sensor/images/airthings_wave_plus.jpg
  images/airthings_logo.png
  index.rst
Labels: has-parent, next

#1420 Document flash_transition_length
  components/light/index.rst
Labels: has-parent, next
