Repository esphome/esphome-docs, pull requests merged in 2021-03, with the labels that each got.

#1036 Migrate ESPColor to Color
  components/light/index.rst
Labels: has-parent, next

#993 Added documentation for the SM300D2 sensor
  components/sensor/images/sm300d2-full.jpg
  components/sensor/images/sm300d2-pins.jpg
  components/sensor/images/sm300d2-ui.png
  components/sensor/sm300d2.rst
  images/sm300d2.jpg
  index.rst
Labels: has-parent, next

#1038 Added new blogpost
  guides/diy.rst
Labels: current

#1032 Document new min/max filters
  components/sensor/index.rst
Labels: has-parent, next

#1039 Uart invert option for ESP32
  components/uart.rst
Labels: has-parent, next

#1044 add-black
  .pre-commit-config.yaml
  conf.py
  github.py
  script/bump-version.py
  seo.py
  setup.cfg
  sitemap.py
  svg2png.py
  travis.py
Labels: next

#1028 Update MCP23XXX docs with interrupts and pin schemas
  components/mcp230xx.rst
  components/mcp23Sxx.rst
Labels: has-parent, next

#1030 Dump schema
  conf.py
  markdown.py
  schema_doc.py
Labels: has-parent, next

#1043 Update i2c.rst
  components/i2c.rst
Labels: current

#1042 Update rf_bridge.rst
  components/rf_bridge.rst
Labels: current

#1045 Fix RF Bridge link to Portisch Repo
  components/rf_bridge.rst
Labels: current

#1047 pin schema and other fixes
  components/mcp230xx.rst
  components/pcf8574.rst
  components/sn74hc595.rst
  components/sx1509.rst
  schema_doc.py
Labels: next

#966 Adding that mpr121_id is a valid option for binary_sensor
  components/binary_sensor/mpr121.rst
Labels: current

#1052 schema-filters
  components/binary_sensor/index.rst
  components/display/st7735.rst
  components/mcp230xx.rst
  components/mcp23Sxx.rst
  components/sensor/index.rst
  components/sn74hc595.rst
  guides/contributing.rst
  schema_doc.py
Labels: next

#1059 Remove cs_pin from rc522 i2c example
  components/binary_sensor/rc522.rst
Labels: current

#1060 Add CLI logs section
  guides/cli.rst
Labels: current

#804 Midea Climate support
  components/climate/midea_ac.rst
  images/midea.svg
  index.rst
Labels: Hacktoberfest, has-parent, next

#1058 Add docs for `name_add_mac_suffix` config
  components/esphome.rst
Labels: has-parent, next

#755 Add docs for addressable_light
  components/display/addressable_light.rst
  components/display/images/addressable_light.jpg
  components/display/images/addressable_light_pixel_map_8x32.png
  components/display/images/addressable_light_pixel_map_default.png
  images/addressable_light.jpg
  index.rst
Labels: has-parent, next

#900 Add documentation for pulse_meter
  components/sensor/pulse_meter.rst
  index.rst
Labels: has-parent, next

#808 Add docs for ttgo-b1 version (next branch)
  components/display/waveshare_epaper.rst
Labels: Hacktoberfest, has-parent, next

#1066 SenseAir: background calibration & ABC commands
  components/sensor/senseair.rst
Labels: has-parent, next

#1049 Add docs for http_request on_response trigger
  components/http_request.rst
Labels: has-parent, next

#1071 Fix typo lambada -> lambda in multiple display compoments
  components/display/ili9341.rst
  components/display/ssd1325.rst
  components/display/ssd1327.rst
  components/display/st7789v.rst
Labels: current

#1068 Consistent spelling of "ID"
  guides/configuration-types.rst
Labels: current

#1073 Change GREYSCALE to GRAYSCALE
  components/display/index.rst
Labels: current

#876 Update CGG1 documentation around bindkey
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#897 Add i2c multiplexer
  components/i2c.rst
  components/images/tca9548a.jpg
  components/tca9548a.rst
  images/tca9548a.jpg
  index.rst
Labels: has-parent, next

#1076 SPI: fix Example
  components/spi.rst
Labels: current
