Repository esphome/esphome-docs, pull requests merged in 2021-01, with the labels that each got.

#896 added slow mode and detach time to servo
  components/servo.rst
Labels: has-parent, next

#913 Update diy.rst
  guides/diy.rst
Labels: current

#901 Add note about default settings in remote transmitter
  components/remote_transmitter.rst
Labels: current

#608 st7735 Docs
  components/display/images/st7735.jpg
  components/display/st7735.rst
  images/st7735.jpg
  index.rst
Labels: integration: st7735

#919 Bump 1.17.0 dev
  Doxygen
  _static/version
  components/remote_transmitter.rst
  components/sensor/apds9960.rst
  conf.py
  devices/sonoff_basic.rst
  guides/diy.rst
Labels: has-parent, next

#910 DS1307 real time clock component
  components/time.rst
  guides/automations.rst
Labels: has-parent

#925 Bump changelog index to 1.16.0
  changelog/index.rst
Labels: beta

#931 1.16.0b2
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/time.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
Labels: beta, has-parent

#909 fixed duplicate id in example for dac output
  components/output/esp32_dac.rst
Labels: current

#923 Add example for human readable uptime sensor
  components/sensor/uptime.rst
Labels: current

#922 Update diy.rst
  guides/diy.rst
Labels: current

#928 Spelling and grammar fixes
  components/api.rst
  components/dfplayer.rst
  components/display/lcd_display.rst
  components/display/max7219digit.rst
  components/display/tm1637.rst
  components/light/cwww.rst
  components/light/index.rst
  components/light/neopixelbus.rst
  components/light/rgbw.rst
  components/logger.rst
  components/ota.rst
  components/remote_receiver.rst
  components/sensor/ads1115.rst
  components/sensor/bh1750.rst
  components/sensor/custom.rst
  components/spi.rst
  components/text_sensor/uart.rst
  cookbook/arduino_port_extender.rst
  cookbook/ifan02.rst
  cookbook/infostrip.rst
  devices/sonoff_t1_uk_3gang_v1.1.rst
  devices/sonoff_t3_eu_3gang_v1.0.rst
  guides/automations.rst
  guides/contributing.rst
Labels: current

#927 Fix duplicated "on_ble" in on_ble_service_data_advertise heading
  components/esp32_ble_tracker.rst
Labels: current

#914 Add hint for swapped data and clock pin
  components/sensor/zyaura.rst
Labels: current

#912 Update nextion.rst
  components/display/nextion.rst
Labels: current

#911 Update mirabella-genio-bulb.rst to show potential use of GPIO14 instead of GPIO13 for specific monochromatic dimmable globes
  cookbook/mirabella-genio-bulb.rst
Labels: current

#933 add rc522 i2c config variant
  components/binary_sensor/rc522.rst
Labels: has-parent, next

#937 add cli link
  guides/getting_started_command_line.rst
Labels: current

#874 Updated Mcp3008 to support reference_voltage and voltage_sampler::VoltageSampler
  changelog/v1.15.0.rst
  components/sensor/images/mcp3008.jpg
  components/sensor/mcp3008.rst
  images/mcp3008.jpg
  images/mcp3008.png
  index.rst
Labels: has-parent, next

#939 cli.rst add --help
  guides/cli.rst
Labels: current

#936 Add docs for pn532 NDEF functionality
  components/binary_sensor/pn532.rst
Labels: has-parent, next

#778 Adding Inkplate 6 docs
  components/display/Inkplate.rst
  components/display/images/Inkplate.jpg
  images/Inkplate.jpg
  index.rst
Labels: has-parent, next

#946 1.16.0b4
  Doxygen
  Makefile
  _static/version
  changelog/v1.15.0.rst
  changelog/v1.16.0.rst
  components/binary_sensor/pn532.rst
  components/binary_sensor/rc522.rst
  components/display/Inkplate.rst
  components/display/images/Inkplate.jpg
  components/sensor/images/mcp3008.jpg
  components/sensor/mcp3008.rst
  conf.py
  guides/cli.rst
  guides/getting_started_command_line.rst
  guides/supporters.rst
  images/Inkplate.jpg
  images/mcp3008.jpg
  images/mcp3008.png
  index.rst
Labels: beta, has-parent

#924 update time (sync) documentation
  components/time.rst
  guides/automations.rst
Labels: has-parent, next

#955 Add directions for handling text strings
  components/display/index.rst
Labels: current

#956 fix typo 5062 => 6052
  guides/faq.rst
Labels: current

#954 Fix of typo in documentation of SPS30
  components/sensor/sps30.rst
Labels: current

#953 Remove reference to measuring humidity
  components/sensor/tmp117.rst
Labels: current

#949 Fix human-readable uptime example so it compiles
  components/sensor/uptime.rst
Labels: current

#960 1.16.0b5
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/display/index.rst
  components/sensor/sps30.rst
  components/sensor/tmp117.rst
  components/sensor/uptime.rst
  components/time.rst
  conf.py
  guides/automations.rst
  guides/faq.rst
  guides/supporters.rst
Labels: beta, has-parent

#963 Added docs for esphome/esphome#1470
  components/climate/ir_climate.rst
Labels: has-parent, next

#958 Add link to baseboard thermostat by rjmurph2241
  guides/diy.rst
Labels: current

#951 Document color_temp
  web-api/index.rst
Labels: current, has-parent

#950 Update tuya.rst
  components/light/tuya.rst
Labels: current

#948 Minor uptime docs fixes
  components/sensor/uptime.rst
Labels: current

#945 Update image type for st7789 display
  components/display/st7789v.rst
Labels: current

#957 Add MHO-C401
  components/sensor/images/xiaomi_mhoc401.jpg
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#965 1.16.0b6
  Doxygen
  Makefile
  _static/version
  changelog/v1.16.0.rst
  components/display/st7789v.rst
  components/light/tuya.rst
  components/sensor/images/xiaomi_mhoc401.jpg
  components/sensor/uptime.rst
  components/sensor/xiaomi_ble.rst
  conf.py
  guides/diy.rst
  guides/supporters.rst
  web-api/index.rst
Labels: beta, has-parent

#970 Update scd30 docs to show sensors are optional
  components/sensor/scd30.rst
Labels: has-parent, next
