Repository esphome/esphome-docs, pull requests merged in 2021-07, with the labels that each got.

#1287 Fix link
  guides/faq.rst
Labels: current

#1282 hlw8012: add constants by sensor model
  components/sensor/hlw8012.rst
Labels: has-parent, next

#1140 Anova component docs
  components/climate/anova.rst
  images/anova.png
  index.rst
Labels: has-parent, next

#1288 add stepper accel and decel to docs
  components/stepper/index.rst
Labels: current, has-parent

#1272 Documentation for white channel changes
  components/light/index.rst
  components/light/rgbw.rst
Labels: has-parent, next

#1294 Update docs for WiFi AP using device name
  components/wifi.rst
Labels: has-parent, next

#1263 Add documentation for ota automation triggers.
  components/ota.rst
  guides/automations.rst
Labels: has-parent, next

#1299 Fix copy/paste error in light documentation
  components/light/index.rst
Labels: current

#1275 Update xiaomi_miscale.rst
  components/sensor/xiaomi_miscale.rst
Labels: current

#1274 Update xiaomi_miscale2.rst
  components/sensor/xiaomi_miscale2.rst
Labels: current

#1257 DIY examples: add ESPHome Heart Rate Display configuration
  guides/diy.rst
Labels: current

#1283 Add number and template number docs
  components/index.rst
  components/number/index.rst
  components/number/template.rst
  guides/automations.rst
  index.rst
Labels: has-parent, next

#1302 Update netlify python version
  runtime.txt
Labels: current

#1289 Add support for IBS-TH1 External Sensor
  components/sensor/inkbird_ibsth1_mini.rst
Labels: has-parent, next

#982 Updated documentation for the SGP30 sensor improvements.
  components/sensor/sgp30.rst
Labels: has-parent, next

#1303 Fix logo
  Dockerfile
  requirements.txt
Labels: current

#1291 Documentation for Havells solar
  components/sensor/havells_inverter.rst
  components/sensor/images/havellsgti5000d.jpg
  images/havellsgti5000d_s.jpg
  index.rst
Labels: has-parent, next

#1304 Add a note about minimum python version
  guides/getting_started_command_line.rst
Labels: current, has-parent

#1305 1.20.0b1
  Doxygen
  Makefile
  _static/changelog-1.20.0.png
  _static/version
  changelog/index.rst
  changelog/v1.20.0.rst
  components/climate/anova.rst
  components/climate/ir_climate.rst
  components/index.rst
  components/light/index.rst
  components/light/rgbw.rst
  components/number/index.rst
  components/number/template.rst
  components/ota.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/havells_inverter.rst
  components/sensor/hlw8012.rst
  components/sensor/images/havellsgti5000d.jpg
  components/sensor/inkbird_ibsth1_mini.rst
  components/sensor/sgp30.rst
  components/wifi.rst
  conf.py
  guides/automations.rst
  guides/getting_started_hassio.rst
  guides/supporters.rst
  images/anova.png
  images/havellsgti5000d_s.jpg
  index.rst
Labels: beta, has-parent

#934 Nextion update
  components/binary_sensor/nextion.rst
  components/display/nextion.rst
  components/sensor/images/nextion.jpg
  components/sensor/nextion.rst
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
  index.rst
Labels: has-parent, next

#1306 Build docs docker image when certain files change
  .github/workflows/docker.yml
Labels: current

#1292 remove note about logging on ESP8266
  components/sensor/custom.rst
Labels: current

#1307 1.20.0b2
  .github/workflows/docker.yml
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  components/binary_sensor/nextion.rst
  components/display/nextion.rst
  components/sensor/custom.rst
  components/sensor/images/nextion.jpg
  components/sensor/nextion.rst
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
  conf.py
  index.rst
Labels: beta, has-parent

#1312 1.20.0b3
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  conf.py
  guides/supporters.rst
Labels: beta, has-parent

#1309 Corrected value for "inverted"
  components/switch/gpio.rst
Labels: current

#1195 Document the cover REST calls
  web-api/index.rst
Labels: current, has-parent

#1097 Add the documentation for the on_page_change display trigger
  components/display/index.rst
  guides/automations.rst
Labels: current, has-parent

#1314 Add initial_value to template number
  components/number/template.rst
Labels: has-parent, next

#1317 1.20.0b4
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  components/display/index.rst
  components/number/template.rst
  components/switch/gpio.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  web-api/index.rst
Labels: beta, has-parent

#1318 Add creators page link
  index.rst
Labels: current

#1319 Add restore_value to template number docs
  components/number/template.rst
Labels: has-parent, next

#1320 1.20.0b5
  Doxygen
  Makefile
  _static/version
  changelog/images/online-indicator.png
  changelog/v1.20.0.rst
  components/number/template.rst
  conf.py
  index.rst
Labels: beta, has-parent

#1316 Add last_reset_type to sensor core docs
  components/sensor/index.rst
Labels: has-parent, next

#1321 1.20.0b6
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  components/sensor/index.rst
  conf.py
  guides/supporters.rst
Labels: beta, has-parent

#1322 1.20.0
  Doxygen
  Makefile
  _static/changelog-1.20.0.png
  _static/version
  changelog/images/online-indicator.png
  changelog/index.rst
  changelog/v1.20.0.rst
  components/binary_sensor/nextion.rst
  components/climate/anova.rst
  components/climate/ir_climate.rst
  components/display/nextion.rst
  components/index.rst
  components/light/index.rst
  components/light/rgbw.rst
  components/number/index.rst
  components/number/template.rst
  components/ota.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/havells_inverter.rst
  components/sensor/hlw8012.rst
  components/sensor/images/havellsgti5000d.jpg
  components/sensor/images/nextion.jpg
  components/sensor/index.rst
  components/sensor/inkbird_ibsth1_mini.rst
  components/sensor/nextion.rst
  components/sensor/sgp30.rst
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
  components/wifi.rst
  conf.py
  guides/automations.rst
  guides/getting_started_hassio.rst
  guides/supporters.rst
  images/anova.png
  images/havellsgti5000d_s.jpg
  index.rst
Labels: current, has-parent

#1311 Thermostat doc update for esphome/esphome#2032
  components/climate/thermostat.rst
Labels: has-parent, next

#1290 PVVX MiThermometer component documentation
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1295 Documentation for Selec meter
  components/sensor/images/selec_meter_em2m.jpg
  components/sensor/selec_meter.rst
  images/selec_meter_em2m.jpg
  index.rst
Labels: has-parent, next

#1324 Fix a bunch of typos
  components/binary_sensor/nextion.rst
  components/binary_sensor/rc522.rst
  components/canbus.rst
  components/climate/thermostat.rst
  components/display/max7219digit.rst
  components/ethernet.rst
  components/light/index.rst
  components/ota.rst
  components/remote_receiver.rst
  components/rf_bridge.rst
  components/sensor/b_parasite.rst
  components/sensor/bh1750.rst
  components/sensor/cs5460a.rst
  components/sensor/havells_inverter.rst
  components/sensor/mcp3008.rst
  components/sensor/nextion.rst
  components/sensor/qmc5883l.rst
  components/sensor/ruuvitag.rst
  components/sensor/teleinfo.rst
  components/sensor/tmp102.rst
  components/switch/nextion.rst
  components/tca9548a.rst
  components/text_sensor/nextion.rst
  components/time.rst
  components/wifi.rst
  cookbook/ble_itag.rst
  cookbook/infostrip.rst
  guides/contributing.rst
  schema_doc.py
Labels: current

#1325 Update logger.rst
  components/logger.rst
Labels: current

#1330 Fix duplicate sentence
  components/sensor/pulse_counter.rst
Labels: current

#1329 Mark required fields for endstop cover as required
  components/cover/endstop.rst
Labels: current

#1331 Note lack of Anova Nano support
  components/climate/anova.rst
Labels: current, has-parent

#1141 New cookbook entry for Ilonda Wifi Smart Fish Feeder (L88)
  cookbook/ilonda-wifi-smart-fish-feeder.rst
  cookbook/images/ilonda-wifi-smart-fish-feeder-cookbook.jpg
  cookbook/images/ilonda-wifi-smart-fish-feeder.jpg
  images/ilonda-wifi-smart-fish-feeder-cookbook.jpg
  index.rst
Labels: current

#1335 Add missed breaking change to section
  changelog/v1.20.0.rst
Labels: current

#1334 Add new climate modes to climate/index.rst
  components/climate/index.rst
Labels: current

#1338 1.20.1
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#1315 docs for pm1006 component
  components/sensor/images/ikea-vindriktning.jpg
  components/sensor/pm1006.rst
  images/pm1006.jpg
  index.rst
Labels: has-parent, next

#1327 Use lowercase true/false values
  components/binary_sensor/esp32_touch.rst
  components/binary_sensor/gpio.rst
  components/binary_sensor/nextion.rst
  components/binary_sensor/xpt2046.rst
  components/canbus.rst
  components/climate/ir_climate.rst
  components/climate/midea_ac.rst
  components/climate/tuya.rst
  components/cover/time_based.rst
  components/dfplayer.rst
  components/display/inkplate6.rst
  components/display/max7219.rst
  components/display/max7219digit.rst
  components/display/st7735.rst
  components/esphome.rst
  components/i2c.rst
  components/light/index.rst
  components/light/rgbw.rst
  components/mcp230xx.rst
  components/mcp23Sxx.rst
  components/mqtt.rst
  components/ota.rst
  components/output/ac_dimmer.rst
  components/output/index.rst
  components/output/mcp4725.rst
  components/pcf8574.rst
  components/remote_receiver.rst
  components/sensor/sgp40.rst
  components/sensor/teleinfo.rst
  components/sensor/vl53l0x.rst
  components/sn74hc595.rst
  components/status_led.rst
  components/stepper/index.rst
  components/switch/index.rst
  components/sx1509.rst
  components/tca9548a.rst
  components/text_sensor/version.rst
  components/uart.rst
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
  cookbook/display_time_temp_oled.rst
  cookbook/ifan02.rst
  cookbook/leak-detector-m5stickC.rst
  cookbook/sonoff-basic-light-switch.rst
  cookbook/sonoff-dual-light-switch.rst
  cookbook/sonoff-t1-3.rst
  devices/sonoff_4ch.rst
  devices/sonoff_4ch.yaml
  devices/sonoff_basic.rst
  devices/sonoff_s20.rst
  devices/sonoff_s20.yaml
  devices/sonoff_t1_uk_3gang_v1.1.rst
  devices/sonoff_t1_uk_3gang_v1.1.yaml
  devices/sonoff_t3_eu_3gang_v1.0.rst
  devices/sonoff_t3_eu_3gang_v1.0.yaml
  devices/teckin.yaml
  devices/teckin_sp20_us.yaml
  guides/configuration-types.rst
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
Labels: current

#1344 Fix number text
  components/number/template.rst
Labels: current

#1345 1.20.2
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent

#692 Add T6615 Dual-Channel CO2 Sensor
  components/sensor/images/t6615-pins.png
  components/sensor/images/t6615.png
  components/sensor/t6615.rst
  images/t6615.png
  index.rst
Labels: awaiting-parent, has-parent, integration: t6615, next

#1337 Add documentation for the tlc5947 LED driver.
  components/output/images/tlc5947.jpg
  components/output/tlc5947.rst
  images/tlc5947.jpg
  index.rst
Labels: has-parent, next, parent-merged

#1308 HRXL MaxSonar Sensor Series
  components/sensor/hrxl_maxsonar_wr.rst
  components/sensor/images/hrxl_maxsonar_wr-full.jpg
  images/hrxl_maxsonar_wr.jpg
  index.rst
Labels: has-parent, next

#1346 Add demo integration
  components/demo.rst
  components/images/demo-ui.png
  index.rst
Labels: has-parent, next

#1349 1.20.3
  Doxygen
  Makefile
  _static/version
  changelog/v1.20.0.rst
  conf.py
  guides/supporters.rst
Labels: current, has-parent
