Repository esphome/esphome-docs, pull requests merged in 2022-09, with the labels that each got.

#2256 2022.8.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.8.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2212 Esp32 pulsecounter optional pcnt
  components/sensor/pulse_counter.rst
Labels: has-parent, next

#2260 Document available docker tags
  guides/getting_started_command_line.rst
Labels: has-parent, next

#2268 2022.8.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.8.0.rst
  components/bluetooth_proxy.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: current

#2269 2022.8.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.8.0.rst
  conf.py
Labels: current

#2276 Update esp32_ble_tracker.rst
  components/esp32_ble_tracker.rst
Labels: current

#2274 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#2277 Add note to bluetooth proxy for min HA version
  components/bluetooth_proxy.rst
Labels: current

#2242 Add doc for tm1621 LCD display
  components/display/images/tm1621-full.jpg
  components/display/tm1621.rst
  images/tm1621.jpg
  index.rst
Labels: has-parent, next

#2009 Add MPL3115A2 component
  components/sensor/images/mpl3115a2-full.jpg
  components/sensor/mpl3115a2.rst
  images/mpl3115a2.jpg
  index.rst
Labels: stale, has-parent, next

#2286 Added documentation for bl0942
  components/sensor/bl0942.rst
  images/bl0942.png
  index.rst
Labels: has-parent, next

#2280 Add Factory Reset button and switch
  components/button/factory_reset.rst
  components/button/images/factory-rst-ui.png
  components/button/restart.rst
  components/button/safe_mode.rst
  components/button/shutdown.rst
  components/switch/factory_reset.rst
  components/switch/images/factory-rst-ui.png
  components/switch/restart.rst
  components/switch/safe_mode.rst
  components/switch/shutdown.rst
  index.rst
Labels: has-parent, next

#1991 Added documentation for TM1638 Led and Key module
  components/display/images/tm1638-full.jpg
  components/display/tm1638.rst
  images/tm1638.jpg
  index.rst
Labels: has-parent, next, not-stale

#2290 remove temperature unit from example
  components/climate/index.rst
Labels: current

#2216 feedback cover: fix typo
  components/cover/feedback.rst
Labels: current

#2192 esp32_ble_tracker updates for new functionality
  components/esp32_ble_tracker.rst
Labels: has-parent, next

#2295 Docs for BLE stop scan action
  components/esp32_ble_tracker.rst
Labels: has-parent, next

#2285 U-fire/ph
  components/sensor/images/ufire_ise.png
  components/sensor/ufire_ec.rst
  components/sensor/ufire_ise.rst
  images/ufire_ise.png
  index.rst
Labels: has-parent, next

#2299 2022.9.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  components/sim800l.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2298 Add note for bluetooth proxy
  components/bluetooth_proxy.rst
Labels: current

#2304 Document steps for adding a password to OTA
  components/ota.rst
Labels: current

#2307 align template sensor unit display
  components/sensor/xiaomi_miscale.rst
Labels: current

#2180 lambda example in the script section
  guides/automations.rst
Labels: stale, current

#2309 2022.9.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  components/bluetooth_proxy.rst
  components/ota.rst
  components/sensor/xiaomi_miscale.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
Labels: beta

#2310 2022.9.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2311 2022.9.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  conf.py
Labels: beta

#2297 ufire doc fixes
  components/sensor/images/ufire_ec.png
  components/sensor/images/ufire_ise.png
  components/sensor/ufire_ec.rst
  images/ufire_ec.png
  images/ufire_ise.png
Labels: current

#2314 2022.9.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2193 fix error for cover doc
  components/cover/index.rst
Labels: stale, current

#2316 Update tm1621.rst
  components/display/tm1621.rst
Labels: current

#2317 Fix Typo in Code Example
  components/cover/feedback.rst
Labels: current

#2321 Update bluetooth_proxy.rst
  components/bluetooth_proxy.rst
Labels: current

#2324 Fix use of "deprecated" terminology
  components/climate/thermostat.rst
Labels: has-parent, current

#2326 Mention that update_interval can be never
  components/sensor/template.rst
Labels: current

#2279 Add BTHome to See Also list
  components/bluetooth_proxy.rst
Labels: current

#2292 Remove deprecated settings and document new default_preset
  components/climate/thermostat.rst
Labels: has-parent, next

#2328 fixed typo's and added coma
  components/sensor/rotary_encoder.rst
Labels: current

#2333 2022.9.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current
