Repository esphome/esphome-docs, pull requests merged in 2022-05, with the labels that each got.

#2028 Allow wifi output_power down to 8.5dB
  components/wifi.rst
Labels: has-parent, next

#1954 Waveshare ePaper 7.5inch v2 alternative
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#2054 Update esp8266.rst
  components/esp8266.rst
Labels: has-parent, next

#1745 ENS210 Humidity & Temperature sensor component
  components/sensor/ens210.rst
  components/sensor/images/ens210.jpg
  images/ens210.jpg
  index.rst
Labels: has-parent, next

#1799 Document USB_CDC option of logger component
  components/logger.rst
Labels: stale, has-parent, next

#2046 Documentation for Select Enhancement PR
  components/select/index.rst
  guides/automations.rst
Labels: has-parent, next

#2049 Documentation for number enhancement PR #3429
  components/number/index.rst
  guides/automations.rst
Labels: has-parent, next

#1526 Document Scd4x environment compensation options
  components/sensor/scd4x.rst
Labels: stale, has-parent, next

#2017 Sen5x docs
  components/sensor/images/jst6pin.png
  components/sensor/images/sen54-web.png
  components/sensor/images/sen54.png
  components/sensor/sen5x.rst
  images/sen54.jpg
  index.rst
Labels: has-parent, next

#1493 Add docs for SML
  components/images/sml-log.png
  components/sml.rst
  images/sml.svg
  index.rst
Labels: has-parent, next, not-stale

#2059 Delonghi IR Documentation - V2
  components/climate/climate_ir.rst
Labels: next

#2032 document new options for scd4x
  components/sensor/scd4x.rst
Labels: has-parent, next

#1803 Document the update_interval support and requirements for PMSX003
  components/sensor/pmsx003.rst
Labels: stale, has-parent, next

#2048 added prev_frame for animation
  components/display/index.rst
Labels: wrong-base-branch, has-parent, next

#2060 fix typo
  components/sensor/scd4x.rst
Labels: next

#2061 remove trailing quote
  components/sensor/scd4x.rst
Labels: next

#2057 Update faq.rst
  guides/faq.rst
Labels: current

#2064 Start a basic netlify _redirects file
  _redirects
  netlify.toml
Labels: current

#2002 Update automations.rst
  guides/automations.rst
Labels: current

#2065 Add docs for select has_option(...) and has_index(...)
  components/select/index.rst
Labels: has-parent, next

#2041 Update thermostat.rst
  components/climate/thermostat.rst
Labels: current

#2066 deep_sleep.allow docs
  components/deep_sleep.rst
  guides/automations.rst
Labels: has-parent, next

#2069 Add notes about Midea MAP14HS1TBL
  components/climate/climate_ir.rst
Labels: current

#2070 Copy _redirects folder to output directory
  conf.py
Labels: current

#1951 TCS34725 automatic integration times
  components/sensor/tcs34725.rst
Labels: has-parent, next

#2071 2022.5.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2073 Update Inkbird TH1 docs to show support for TH2 sensors
  components/sensor/inkbird_ibsth1_mini.rst
Labels: current

#2080 Fixed grammatical error
  components/binary_sensor/analog_threshold.rst
Labels: current

#2082 Fix mopeka pro check links
  changelog/2022.3.0.rst
  index.rst
Labels: current

#2072 Tuya status gpio support
  components/tuya.rst
Labels: has-parent, current

#2075 Add Tuya select documentation
  components/select/tuya.rst
  index.rst
Labels: has-parent, next

#2085 Revert "Tuya status gpio support"
  components/tuya.rst
Labels: current

#2084 2022.5.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2022.3.0.rst
  changelog/2022.5.0.rst
  components/binary_sensor/analog_threshold.rst
  components/sensor/inkbird_ibsth1_mini.rst
  components/tuya.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: beta

#2088 2022.5.0
  Doxygen
  Makefile
  _static/changelog-2022.5.0.png
  _static/version
  changelog/2022.5.0.rst
  changelog/index.rst
  components/canbus.rst
  components/climate/bedjet.rst
  components/climate/climate_ir.rst
  components/deep_sleep.rst
  components/display/index.rst
  components/display/waveshare_epaper.rst
  components/esp8266.rst
  components/images/sml-log.png
  components/logger.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/bl0939.rst
  components/sensor/ens210.rst
  components/sensor/images/ens210.jpg
  components/sensor/images/jst6pin.png
  components/sensor/images/sen54-web.png
  components/sensor/images/sen54.png
  components/sensor/mopeka_pro_check.rst
  components/sensor/pmsx003.rst
  components/sensor/scd4x.rst
  components/sensor/sen5x.rst
  components/sensor/sps30.rst
  components/sml.rst
  components/wifi.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/bedjet.png
  images/bl0939.png
  images/ens210.jpg
  images/sen54.jpg
  images/sml.svg
  index.rst
Labels: current

#2078 Update esp32_camera.rst
  components/esp32_camera.rst
Labels: has-parent, next

#2016 Sgp4x
  _redirects
  components/sensor/sen5x.rst
  components/sensor/sgp40.rst
  components/sensor/sgp4x.rst
  cookbook/iaq_board.rst
  index.rst
Labels: has-parent, next

#2094 midea: new power_toggle action
  components/climate/midea.rst
Labels: has-parent, next

#2095 2022.5.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1966 Update thermostat documentation in line with changes for #3298
  components/climate/thermostat.rst
Labels: has-parent, next

#2099 Prometheus: include internals
  components/prometheus.rst
Labels: next

#2102 Document new Bedjet `heat_mode` config
  components/climate/bedjet.rst
Labels: has-parent, next

#2100 Add documentation for parameterized !include
  guides/faq.rst
Labels: has-parent, next
