Repository esphome/esphome-docs, pull requests merged in 2022-08, with the labels that each got.

#2191 Update FAQ to document NVS write error
  guides/faq.rst
Labels: has-parent, current

#2207 docs for PR 3676 (add address option)
  components/sensor/daly_bms.rst
Labels: has-parent, next

#2113 Fixed erroneous Nextion Sensor attributes
  components/sensor/nextion.rst
Labels: stale, current

#2210 Document existing feature for "on_value_range"
  components/sensor/index.rst
Labels: current

#2211 Updating xiaomi_ble.rst to add signal_strength to pvvx_mithermometer
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#2195 ST7789V doc update
  components/display/st7789v.rst
Labels: integration: st7789v, has-parent, next

#2213 2022.6.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2024 Adds docs for the new ble_client.ble_write Action
  components/ble_client.rst
  guides/automations.rst
Labels: has-parent, next

#2109 Document BedJet hub component
  components/climate/bedjet.rst
Labels: has-parent, next

#2214 Added documentation on selecting a specific frame in an animated gif
  components/display/index.rst
Labels: has-parent, next

#2186 Adding Whynter AC support
  components/climate/climate_ir.rst
Labels: has-parent, next

#1471 Sprinkler Controller documentation
  components/images/sprinkler-ui.jpg
  components/images/sprinkler.png
  components/sprinkler.rst
  guides/automations.rst
  images/sprinkler-variant.svg
  index.rst
Labels: has-parent, next

#2209 [Nextion] Add on_page trigger
  components/display/nextion.rst
Labels: has-parent, next

#1942 add feedback cover component
  components/cover/feedback.rst
  images/feedback_cover.svg
  index.rst
Labels: has-parent, next

#2189 Add priority to on_shutdown trigger.
  components/esphome.rst
Labels: has-parent, next

#2219 2022.8.0b1
  Doxygen
  Makefile
  _static/changelog-2022.8.0.png
  _static/version
  changelog/2022.8.0.rst
  changelog/index.rst
  components/binary_sensor/index.rst
  components/ble_client.rst
  components/climate/bedjet.rst
  components/climate/climate_ir.rst
  components/cover/feedback.rst
  components/display/index.rst
  components/display/nextion.rst
  components/display/st7789v.rst
  components/esphome.rst
  components/images/sprinkler-ui.jpg
  components/images/sprinkler.png
  components/media_player/index.rst
  components/output/dac7678.rst
  components/sensor/daly_bms.rst
  components/sensor/images/smt100.jpg
  components/sensor/integration.rst
  components/sensor/pulse_counter.rst
  components/sensor/smt100.rst
  components/sensor/total_daily_energy.rst
  components/sensor/xiaomi_ble.rst
  components/sprinkler.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/dac7678.svg
  images/feedback_cover.svg
  images/smt100.jpg
  images/sprinkler-variant.svg
  index.rst
Labels: beta

#2221 Added how to use the built-in battery voltage divider network in the Firebeetle ESP32-E
  components/sensor/adc.rst
Labels: current

#2224 2022.8.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.8.0.rst
  components/sensor/adc.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2222 document new apds9960 parameters
  components/sensor/apds9960.rst
Labels: has-parent, next

#1986 Add documentation of pvvx_mithermometer display platform
  components/display/pvvx_mithermometer.rst
  components/sensor/xiaomi_ble.rst
  index.rst
Labels: has-parent

#2225 Docs for templated ble_client.write_action
  components/ble_client.rst
Labels: has-parent, next

#2227 2022.8.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2022.8.0.rst
  components/ble_client.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2228 Update remote_transmitter.rst
  components/remote_transmitter.rst
Labels: current

#2223 Fix pca9685 example
  components/output/pca9685.rst
Labels: current

#2132 diy: add tcs34725 ambient light sensor example
  guides/diy.rst
Labels: stale, current

#2220 Added “devices” example to docker-compose notes
  guides/faq.rst
Labels: current

#2151 Adding notes about mulit-phase applications.
  components/sensor/atm90e32.rst
Labels: current

#2127 tcs34725: Add overexposure quirk note
  components/sensor/tcs34725.rst
Labels: stale, current

#2230 2022.8.0
  Doxygen
  Makefile
  _static/changelog-2022.8.0.png
  _static/version
  changelog/2022.8.0.rst
  changelog/index.rst
  components/binary_sensor/index.rst
  components/ble_client.rst
  components/climate/bedjet.rst
  components/climate/climate_ir.rst
  components/cover/feedback.rst
  components/display/index.rst
  components/display/nextion.rst
  components/display/st7789v.rst
  components/esphome.rst
  components/images/sprinkler-ui.jpg
  components/images/sprinkler.png
  components/media_player/index.rst
  components/output/dac7678.rst
  components/sensor/daly_bms.rst
  components/sensor/images/smt100.jpg
  components/sensor/integration.rst
  components/sensor/pulse_counter.rst
  components/sensor/smt100.rst
  components/sensor/total_daily_energy.rst
  components/sensor/xiaomi_ble.rst
  components/sprinkler.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/dac7678.svg
  images/feedback_cover.svg
  images/smt100.jpg
  images/sprinkler-variant.svg
  index.rst
Labels: current

#2188 hydreon: Document temperature, lens_bad and em_sat
  components/binary_sensor/hydreon_rgxx.rst
  components/sensor/hydreon_rgxx.rst
Labels: has-parent, next

#2163 wifi: document enable_btm and enable_rrm
  components/wifi.rst
Labels: has-parent, next

#2232 Fix sprinkler number example
  components/sprinkler.rst
Labels: current

#2218 Add dps310 sensor doc
  components/sensor/dps310.rst
  components/sensor/images/dps310-full.jpg
  images/dps310.jpg
  index.rst
Labels: has-parent, next

#2139 Add docs for bitmap fonts
  components/display/index.rst
Labels: stale, has-parent, next

#2233 Fix minor typo in feedback cover docs
  components/cover/feedback.rst
Labels: current

#2141 Warn against running Docker on Mac
  guides/getting_started_command_line.rst
Labels: stale, current

#2047 Instructions for mjpeg web service into Zoneminder NVRs
  components/esp32_camera_web_server.rst
Labels: current

#2126 Document how packages are merged into a configuration
  guides/configuration-types.rst
Labels: stale, has-parent, next

#2247 Add docs for bluetooth proxy
  components/bluetooth_proxy.rst
  index.rst
Labels: has-parent, next

#2217 Support for MCP9600 sensor
  components/sensor/images/mcp9600.jpg
  components/sensor/mcp9600.rst
  images/mcp9600.jpg
  index.rst
Labels: has-parent, next

#2238 Add Prometheus metrics relabeling
  components/prometheus.rst
Labels: has-parent, next

#2250 Add docs for IP101 support
  components/ethernet.rst
Labels: has-parent, next

#2239 Document BedJet Fan component
  components/climate/bedjet.rst
Labels: has-parent, next

#2243 schema-202208
  components/ble_client.rst
  components/climate/bedjet.rst
  components/esp32_camera.rst
  components/media_player/i2s_audio.rst
  components/output/dac7678.rst
  components/sensor/sgp4x.rst
  components/sensor/smt100.rst
  components/sprinkler.rst
Labels: current

#2251 Update automations.rst
  guides/automations.rst
Labels: current

#2244 updates schema generator
  markdown.py
  schema_doc.py
Labels: next

#2152 Update actions
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/stale.yml
Labels: current

#2253 Add dependabot for gh actions
  .github/dependabot.yml
Labels: current

#2249 add Mi Door Window Sensor 2 doc
  .github/dependabot.yml
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  .github/workflows/stale.yml
  components/ble_client.rst
  components/climate/bedjet.rst
  components/esp32_camera.rst
  components/esp32_camera_web_server.rst
  components/media_player/i2s_audio.rst
  components/output/dac7678.rst
  components/sensor/sgp4x.rst
  components/sensor/smt100.rst
  components/sprinkler.rst
  guides/automations.rst
Labels: has-parent, next

#2248 Feature/ibeacon rssi sensor
  components/sensor/ble_rssi.rst
Labels: has-parent, next

#2246 Add AEHA IR Protocol
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#2123 Add documentation for binary sensor map sum type
  components/sensor/binary_sensor_map.rst
Labels: has-parent, next
