Repository esphome/esphome-docs, pull requests merged in 2022-04, with the labels that each got.

#1776 document mqtt for esp-idf
  components/mqtt.rst
Labels: stale, has-parent, next

#1948 CAN Bus Updates
  components/canbus.rst
Labels: has-parent, next

#1653 Add tm1637 binarysensor documentation to existing display docs
  components/display/images/tm1637_2devices.png
  components/display/images/tm1637_3plus_devices.png
  components/display/images/tm1637_key_connections.png
  components/display/tm1637.rst
Labels: stale, has-parent, next

#1999 added protocol to Arduino-heatpumpIR page
  components/climate/climate_ir.rst
Labels: has-parent, next

#1976 Document new option for Growatt Protocol version
  components/sensor/growatt_solar.rst
Labels: has-parent, next

#2006 Add MCP3208 to MCP3204 integration
  components/sensor/mcp3204.rst
Labels: has-parent, next

#2008 Add missing note about python 3.8 min version
  changelog/2022.3.0.rst
Labels: current

#1616 Add integration hydreon_rgxx for rain sensors by Hydreon
  components/binary_sensor/hydreon_rgxx.rst
  components/sensor/hydreon_rgxx.rst
  components/sensor/images/hydreon_rg9_full.jpg
  images/hydreon_rg9.jpg
  index.rst
Labels: has-parent, next

#1896 Add docs for xiaomi_rtcgq02lm
  components/sensor/images/xiaomi_rtcgq02lm.jpg
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1878 Include documentation on Pronto receive capability
  components/remote_receiver.rst
Labels: has-parent, next

#2012 Add docs for deep_sleep until
  components/deep_sleep.rst
Labels: has-parent, next

#1995 Update xiaomi_miscale.rst
  components/sensor/xiaomi_miscale.rst
Labels: current

#1998 Added note on WAK signal for CCS811
  components/sensor/ccs811.rst
Labels: current

#1994 Add border-radius to images + dropshadow to tables
  _static/custom.css
Labels: current

#1996 added closing bracket, corrected bootloader baudrate to 74880
  devices/esp8266.rst
Labels: current

#2014 Revert table shadow added in #1994
  _static/custom.css
Labels: current

#2013 2022.4.0b1
  Doxygen
  Makefile
  _static/changelog-2022.4.0.png
  _static/version
  changelog/2022.4.0.rst
  changelog/index.rst
  components/binary_sensor/hydreon_rgxx.rst
  components/canbus.rst
  components/climate/climate_ir.rst
  components/deep_sleep.rst
  components/display/images/tm1637_2devices.png
  components/display/images/tm1637_3plus_devices.png
  components/display/images/tm1637_key_connections.png
  components/display/index.rst
  components/display/lcd_display.rst
  components/display/tm1637.rst
  components/light/images/sonoff_d1.jpg
  components/light/images/sonoff_d1_gpio0.jpg
  components/light/images/sonoff_d1_serial.jpg
  components/light/sonoff_d1.rst
  components/mqtt.rst
  components/remote_receiver.rst
  components/sensor/growatt_solar.rst
  components/sensor/hydreon_rgxx.rst
  components/sensor/images/hydreon_rg9_full.jpg
  components/sensor/images/xiaomi_rtcgq02lm.jpg
  components/sensor/mcp3204.rst
  components/sensor/qmp6988.rst
  components/sensor/xiaomi_ble.rst
  conf.py
  guides/supporters.rst
  images/hydreon_rg9.jpg
  images/qmp6988_env3.png
  images/sonoff_d1.jpg
  images/xiaomi_rtcgq02lm.jpg
  index.rst
Labels: beta

#2015 Help people that want to attach a button
  components/button/index.rst
Labels: current

#1753 Add documentation for Shelly Dimmer 2
  components/light/shelly_dimmer.rst
  images/shellydimmer2.jpg
  index.rst
Labels: stale, has-parent, next

#1508 BedJet component docs
  components/climate/bedjet.rst
  images/bedjet.png
  index.rst
Labels: has-parent, next

#2019 2022.4.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.4.0.rst
  components/button/index.rst
  components/light/shelly_dimmer.rst
  conf.py
  guides/supporters.rst
  images/shellydimmer2.jpg
  index.rst
Labels: beta

#1992 Update automations.rst
  guides/automations.rst
Labels: current

#2004 Add newer HomeAssistant actions to list of all actions
  guides/automations.rst
Labels: current

#1987 Clarification on network configuration
  components/wifi.rst
Labels: current

#1988 update component description
  components/ethernet.rst
Labels: current

#1981 Update mcp3008 to fix wrong component description
  components/sensor/mcp3008.rst
Labels: current

#1982 Clarify things about Safe Mode + links to button/switch
  components/ota.rst
Labels: current

#1979 Add information about interval.
  components/sun.rst
Labels: current

#1962 typos
  components/sensor/adc.rst
Labels: current

#1957 Update ref to esp8266 restore_from_flash
  components/switch/gpio.rst
Labels: current

#1959 Improve exponential_moving_average alpha description
  components/sensor/index.rst
Labels: current

#2005 Fixing subnet mask
  components/wifi.rst
Labels: current

#2010 Change temperature to signed
  cookbook/tracer-an.rst
Labels: current

#2018 Updating the ST7789 docs page to show limitation
  components/display/st7789v.rst
Labels: current

#1917 Add switch example with `register_type: holding`
  components/switch/modbus_controller.rst
Labels: current

#2025 Note about graph history
  components/display/index.rst
Labels: current

#2026 Adding support for the Mopeka Plus Plus sensor
  components/sensor/mopeka_pro_check.rst
Labels: wrong-base-branch, has-parent, next

#2030 2022.4.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2022.4.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2031 2022.4.0
  Doxygen
  Makefile
  _static/changelog-2022.4.0.png
  _static/version
  changelog/2022.4.0.rst
  changelog/index.rst
  components/binary_sensor/hydreon_rgxx.rst
  components/canbus.rst
  components/climate/climate_ir.rst
  components/deep_sleep.rst
  components/display/images/tm1637_2devices.png
  components/display/images/tm1637_3plus_devices.png
  components/display/images/tm1637_key_connections.png
  components/display/index.rst
  components/display/lcd_display.rst
  components/display/tm1637.rst
  components/light/images/sonoff_d1.jpg
  components/light/images/sonoff_d1_gpio0.jpg
  components/light/images/sonoff_d1_serial.jpg
  components/light/shelly_dimmer.rst
  components/light/sonoff_d1.rst
  components/mqtt.rst
  components/remote_receiver.rst
  components/sensor/growatt_solar.rst
  components/sensor/hydreon_rgxx.rst
  components/sensor/images/hydreon_rg9_full.jpg
  components/sensor/images/xiaomi_rtcgq02lm.jpg
  components/sensor/mcp3204.rst
  components/sensor/qmp6988.rst
  components/sensor/xiaomi_ble.rst
  conf.py
  guides/supporters.rst
  images/hydreon_rg9.jpg
  images/qmp6988_env3.png
  images/shellydimmer2.jpg
  images/sonoff_d1.jpg
  images/xiaomi_rtcgq02lm.jpg
  index.rst
Labels: current

#1970 Documentation for BL0939 (Sonoff Dual R3 v2)
  components/sensor/bl0939.rst
  images/bl0939.png
  index.rst
Labels: has-parent, next

#2034 Fix typos in 2022.4.0 post
  changelog/2022.4.0.rst
Labels: current

#2020 clean up beta 202204
  components/binary_sensor/hydreon_rgxx.rst
  components/canbus.rst
  components/light/shelly_dimmer.rst
  components/light/sonoff_d1.rst
  components/mqtt.rst
  components/select/modbus_controller.rst
  components/sensor/hydreon_rgxx.rst
  components/web_server.rst
  schema_doc.py
Labels: current

#2023 Fix hx711 docs.rst
  components/sensor/hx711.rst
Labels: current

#2022 added Converting a Carro Home DC Fan to ESPHome
  guides/diy.rst
Labels: current

#2003 Added informations about connection with LedFX
  components/light/index.rst
Labels: current

#1961 on_state gets only called on state change
  components/binary_sensor/index.rst
Labels: current

#1958 Update pzemac.rst
  components/sensor/pzemac.rst
Labels: current

#2033 sps30: document pr#3410
  components/sensor/sps30.rst
Labels: has-parent, next

#1927 Added RGB565 as image type
  components/display/index.rst
Labels: stale, has-parent, next
