Repository esphome/esphome-docs, pull requests merged in 2022-02, with the labels that each got.

#1874 2022.1.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.1.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1867 Add lock component documentation
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  components/index.rst
  components/lock/images/output-ui.png
  components/lock/index.rst
  components/lock/output.rst
  components/lock/template.rst
  index.rst
Labels: has-parent, next

#1853 Document device class support for Switch
  components/switch/index.rst
Labels: has-parent, next

#1879 [debug] Update debug component docs
  components/debug.rst
Labels: has-parent, next

#1857 Added RadonEye RD200 Component
  components/sensor/images/radon_eye_rd200.jpg
  components/sensor/radon_eye_ble.rst
  images/radon_eye_logo.png
  index.rst
Labels: has-parent, next

#1641 MLX90393: Add documentation
  components/sensor/images/mlx90393-full.jpg
  components/sensor/mlx90393.rst
  images/mlx90393.jpg
  index.rst
Labels: has-parent, next

#1869 Update ble_client.rst
  components/output/ble_client.rst
Labels: has-parent, current

#1884 Revert "Update ble_client.rst (#1869)"
  components/output/ble_client.rst
Labels: current

#1885 Update ble_client.rst
  components/output/ble_client.rst
Labels: has-parent, next

#1886 Add lilygo t5 4.7" touchscreen docs
  components/touchscreen/lilygo_t5_47.rst
  images/lilygo_t5_47_touch.png
  index.rst
Labels: has-parent, next

#1827 Add documentation for new modbus select
  components/select/modbus_controller.rst
  index.rst
Labels: has-parent, next

#1612 Add Max9611 Docs
  components/sensor/images/max9611.jpg
  components/sensor/max9611.rst
  images/max9611.jpg
  index.rst
Labels: has-parent, next

#1856 Describe MQTT discovery object_id generator
  components/mqtt.rst
Labels: has-parent, next

#1890 Update home assistant addon repo
  guides/faq.rst
Labels: current

#1891 2022.1.4
  Doxygen
  Makefile
  _static/version
  changelog/2022.1.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1893 2022.2.0b1
  Doxygen
  Makefile
  _static/version
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  changelog/2022.1.0.rst
  changelog/2022.2.0.rst
  changelog/index.rst
  components/button/images/generic-ui.png
  components/button/output.rst
  components/button/wake_on_lan.rst
  components/debug.rst
  components/display/index.rst
  components/display/inkplate6.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/ethernet.rst
  components/fan/hbridge.rst
  components/fan/index.rst
  components/fingerprint_grow.rst
  components/http_request.rst
  components/index.rst
  components/light/index.rst
  components/lock/images/output-ui.png
  components/lock/index.rst
  components/lock/output.rst
  components/lock/template.rst
  components/mqtt.rst
  components/network.rst
  components/output/ble_client.rst
  components/output/slow_pwm.rst
  components/select/modbus_controller.rst
  components/sensor/cd74hc4067.rst
  components/sensor/images/max9611.jpg
  components/sensor/images/mlx90393-full.jpg
  components/sensor/images/radon_eye_rd200.jpg
  components/sensor/images/xiaomi_mhoc303.jpg
  components/sensor/max9611.rst
  components/sensor/mlx90393.rst
  components/sensor/radon_eye_ble.rst
  components/sensor/tcs34725.rst
  components/sensor/tsl2591.rst
  components/sensor/xiaomi_ble.rst
  components/switch/index.rst
  components/touchscreen/ektf2232.rst
  components/touchscreen/index.rst
  components/touchscreen/lilygo_t5_47.rst
  components/wifi.rst
  conf.py
  guides/supporters.rst
  images/ektf2232.svg
  images/lilygo_t5_47_touch.png
  images/max9611.jpg
  images/mlx90393.jpg
  images/qr-code.svg
  images/radon_eye_logo.png
  index.rst
Labels: beta

#1894 Added missing verb
  components/output/gpio.rst
Labels: current

#1889 Update Home Assistant getting started guide
  guides/getting_started_hassio.rst
Labels: current

#1882 fixed on_boot wrongly positioned in modbus controller example
  components/modbus_controller.rst
Labels: current

#1881 Update diy.rst
  guides/diy.rst
Labels: current

#1883 Switch modbus controller register_type
  components/switch/modbus_controller.rst
Labels: current

#1895 Some docs tidy up
  components/api.rst
  components/captive_portal.rst
  components/cover/current_based.rst
  components/cover/tuya.rst
  components/dfplayer.rst
  components/display/inkplate6.rst
  components/display/st7789v.rst
  components/esphome.rst
  components/fingerprint_grow.rst
  components/light/tuya.rst
  components/modbus_controller.rst
  components/mqtt.rst
  components/nspanel.rst
  components/ota.rst
  components/output/my9231.rst
  components/output/sm16716.rst
  components/rtttl.rst
  components/tuya.rst
  components/wifi.rst
  cookbook/arduino_port_extender.rst
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
  cookbook/bruh.rst
  cookbook/dual-r2-cover.rst
  cookbook/esw01-eu.rst
  cookbook/h801.rst
  cookbook/ifan02.rst
  cookbook/ilonda-wifi-smart-fish-feeder.rst
  cookbook/infostrip.rst
  cookbook/iwoole_rgbw_table_lamp.rst
  cookbook/leak-detector-m5stickC.rst
  cookbook/mirabella-genio-bulb.rst
  cookbook/sonoff-basic-light-switch.rst
  cookbook/sonoff-dual-light-switch.rst
  cookbook/sonoff-fishpond-pump.rst
  cookbook/sonoff-t1-3.rst
  cookbook/teckin_sb50.rst
  cookbook/tracer-an.rst
  cookbook/zemismart-rgbw-downlights.rst
  devices/esp32.rst
  devices/esp8266.rst
  devices/nodemcu_esp32.rst
  devices/nodemcu_esp8266.rst
  devices/sonoff.rst
  devices/sonoff_4ch.rst
  devices/sonoff_4ch.yaml
  devices/sonoff_basic.rst
  devices/sonoff_s20.rst
  devices/sonoff_s20.yaml
  devices/sonoff_t1_uk_3gang_v1.1.rst
  devices/sonoff_t1_uk_3gang_v1.1.yaml
  devices/sonoff_t3_eu_3gang_v1.0.rst
  devices/sonoff_t3_eu_3gang_v1.0.yaml
  devices/teckin.yaml
  devices/teckin_sp20_us.yaml
  guides/configuration-types.rst
  guides/creators.rst
  index.rst
Labels: current

#1900 Change add-on repo to official links
  guides/getting_started_hassio.rst
Labels: current

#1905 Add warning to FastLED page for esp8266
  components/light/fastled.rst
Labels: has-parent, next

#1908 Add email link and Nabu Casa line
  _templates/contact.html
Labels: current

#1864 add sim800l diags
  components/sim800l.rst
Labels: has-parent, next

#1909 2022.2.0b3
  Doxygen
  Makefile
  _static/changelog-2022.2.0.png
  _static/version
  _templates/contact.html
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1906 Fixed link to datasheet.
  components/sensor/sgp30.rst
Labels: current

#1903 Add docker-compose sample file
  guides/getting_started_command_line.rst
Labels: current

#1911 2022.2.0
  Doxygen
  Makefile
  _static/changelog-2022.2.0.png
  _static/version
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  changelog/2022.2.0.rst
  changelog/index.rst
  components/button/images/generic-ui.png
  components/button/output.rst
  components/button/wake_on_lan.rst
  components/debug.rst
  components/display/index.rst
  components/display/inkplate6.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/ethernet.rst
  components/fan/hbridge.rst
  components/fan/index.rst
  components/fingerprint_grow.rst
  components/http_request.rst
  components/index.rst
  components/light/fastled.rst
  components/light/index.rst
  components/lock/images/output-ui.png
  components/lock/index.rst
  components/lock/output.rst
  components/lock/template.rst
  components/mqtt.rst
  components/network.rst
  components/output/ble_client.rst
  components/output/slow_pwm.rst
  components/select/modbus_controller.rst
  components/sensor/cd74hc4067.rst
  components/sensor/images/max9611.jpg
  components/sensor/images/mlx90393-full.jpg
  components/sensor/images/radon_eye_rd200.jpg
  components/sensor/images/xiaomi_mhoc303.jpg
  components/sensor/max9611.rst
  components/sensor/mlx90393.rst
  components/sensor/radon_eye_ble.rst
  components/sensor/tcs34725.rst
  components/sensor/tsl2591.rst
  components/sensor/xiaomi_ble.rst
  components/switch/index.rst
  components/touchscreen/ektf2232.rst
  components/touchscreen/index.rst
  components/touchscreen/lilygo_t5_47.rst
  components/wifi.rst
  conf.py
  guides/supporters.rst
  images/ektf2232.svg
  images/lilygo_t5_47_touch.png
  images/max9611.jpg
  images/mlx90393.jpg
  images/qr-code.svg
  images/radon_eye_logo.png
  index.rst
Labels: current

#1913 2022.2.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1901 Add analog_threshold component
  components/binary_sensor/analog_threshold.rst
  images/analog_threshold.svg
  index.rst
Labels: has-parent, next

#1919 2022.2.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1910 Update daly_bms.rst
  components/sensor/daly_bms.rst
Labels: has-parent, next

#1921 2022.2.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1920 Update copyright and author
  conf.py
Labels: current

#1760 Remote magiquest protocol
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1897 Add sensor support: MAX44009
  components/sensor/max44009.rst
  images/max44009.svg
  index.rst
Labels: has-parent, next

#1823 text_sensor for ble_client - docs
  components/text_sensor/ble_client.rst
Labels: has-parent, next

#1861 [miscale] Add clear impedance documentation
  components/sensor/xiaomi_miscale.rst
Labels: has-parent, next

#1876 Added article on water meter with proximity sensor
  guides/diy.rst
Labels: current

#1872 fixed example lambda key
  components/output/modbus_controller.rst
Labels: current

#1863 Minor text change
  components/modbus_controller.rst
Labels: current

#1862 homeassistant notify correct data keys
  components/api.rst
Labels: current

#1769 Document sensor id and how it relates to the name
  components/sensor/index.rst
Labels: current

#1873 Add missing buttons to top-level index
  index.rst
Labels: current

#1915 BH1750 dynamically calculate options
  components/sensor/bh1750.rst
Labels: has-parent, next

#1924 Rework lint
  .devcontainer/devcontainer.json
  .github/workflows/lint.yml
  .github/workflows/matchers/ci-custom.json
  .travis.yml
  Makefile
  changelog/2022.2.0.rst
  components/climate/ir_climate.rst
  components/sensor/images/dsmr-request-pin-circuit-example.png
  components/sensor/pmsa003i.rst
  components/switch/images/safemode-ui.png
  components/touchscreen/lilygo_t5_47.rst
  cookbook/images/leak-detector-m5stickC_LeakDetected.gif
  devices/images/sonoff_t1_uk_3g_backplate_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_touchpads_v1.1.jpg
  images/donate-patreon.png
  images/donate-paypal.png
  images/esp32-modbus.jpg
  images/improv-social.png
  images/index.rst
  images/lilygo_t5_47_touch.jpg
  images/lilygo_t5_47_touch.png
  images/mcp3008.jpg
  images/mcp3204.jpg
  images/pipsolar.jpg
  images/pmsa003i-full.jpg
  images/pwm.png
  images/rf_bridge.jpg
  images/rs485.jpg
  images/scd30.jpg
  images/sgp40.jpg
  images/shield-donate.svg
  images/sht4x.jpg
  images/sps30.jpg
  images/teleinfo-full.jpg
  images/tuya.png
  images/vl53l0x.jpg
  images/xiaomi_miscale1&2.jpg
  images/xiaomi_miscale2.jpg
  index.rst
  lint.py
  misc/index.rst
  misc/privacy.rst
  requirements_test.txt
  travis.py
Labels: next

#1932 Add copy integration
  components/copy.rst
  images/content-copy.svg
  index.rst
Labels: has-parent, next

#1832 Added documentation for the pulse_meter internal_filter_mode
  components/sensor/pulse_meter.rst
Labels: has-parent, next

#1934 2022.2.4
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1933 Add MPU6886 docs
  components/sensor/images/mpu6886-ui.png
  components/sensor/mpu6886.rst
  images/mpu6886.jpg
  index.rst
Labels: has-parent, next

#1923 light: add RESTORE_AND_OFF/RESTORE_AND_ON LightRestoreMode
  components/light/index.rst
Labels: has-parent, next

#1928 send_first_at for exponential_moving_average
  components/sensor/index.rst
Labels: has-parent, next

#1888 Add device support: MCP4728
  components/output/mcp4728.rst
  images/mcp4728.jpg
  index.rst
Labels: has-parent, next

#1926 Update waveshare_epaper.rst
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#1880 Honeywellabp
  components/sensor/honeywellabp.rst
  components/sensor/images/honeywellabp.jpg
  images/honeywellabp.jpg
  index.rst
Labels: has-parent, next

#1936 Add doc for touchscreen binary_sensor page_id
  components/touchscreen/index.rst
Labels: has-parent, next

#1939 2022.2.5
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1943 Add note about remote package secrets (and fix lint.py)
  guides/configuration-types.rst
  lint.py
Labels: current

#1945 Update lambdas in rf_bridge
  components/rf_bridge.rst
Labels: current

#1564 Add mopeka pro check integration docs
  components/sensor/images/mopeka_pro_check.jpg
  components/sensor/mopeka_ble.rst
  images/mopeka_pro_check.jpg
  index.rst
Labels: has-parent, next
