Repository esphome/esphome-docs, pull requests merged in 2022-01, with the labels that each got.

#1768 Fix documentation to use correct values for the 'inverted' restore modes.
  components/light/index.rst
  components/switch/gpio.rst
Labels: has-parent, current

#1767 Sensor for ltr390 is uv, not uvi
  components/sensor/ltr390.rst
Labels: current

#1766 Add link to "Restart Button" doc
  components/switch/restart.rst
Labels: current

#1755 doc: Fix typos in modbus_controller.rst
  components/sensor/modbus_controller.rst
Labels: current

#1750 Typo
  components/mcp23Sxx.rst
Labels: current

#1746 Modbus document modbus binary output
  components/output/modbus_controller.rst
Labels: has-parent, next

#1752 Added bl0940 documentation
  components/sensor/bl0940.rst
  images/bl0940.png
  index.rst
Labels: has-parent, next

#1765 Add SH1107 128x64 to SSD1306 Display documentation
  components/display/ssd1306.rst
Labels: has-parent, next

#1728 Add docker commandline for Windows
  guides/contributing.rst
Labels: current

#1771 Update xiaomi_ble.rst add signal_strength to atc_mithermometer
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1487 Added example for transmitting IR codes from lambda functions
  components/remote_transmitter.rst
Labels: stale, current

#1617 Document BMP388 / BMP390
  components/sensor/bmp3xx.rst
  components/sensor/images/bmp388.jpg
  images/bmp388.jpg
  index.rst
Labels: has-parent, next

#1773 Update esp32.rst
  components/esp32.rst
Labels: current

#1782 Fix URL
  guides/faq.rst
Labels: current

#1727 Add AirGradient DIY Air Quality to cookbook
  cookbook/air_gradient_diy_air_quality_sensor.rst
  cookbook/images/air_gradient_diy_air_quality_sensor.jpg
  images/air_gradient_diy_air_quality_sensor.jpg
  index.rst
Labels: current

#1780 Add MCP47A1 docs
  components/output/mcp47a1.rst
  images/mcp47a1.svg
  index.rst
Labels: has-parent, next

#1783 Bump sphinx from 4.1.1 to 4.3.2
  requirements.txt
Labels: current

#1781 Document `restore_mode` for `switch.output`
  components/switch/output.rst
Labels: has-parent, next

#1730 Document slow_pwm triggers
  components/output/slow_pwm.rst
Labels: has-parent, next

#1694 New Coolix protocol. New midea_ir climate component.
  components/climate/ir_climate.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1762 Add kalman_combinator docs
  components/sensor/index.rst
  components/sensor/kalman_combinator.rst
  index.rst
Labels: has-parent, next

#1712 Mcp3204 docs
  components/sensor/images/mcp3204.jpg
  components/sensor/mcp3204.rst
  images/mcp3204.jpg
  index.rst
Labels: has-parent, next

#1785 typo single vs simple
  components/display/index.rst
Labels: current

#1788 Drop oscillation_output option from H-bridge fan
  components/fan/hbridge.rst
Labels: current

#1585 Add M5Stack Timer Camera X/F
  components/esp32_camera.rst
Labels: current

#1754 Adding sdm_meter ability to report total power
  components/sensor/sdm_meter.rst
Labels: has-parent, next

#1522 Add an action for pzemac to reset the total energy
  components/sensor/pzemac.rst
  guides/automations.rst
Labels: has-parent, next

#1313 Added docs for Nexa codec
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#1779 Changed GREYSCALE to GRAYSCALE in animation
  components/display/index.rst
Labels: current

#1778 Use invert_colors and use_bgr in leak detector recipe
  cookbook/leak-detector-m5stickC.rst
Labels: current

#1688 Improve board documentation
  components/esp32.rst
  components/esp8266.rst
  components/esphome.rst
Labels: current

#1503 Add cd74hc4067 docs
  components/sensor/cd74hc4067.rst
  images/cd74hc4067.jpg
  index.rst
Labels: has-parent, next

#1726 Add documentation for ESP32 CAN component
  components/canbus.rst
Labels: has-parent, next

#1794 2022.1.0b1
  Doxygen
  Makefile
  _static/changelog-2022.1.0.png
  _static/version
  changelog/2022.1.0.rst
  changelog/index.rst
  components/button/images/safemode-ui.png
  components/button/images/shutdown-ui.png
  components/button/safe_mode.rst
  components/button/shutdown.rst
  components/canbus.rst
  components/climate/ir_climate.rst
  components/deep_sleep.rst
  components/display/inkplate6.rst
  components/display/ssd1306.rst
  components/display/tm1637.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/light/index.rst
  components/number/tuya.rst
  components/output/mcp47a1.rst
  components/output/modbus_controller.rst
  components/output/slow_pwm.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/bl0940.rst
  components/sensor/bmp3xx.rst
  components/sensor/cd74hc4067.rst
  components/sensor/growatt_solar.rst
  components/sensor/images/bmp388.jpg
  components/sensor/images/growatt.jpg
  components/sensor/images/ina260-full.png
  components/sensor/images/mcp3204.jpg
  components/sensor/ina260.rst
  components/sensor/index.rst
  components/sensor/kalman_combinator.rst
  components/sensor/mcp3204.rst
  components/sensor/pzemac.rst
  components/sensor/sdm_meter.rst
  components/sensor/xiaomi_ble.rst
  components/switch/output.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/bl0940.png
  images/bmp388.jpg
  images/cd74hc4067.jpg
  images/growatt.jpg
  images/ina260.jpg
  images/mcp3204.jpg
  images/mcp47a1.svg
  index.rst
Labels: beta

#1795 Remove the changelog toctrees
  changelog/2021.10.0.rst
  changelog/2021.11.0.rst
  changelog/2021.12.0.rst
  changelog/2021.8.0.rst
  changelog/2021.9.0.rst
  changelog/v1.10.0.rst
  changelog/v1.11.0.rst
  changelog/v1.12.0.rst
  changelog/v1.13.0.rst
  changelog/v1.14.0.rst
  changelog/v1.15.0.rst
  changelog/v1.16.0.rst
  changelog/v1.17.0.rst
  changelog/v1.18.0.rst
  changelog/v1.19.0.rst
  changelog/v1.20.0.rst
  changelog/v1.9.0.rst
Labels: current

#1777 Fix options and use smaller/better example.
  components/text_sensor/modbus_controller.rst
Labels: current

#1772 Add docs to pzemac on how to change its address
  components/sensor/pzemac.rst
Labels: current

#1770 Clearified heartbeat
  components/sensor/index.rst
Labels: current

#1720 Add See Also Base Text Sensor
  components/text_sensor/custom.rst
Labels: current

#1721 Add See Also Base Text Sensor
  components/text_sensor/template.rst
Labels: current

#1580 Add suggestion for reducing DTIM to improve WiFi
  guides/faq.rst
Labels: current

#1747 Added a DIY sample configuration
  guides/diy.rst
Labels: current

#1757 Adds missing update_interval config variable
  components/display/st7735.rst
Labels: current

#1792 Fix MAX31856 image
  components/sensor/max31856.rst
Labels: current

#1797 2022.1.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.1.0.rst
  components/display/st7735.rst
  components/sensor/index.rst
  components/sensor/max31856.rst
  components/sensor/pzemac.rst
  components/sensor/rotary_encoder.rst
  components/text_sensor/custom.rst
  components/text_sensor/modbus_controller.rst
  components/text_sensor/template.rst
  conf.py
  guides/diy.rst
  guides/faq.rst
  guides/supporters.rst
Labels: beta

#1805 Add select and button to REST API docs
  web-api/index.rst
Labels: current

#1804 Add number setting to web_server
  Makefile
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  web-api/index.rst
Labels: has-parent, next

#1807 2022.1.0b3
  Doxygen
  Makefile
  _static/version
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  changelog/2022.1.0.rst
  conf.py
  guides/supporters.rst
  web-api/index.rst
Labels: beta

#1808 Add discord and forums to keeping up
  index.rst
Labels: current

#1813 A few updates on canbus page
  components/canbus.rst
Labels: next

#1814 2022.1.0
  Doxygen
  Makefile
  _static/changelog-2022.1.0.png
  _static/version
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  changelog/2022.1.0.rst
  changelog/index.rst
  components/button/images/safemode-ui.png
  components/button/images/shutdown-ui.png
  components/button/safe_mode.rst
  components/button/shutdown.rst
  components/canbus.rst
  components/climate/ir_climate.rst
  components/deep_sleep.rst
  components/display/inkplate6.rst
  components/display/ssd1306.rst
  components/display/tm1637.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/light/index.rst
  components/number/tuya.rst
  components/output/mcp47a1.rst
  components/output/modbus_controller.rst
  components/output/slow_pwm.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/bl0940.rst
  components/sensor/bmp3xx.rst
  components/sensor/cd74hc4067.rst
  components/sensor/growatt_solar.rst
  components/sensor/images/bmp388.jpg
  components/sensor/images/growatt.jpg
  components/sensor/images/ina260-full.png
  components/sensor/images/mcp3204.jpg
  components/sensor/ina260.rst
  components/sensor/index.rst
  components/sensor/kalman_combinator.rst
  components/sensor/mcp3204.rst
  components/sensor/pzemac.rst
  components/sensor/sdm_meter.rst
  components/sensor/xiaomi_ble.rst
  components/switch/output.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/bl0940.png
  images/bmp388.jpg
  images/cd74hc4067.jpg
  images/growatt.jpg
  images/ina260.jpg
  images/mcp3204.jpg
  images/mcp47a1.svg
  index.rst
  web-api/index.rst
Labels: current

#1815 Fix pronoun
  changelog/2022.1.0.rst
Labels: current

#1812 Update tuya.rst
  components/cover/tuya.rst
Labels: current

#1817 Removed copy/paste error from ina260 doc
  components/sensor/ina260.rst
Labels: current

#1816 Update menu path for compiled firmware download
  guides/faq.rst
Labels: current

#1818 Fix gpio page mentioning PWM
  components/output/gpio.rst
Labels: current

#1819 2022.1.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.1.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1821 fix typo in it.invert_on_off()
  components/display/max7219digit.rst
Labels: current

#1806 Add initial_run to regular lambda effect
  components/light/index.rst
Labels: has-parent, next

#1796 Add doc for transparent_binary image type
  components/display/index.rst
Labels: has-parent, next

#1791 Update dashboard screenshots
  guides/contributing.rst
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
  guides/images/dashboard.png
  guides/images/dashboard_empty.png
  guides/images/dashboard_states.png
  guides/images/hassio_start.png
Labels: current

#1828 Update qmc5883l.rst
  components/sensor/qmc5883l.rst
Labels: current

#1825 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#1824 Update esp32_ble_tracker.rst
  components/esp32_ble_tracker.rst
Labels: current

#1793 Add ektf2232 touchscreen controller
  components/binary_sensor/ektf2232.rst
  images/ektf2232.svg
  index.rst
Labels: has-parent, next

#1820 Fix temperature-related variable names
  components/sensor/bl0940.rst
Labels: current

#898 add sample config for Tuya Smart Life RGBW controller
  cookbook/images/tuya_rgbw.jpg
  cookbook/tuya_rgbw.rst
  index.rst
Labels: current, not-stale

#1701 Clarification of the behavior of calibraty_linear filter
  components/sensor/index.rst
Labels: current

#1809 Specified how the sensor values get populated
  components/binary_sensor/template.rst
Labels: current

#1826 Update mqtt to reflect changes in 2022.1
  components/mqtt.rst
Labels: current

#1830 Remove recommendation from calibrate_linear
  components/sensor/index.rst
Labels: current

#1787 Improve documentation around installing ESPHome and connecting devices to computers
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
  guides/images/breakable-header.jpg
  guides/images/flux.jpg
  guides/images/jumper-wires.jpg
  guides/images/module-only-programming.jpg
  guides/images/programming-bare-chip.jpg
  guides/images/programming-header-filled.jpg
  guides/images/programming-header-populated.jpg
  guides/images/programming-header-unpopulated.jpg
  guides/images/python-win-installer.png
  guides/images/solder.jpg
  guides/images/soldering-iron.jpg
  guides/images/strippers.jpg
  guides/images/usb-cable.jpg
  guides/images/usb-serial-adapter.jpg
  guides/images/wire-cutters.jpg
  guides/installing_esphome.rst
  guides/physical_device_connection.rst
  images/high-voltage-warning.svg
  index.rst
Labels: current

#1831 Add note that buttons are unidirectional
  components/button/index.rst
Labels: has-parent, current

#1833 Update for multiple cd74hc4067
  components/sensor/cd74hc4067.rst
Labels: has-parent, next

#1775 Add Wake-on-LAN docs
  components/button/wake_on_lan.rst
  index.rst
Labels: has-parent, next

#1802 Add restore_mode to fan component
  components/fan/index.rst
Labels: has-parent, next

#1774 Slow pwm restart cycle on state change
  components/output/slow_pwm.rst
Labels: has-parent, next

#1822 Command retain option for MQTT component
  components/mqtt.rst
Labels: has-parent, next

#1837 Fan platform refactor
  components/fan/hbridge.rst
  components/fan/index.rst
Labels: has-parent, next

#1840 Add virtualenvs to sphinx ignore
  conf.py
Labels: current

#1841 Process files with netlify
  netlify.toml
Labels: current

#1842 Revert "Process files with netlify (#1841)"
  netlify.toml
Labels: current

#1845 Use Buttons instead of switches in midea example
  components/climate/midea.rst
Labels: current

#1846 Add output button documentation
  components/button/images/generic-ui.png
  components/button/output.rst
  index.rst
Labels: has-parent, next

#1847 2022.1.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.1.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1844 document changes from PR#3037
  components/sensor/tcs34725.rst
Labels: has-parent, next

#1836 Esp32cam full control
  components/esp32_camera.rst
Labels: has-parent, next

#1839 Document HTTP redirections follow options
  components/http_request.rst
Labels: has-parent, next

#1749 Add documentation for enable_ipv6 flag.
  components/ethernet.rst
  components/network.rst
  components/wifi.rst
  index.rst
Labels: has-parent, next

#1838 Add Github UI instructions
  guides/contributing.rst
  guides/images/docs_ghedit_1.png
  guides/images/docs_ghedit_2.png
  guides/images/docs_ghedit_3.png
  guides/images/docs_ghedit_4.png
  guides/images/docs_ghedit_ci_details.png
  guides/images/docs_ghedit_ci_failed.png
  guides/images/docs_ghedit_ci_logs.png
Labels: current

#1786 Add live reloading
  Dockerfile
  Makefile
  guides/contributing.rst
  requirements.txt
Labels: current

#1851 Add additional colours for GROW R503-RGB.
  components/fingerprint_grow.rst
Labels: next

#1041 Add Heap Sensors - free/max block/fragmentation #1578
  components/debug.rst
Labels: has-parent, next

#1834 Reorganize for base touchscreen docs
  components/binary_sensor/ektf2232.rst
  components/index.rst
  components/touchscreen/ektf2232.rst
  components/touchscreen/index.rst
  index.rst
Labels: has-parent, next

#1748 Added documentation for qr code component
  components/display/index.rst
Labels: has-parent, next

#1843 Add auto gain setting to tsl2591 docs
  components/sensor/tsl2591.rst
Labels: has-parent, next

#1854 Clarification for MCP23017
  components/mcp230xx.rst
Labels: current

#1852 Update link to PlatformIO boards list
  devices/esp32.rst
Labels: current

#1848 remove incomple mqtt component
  cookbook/tracer-an.rst
Labels: current

#1858 Fix misleading status led note
  components/light/status_led.rst
Labels: current

#1855 Documentation for Xiaomi MHO-C303 sensor
  components/sensor/images/xiaomi_mhoc303.jpg
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#1859 Add support for Waveshare 7.5in-bv2
  components/display/waveshare_epaper.rst
Labels: has-parent, next
