Repository esphome/esphome-docs, pull requests merged in 2022-10, with the labels that each got.

#2335 Fix typo
  components/display/max7219digit.rst
Labels: current

#2336 mqtt: MbedTLS doesn't like wildcard certificates
  components/mqtt.rst
Labels: has-parent, current

#2340 Add id and teleinfo_id to teleinfo configuration variables
  components/sensor/teleinfo.rst
Labels: current

#2342 Add min_version docs
  components/esphome.rst
Labels: has-parent, next

#2345 Active connection config for bluetooth_proxy
  components/bluetooth_proxy.rst
Labels: has-parent, next

#2350 2022.9.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  components/bluetooth_proxy.rst
  conf.py
  guides/supporters.rst
Labels: current

#2351 2022.9.4
  Doxygen
  Makefile
  _static/version
  changelog/2022.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2358 Fix broken SGP4x links
  components/sensor/sgp4x.rst
Labels: current

#2259 Update xpt2046 documentation
  _redirects
  components/touchscreen/images/xpt2046-full.jpg
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
Labels: has-parent, next

#2359 Changed `relay_1` to `light_1`
  components/output/index.rst
Labels: current

#2339 Update docs for ble_client RSSI sensor
  components/sensor/ble_client.rst
  cookbook/ble_itag.rst
Labels: has-parent, next

#2199 Add support for ZHLT01 heatpump IR protocol
  components/climate/climate_ir.rst
Labels: has-parent, next

#2354 Do not requre CS pin for st7789v
  components/display/st7789v.rst
Labels: has-parent, next

#2361 2022.10.0b1
  Doxygen
  Makefile
  _redirects
  _static/version
  changelog/2022.10.0.rst
  changelog/index.rst
  components/climate/climate_ir.rst
  components/climate/thermostat.rst
  components/display/st7789v.rst
  components/esphome.rst
  components/sensor/ble_client.rst
  components/touchscreen/images/xpt2046-full.jpg
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
  conf.py
  cookbook/ble_itag.rst
  guides/supporters.rst
Labels: beta

#2362 Add components.json
  components.py
  conf.py
  schema_doc.py
Labels: current

#2337 Add min/max_interval and measured_power to esp32_ble_beacon
  components/esp32_ble_beacon.rst
Labels: has-parent, next

#2301 Add docs for keep_user_credentials
  components/captive_portal.rst
  guides/creators.rst
Labels: has-parent, next

#2364 Adjust components output
  components.py
Labels: current

#2365 2022.10.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.10.0.rst
  components.py
  conf.py
  guides/supporters.rst
  schema_doc.py
Labels: beta

#2367 Fix Gitpod launch command to use live-html target
  .gitpod.yml
Labels: current

#2368 Add breadcrumbs to the top of pages
  _static/custom.css
  _templates/layout.html
  devices/index.rst
Labels: current

#2357 Fixed UFire EC Documentation
  components/sensor/ufire_ec.rst
Labels: current

#2327 Update cse7766.rst
  components/sensor/cse7766.rst
Labels: current

#2305 Update LYWSDCGQ description in xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: has-parent, current

#2370 2022.10.0
  Doxygen
  Makefile
  _redirects
  _static/changelog-2022.10.0.png
  _static/version
  changelog/2022.10.0.rst
  changelog/index.rst
  components/climate/climate_ir.rst
  components/climate/thermostat.rst
  components/display/st7789v.rst
  components/esphome.rst
  components/sensor/ble_client.rst
  components/touchscreen/images/xpt2046-full.jpg
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
  conf.py
  cookbook/ble_itag.rst
  guides/supporters.rst
Labels: current

#2137 Add support for wl-134
  components/text_sensor/wl_134.rst
  index.rst
Labels: has-parent, next

#2300 Add ethernet_info docs
  components/text_sensor/ethernet_info.rst
  index.rst
Labels: wrong-base-branch, has-parent, next

#2115 Documentation for Atlas Scientific Peristaltic Pump
  components/ezo_pmp.rst
  components/images/ezo-pmp.jpg
  images/ezo-pmp.jpg
Labels: has-parent, next

#2308 Add docs from adc128s102 sensor
  components/sensor/adc128s102.rst
  components/sensor/images/adc128s102.png
  images/adc128s102.png
  index.rst
Labels: has-parent, next

#2245 Added Daikin BRC Component to the Climate IR doc
  components/climate/climate_ir.rst
Labels: has-parent, next

#2375 Fix color temp units for strobe effect
  components/light/index.rst
Labels: current

#2377 Revert "Fix color temp units for strobe effect"
  components/light/index.rst
Labels: current

#2380 clarify that `active` is nested
  components/sensor/xiaomi_ble.rst
Labels: current

#2387 fix example indent
  components/sensor/pulse_counter.rst
Labels: current

#2240 replace deprecated hexencode usage
  components/exposure_notifications.rst
  components/tuya.rst
Labels: stale, current

#2384 Remove human readable example from uptime
  components/sensor/uptime.rst
Labels: has-parent, next

#2388 2022.10.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2389 remove invalid method from docs
  guides/automations.rst
Labels: current

#2390 fix lambda entries in the script docs
  guides/automations.rst
Labels: current

#2391 Add compile_process_limit docs
  components/esphome.rst
Labels: has-parent, next

#2392 Add basic rp2040 docs page
  components/rp2040.rst
  images/rp2040.svg
  index.rst
Labels: next

#2393 Remove devices on home page and replace with platforms
  _redirects
  components/esp32.rst
  components/esp8266.rst
  components/rp2040.rst
  components/sensor/esp32_hall.rst
  devices/esp32.rst
  devices/esp8266.rst
  devices/nodemcu_esp32.rst
  devices/nodemcu_esp8266.rst
  devices/sonoff.rst
  guides/migrate_espeasy.rst
  guides/migrate_espurna.rst
  guides/migrate_sonoff_tasmota.rst
  index.rst
Labels: next

#2399 Remove gitpod instructions
  guides/contributing.rst
Labels: has-parent, current

#2400 Spelling miss on interRupt
  components/touchscreen/xpt2046.rst
Labels: current

#2401 id cannot be the same as the component name
  components/touchscreen/xpt2046.rst
Labels: current

#2255 update numbercall function names
  components/number/index.rst
Labels: stale, current
