Repository esphome/esphome-docs, pull requests merged in 2022-12, with the labels that each got.

#2497 2022.11.4
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2499 fix mistake in example for .active_index()
  components/select/index.rst
Labels: current

#2495 Update diy.rst
  guides/diy.rst
Labels: current

#2505 Update installation docs with newer versions
  guides/installing_esphome.rst
Labels: current

#2508 2022.11.5
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2504 Added documentation for SN74HC165
  components/sn74hc165.rst
  index.rst
Labels: has-parent, next

#2509 2022.12.0b1
  Doxygen
  Makefile
  _static/changelog-2022.12.0.png
  _static/version
  changelog/2022.11.0.rst
  changelog/2022.12.0.rst
  components/climate/climate_ir.rst
  components/climate/images/deadband1.png
  components/climate/images/deadband2.png
  components/climate/pid.rst
  components/climate/tuya.rst
  components/debug.rst
  components/number/index.rst
  components/remote_transmitter.rst
  components/sn74hc165.rst
  components/sn74hc595.rst
  components/switch/gpio.rst
  components/switch/index.rst
  components/switch/modbus_controller.rst
  components/switch/output.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: beta

#2511 2022.12.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2517 Update pid.rst
  components/climate/pid.rst
Labels: current

#2521 2022.12.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2522 2022.12.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
Labels: beta

#2526 2022.12.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2527 2022.12.0
  Doxygen
  Makefile
  _static/changelog-2022.12.0.png
  _static/version
  changelog/2022.12.0.rst
  changelog/index.rst
  components/climate/climate_ir.rst
  components/climate/images/deadband1.png
  components/climate/images/deadband2.png
  components/climate/pid.rst
  components/climate/tuya.rst
  components/debug.rst
  components/number/index.rst
  components/remote_transmitter.rst
  components/sn74hc165.rst
  components/sn74hc595.rst
  components/switch/gpio.rst
  components/switch/index.rst
  components/switch/modbus_controller.rst
  components/switch/output.rst
  conf.py
  guides/creators.rst
  guides/supporters.rst
  index.rst
Labels: current

#2529 Ethernet wESP32 rev 7, AiThinker, SLZB-06 and appearance
  components/ethernet.rst
Labels: current

#2498 Added basic usage example
  components/select/index.rst
Labels: current

#2531 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#2534 Update ethernet.rst
  components/ethernet.rst
Labels: current

#2535 Update network.rst
  components/network.rst
Labels: current

#2537 Update wifi.rst
  components/wifi.rst
Labels: current

#2536 Update wifi_signal.rst
  components/sensor/wifi_signal.rst
Labels: current

#2538 Update wifi_info.rst
  components/text_sensor/wifi_info.rst
Labels: current

#2539 Update ethernet_info.rst
  components/text_sensor/ethernet_info.rst
Labels: current

#2540 Update wifi.rst
  components/wifi.rst
Labels: current

#2469 Update bluetooth proxy docs with latest information on active bluetooth connections
  components/bluetooth_proxy.rst
Labels: current, awaiting-feedback

#2543 Added example for 16x32 display in addressable_light.rst
  components/display/addressable_light.rst
Labels: current

#2544 2022.12.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2545 Updated example
  components/select/index.rst
Labels: current

#2546 Update servo.rst
  components/servo.rst
Labels: current

#2552 Update sn74hc165.rst
  components/sn74hc165.rst
Labels: current

#2555 document that cron behaves like days_of_week, not like crontab
  components/time.rst
Labels: current

#2558 docs(getting_started): fix typo
  guides/getting_started_hassio.rst
Labels: current

#2559 2022.12.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2532 Add PCA9554 docs
  components/pca9554.rst
  images/pca9554a.jpg
  index.rst
Labels: has-parent, next

#2089 Add docs for ili9341 image adaptive pallet mode
  components/display/ili9341.rst
Labels: has-parent, next

#2563 Add disable_crc to modbus doc
  components/modbus.rst
Labels: has-parent, next

#2564 Fix syntax in the script.is_running lambda example
  guides/automations.rst
Labels: current

#2433 Add documentation for new component BP5758D LED driver.
  components/output/bp5758d.rst
  images/bp5758d.svg
  index.rst
Labels: has-parent, next

#2432 Add documentation for new component BB1658CJ LED Driver
  components/output/bp1658cj.rst
  images/bp1658cj.svg
  index.rst
Labels: has-parent, next

#2514 Add documentation for SM2235 & SM2335 LED drivers
  components/output/sm2235.rst
  components/output/sm2335.rst
  images/sm2235.svg
  images/sm2335.svg
  index.rst
Labels: has-parent, next

#2566 Restructure time docs into its own folder and split
  changelog/v1.10.0.rst
  components/climate/bedjet.rst
  components/display/pvvx_mithermometer.rst
  components/gps.rst
  components/index.rst
  components/time/ds1307.rst
  components/time/gps.rst
  components/time/homeassistant.rst
  components/time/index.rst
  components/time/sntp.rst
  components/tuya.rst
  index.rst
Labels: current

#2565 Rework reference to MQTT as its not really the point
  components/sensor/index.rst
Labels: current

#2347 Pcf85063 rtc
  components/time/pcf85063.rst
  guides/automations.rst
  index.rst
Labels: has-parent, next

#2567 Updated pmsx003.rst
  components/sensor/pmsx003.rst
Labels: current
