Repository esphome/esphome-docs, pull requests merged in 2022-07, with the labels that each got.

#2164 Clarify `accuracy_decimals` in sensor config
  components/sensor/index.rst
Labels: current

#2083 Feature 1398
  components/sensor/aht10.rst
  index.rst
Labels: current

#2081 Update AHT10 to include AHT20/21
  components/sensor/aht10.rst
  index.rst
Labels: current

#2044 Update dht.rst with DHT21/AMS2301
  components/sensor/dht.rst
Labels: stale, current

#2096 Update ethernet.rst
  components/ethernet.rst
Labels: current

#2171 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#2172 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#2173 Update ethernet.rst
  components/ethernet.rst
Labels: current

#2154 reference to alternative hardware added
  components/climate/midea.rst
Labels: current

#2174 Update xiaomi_ble.rst
  components/sensor/xiaomi_ble.rst
Labels: current

#2159 Documentation Update: Added in Inkplate 6 PLUS backlight controls example
  components/display/inkplate6.rst
Labels: current

#2175 Update i2c.rst
  components/i2c.rst
Labels: current

#2167 Update index.rst
  components/climate/index.rst
Labels: current

#2198 Update modbus_controller.rst
  components/sensor/modbus_controller.rst
Labels: current

#2187 Add set_total_pulses to pulse_counter docs
  components/sensor/pulse_counter.rst
Labels: has-parent, next

#2194 Update web_server documentation to include information about the local attribute
  components/web_server.rst
Labels: current

#2183 doc update for PR#3636
  components/binary_sensor/index.rst
Labels: has-parent, next

#2197 Add SMT100 Soil Moisture Sensor documentation
  components/sensor/images/smt100.jpg
  components/sensor/smt100.rst
  images/smt100.jpg
  index.rst
Labels: has-parent, next

#2205 doc: Selects also implement writes
  components/modbus_controller.rst
Labels: current
