Repository esphome/esphome-docs, pull requests merged in 2022-11, with the labels that each got.

#2404 Change stepper example to use number instead of HA config
  components/stepper/index.rst
Labels: current

#2403 2022.10.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2413 update_interval missing in docs
  components/modbus_controller.rst
Labels: current

#2267 added a sentence to script.is_running -check links
  guides/automations.rst
Labels: stale, current

#2264 clarify non normal cron - 6 fields with seconds
  components/time.rst
Labels: stale, current

#2271 web_server: Fix Example configuration entry V1
  components/web_server.rst
Labels: stale, next

#2270 fix web_server javascript when in strict mode / local files
  _static/webserver-v1.js
  _static/webserver-v1.min.js
Labels: next

#2291 "name" not required
  components/text_sensor/homeassistant.rst
Labels: current

#2029 Implement a simple LCD menu
  components/display_menu/images/lcd_menu.png
  components/display_menu/index.rst
  components/display_menu/lcd_menu.rst
  components/index.rst
  images/lcd_menu.png
  index.rst
Labels: has-parent, next

#2412 Remove misleading specification in example yaml
  components/sensor/tcs34725.rst
Labels: current

#2415 Add default ota port for rp2040
  components/ota.rst
Labels: next

#2416 Update sonoff.rst
  devices/sonoff.rst
Labels: current

#2417 Update esphome.rst
  components/esphome.rst
Labels: current

#2120 Add documentation on script parameters
  guides/automations.rst
Labels: has-parent, next, not-stale

#2418 2022.11.0b1
  Doxygen
  Makefile
  _redirects
  _static/version
  _static/webserver-v1.js
  _static/webserver-v1.min.js
  changelog/2022.11.0.rst
  changelog/index.rst
  components/captive_portal.rst
  components/climate/climate_ir.rst
  components/display_menu/images/lcd_menu.png
  components/display_menu/index.rst
  components/display_menu/lcd_menu.rst
  components/esp32.rst
  components/esp32_ble_beacon.rst
  components/esp8266.rst
  components/esphome.rst
  components/ezo_pmp.rst
  components/images/ezo-pmp.jpg
  components/index.rst
  components/ota.rst
  components/rp2040.rst
  components/sensor/adc128s102.rst
  components/sensor/esp32_hall.rst
  components/sensor/images/adc128s102.png
  components/sensor/uptime.rst
  components/text_sensor/ethernet_info.rst
  components/text_sensor/wl_134.rst
  components/web_server.rst
  conf.py
  devices/esp32.rst
  devices/esp8266.rst
  devices/nodemcu_esp32.rst
  devices/nodemcu_esp8266.rst
  devices/sonoff.rst
  guides/automations.rst
  guides/creators.rst
  guides/migrate_espeasy.rst
  guides/migrate_espurna.rst
  guides/migrate_sonoff_tasmota.rst
  guides/supporters.rst
  images/adc128s102.png
  images/ezo-pmp.jpg
  images/lcd_menu.png
  images/rp2040.svg
  index.rst
Labels: beta

#2406 SDM230M important notice to user to pay attention when configuring the energy monitor
  components/sensor/sdm_meter.rst
Labels: current

#2419 Explicit wiring a bit
  components/sensor/pulse_counter.rst
Labels: current

#2282 Update custom_component.rst
  custom/custom_component.rst
Labels: stale, current

#2382 Added Geiger Counter to the cookbook
  cookbook/geiger-counter.rst
  cookbook/images/radiationD-v1-1-cajoe_small.jpg
  images/radiationD-v1-1-cajoe_small.jpg
  index.rst
Labels: current

#2281 Add information about 3.3v current ability and UART rx_buffer_size
  components/sensor/daly_bms.rst
Labels: current

#2133 Updates for new functionality of the EZO component.
  components/sensor/ezo.rst
Labels: has-parent, next

#2275 Added project "Automated Coffee Bean Roaster"
  guides/diy.rst
Labels: stale, current

#2420 Add M5Stack PoESP32 Unit ethernet configuration
  components/ethernet.rst
Labels: current

#2423 Fix github path in components json
  components.py
Labels: current

#2287 Update power_supply.rst
  components/power_supply.rst
Labels: stale, current

#2430 Typo
  components/button/index.rst
Labels: current

#2294 Update custom_component.rst
  custom/custom_component.rst
Labels: stale, current

#2436 2022.11.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2383 Remove duplicated option in hmc5883l.rst
  components/sensor/hmc5883l.rst
Labels: current

#2394 Revise SM300D2 documentation
  components/sensor/sm300d2.rst
Labels: current

#2437 `homeassistant` numeric sensor note about internal defalult value
  components/sensor/homeassistant.rst
Labels: current

#2438 `homeassistant` text sensor remove obsolete old version specification
  components/text_sensor/homeassistant.rst
Labels: current

#2374 better error messages
  schema_doc.py
Labels: next

#2293 suggest broadcast address
  components/sensor/pzemac.rst
Labels: current

#2302 Add reset_reason text sensor to debug component
  components/debug.rst
Labels: stale, has-parent, next

#2441 Cleaner images for LCD Menu component, nicer back arrow character
  components/display_menu/images/lcd_menu.png
  components/display_menu/lcd_menu.rst
  images/lcd_menu.png
Labels: next

#2443 Updates for runtime entered wifi credentials
  components/captive_portal.rst
  components/wifi.rst
Labels: has-parent, next

#2444 2022.11.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  components/captive_portal.rst
  components/wifi.rst
  conf.py
Labels: beta

#2446 Add notes for ADC on RP2040
  components/sensor/adc.rst
Labels: has-parent, next

#2447 2022.11.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  components/sensor/adc.rst
  conf.py
  guides/supporters.rst
Labels: current

#2449 Update datasheet link on scd4x
  components/sensor/scd4x.rst
Labels: current

#2451 Update index.rst
  components/display_menu/index.rst
Labels: current

#2453 Update lcd_display.rst
  components/display/lcd_display.rst
Labels: current

#2454 Add LCD display SVG picture with GPIO pinout
  components/display/images/lcd_gpio.svg
Labels: current

#2455 Replace image with SVG containing pinout
  components/display/lcd_display.rst
Labels: current

#2457 Add number device class support
  components/number/index.rst
Labels: has-parent, next

#2458 Fix of typos again
  components/display/lcd_display.rst
Labels: current

#2459 Update lcd_menu.rst
  components/display_menu/lcd_menu.rst
Labels: current

#2465 Fix indentation for sgp4x
  components/sensor/sgp4x.rst
Labels: current

#2463 feat: Doc to support templatable code for Midea IR
  components/climate/climate_ir.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#2470 2022.11.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2474 Update debug.rst
  components/debug.rst
Labels: current

#2473 2022.11.3
  Doxygen
  Makefile
  _static/version
  changelog/2022.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2476 Update ezo.rst
  components/sensor/ezo.rst
Labels: current

#2478 Update getting_started_hassio.rst
  guides/getting_started_hassio.rst
Labels: current

#2479 climate cosmetic fixes
  components/climate/index.rst
Labels: current

#2480 Update thermostat.rst
  components/climate/thermostat.rst
Labels: current

#2428 Update faq.rst
  guides/faq.rst
Labels: current

#2168 Add examples to pca9685
  components/output/pca9685.rst
Labels: current

#2265 Add Sonoff THR316D description
  devices/sonoff.rst
Labels: current

#2343 docs: update the quantile link
  components/sensor/index.rst
Labels: current

#2334 update bedjet.rst
  components/climate/bedjet.rst
Labels: current

#2332 Update YAML indent of mpl3115a2
  components/sensor/mpl3115a2.rst
Labels: stale, current

#2484 Update mirabella-genio-bulb.rst
  cookbook/mirabella-genio-bulb.rst
Labels: current

#2402 Added note about decimal accuracy of other sensors
  components/sensor/dht.rst
Labels: current

#2396 Update max31856.rst
  components/sensor/max31856.rst
Labels: current

#2372 Add copy-sensor anchor
  components/copy.rst
Labels: current

#2434 Fixed syntax
  components/select/tuya.rst
Labels: current

#2435 Update description on temperature offset
  components/sensor/bme680_bsec.rst
Labels: current

#2485 Fix anchor
  components/copy.rst
Labels: current

#2371 Add example workaround for static uniqueid
  components/sensor/wifi_signal.rst
Labels: current

#2466 update clean-mqtt commandline order
  components/mqtt.rst
Labels: current

#2481 expand substitution
  guides/configuration-types.rst
Labels: has-parent, current

#2483 Multiplexing annotation outdated,
  components/i2c.rst
Labels: current

#2381 move restore mode from gpio/output to base switch
  components/switch/gpio.rst
  components/switch/index.rst
  components/switch/modbus_controller.rst
  components/switch/output.rst
Labels: has-parent, next

#1944 Update PID Climate with deadband and sampling
  components/climate/images/deadband1.png
  components/climate/images/deadband2.png
  components/climate/pid.rst
Labels: stale, has-parent, next

#2489 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: current
