Repository esphome/esphome-docs, pull requests merged in 2022-03, with the labels that each got.

#1946 2022.2.6
  Doxygen
  Makefile
  _static/version
  changelog/2022.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1952 Update honeywellabp.rst
  components/sensor/honeywellabp.rst
Labels: next

#1947 Update link to PlatformIO boards list.
  devices/esp8266.rst
Labels: current

#1600 Webserver v2
  components/images/web_server-v2.png
  components/web_server.rst
Labels: has-parent, next

#1955 2022.3.0b1
  Doxygen
  Makefile
  _static/changelog-2022.3.0.png
  _static/version
  changelog/2022.3.0.rst
  changelog/index.rst
  components/binary_sensor/analog_threshold.rst
  components/copy.rst
  components/display/waveshare_epaper.rst
  components/images/web_server-v2.png
  components/light/index.rst
  components/output/mcp4728.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/bh1750.rst
  components/sensor/daly_bms.rst
  components/sensor/honeywellabp.rst
  components/sensor/images/honeywellabp.jpg
  components/sensor/images/mopeka_pro_check.jpg
  components/sensor/images/mpu6886-ui.png
  components/sensor/index.rst
  components/sensor/max44009.rst
  components/sensor/mopeka_ble.rst
  components/sensor/mpu6886.rst
  components/sensor/pulse_meter.rst
  components/sensor/xiaomi_miscale.rst
  components/sim800l.rst
  components/text_sensor/ble_client.rst
  components/touchscreen/index.rst
  components/web_server.rst
  conf.py
  guides/supporters.rst
  images/analog_threshold.svg
  images/content-copy.svg
  images/honeywellabp.jpg
  images/max44009.svg
  images/mcp4728.jpg
  images/mopeka_pro_check.jpg
  images/mpu6886.jpg
  index.rst
Labels: beta

#1949 Add optimistic flag to Modbus Select
  components/select/modbus_controller.rst
Labels: has-parent, next

#1940 Add airquality wp6003 + am312 tutorial
  guides/diy.rst
Labels: current

#1938 Fix typos in code snippets for stepper component
  components/stepper/index.rst
Labels: current

#1930 Added alternative pin labeling for 74HC595
  components/sn74hc595.rst
Labels: current

#1898 Additional clarification to update_interval and sample_duration relat…
  components/sensor/ct_clamp.rst
Labels: current

#1956 MarioGK/current
  components/binary_sensor/rdm6300.rst
Labels: current

#1914 Example to parse values from JSON response to HTTP Request
  components/http_request.rst
Labels: current

#1931 Update htu21d.rst
  components/sensor/htu21d.rst
  index.rst
Labels: current

#1918 Add bitmasks description and example to extract bits
  components/modbus_controller.rst
Labels: current

#1935 QMP6988 Documentation
  components/sensor/qmp6988.rst
  images/qmp6988_env3.png
  index.rst
Labels: has-parent, next

#1964 2022.3.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2022.3.0.rst
  components/select/modbus_controller.rst
  conf.py
  guides/supporters.rst
Labels: beta

#1965 2022.3.0
  Doxygen
  Makefile
  _static/changelog-2022.3.0.png
  _static/version
  changelog/2022.3.0.rst
  changelog/index.rst
  components/binary_sensor/analog_threshold.rst
  components/copy.rst
  components/display/waveshare_epaper.rst
  components/images/web_server-v2.png
  components/light/index.rst
  components/output/mcp4728.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/select/modbus_controller.rst
  components/sensor/bh1750.rst
  components/sensor/daly_bms.rst
  components/sensor/honeywellabp.rst
  components/sensor/images/honeywellabp.jpg
  components/sensor/images/mopeka_pro_check.jpg
  components/sensor/images/mpu6886-ui.png
  components/sensor/index.rst
  components/sensor/max44009.rst
  components/sensor/mopeka_ble.rst
  components/sensor/mpu6886.rst
  components/sensor/pulse_meter.rst
  components/sensor/xiaomi_miscale.rst
  components/sim800l.rst
  components/text_sensor/ble_client.rst
  components/touchscreen/index.rst
  components/web_server.rst
  conf.py
  guides/supporters.rst
  images/analog_threshold.svg
  images/content-copy.svg
  images/honeywellabp.jpg
  images/max44009.svg
  images/mcp4728.jpg
  images/mopeka_pro_check.jpg
  images/mpu6886.jpg
  index.rst
Labels: current

#1960 Add simpler Home Assistant configuration for servo control
  components/servo.rst
Labels: current

#1972 Update diy.rst
  guides/diy.rst
Labels: current

#1983 2022.3.1
  Doxygen
  Makefile
  _static/version
  changelog/2022.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#1980 Allow to set user defined characters on LCD
  components/display/lcd_display.rst
Labels: has-parent, next

#1990 Add docs for google fonts
  components/display/index.rst
Labels: has-parent, next

#1993 2022.3.2
  Doxygen
  Makefile
  _static/version
  changelog/2022.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current
