Repository esphome/esphome-docs, pull requests merged in 2023-09, with the labels that each got.

#3150 Feature/heating si7021
  components/sensor/htu21d.rst
Labels: has-parent, next

#3159 Add LibreTiny documentation
  components/libretiny.rst
  components/output/libretiny_pwm.rst
  components/text_sensor/libretiny.rst
  images/bk72xx.svg
  images/libretiny.svg
  images/rtl87xx.svg
  index.rst
Labels: has-parent, next

#3142 Extend supported CAN bit_rate for ESP32 variants
  components/canbus.rst
Labels: has-parent, next

#3160 Documentation for new free PSRAM sensor
  components/debug.rst
Labels: has-parent, next

#3161 Add new documentation for ST7789V displays
  components/display/st7789v.rst
Labels: has-parent, next

#3046 Docker Dashboard Doc: add Username and Password environment variables
  guides/getting_started_command_line.rst
Labels: stale, current

#3038 Mention how to disable MQTT logging
  components/mqtt.rst
Labels: stale, current

#2718 Add reference to MaxBotix XL sensor as well as the HRXL
  components/sensor/hrxl_maxsonar_wr.rst
Labels: stale, has-parent, next

#2897 Documentation for DFRobot Ozone Sensor (sen0321)
  components/sensor/images/sen0321.jpg
  components/sensor/sen0321.rst
  images/sen0321.jpg
  index.rst
Labels: has-parent, next

#2915 add lightwave
  components/light/images/lightwaverf.jpg
  components/light/lightwaverf.rst
  index.rst
Labels: has-parent, next

#3164 2023.8.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.8.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3156 Add spi_device
  components/spi.rst
Labels: has-parent, next

#3174 [ADC] Documented measuring VCC on Raspberry Pico (W)
  components/sensor/adc.rst
Labels: has-parent, next

#3052 Link to compiler options, fix example
  components/esp32.rst
Labels: stale, current

#3086 Add BMI160 support
  components/sensor/bmi160.rst
  components/sensor/images/bmi160-full.jpg
  components/sensor/images/bmi160-ui.png
  images/bmi160.jpg
  index.rst
Labels: has-parent, next

#3147 SPI RGB LED component description
  components/light/fastled.rst
  components/light/images/apa102.jpg
  components/light/neopixelbus.rst
  components/light/spi_led_strip.rst
  images/apa102.jpg
  index.rst
Labels: has-parent, next

#3177 Add a doc for PSRAM config
  components/psram.rst
  images/psram.svg
  index.rst
Labels: next

#3178 Correcting battery level UOM and adding "See Also" section
  components/sensor/airthings_ble.rst
Labels: current

#2948 Documentation for WireGuard component and sensors
  components/wireguard.rst
  images/wireguard_custom_logo.svg
  index.rst
Labels: has-parent, next

#3151 Documentation for persistable globals
  guides/automations.rst
Labels: has-parent, next

#3163 Add new configuration for Modbus Controller.
  components/modbus_controller.rst
Labels: has-parent, next

#3149 Added heater_enabled parameter
  components/sensor/sht3xd.rst
Labels: has-parent, next

#3182 2023.9.0b1
  Doxygen
  Makefile
  _static/changelog-2023.9.0.png
  _static/version
  changelog/2023.9.0.rst
  changelog/index.rst
  components/canbus.rst
  components/climate/climate_ir.rst
  components/debug.rst
  components/display/st7789v.rst
  components/esp32_ble_server.rst
  components/libretiny.rst
  components/light/fastled.rst
  components/light/images/apa102.jpg
  components/light/images/lightwaverf.jpg
  components/light/lightwaverf.rst
  components/light/neopixelbus.rst
  components/light/spi_led_strip.rst
  components/modbus_controller.rst
  components/output/libretiny_pwm.rst
  components/psram.rst
  components/sensor/adc.rst
  components/sensor/bmi160.rst
  components/sensor/hrxl_maxsonar_wr.rst
  components/sensor/htu21d.rst
  components/sensor/images/bmi160-full.jpg
  components/sensor/images/bmi160-ui.png
  components/sensor/images/pmwcs3.jpg
  components/sensor/images/sen0321.jpg
  components/sensor/pmwcs3.rst
  components/sensor/sen0321.rst
  components/sensor/sht3xd.rst
  components/spi.rst
  components/text_sensor/libretiny.rst
  components/wireguard.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/apa102.jpg
  images/bk72xx.svg
  images/bmi160.jpg
  images/libretiny.svg
  images/pmwcs3.jpg
  images/psram.svg
  images/rtl87xx.svg
  images/sen0321.jpg
  images/wireguard_custom_logo.svg
  index.rst
Labels: beta

#3191 Fix Typo in http_request_sensor.rst
  cookbook/http_request_sensor.rst
Labels: current

#3189 extend clamp sensor description
  components/sensor/index.rst
Labels: current

#3192 Fix broken link to `CustomAPIDevice` documentation
  custom/custom_component.rst
Labels: current

#3194 Update esp32.rst
  components/esp32.rst
Labels: current

#3195 Update hydreon_rgxx.rst
  components/sensor/hydreon_rgxx.rst
Labels: current

#3196 Update diy.rst
  guides/diy.rst
Labels: current

#3190 Remove enable_ipv6 restricted to ESP32 with ESP-IDF
  components/network.rst
Labels: has-parent, next

#3198 document pulldowns option
  components/matrix_keypad.rst
Labels: has-parent, next

#3199 2023.9.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.9.0.rst
  components/network.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3185 Update growatt_solar.rst
  components/sensor/growatt_solar.rst
Labels: current

#3203 Fix typo in tm1637.rst
  components/display/tm1637.rst
Labels: current

#3207 Fix typos in pmsa003i.rst
  components/sensor/pmsa003i.rst
Labels: has-parent, current

#3211 Update neopixelbus.rst
  components/light/neopixelbus.rst
Labels: current

#3212 2023.9.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.9.0.rst
  components/light/neopixelbus.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3213 2023.9.0
  Doxygen
  Makefile
  _static/changelog-2023.9.0.png
  _static/version
  changelog/2023.9.0.rst
  changelog/index.rst
  components/canbus.rst
  components/climate/climate_ir.rst
  components/debug.rst
  components/display/st7789v.rst
  components/esp32_ble_server.rst
  components/libretiny.rst
  components/light/fastled.rst
  components/light/images/apa102.jpg
  components/light/images/lightwaverf.jpg
  components/light/lightwaverf.rst
  components/light/neopixelbus.rst
  components/light/spi_led_strip.rst
  components/modbus_controller.rst
  components/network.rst
  components/output/libretiny_pwm.rst
  components/psram.rst
  components/sensor/adc.rst
  components/sensor/bmi160.rst
  components/sensor/hrxl_maxsonar_wr.rst
  components/sensor/htu21d.rst
  components/sensor/images/bmi160-full.jpg
  components/sensor/images/bmi160-ui.png
  components/sensor/images/pmwcs3.jpg
  components/sensor/images/sen0321.jpg
  components/sensor/pmwcs3.rst
  components/sensor/sen0321.rst
  components/sensor/sht3xd.rst
  components/spi.rst
  components/text_sensor/libretiny.rst
  components/wireguard.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/apa102.jpg
  images/bk72xx.svg
  images/bmi160.jpg
  images/libretiny.svg
  images/pmwcs3.jpg
  images/psram.svg
  images/rtl87xx.svg
  images/sen0321.jpg
  images/wireguard_custom_logo.svg
  index.rst
Labels: current

#3143 fix display always on issue with 7.50inv2 epaper screens
  components/display/waveshare_epaper.rst
Labels: has-parent, current

#3214 Add some breaking Changes to changelog
  changelog/2023.9.0.rst
Labels: has-parent, current

#3075 Tuya number scaling
  components/number/tuya.rst
Labels: has-parent, next

#3218 2023.9.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.9.0.rst
  components/number/tuya.rst
  conf.py
  guides/supporters.rst
Labels: current

#3219 SHT3x heater_enabled defaults to false
  components/sensor/sht3xd.rst
Labels: has-parent, next
