Repository esphome/esphome-docs, pull requests merged in 2023-02, with the labels that each got.

#2637 Correct modbus_controller "value_type" signed and unsigned data type descriptions
  components/output/modbus_controller.rst
Labels: current

#2638 Bump devcontainer to python 3.10
  .devcontainer/devcontainer.json
Labels: current

#2639 sensor index: add missing commas
  components/sensor/index.rst
Labels: current

#2553 Add initial docs for mdns extensions
  components/mdns.rst
Labels: has-parent, next

#2631 Update SCD30 sensor documentation
  components/sensor/scd30.rst
Labels: has-parent, next

#2629 Add dot
  components/sensor/index.rst
Labels: current

#2643 Update index.rst
  components/output/index.rst
Labels: current

#2635 Added example with the expanded form for file
  components/display/index.rst
Labels: current

#2627 Onboard USB chip may interfere with deep sleep.
  components/deep_sleep.rst
Labels: current

#2632 Update migrate_sonoff_tasmota.rst
  guides/migrate_sonoff_tasmota.rst
Labels: current

#2591 Alternative Costco Feit A19 Bulb config
  components/output/sm16716.rst
Labels: current

#2622 Update st7789v.rst
  components/display/st7789v.rst
Labels: current

#2584 Examples of Daly BMS control using uart.write
  components/sensor/daly_bms.rst
Labels: current

#2577 Fix list layout for Graph>'Trace specific fields'
  components/display/index.rst
Labels: current

#2570 Update dallas.rst
  components/sensor/dallas.rst
Labels: current

#2568 Removing information that after some testing isn't true
  components/rp2040.rst
Labels: current

#2561 Update getting_started_command_line.rst
  guides/getting_started_command_line.rst
Labels: current

#2574 Update index.rst
  components/light/index.rst
Labels: current

#2560 Update diy.rst
  guides/diy.rst
Labels: current

#2549 Update ccs811.rst
  components/sensor/ccs811.rst
Labels: current

#2385 Add documentation for LD2410
  components/sensor/images/ld2410.jpg
  components/sensor/ld2410.rst
  images/ld2410.jpg
  index.rst
Labels: has-parent, next

#2397 Documentation for `vbus` component
  components/vbus.rst
  images/resol_deltasol_bs_plus.jpg
  images/resol_vbus_adapter_schematic.png
  index.rst
Labels: has-parent, next

#2649 Add JL1101 to ethernet docs
  components/ethernet.rst
Labels: has-parent, next

#2646 adds INPUT_OUTPUT_OPEN_DRAIN
  guides/configuration-types.rst
Labels: has-parent, next

#2493 Update mopeka_pro_check documentation to support Lippert devices
  components/sensor/images/mopeka_pro_check_lippert.jpg
  components/sensor/mopeka_pro_check.rst
Labels: stale, has-parent, next

#2160 climate: add support for quiet fan speed
  components/climate/index.rst
  components/climate/thermostat.rst
Labels: has-parent, next

#2641 Add preset MQTT topics + remove away mode refs
  components/climate/index.rst
Labels: has-parent, next

#2650 Add note about startup time for mics4514
  components/sensor/mics_4514.rst
Labels: next

#2318 Added documentation for the CanalSat and CanalSatLD codec
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, not-stale

#2655 2023.2.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.2.0.rst
  conf.py
Labels: beta

#2656 2023.2.0b3
  Doxygen
  Makefile
  _static/2023-02-09_16-51.png
  _static/version
  changelog/2023.2.0.rst
  conf.py
Labels: beta

#2657 LED Drivers - Fix typo
  components/output/bp1658cj.rst
  components/output/bp5758d.rst
  components/output/my9231.rst
  components/output/sm16716.rst
  components/output/sm2135.rst
  components/output/sm2235.rst
  components/output/sm2335.rst
Labels: next

#2660 Added note for “SetOption78 1” in Tasmota
  guides/migrate_sonoff_tasmota.rst
Labels: current

#2659 Nvds display clipping
  components/display/index.rst
Labels: has-parent, next

#2661 Fix typos on Geiger counter page
  cookbook/geiger-counter.rst
Labels: current

#2662 Update description on power measuring in v2.x
  devices/sonoff.rst
Labels: current

#2652 Update hdc1080.rst
  components/sensor/hdc1080.rst
Labels: current

#2636 Update sgp30 URL
  components/sensor/sgp30.rst
Labels: current

#2665 Issue3914
  components/climate/midea.rst
Labels: has-parent, next

#2666 2023.2.0b5
  Doxygen
  Makefile
  _static/2023-02-13_16-27.png
  _static/2023-02-13_16-29.png
  _static/2023-02-14_10-09.png
  _static/version
  changelog/2023.2.0.rst
  components/climate/midea.rst
  components/sensor/sgp30.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2670 Update example to use Color::BLACK not COLOR_BLACK
  components/display/ili9341.rst
Labels: current

#2673 2023.2.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2675 Update pid doc with sigma_delta link
  components/climate/pid.rst
Labels: current

#2676 Update sigma_delta doc links on bottom
  components/output/sigma_delta.rst
Labels: current

#2677 Update floating outputs links
  components/output/index.rst
Labels: current

#2679 2023.2.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2684 Fix CT clamp API URL
  components/sensor/ct_clamp.rst
Labels: current

#2683 Fix SEN5X datasheet URL
  components/sensor/sen5x.rst
Labels: current

#2674 Fixed SenseAir CO2 sensor product url
  components/sensor/senseair.rst
Labels: current

#2689 2023.2.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2686 Support for color types on Tuya light
  components/light/tuya.rst
Labels: has-parent, next

#2611 Add internal_temperature component
  components/sensor/images/internal_temperature-ui.png
  components/sensor/internal_temperature.rst
  images/thermometer.svg
  index.rst
Labels: has-parent, next

#2690 ens210 must be lowercase
  components/sensor/ens210.rst
Labels: current

#2687 remove keep_user_credentials
  guides/creators.rst
Labels: current

#2691 Add docs for split visual temperature step
  components/climate/index.rst
Labels: has-parent, next

#2510 Sprinkler docs v2 update
  components/sprinkler.rst
  guides/automations.rst
Labels: has-parent, next

#2694 clarify matrix keypad pin requirements
  components/matrix_keypad.rst
Labels: current

#2678 add person sensor (sen21231) from useful sensors
  components/sensor/images/sen21231.png
  components/sensor/sen21231.rst
  images/sen21231.png
  index.rst
Labels: has-parent, next

#2697 2023.2.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2411 Documentation for `kuntze` component
  components/kuntze.rst
  images/kuntze.jpg
Labels: has-parent, next, not-stale

#2431 Add haier climate component
  components/climate/haier.rst
  components/climate/images/usb_pinout.png
  images/haier.svg
  index.rst
Labels: has-parent, next

#2177 Added energy sensor to pzemdc
  components/sensor/pzemdc.rst
Labels: has-parent, next, not-stale

#2707 Add friendly name to docs
  components/esphome.rst
Labels: current

#2704 2 Update gps.rst
  components/gps.rst
Labels: current

#2710 Fix adc link
  components/sensor/adc.rst
Labels: current

#2711 Remove copy paste config var mistake on mics-4514
  components/sensor/mics_4514.rst
Labels: current
