Repository esphome/esphome-docs, pull requests merged in 2023-04, with the labels that each got.

#2763 Add clarity for use of multiplier
  components/sprinkler.rst
Labels: current

#2802 Group and sort binary sensors into categories
  index.rst
Labels: current

#2803 fix typo
  components/switch/safe_mode.rst
Labels: current

#2524 Mmc5603
  components/sensor/mmc5063.rst
  images/mmc5603.jpg
  index.rst
Labels: stale, has-parent, next

#2810 Fix datasheet link for PCA9685 component
  components/output/pca9685.rst
Labels: current

#2811 Fix pulse_counter example unit name
  components/sensor/pulse_counter.rst
Labels: current

#2806 Add TZ timezone string examples
  components/time/index.rst
Labels: current

#2804 Update sht3xd.rst
  components/sensor/sht3xd.rst
Labels: current

#2792 H801 Documentation cleanup
  cookbook/h801.rst
  cookbook/images/gpio.jpg
  cookbook/images/h801-board-back.jpg
  cookbook/images/h801-board-front.jpg
  cookbook/images/h801-header.jpg
  cookbook/images/rgbw.jpg
  cookbook/images/rgbwarm.jpg
Labels: current

#2814 fix link to config example
  cookbook/ehmtx.rst
Labels: current

#2815 BP1658CJ - Fix power level defaults in configuration variables section.
  components/output/bp1658cj.rst
Labels: current

#2816 Remove migrated items from Cookbook
  components/modbus.rst
  components/modbus_controller.rst
  components/sensor/ltr390.rst
  components/sensor/modbus_controller.rst
  cookbook/air_gradient_diy_air_quality_sensor.rst
  cookbook/ble_itag.rst
  cookbook/bruh.rst
  cookbook/esw01-eu.rst
  cookbook/geiger-counter.rst
  cookbook/h801.rst
  cookbook/iaq_board.rst
  cookbook/ifan02.rst
  cookbook/ilonda-wifi-smart-fish-feeder.rst
  cookbook/images/air_gradient_diy_air_quality_sensor.jpg
  cookbook/images/esw01-eu-pcb-bottom.jpg
  cookbook/images/esw01-eu-pcb-top.jpg
  cookbook/images/esw01-eu.jpg
  cookbook/images/h801-board-back.jpg
  cookbook/images/h801-board-front.jpg
  cookbook/images/h801-pir_sensor.jpg
  cookbook/images/h801.jpg
  cookbook/images/iaq_board1.jpg
  cookbook/images/iaq_board2.jpg
  cookbook/images/ilonda-wifi-smart-fish-feeder-cookbook.jpg
  cookbook/images/ilonda-wifi-smart-fish-feeder.jpg
  cookbook/images/iwoole_rgbw_table_lamp.png
  cookbook/images/iwoole_rgbw_table_lamp_connections_bottom.jpg
  cookbook/images/iwoole_rgbw_table_lamp_connections_top.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_1.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_2.jpg
  cookbook/images/iwoole_rgbw_table_lamp_internal_3.jpg
  cookbook/images/iwoole_rgbw_table_lamp_wires_bottom.jpg
  cookbook/images/iwoole_rgbw_table_lamp_wires_top.jpg
  cookbook/images/radiationD-v1-1-cajoe_small.jpg
  cookbook/images/teckin_sb50.jpg
  cookbook/images/temt6000-header.jpg
  cookbook/images/temt6000-pins.jpg
  cookbook/images/tracer-an.jpg
  cookbook/images/tuya_rgbw.jpg
  cookbook/iwoole_rgbw_table_lamp.rst
  cookbook/pir.rst
  cookbook/relay.rst
  cookbook/teckin_sb50.rst
  cookbook/temt6000.rst
  cookbook/tracer-an.rst
  cookbook/tuya_rgbw.rst
  index.rst
Labels: has-parent, current

#2813 Initial voice assistant documentation
  components/i2s_audio.rst
  components/index.rst
  components/media_player/i2s_audio.rst
  components/microphone/i2s_audio.rst
  components/microphone/index.rst
  components/voice_assistant.rst
  images/microphone.svg
  images/voice-assistant.svg
  index.rst
Labels: has-parent, next

#2805 Add docs for SSD1306 72x40 display
  components/display/ssd1306.rst
Labels: has-parent, next

#2820 Remove migrated items from Cookbook (part2)
  cookbook/brilliant-mirabella-genio-smart-plugs.rst
  cookbook/images/brilliant-mirabella-genio-smart-plugs-homeassistant.jpg
  cookbook/images/brilliant-mirabella-genio-smart-plugs.jpg
  cookbook/images/mirabella-genio-b22-rgbw-homeassistant.jpg
  cookbook/images/mirabella-genio-b22-rgbw.jpg
  cookbook/images/pir-header.jpg
  cookbook/images/pir-inside.jpg
  cookbook/images/pir-pins.jpg
  cookbook/images/pir-ui.png
  cookbook/images/relay-full.jpg
  cookbook/images/zemismart-rgbw-downlight-homeassistant.jpg
  cookbook/images/zemismart-rgbw-downlight.jpg
  cookbook/mirabella-genio-bulb.rst
  cookbook/pir.rst
  cookbook/relay.rst
  cookbook/zemismart-rgbw-downlights.rst
  index.rst
Labels: has-parent, current

#2821 Add/Rename item in Cookbook
  components/display/lcd_display.rst
  cookbook/lambda_magic.rst
  index.rst
Labels: current

#2819 Add some missing binary sensors to the index
  index.rst
Labels: current

#2817 Update modbus_controller.rst
  components/modbus_controller.rst
Labels: current

#2825 Queuing Remote Transmissions cookbook
  cookbook/lambda_magic.rst
Labels: current

#2827 Add seealso link to cookbook
  components/rf_bridge.rst
Labels: current

#2808 [Ethernet] Add PHY KSZ8081 support
  components/ethernet.rst
Labels: has-parent, next

#2571 feat: Add manual control config variable doc
  components/cover/time_based.rst
Labels: has-parent, next

#2831 2023.4.0b1
  Doxygen
  Makefile
  _static/changelog-2023.4.0.png
  _static/version
  changelog/2023.4.0.rst
  changelog/index.rst
  components/binary_sensor/index.rst
  components/button/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/cover/time_based.rst
  components/display/max7219digit.rst
  components/display/ssd1306.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/ethernet.rst
  components/fan/index.rst
  components/i2s_audio.rst
  components/index.rst
  components/light/index.rst
  components/light/status_led.rst
  components/lock/index.rst
  components/media_player/i2s_audio.rst
  components/media_player/index.rst
  components/microphone/i2s_audio.rst
  components/microphone/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/sensor/mmc5063.rst
  components/sensor/pmsx003.rst
  components/spi.rst
  components/switch/index.rst
  components/text_sensor/index.rst
  components/voice_assistant.rst
  conf.py
  guides/supporters.rst
  images/microphone.svg
  images/mmc5603.jpg
  images/voice-assistant.svg
  index.rst
Labels: beta

#2796 Document Bayesian type for binary_sensor_map component
  components/sensor/binary_sensor_map.rst
Labels: has-parent, next

#2833 redirects items transferred to devices site
  _redirects
Labels: current

#2824 Added Sensor Longevity and correction to PMSX003
  components/sensor/pmsx003.rst
Labels: has-parent, next

#2835 Further movement to devices site
  _redirects
  components/output/template.rst
  cookbook/dual-r2-cover.rst
  cookbook/endstop-cover.rst
  cookbook/lambda_magic.rst
  cookbook/sonoff-basic-light-switch.rst
  cookbook/sonoff-dual-light-switch.rst
  cookbook/sonoff-light-switch.rst
  cookbook/sonoff-t1-3.rst
  images/garage-variant.svg
  images/head-lightbulb-outline.svg
  index.rst
Labels: current

#2836 Small corrections
  components/sensor/homeassistant.rst
Labels: current

#2846 Add tasks file for vscode
  .vscode/tasks.json
Labels: current

#2849 Add triggers to voice assistant
  components/voice_assistant.rst
Labels: has-parent, next

#2854 fix "cycle: !lambda:"
  components/number/index.rst
Labels: current

#2856 Fix strftime issue in max7219 doc
  components/display/max7219.rst
Labels: current

#2858 2023.4.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.4.0.rst
  conf.py
Labels: beta

#2859 2023.4.0
  Doxygen
  Makefile
  _static/changelog-2023.4.0.png
  _static/version
  changelog/2023.4.0.rst
  changelog/index.rst
  components/binary_sensor/index.rst
  components/button/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/cover/time_based.rst
  components/display/max7219digit.rst
  components/display/ssd1306.rst
  components/display/waveshare_epaper.rst
  components/esp32_camera.rst
  components/ethernet.rst
  components/fan/index.rst
  components/i2s_audio.rst
  components/index.rst
  components/light/index.rst
  components/light/status_led.rst
  components/lock/index.rst
  components/media_player/i2s_audio.rst
  components/media_player/index.rst
  components/microphone/i2s_audio.rst
  components/microphone/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/sensor/mmc5063.rst
  components/sensor/pmsx003.rst
  components/spi.rst
  components/switch/index.rst
  components/text_sensor/index.rst
  components/voice_assistant.rst
  conf.py
  guides/supporters.rst
  images/microphone.svg
  images/mmc5603.jpg
  images/voice-assistant.svg
  index.rst
Labels: current

#2812 Add support for passive WiFi scanning.
  components/wifi.rst
Labels: has-parent, next

#2860 Add HA version requirement on release notes
  changelog/2023.4.0.rst
Labels: current

#2869 fix uart id in example
  components/sensor/growatt_solar.rst
Labels: current

#2870 Update servo.rst
  components/servo.rst
Labels: current

#2872 Fix examples with `uart1` in id
  components/sensor/havells_solar.rst
  components/sensor/ld2410.rst
Labels: current

#2871 2023.4.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2876 Add copy for on_tag_removed trigger for RC522
  components/binary_sensor/rc522.rst
  guides/automations.rst
Labels: has-parent, next

#2845 Adding docs for mlx90614
  components/sensor/images/mlx90614.jpg
  components/sensor/mlx90614.rst
  images/mlx90614.jpg
  index.rst
Labels: has-parent, next

#2877 2023.4.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current
