Repository esphome/esphome-docs, pull requests merged in 2023-06, with the labels that each got.

#2961 Update http_request_sensor.rst
  cookbook/http_request_sensor.rst
Labels: current

#2962 Update http_request_sensor.rst
  cookbook/http_request_sensor.rst
Labels: current

#2963 Add more links to See Also
  web-api/index.rst
Labels: current

#2964 Add more links to See Also, fix REST API hook
  components/web_server.rst
Labels: current

#2965 Add more links to See Also
  components/prometheus.rst
Labels: current

#2966 Correct web_server auth type
  components/web_server.rst
Labels: current

#2967 Update http_request_sensor.rst
  cookbook/http_request_sensor.rst
Labels: current

#2969 Brush up page looks for Web Server Component
  components/web_server.rst
Labels: current

#2972 Remove python-based update cookbook
  index.rst
Labels: current

#2973 Remove python-based update cookbook
  cookbook/homeassistant_upgrade.rst
Labels: current

#2976 document addition of power_supply option to ST7789V component
  components/display/st7789v.rst
Labels: has-parent, next

#2980 configuration-types: Demonstrate usage of packages as templates
  guides/configuration-types.rst
Labels: current

#2837 Add mdi image documentation
  components/display/index.rst
Labels: has-parent, next

#2888 Allow list of MAC addresses for 'on_ble_advertise' trigger
  components/esp32_ble_tracker.rst
Labels: has-parent, next

#2983 Add SVG support
  components/display/index.rst
Labels: has-parent, next

#2979 New i2s_comm_fmt parameter for i2c_audio media_player
  components/media_player/i2s_audio.rst
Labels: has-parent, next

#2985 Adding clarity to the "Note" in deepsleep docs
  components/deep_sleep.rst
Labels: current

#2989 Add warning for addressable lights on esp-idf
  components/light/fastled.rst
  components/light/neopixelbus.rst
Labels: current

#2891 Add Alarm Control Panel
  components/alarm_control_panel/index.rst
  components/alarm_control_panel/template.rst
  components/index.rst
  images/alarm-panel.svg
  index.rst
Labels: has-parent, next

#2993 Fix ACP Header
  components/alarm_control_panel/index.rst
Labels: next

#2992 Add Deltasol 2009
  components/images/vbus_serial_optocoupler.png
  components/vbus.rst
Labels: has-parent, next

#2997 Fix alarm template cosmetics
  components/alarm_control_panel/template.rst
Labels: next

#2988 Add ESP32-S3-Box-Lite display documentation
  components/display/ili9xxx.rst
Labels: has-parent, next

#2994 S3 box display
  components/display/ili9xxx.rst
Labels: has-parent, next

#3000 Added hints about repetition of signals
  components/remote_transmitter.rst
Labels: current

#2996 display: allow to align image with `ImageAlign`
  components/display/index.rst
Labels: has-parent, next

#3003 2023.6.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  components/alarm_control_panel/index.rst
  components/alarm_control_panel/template.rst
  components/display/ili9xxx.rst
  components/display/index.rst
  components/images/vbus_serial_optocoupler.png
  components/remote_transmitter.rst
  components/vbus.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2809 Haier climate documentation updated to support new functionality
  components/climate/haier.rst
  components/climate/images/haier_pinout.jpg
Labels: has-parent, next

#2949 XL9535 I/O Expander
  components/xl9535.rst
  images/xl9535.svg
  index.rst
Labels: has-parent, next

#3001 Add animation actions documentation
  components/display/index.rst
Labels: has-parent, next

#3006 2023.6.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: beta

#3008 2023.6.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3009 2023.6.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
Labels: beta

#3010 2023.6.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3012 2023.6.0b7
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3013 2023.6.0
  Doxygen
  Makefile
  _static/changelog-2023.6.0.png
  _static/version
  changelog/2023.6.0.rst
  changelog/index.rst
  components/alarm_control_panel/index.rst
  components/alarm_control_panel/template.rst
  components/binary_sensor/ble_presence.rst
  components/display/ili9xxx.rst
  components/display/index.rst
  components/display/st7789v.rst
  components/esp32_ble_tracker.rst
  components/i2s_audio.rst
  components/images/vbus_serial_optocoupler.png
  components/index.rst
  components/light/rp2040_pio_led_strip.rst
  components/media_player/i2s_audio.rst
  components/microphone/i2s_audio.rst
  components/sensor/images/tmp1075.jpg
  components/sensor/mopeka_pro_check.rst
  components/sensor/tmp1075.rst
  components/text_sensor/wifi_info.rst
  components/vbus.rst
  components/voice_assistant.rst
  components/wifi.rst
  conf.py
  guides/supporters.rst
  images/alarm-panel.svg
  images/tmp1075.jpg
  index.rst
Labels: current

#3014 Update wifi.rst
  components/wifi.rst
Labels: current

#3018 2023.6.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3020 Fix schema 202306
  components/alarm_control_panel/template.rst
  components/display/index.rst
  components/max6956.rst
  components/sensor/tmp1075.rst
  components/speaker/index.rst
  schema_doc.py
Labels: has-parent, current

#3019 2023.6.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3023 ili9xxx: add list of models on top of the document.
  components/display/ili9xxx.rst
  index.rst
Labels: current

#3024 Update display index images and alphabetise
  images/ili9341.svg
  images/ili9342.svg
  images/ili9481.svg
  images/ili9486.svg
  images/ili9488.svg
  images/st7796.svg
  index.rst
Labels: current

#3016 Added missing indentation in example RP2040 PIO LED Strip
  components/light/rp2040_pio_led_strip.rst
Labels: current

#3017 [time] Fix cron typo to real every 5min
  components/time/index.rst
Labels: current

#2999 bluetooth_proxy: Clarify that only BLE devices are supported.
  components/bluetooth_proxy.rst
Labels: current

#3026 Add missing "activate venv" instructions
  guides/contributing.rst
Labels: current

#3004 Updates migrate_sonoff_tasmota.rst. Improves information about compressed images.
  guides/images/dashboard-install-manual-modern.png
  guides/images/dashboard-install-manual.png
  guides/images/dashboard-install.png
  guides/migrate_sonoff_tasmota.rst
Labels: has-parent, current

#3027 2023.6.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3032 Fix typo
  components/uart.rst
Labels: current
