Repository esphome/esphome-docs, pull requests merged in 2023-10, with the labels that each got.

#3226 2023.9.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3227 Add installer page
  _static/ready-made/bluetooth-proxy/esp32_generic.png
  _static/ready-made/bluetooth-proxy/gl-s10.png
  _static/ready-made/bluetooth-proxy/header.png
  _static/ready-made/bluetooth-proxy/lilygo-eth-poe.png
  _static/ready-made/bluetooth-proxy/m5stack_atom_lite.png
  _static/ready-made/bluetooth-proxy/olimex_esp32_poe_iso.png
  _static/ready-made/bluetooth-proxy/wt32-eth01.png
  _static/ready-made/empty/espressif.png
  _static/ready-made/empty/pico-w.png
  _static/ready-made/media-player/atom_echo.png
  _static/ready-made/media-player/atom_speaker_kit.png
  _static/ready-made/media-player/esp_muse_luxe.png
  _static/ready-made/media-player/esp_muse_proto.png
  index.rst
  ready-made/installer.html
  ready-made/projects.rst
Labels: current

#3228 Fix empty espressif install
  ready-made/installer.html
Labels: current

#3205 Allow Poller Component suspend / resume action
  guides/automations.rst
Labels: has-parent, next

#3229 ready-made/devices -> projects
  _redirects
  _static/projects/bluetooth-proxy/esp32_generic.png
  _static/projects/bluetooth-proxy/gl-s10.png
  _static/projects/bluetooth-proxy/header.png
  _static/projects/bluetooth-proxy/lilygo-eth-poe.png
  _static/projects/bluetooth-proxy/m5stack_atom_lite.png
  _static/projects/bluetooth-proxy/olimex_esp32_poe_iso.png
  _static/projects/bluetooth-proxy/wt32-eth01.png
  _static/projects/empty/espressif.png
  _static/projects/empty/pico-w.png
  _static/projects/media-player/atom_echo.png
  _static/projects/media-player/atom_speaker_kit.png
  _static/projects/media-player/esp_muse_luxe.png
  _static/projects/media-player/esp_muse_proto.png
  index.rst
  projects/index.rst
  projects/installer.html
Labels: current

#3230 Fix ready made projects redirect
  _redirects
Labels: current

#3224 Tuya Number: split "multiply" to a separate option
  components/number/tuya.rst
Labels: has-parent, next

#3231 2023.9.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.9.0.rst
  components/number/tuya.rst
  conf.py
  guides/supporters.rst
Labels: current

#3222 Add Xor Condition
  guides/automations.rst
Labels: has-parent, next

#3220 Fix units for SPS30 number concentration sensors
  components/sensor/sps30.rst
Labels: has-parent, next

#3236 Add mode and data_rate configuration for st7789v.
  components/display/st7789v.rst
Labels: has-parent, next

#3237 sht3xd: document the reason & effects for `heater_enabled`
  components/sensor/sht3xd.rst
Labels: current

#3238 Install bluetooth proxies and media players from firmware.esphome.io
  projects/installer.html
Labels: has-parent, current

#3246 Fixed typo in automations.rst
  guides/automations.rst
Labels: current

#3233 Documentation for Haier IR protocol added
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3170 Add docs for new sensor MMC5983
  components/sensor/mmc5983.rst
  images/mmc5983.jpg
  index.rst
Labels: has-parent, next

#3249 Clarifications to pulse_width documentation
  components/sensor/pulse_width.rst
Labels: has-parent, current

#3248 Documentation for !extend
  guides/configuration-types.rst
Labels: has-parent, current

#3252 Don't hide all hardware when webserial unsupported
  projects/installer.html
Labels: current

#3152 Voice assistant updates
  components/voice_assistant.rst
Labels: has-parent, next

#3251 fixes docs for 202310
  components/alarm_control_panel/index.rst
  components/display/st7789v.rst
  components/grove_tb6612fng.rst
  components/images/lightwaverf.jpg
  components/lightwaverf.rst
  components/mqtt.rst
  components/number/tuya.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/gcja5.rst
  components/sensor/ld2410.rst
  components/sensor/pmwcs3.rst
  components/vbus.rst
  index.rst
  schema_doc.py
Labels: current

#3256 Add Voice installers to ready-made projects
  _static/projects/voice-assistant/esp32-s3-box-3.png
  projects/installer.html
Labels: current

#3245 add manual set the invert_display option
  components/display/ili9xxx.rst
Labels: has-parent, next

#3173 As3935 calibration
  components/sensor/as3935.rst
Labels: has-parent, next

#3257 Add documentation for the new selecy entity detail query parameter
  web-api/index.rst
Labels: has-parent, next

#3235 Add doc for backlight pin disable
  components/display/st7789v.rst
Labels: has-parent, next

#3258 2023.10.0b1
  Doxygen
  Makefile
  _static/changelog-2023.10.0.png
  _static/version
  changelog/2023.10.0.rst
  changelog/index.rst
  components/display/ili9xxx.rst
  components/display/st7789v.rst
  components/matrix_keypad.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/as3935.rst
  components/sensor/mmc5983.rst
  components/sensor/sht3xd.rst
  components/sensor/sps30.rst
  components/voice_assistant.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/mmc5983.jpg
  index.rst
  web-api/index.rst
Labels: beta

#3262 Add status indicator information to esp32 improv
  components/esp32_improv.rst
Labels: current

#3263 2023.10.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  components/display/st7789v.rst
  components/esp32_improv.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3266 Add round sensor filter
  components/sensor/index.rst
Labels: has-parent, next

#3268 Add documentation for the color_temp light POST query parameter
  web-api/index.rst
Labels: current

#3260 Documentation for SFA30 component
  components/sensor/images/sfa30.jpg
  components/sensor/sfa30.rst
  images/sfa30.jpg
  index.rst
Labels: has-parent, next

#3267 Include multi conf and change address for TB6612FNG
  components/grove_tb6612fng.rst
Labels: has-parent, next

#3274 2023.10.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  components/grove_tb6612fng.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3270 document uart button
  components/button/uart.rst
  index.rst
Labels: has-parent, next

#3269 document new uart switch options
  components/switch/uart.rst
Labels: has-parent, next

#3276 2023.10.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3278 2023.10.0
  Doxygen
  Makefile
  _static/changelog-2023.10.0.png
  _static/version
  changelog/2023.10.0.rst
  changelog/index.rst
  components/display/ili9xxx.rst
  components/display/st7789v.rst
  components/grove_tb6612fng.rst
  components/matrix_keypad.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/as3935.rst
  components/sensor/mmc5983.rst
  components/sensor/sht3xd.rst
  components/sensor/sps30.rst
  components/voice_assistant.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/mmc5983.jpg
  index.rst
  web-api/index.rst
Labels: current

#3280 devcontainer updates
  .devcontainer/devcontainer.json
Labels: current

#3279 Add wifi_timeout to esp32_improv
  components/esp32_improv.rst
Labels: has-parent, next

#3146 Add strapping: config for GPIO pins
  guides/configuration-types.rst
  guides/faq.rst
Labels: has-parent, next

#3206 Update hydreon_rgxx.rst
  components/sensor/hydreon_rgxx.rst
Labels: has-parent, next

#3284 2023.10.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  components/esp32_improv.rst
  conf.py
  guides/supporters.rst
Labels: current

#3283 Fan no off cycle action
  components/fan/index.rst
Labels: has-parent, next

#3286 Add LILYGO T-ETH-Lite to ethernet.rst
  components/ethernet.rst
Labels: current

#3287 Fix an embarrassing typo in the new mmc5983 docs
  components/sensor/mmc5983.rst
Labels: current

#3244 Update display document with test script
  components/display/index.rst
Labels: current

#3288 Add documentation for WireGuard address text sensor
  components/wireguard.rst
  index.rst
Labels: has-parent, next

#3290 2023.10.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2204 Add ZH/LT-01 climate ir integration
  components/climate/climate_ir.rst
Labels: has-parent, next

#2685 Add GREE to climate_ir
  components/climate/climate_ir.rst
Labels: next, not-stale

#3104 iAQ Core
  components/sensor/iaqcore.rst
  components/sensor/images/iaqcore.jpg
  images/iaqcore.jpg
  index.rst
Labels: has-parent, next

#3292 2023.10.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3061 Update climate_ir.rst
  components/climate/climate_ir.rst
Labels: has-parent, next

#3293 Add text component docs
  components/copy.rst
  components/index.rst
  components/text/index.rst
  components/text/template.rst
  index.rst
Labels: has-parent, next

#3053 Update esp32_camera.rst
  components/esp32_camera.rst
Labels: current

#3240 PM1006: add note regarding standalone UART init
  components/sensor/pm1006.rst
Labels: current

#3253 HLW8012: Add calibration instructions and calculator
  components/sensor/hlw8012.rst
Labels: current

#2883 display font: document using gfonts:// for icons
  components/display/index.rst
Labels: current, not-stale

#3265 Improve explanation of "while"
  guides/automations.rst
Labels: current

#3272 Update bme680.rst - add indoor air quality index and IAQ label
  components/sensor/bme680.rst
Labels: current

#3282 Correct typo in mcp23Sxx.rst
  components/mcp23Sxx.rst
Labels: current

#3289 fix canbus send config docs
  components/canbus.rst
Labels: current

#3215 Update LibreTiny docs
  components/libretiny.rst
Labels: current

#3197 Example for ESP32S3_EYE on Freenove ESP32-S3-DevKitC-1
  components/esp32_camera.rst
Labels: current

#3169 Update LD2410 Home Assistant card sample
  components/sensor/ld2410.rst
Labels: current

#3204 Honeywellabp2
  components/sensor/honeywellabp2_i2c.rst
  index.rst
Labels: has-parent, next

#2709 add emc2101 component
  components/emc2101.rst
  components/images/emc2101-full.png
  images/emc2101.jpg
  index.rst
Labels: has-parent, next, not-stale

#3106 Documentation for new Qwiic PIR binary sensor component
  components/binary_sensor/images/qwiic_pir.jpg
  components/binary_sensor/qwiic_pir.rst
  images/qwiic_pir.jpg
  index.rst
Labels: has-parent, next

#3223 Document clamp filter's ignore out of range option
  components/sensor/index.rst
Labels: has-parent, next

#3298 Add resource warnings to BLE, voice and audio component docs
  components/binary_sensor/ble_presence.rst
  components/ble_client.rst
  components/esp32_ble.rst
  components/esp32_ble_beacon.rst
  components/esp32_ble_server.rst
  components/esp32_ble_tracker.rst
  components/esp32_improv.rst
  components/microphone/i2s_audio.rst
  components/output/ble_client.rst
  components/sensor/ble_client.rst
  components/sensor/ble_rssi.rst
  components/speaker/i2s_audio.rst
  components/switch/ble_client.rst
  components/text_sensor/ble_scanner.rst
  components/voice_assistant.rst
Labels: current

#3297 Add area (zone) to esphome core config to be suggested through API and MQTT.
  components/esphome.rst
Labels: has-parent, next

#2554 Add documentation for DFRobot mmWave Radar
  components/dfrobot_sen0395.rst
  components/images/dfrobot_sen0395-full.jpg
  images/dfrobot_sen0395.jpg
  index.rst
Labels: has-parent, next, not-stale

#3299 update mcp4728 docs
  components/output/mcp4728.rst
Labels: has-parent, next

#3295 Brush up modbus
  components/modbus.rst
Labels: current

#3294 Brush up modbus controller
  components/modbus_controller.rst
Labels: current

#3307 2023.10.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3308 Add connection triggers to API doc
  components/api.rst
  guides/automations.rst
Labels: has-parent, next

#3309 Document variables available to new API triggers
  components/api.rst
Labels: has-parent, next

#3310 Add on_client_connects and disconnected triggers to voice assistant
  components/voice_assistant.rst
Labels: has-parent, next

#3315 Document PCA9535 support
  components/pca9554.rst
Labels: has-parent, next
