Repository esphome/esphome-docs, pull requests merged in 2023-11, with the labels that each got.

#3317 2023.10.5
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  components/api.rst
  components/voice_assistant.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
Labels: current

#3318 Add deprecation message to custom component pages
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/external_components.rst
  components/light/custom.rst
  components/output/custom.rst
  components/sensor/custom.rst
  components/switch/custom.rst
  components/text_sensor/custom.rst
  custom/custom_component.rst
  custom/i2c.rst
  custom/spi.rst
  custom/uart.rst
  guides/contributing.rst
Labels: current

#3319 Update api.rst
  components/api.rst
Labels: current

#3320 reupdate the changes for the RTTTL component
  components/rtttl.rst
Labels: has-parent, next

#3322 2023.10.6
  Doxygen
  Makefile
  _static/version
  changelog/2023.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3323 Fix typo in canbus.rst
  components/canbus.rst
Labels: current

#2956 LD2420 Documentation
  components/sensor/ld2420.rst
  images/ld2420.jpg
  index.rst
Labels: has-parent, next

#3324 Tweaks to index.rst for presence sensors
  index.rst
Labels: next

#2890 MicroNova component documentation
  components/images/micronova_optocouplers.png
  components/images/micronova_serial.png
  components/images/micronova_serial_layout.png
  components/micronova.rst
  images/pellet.svg
  index.rst
Labels: has-parent, next, not-stale

#3325 Add hint for activating new ESPHome devices in HA
  components/api.rst
Labels: current

#3329 min_integral and max_integral had transposed minimum & maximum
  components/climate/pid.rst
Labels: current

#3331 Added documentation for id and uart_id variables of modbus
  components/modbus.rst
Labels: current

#3335 Update esp32_camera.rst to include M5CameraF New example
  components/esp32_camera.rst
Labels: current

#3301 Add shell auto-completion documentation
  guides/cli.rst
Labels: has-parent, next

#3326 Feature/sml raw data
  components/sml.rst
Labels: has-parent, next

#3316 Document null MQTT topic behavior
  components/mqtt.rst
Labels: has-parent, next

#3303 feat: Add ESP32 BLE enable/disable automations
  components/esp32_ble.rst
Labels: has-parent, next

#3247 Add Byron SX Doorbell RF protocol to remote_base integration
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3321 Pulse light effect transition updates
  components/light/index.rst
Labels: has-parent, next

#3285 Documentation for XGZP68xx series
  components/sensor/images/6897d.jpg
  components/sensor/xgzp68xx.rst
  images/6897d.jpg
  index.rst
Labels: has-parent, next

#3217 add SPI support to ADE7953
  components/sensor/ade7953.rst
Labels: has-parent, next

#3336 Adds docs for Nextion `start_up_page`
  components/display/nextion.rst
Labels: has-parent, next

#3338 [web_server] Add documentation for Private Network Access support
  components/web_server.rst
Labels: has-parent, next

#2185 add docs for wifi.on_connect and wifi.on_disconnect
  components/wifi.rst
  guides/automations.rst
Labels: stale, has-parent, next

#3341 [sn74hc595 ] SPI config
  components/sn74hc595.rst
Labels: has-parent, next

#3337 Tidying up LD2420 doc
  components/sensor/ld2420.rst
Labels: next

#3346 Update Home Assistant logo
  images/home-assistant.svg
Labels: current

#3348 2023.11.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/sensor/ld2420.rst
  conf.py
  guides/supporters.rst
  images/home-assistant.svg
Labels: beta

#3351 Fix reference error in tm1637.rst
  components/display/tm1637.rst
Labels: current

#3352 describe valid pin numbers
  components/xl9535.rst
Labels: has-parent, next

#3354 Quick LD2420 Edit
  components/sensor/ld2420.rst
Labels: next

#3355 Update contributing.rst
  guides/contributing.rst
Labels: current

#3358 Fix a typo in the text template documentation
  components/text/template.rst
Labels: next

#3361 Update text+links for projects page
  projects/installer.html
Labels: current

#3364 2023.11.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/display/tm1637.rst
  components/text/template.rst
  conf.py
  guides/contributing.rst
  guides/supporters.rst
  projects/installer.html
Labels: beta

#3360 Fix types for text template options
  components/text/template.rst
Labels: next

#3365 2023.11.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/text/template.rst
  conf.py
Labels: beta

#3345 Add documentation for flash size
  components/esp32.rst
Labels: has-parent, next

#3363 Fix typo, double colon in fan action
  components/fan/index.rst
Labels: next

#3367 2023.11.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/esp32.rst
  components/fan/index.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3368 Add ESP32 S3 box to ESPHome projects
  projects/installer.html
Labels: has-parent, current

#3369 Fix decay_mode comment in hbridge fan example configuration.
  components/fan/hbridge.rst
Labels: current

#3340 Update servo.rst
  components/servo.rst
Labels: current

#3376 Add Seeed Studio mmWave Sensor MR24HPC1 document
  components/images/seeed-mr24hpc1-card.png
  components/images/seeed-mr24hpc1-mmwave-kit.png
  components/images/seeed-mr24hpc1.jpg
  components/sensor/images/seeed-mr24hpc1-card.png
  components/sensor/images/seeed-mr24hpc1-mmwave-kit.png
  components/sensor/images/seeed-mr24hpc1.jpg
  components/sensor/seeed_mr24hpc1.rst
  images/seeed-mr24hpc1-card.jpg
  images/seeed-mr24hpc1-mmwave-kit.jpg
  images/seeed-mr24hpc1.jpg
  index.rst
Labels: has-parent, next

#3379 wifi signal percent device class blank for HA log warning
  components/sensor/wifi_signal.rst
Labels: current

#3380 Revert "Add Seeed Studio mmWave Sensor MR24HPC1 document"
  components/images/seeed-mr24hpc1-card.png
  components/images/seeed-mr24hpc1-mmwave-kit.png
  components/images/seeed-mr24hpc1.jpg
  components/sensor/images/seeed-mr24hpc1-card.png
  components/sensor/images/seeed-mr24hpc1-mmwave-kit.png
  components/sensor/images/seeed-mr24hpc1.jpg
  components/sensor/seeed_mr24hpc1.rst
  images/seeed-mr24hpc1-card.jpg
  images/seeed-mr24hpc1-mmwave-kit.jpg
  images/seeed-mr24hpc1.jpg
  index.rst
Labels: next

#3384 Enable Box 3 variant
  projects/installer.html
Labels: has-parent, current

#3382 Add docs for additional VA triggers
  components/voice_assistant.rst
Labels: has-parent, next

#3094 Add SH1107 documentation to SSD1306 page
  components/display/ssd1306.rst
Labels: has-parent, next

#3385 2023.11.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/voice_assistant.rst
  conf.py
  guides/supporters.rst
Labels: current

#3388 Add 2MB option for partitions.csv generation and restore use of user-defined partitions
  components/esp32.rst
Labels: has-parent, next

#3392 2023.11.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/esp32.rst
  conf.py
  guides/supporters.rst
Labels: current

#3394 Update mopeka docs
  components/sensor/mopeka_pro_check.rst
Labels: wrong-base-branch, has-parent, current

#3395 Update esp32_ble_tracker.rst - typo
  components/esp32_ble_tracker.rst
Labels: current

#3349 Updated Haier documentation with new configuration values description
  components/climate/haier.rst
Labels: has-parent, next

#3398 Revert "Update mopeka docs"
  components/sensor/mopeka_pro_check.rst
Labels: current

#3378 Update Lambda Magic Cookbook with text-to-float conversion example
  cookbook/lambda_magic.rst
Labels: current

#3399 Add some additional VA triggers, part 2
  components/voice_assistant.rst
Labels: has-parent, next

#3403 2023.11.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/voice_assistant.rst
  conf.py
  guides/supporters.rst
Labels: current

#3404 Document non-numeric Wiegand keys
  components/wiegand.rst
Labels: current

#2981 sen5x normalized_offset_slope as float
  components/sensor/sen5x.rst
Labels: has-parent, next, not-stale

#3407 Update index.rst
  components/select/index.rst
Labels: current

#3158 Document startup_delay for interval component
  guides/automations.rst
Labels: has-parent, next

#3409 Add documentation for images using URL
  components/display/index.rst
  lint.py
Labels: has-parent, next

#3401 Pillow: bump to 10.1.0
  components/display/index.rst
Labels: has-parent, next

#3410 2023.11.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  components/display/index.rst
  conf.py
  guides/supporters.rst
  lint.py
Labels: current

#2931 Documentation for `ens160` component
  components/sensor/ens160.rst
  components/sensor/images/ens160.jpg
  images/ens160.jpg
  index.rst
Labels: has-parent, next

#3411 Add docs for power_supply enable_on_boot config option.
  components/power_supply.rst
Labels: has-parent, next

#3400 Gt911 touchscreen component
  components/touchscreen/gt911.rst
  components/touchscreen/images/esp32_s3_box_3.png
  components/touchscreen/index.rst
  images/esp32_s3_box_3.png
  index.rst
Labels: has-parent, next

#3414 Add 'voice_assistant.connected' condition
  components/voice_assistant.rst
Labels: has-parent, next

#2841 Add pylontech integration
  components/images/pylontech.jpg
  components/images/rj45_pinout.jpg
  components/pylontech.rst
  images/pylontech.jpg
  index.rst
Labels: has-parent, next, not-stale

#3417 2023.11.6
  Doxygen
  Makefile
  _static/version
  changelog/2023.11.0.rst
  conf.py
Labels: current

#3412 Nextion `on_touch` trigger
  components/display/nextion.rst
Labels: has-parent, next

#3418 Update mopeka pro documentation to include details about universal sensor
  components/sensor/mopeka_pro_check.rst
Labels: has-parent, next

#3393 Clarify NEC data length
  components/remote_transmitter.rst
Labels: current

#3408 Update spi_led_strip.rst
  components/light/spi_led_strip.rst
Labels: current

#3402 Update ld2420.rst
  components/sensor/ld2420.rst
Labels: current

#3391 missing change directory directive
  guides/contributing.rst
Labels: current

#3386 Update sntp.rst
  components/time/sntp.rst
Labels: current

#3396 Fix DSMR request pin diagram for 3V3 GPIO output
  components/sensor/dsmr.rst
  components/sensor/images/dsmr-request-pin-circuit-example.png
Labels: current, integration: dsmr

#3413 Add HE60R Garage Door Opener
  components/cover/he60r.rst
  components/cover/images/he60r-sch.jpg
  components/cover/images/he60r.jpg
  images/he60r.jpg
  index.rst
Labels: has-parent, next

#3200 ili9xxx display component doc update
  components/display/ili9xxx.rst
Labels: has-parent, next
