Repository esphome/esphome-docs, pull requests merged in 2023-12, with the labels that each got.

#3426 Warn users about ESP32 Tasmota v12 incompatibility
  guides/migrate_sonoff_tasmota.rst
Labels: current

#3428 Add missing required attribute name
  components/sensor/airthings_ble.rst
Labels: current

#3431 Security improvement: Support wifi ap_timeout=0s (disable)
  components/wifi.rst
Labels: has-parent, next

#3366 Document option to suppress check for multiple pin usage
  guides/configuration-types.rst
Labels: has-parent, next

#3420 Change the URL of the YAML repository, as the old one is archived
  projects/installer.html
Labels: current

#3422 Adding ESPHome-Econet pointer
  guides/diy.rst
Labels: current

#3425 Update configuration-types.rst
  guides/configuration-types.rst
Labels: current

#3432 Update teleinfo.rst
  components/sensor/teleinfo.rst
Labels: current

#3435 Fix typo
  components/sensor/index.rst
Labels: current

#3406 add documentation for !remove
  guides/configuration-types.rst
Labels: has-parent, next

#3436 Added a missing tab to fix code formatting
  guides/cli.rst
Labels: current

#2572 Add graphical display menu docs
  components/display_menu/graphical_display_menu.rst
  components/display_menu/images/graphical_display_menu.jpg
  images/graphical_display_menu.jpg
  index.rst
Labels: has-parent, next, not-stale

#2933 Added description for `on_image` callback.
  components/esp32_camera.rst
Labels: has-parent, next

#3362 Update speed fan with configuration options for preset modes
  components/fan/hbridge.rst
  components/fan/index.rst
  components/fan/speed.rst
Labels: has-parent, next

#3405 Touchscreen update to explain the new features added
  components/touchscreen/ft63x6.rst
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
  images/wt32-sc01.png
  index.rst
Labels: has-parent, next

#3356 Added the A02YYUW distance sensor
  components/sensor/a02yyuw.rst
  components/sensor/images/a02yyuw-full.jpg
  images/a02yyuw.jpg
  index.rst
Labels: has-parent, next

#3221 New documentation for AHT10/AHT20 sensors
  components/sensor/aht10.rst
Labels: has-parent, next

#3069 Add doc for nec repeats commands field
  components/remote_transmitter.rst
Labels: has-parent, next, not-stale

#3359 Add humidity support to climate
  components/climate/bang_bang.rst
  components/climate/index.rst
  components/climate/pid.rst
  components/climate/thermostat.rst
Labels: has-parent, next

#3241 Add PN7160 doc
  components/binary_sensor/images/pn716x-full.jpg
  components/binary_sensor/pn7160.rst
  images/pn716x.jpg
  index.rst
Labels: has-parent, next

#3242 Add PN7150 doc
  components/binary_sensor/images/pn7150-full.jpg
  components/binary_sensor/pn7150.rst
  images/pn7150.jpg
  index.rst
Labels: has-parent, next

#3452 Template cover toggle
  components/cover/template.rst
Labels: has-parent, next

#3456 UART changing at runtime
  components/uart.rst
Labels: has-parent, next

#3457 2023.12.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  components/cover/template.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3423 Added Ft5x06 touchscreen
  components/touchscreen/ft5x06.rst
  components/touchscreen/images/indicator.jpg
  images/indicator.jpg
  index.rst
Labels: has-parent, next

#3464 2023.12.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3470 Add 'important' class to css to fix for dark mode
  _static/custom.css
Labels: current

#3475 2023.12.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3469 Update logger component docs for new USB support
  components/logger.rst
Labels: next

#3476 2023.12.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  components/logger.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3473 `HLW8012`: add `"never"` option to `change_mode_every`
  components/sensor/hlw8012.rst
Labels: has-parent, next

#3479 2023.12.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/contributing.rst
  guides/images/pr-draft-ready.png
  guides/supporters.rst
Labels: beta

#3304 feat: add documentation for AS5600
  components/sensor/as5600.rst
  components/sensor/images/as5600-full.jpg
  components/sensor/images/as5600-magnet-position.png
  components/sensor/images/as5600-ui-derived.jpg
  components/sensor/images/as5600-ui.jpg
  images/as5600.jpg
  index.rst
Labels: has-parent, next

#3370 Add documentation for include substitution defaults
  guides/configuration-types.rst
Labels: has-parent, next

#3339 Add docs for addressable color wipe gradient feature
  components/light/index.rst
Labels: has-parent, next

#3474 Updated Haier integration documentation to support alarm triggers
  components/climate/haier.rst
Labels: has-parent, next

#3481 Update ens160.rst
  components/sensor/ens160.rst
Labels: current

#3444 Add 2.7inv2 version for waveshare
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3443 Add waveshare 2.9inV3 model
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3440 Add Waveshare 1.47in to st7789v (documentation for esphome PR#5884)
  components/display/st7789v.rst
Labels: has-parent, next

#3430 (fingerprint_grow) on_finger_scan_invalid automation.
  components/fingerprint_grow.rst
Labels: has-parent, next

#3334 Update alarm docs to reflect changes in esphome/esphome#5671
  components/alarm_control_panel/index.rst
  components/alarm_control_panel/template.rst
Labels: has-parent, next

#3255 Add KeeLoq RF protocol to remote_base integration
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3484 Add a bit more text to the pin reuse message in changelog
  changelog/2023.12.0.rst
Labels: current

#3439 Add a Binary Sensor Filter for state settling
  components/binary_sensor/index.rst
Labels: has-parent, next

#3485 2023.12.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  components/uart.rst
  conf.py
  guides/supporters.rst
Labels: current

#3486 2023.12.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
Labels: current

#3494 2023.12.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3495 2023.12.5
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
Labels: current

#3482 ST7567 display support
  components/display/images/st7567-full.jpg
  components/display/st7567.rst
  images/st7567.jpg
  index.rst
Labels: has-parent, next

#3499 Note about st7789v being replaced by ili9xxx
  components/display/ili9xxx.rst
  components/display/st7789v.rst
Labels: current

#3503 Update ld2410.rst - Typo
  components/sensor/ld2410.rst
Labels: current

#3302 mcp4728 component is required
  components/output/mcp4728.rst
Labels: stale, current

#3138 Ble client additions.
  components/ble_client.rst
  guides/automations.rst
Labels: has-parent, next

#3504 Add note about the requirement for Pages in Pop Up Mode + sample to emulate Pop Up Mode in Advanced Mode
  components/display_menu/graphical_display_menu.rst
Labels: current
