Repository esphome/esphome-docs, pull requests merged in 2023-05, with the labels that each got.

#2834 Add PCA6416A
  components/pca6416a.rst
  images/pca6416a.svg
  index.rst
Labels: has-parent, next

#2879 Adding play_mp3 action documentation to dfplayer component
  components/dfplayer.rst
Labels: has-parent, next

#2712 Added documentation for Drayton Digistat codec
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#2583 Add HYT271 doc
  components/sensor/hyt271.rst
  components/sensor/images/hyt271.jpg
  images/hyt271.jpg
  index.rst
Labels: has-parent, next

#2607 Add support for BLE passkey authentication
  components/ble_client.rst
  components/esp32_ble.rst
Labels: has-parent, next

#2200 Add support for V2 of the waveshare 5.83in e-paper display.
  components/display/waveshare_epaper.rst
Labels: stale, has-parent, next

#2320 Max6956 support added
  components/images/max6956.jpg
  components/max6956.rst
  images/max6956.jpg
  index.rst
Labels: has-parent, next, not-stale

#2885 2023.4.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2880 Update total_daily_energy.rst
  components/sensor/total_daily_energy.rst
Labels: current

#2889 Revert template sensor publish updates
  components/sensor/template.rst
  components/text_sensor/template.rst
Labels: has-parent, next

#2896 2023.4.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2892 Speaker docs
  components/index.rst
  components/speaker/i2s_audio.rst
  components/speaker/index.rst
  images/speaker.svg
  index.rst
Labels: has-parent, next

#2900 Add speaker to VA docs
  components/voice_assistant.rst
Labels: next

#2901 Add gp8403 docs
  components/output/gp8403.rst
  images/gp8403.svg
  index.rst
Labels: has-parent, next

#2902 Add esp32_rmt_led_strip docs
  components/light/esp32_rmt_led_strip.rst
  index.rst
Labels: has-parent, next

#2331 Sm2135 current fixes
  components/output/sm2135.rst
Labels: has-parent, next

#2899 Add docs for extended microphone config
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#2907 Mark i2s_audio bclk_pin as optional
  components/i2s_audio.rst
Labels: has-parent, next

#2909 2023.5.0b1
  Doxygen
  Makefile
  _static/changelog-2023.5.0.png
  _static/version
  changelog/2023.5.0.rst
  changelog/index.rst
  components/binary_sensor/rc522.rst
  components/ble_client.rst
  components/dfplayer.rst
  components/display/waveshare_epaper.rst
  components/esp32_ble.rst
  components/i2s_audio.rst
  components/images/max6956.jpg
  components/index.rst
  components/light/esp32_rmt_led_strip.rst
  components/max6956.rst
  components/microphone/i2s_audio.rst
  components/output/gp8403.rst
  components/output/sm2135.rst
  components/pca6416a.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/binary_sensor_map.rst
  components/sensor/hyt271.rst
  components/sensor/images/hyt271.jpg
  components/sensor/images/mlx90614.jpg
  components/sensor/mlx90614.rst
  components/sensor/template.rst
  components/speaker/i2s_audio.rst
  components/speaker/index.rst
  components/text_sensor/template.rst
  components/voice_assistant.rst
  components/wifi.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/gp8403.svg
  images/hyt271.jpg
  images/max6956.jpg
  images/mlx90614.jpg
  images/pca6416a.svg
  images/speaker.svg
  index.rst
Labels: beta

#2908 Add note for project info requirement for dashboard import
  guides/creators.rst
Labels: current

#2910 Updated Image reference to be correct
  components/binary_sensor/rc522.rst
Labels: current

#2913 2023.5.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2920 2023.5.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2918 update doc Pulse Light Effect
  components/light/index.rst
Labels: has-parent, next

#2922 2023.5.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  components/light/index.rst
  components/spi.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2923 document new sending method
  components/key_collector.rst
Labels: has-parent, next

#2924 2023.5.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  components/key_collector.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2925 2023.5.0
  Doxygen
  Makefile
  _static/changelog-2023.5.0.png
  _static/version
  changelog/2023.5.0.rst
  changelog/index.rst
  components/binary_sensor/rc522.rst
  components/ble_client.rst
  components/dfplayer.rst
  components/display/waveshare_epaper.rst
  components/esp32_ble.rst
  components/i2s_audio.rst
  components/images/max6956.jpg
  components/index.rst
  components/key_collector.rst
  components/light/esp32_rmt_led_strip.rst
  components/light/index.rst
  components/max6956.rst
  components/microphone/i2s_audio.rst
  components/output/gp8403.rst
  components/output/sm2135.rst
  components/pca6416a.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/binary_sensor_map.rst
  components/sensor/hyt271.rst
  components/sensor/images/hyt271.jpg
  components/sensor/images/mlx90614.jpg
  components/sensor/mlx90614.rst
  components/sensor/template.rst
  components/speaker/i2s_audio.rst
  components/speaker/index.rst
  components/text_sensor/template.rst
  components/voice_assistant.rst
  components/wifi.rst
  conf.py
  guides/automations.rst
  guides/supporters.rst
  images/gp8403.svg
  images/hyt271.jpg
  images/max6956.jpg
  images/mlx90614.jpg
  images/pca6416a.svg
  images/speaker.svg
  index.rst
Labels: current

#2919 update doc DNS Address
  components/text_sensor/wifi_info.rst
Labels: has-parent, next

#2886 Insert Europe Tank Types from mopeka_std_check
  components/sensor/mopeka_pro_check.rst
Labels: has-parent, next

#2926 correct spelling of Revspace in link to wiki page Tiny nitpick: fix typo.
  components/sensor/mhz19.rst
Labels: current

#2929 2023.5.1
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2770 Add transparency support to images and animations
  components/display/index.rst
Labels: has-parent, next

#2917 Add rp2040_pio_led_strip docs
  components/light/rp2040_pio_led_strip.rst
  index.rst
Labels: has-parent, next

#2936 2023.5.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2937 Add channel to i2s_microphone
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#2938 2023.5.3
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  components/microphone/i2s_audio.rst
  conf.py
  guides/supporters.rst
Labels: current

#2941 Update i2s_audio.rst
  components/i2s_audio.rst
Labels: has-parent, next

#2928 Add mute pin to i2s_audio/media_player
  components/media_player/i2s_audio.rst
Labels: current

#2942 2023.5.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2943 Add bits_per_sample config option for i2s_microphone
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#2895 Add docs for TMP1075 temperature sensor
  components/sensor/images/tmp1075.jpg
  components/sensor/tmp1075.rst
  images/tmp1075.jpg
  index.rst
Labels: has-parent, next

#2847 Document looping animations
  components/display/index.rst
Labels: has-parent, next

#2951 Fix mmc5603 example
  components/sensor/mmc5603.rst
Labels: current

#2946 Update i2s_audio.rst
  components/i2s_audio.rst
Labels: current

#2952 2023.5.5
  Doxygen
  Makefile
  _static/version
  changelog/2023.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2955 Update internal_temperature.rst - Clarify 53.3/128 value
  components/sensor/internal_temperature.rst
Labels: current

#2947 Update i2s_audio.rst
  components/media_player/i2s_audio.rst
Labels: current

#2957 Add conversation and silence detection docs
  components/voice_assistant.rst
Labels: has-parent, next

#2959 tweak around tone examples
  components/rtttl.rst
Labels: current

#2930 added note on NFS for container config volume
  guides/getting_started_command_line.rst
Labels: current

#2927 Update sensirion datasheets
  components/sensor/scd30.rst
  components/sensor/sdp3x.rst
  components/sensor/sht4x.rst
  components/sensor/shtcx.rst
  components/sensor/sps30.rst
  components/sensor/sts3x.rst
Labels: current

#2914 Add directions on how to automate firmware updates
  cookbook/homeassistant_upgrade.rst
  index.rst
Labels: current

#2960 add "See also" footer and inner reference anchors
  web-api/index.rst
Labels: current

#2893 Create how to share sensor data via http_request
  cookbook/http_request_sensor.rst
  cookbook/images/clients.png
  cookbook/images/server.png
  index.rst
Labels: current

#2898 Update captive_portal.rst
  components/captive_portal.rst
Labels: current

#2887 Current-gen-schema
  components/climate/haier.rst
  components/climate/index.rst
  components/climate/pid.rst
  components/matrix_keypad.rst
  components/mdns.rst
  components/output/index.rst
  components/output/sigma_delta_output.rst
  components/output/slow_pwm.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/ads1115.rst
  components/sensor/ee895.rst
  components/sensor/index.rst
  components/sensor/kuntze.rst
  components/sensor/ld2410.rst
  components/vbus.rst
  index.rst
  schema_doc.py
Labels: current

#2864 Update hmc5883l.rst
  components/sensor/hmc5883l.rst
Labels: current

#2862 Update mics_4514.rst
  components/sensor/mics_4514.rst
Labels: current

#2848 Add "dimensions" and remove "cs_pin"
  components/display/ili9xxx.rst
Labels: current

#2944 Update custom.rst to include changes made in CoverTraits
  components/cover/custom.rst
Labels: has-parent, current

#2912 Expand custom I2C documentation
  custom/i2c.rst
Labels: current

#2958 Docs for wifi enable/disable
  components/wifi.rst
Labels: has-parent, next
