Repository esphome/esphome-docs, pull requests merged in 2023-03, with the labels that each got.

#2714 Clarify what IAQ is
  components/sensor/bme680_bsec.rst
Labels: current

#2719 Mention MH-Z14 as working with MH-Z19 library.
  components/sensor/mhz19.rst
Labels: current

#2721 Clarify purpose of appending the mac address
  components/esphome.rst
Labels: current

#2722 Minor updates on sharing page
  guides/creators.rst
Labels: current

#2645 Improve example in SCD4X for ambient pressure compensation
  components/sensor/scd4x.rst
Labels: has-parent, current

#2725 Update resistance.rst
  components/sensor/resistance.rst
Labels: current

#2720 climate on_control documentation
  components/climate/index.rst
Labels: has-parent, next

#2715 Add documentation for fs3000 sensor.
  components/sensor/fs3000.rst
  components/sensor/images/fs3000.jpg
  images/fs3000.jpg
  index.rst
Labels: has-parent, next

#2716 Removing default setting
  components/mqtt.rst
Labels: current

#2713 Update safe_mode.rst
  components/switch/safe_mode.rst
Labels: current

#2708 Update modbus_controller.rst
  components/select/modbus_controller.rst
Labels: current

#2701 Fix typo in filter max docs
  components/sensor/index.rst
Labels: current

#2695 EE895 wrong name for a link
  components/sensor/ee895.rst
Labels: current

#2696 Update anova.rst
  components/climate/anova.rst
Labels: current

#2693 small issue on unit used
  components/sensor/pulse_counter.rst
Labels: current

#2692 correct details in SEN5x documentation
  components/sensor/sen5x.rst
Labels: current

#2667 Update air_gradient_diy_air_quality_sensor.rst
  cookbook/air_gradient_diy_air_quality_sensor.rst
Labels: current

#2706 Update diy.rst
  guides/diy.rst
Labels: current

#2726 Update index.rst
  components/climate/index.rst
Labels: current

#2723 Add absolute humidity component
  components/sensor/absolute_humidity.rst
  components/sensor/aht10.rst
  components/sensor/am2320.rst
  components/sensor/b_parasite.rst
  components/sensor/bme280.rst
  components/sensor/bme680.rst
  components/sensor/bme680_bsec.rst
  components/sensor/dht.rst
  components/sensor/dht12.rst
  components/sensor/ens210.rst
  components/sensor/hdc1080.rst
  components/sensor/hte501.rst
  components/sensor/htu21d.rst
  components/sensor/inkbird_ibsth1_mini.rst
  components/sensor/ruuvitag.rst
  components/sensor/scd30.rst
  components/sensor/scd4x.rst
  components/sensor/sen5x.rst
  components/sensor/sht3xd.rst
  components/sensor/sht4x.rst
  components/sensor/shtcx.rst
  components/sensor/zyaura.rst
  cookbook/bme280_environment.rst
  images/water-drop.svg
  index.rst
Labels: has-parent, next

#2234 bme680_bsec: Add information and example about multiple devices support
  components/sensor/bme680_bsec.rst
Labels: has-parent, next, not-stale

#2609 Add documentation for AS7341 spectral color sensor
  components/sensor/as7341.rst
  components/sensor/images/as7341-full.jpg
  images/as7341.jpg
  index.rst
Labels: has-parent, next

#2700 added reset energy action to pzemdc
  components/sensor/pzemdc.rst
Labels: has-parent, next

#2698 fix kuntze docs
  components/logger.rst
  components/sensor/kuntze.rst
  index.rst
Labels: next

#2491 Document NeoPixelBus support on ESP32-S3
  components/light/neopixelbus.rst
Labels: has-parent, next

#2730 2023.3.0b2
  Doxygen
  Makefile
  _redirects
  _static/version
  changelog/2023.3.0.rst
  components/display/ili9xxx.rst
  components/light/neopixelbus.rst
  components/logger.rst
  components/sensor/kuntze.rst
  conf.py
  guides/supporters.rst
  index.rst
Labels: beta

#2733 Update hbridge.rst
  components/fan/hbridge.rst
Labels: current

#2734 Update uart.rst
  components/uart.rst
Labels: current

#2735 Add automation example to remote_receiver
  components/remote_receiver.rst
Labels: current

#2736 fix example
  components/matrix_keypad.rst
Labels: current

#2738 time valid lambda example
  components/time/index.rst
Labels: current

#2742 include i2c requirement in docs
  components/sensor/mics_4514.rst
Labels: current

#2731 Feat: add hex color
  components/display/index.rst
Labels: has-parent, next

#2743 Add supported touch pins for esp32-s2/s3
  components/binary_sensor/esp32_touch.rst
Labels: next

#2744 2023.3.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.3.0.rst
  components/binary_sensor/esp32_touch.rst
  components/display/index.rst
  components/fan/hbridge.rst
  components/matrix_keypad.rst
  components/remote_receiver.rst
  components/sensor/mics_4514.rst
  components/time/index.rst
  components/uart.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2745 Add esp32 + improv requirements for Made for ESPHome
  guides/made_for_esphome.rst
Labels: current

#2749 Prefix all docker image references with ghcr.io
  components/mqtt.rst
  guides/contributing.rst
  guides/faq.rst
  guides/getting_started_command_line.rst
Labels: current

#2750 Format long single line note
  guides/getting_started_hassio.rst
Labels: current

#2751 Revert "Add supported touch pins for esp32-s2/s3"
  components/binary_sensor/esp32_touch.rst
Labels: next

#2752 2023.3.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2023.3.0.rst
  components/binary_sensor/esp32_touch.rst
  components/mqtt.rst
  conf.py
  guides/contributing.rst
  guides/faq.rst
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
  guides/supporters.rst
Labels: beta

#2753 typo fix (double the) Update prometheus.rst
  components/prometheus.rst
Labels: current

#2754 2023.3.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2023.3.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#2647 Update delta filter docs for new percentage mode
  components/sensor/index.rst
Labels: has-parent, next

#2741 Added missing PM_1_0 and PM_10_0 for TYPE_PMS5003T
  components/sensor/pmsx003.rst
Labels: has-parent, next

#2748 Spi force sw
  components/spi.rst
Labels: has-parent, next

#2727 add output option for status led
  components/light/status_led.rst
Labels: has-parent, next

#2746 Add flip_x
  components/display/max7219digit.rst
Labels: has-parent, next

#2761 Document how to return 'no value' from a lambda filter
  components/sensor/index.rst
Labels: current

#2760 Documentation for the `skip_initial` filter
  components/sensor/index.rst
Labels: has-parent, next

#2759 Add support for ESP32 CAM 3MP and 5MP resolutions and arbitrary camera clock.
  components/esp32_camera.rst
Labels: has-parent, next

#2765 GooDisplay GDEY029T94
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#2766 Update bme280.rst
  components/sensor/bme280.rst
Labels: current

#2764 Update title of ADS1115 component (ads1115.rst)
  components/sensor/ads1115.rst
Labels: current

#2773 Document what remote "raw format" is
  components/remote_receiver.rst
Labels: current

#2775 Add remote_* to seealso
  components/rf_bridge.rst
Labels: current

#2780 Update metadata description on Web Server API page
  web-api/index.rst
Labels: current

#2781 brush up pca9554.rst
  components/pca9554.rst
Labels: current

#2782 move datasheet links to bottom
  components/pca9554.rst
Labels: current

#2369 added new ustom component RGB matrix display (EHMTX) to cookbook
  cookbook/ehmtx.rst
  cookbook/images/ehmtx.jpg
  images/ehmtx.jpg
  index.rst
Labels: current

#2777 Update tuya.rst
  components/climate/tuya.rst
Labels: current

#2785 Add variable name for touchscreen touches
  components/touchscreen/index.rst
Labels: current

#2774 Add note for names to use friendly_name
  components/binary_sensor/index.rst
  components/button/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/fan/index.rst
  components/light/index.rst
  components/lock/index.rst
  components/media_player/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text_sensor/index.rst
Labels: has-parent, next

#2788 2023.3.2
  Doxygen
  Makefile
  _static/version
  changelog/2023.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2789 Update pre-commit files
  .pre-commit-config.yaml
Labels: current

#2794 Fix broken link, add new link in midea.rst
  components/climate/midea.rst
Labels: current

#2793 Adjusted indentation
  components/display/st7789v.rst
Labels: current

#2795 Update binary_sensor_map.rst
  components/sensor/binary_sensor_map.rst
Labels: has-parent, current
