Repository esphome/esphome-docs, pull requests merged in 2023-07, with the labels that each got.

#3035 docs: fix typoed default port in migrate_sonoff_tasmota.rst
  guides/migrate_sonoff_tasmota.rst
Labels: current

#3034 binary_sensor templatable delays
  components/binary_sensor/index.rst
Labels: has-parent, next

#3041 2023.6.4
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3031 Update ili9xxx.rst - Add Ili9488_A
  components/display/ili9xxx.rst
Labels: has-parent, next

#2874 [ili9xxx] Allow config of spi data rate.
  components/display/ili9xxx.rst
Labels: has-parent, next

#3048 small typo
  components/sensor/ld2410.rst
Labels: current

#3025 Dark mode
  _static/custom.css
  _themes/esphome/theme.conf
  changelog/2021.10.0.rst
  changelog/2021.11.0.rst
  changelog/2021.12.0.rst
  changelog/2021.8.0.rst
  changelog/2021.9.0.rst
  changelog/2022.1.0.rst
  changelog/2022.10.0.rst
  changelog/2022.11.0.rst
  changelog/2022.12.0.rst
  changelog/2022.2.0.rst
  changelog/2022.3.0.rst
  changelog/2022.5.0.rst
  changelog/2022.6.0.rst
  changelog/2022.8.0.rst
  changelog/2022.9.0.rst
  changelog/2023.2.0.rst
  changelog/2023.3.0.rst
  changelog/2023.4.0.rst
  changelog/2023.5.0.rst
  changelog/2023.6.0.rst
  changelog/v1.10.0.rst
  changelog/v1.11.0.rst
  changelog/v1.12.0.rst
  changelog/v1.13.0.rst
  changelog/v1.14.0.rst
  changelog/v1.15.0.rst
  changelog/v1.16.0.rst
  changelog/v1.17.0.rst
  changelog/v1.18.0.rst
  changelog/v1.19.0.rst
  changelog/v1.20.0.rst
  changelog/v1.7.0.rst
  changelog/v1.8.0.rst
  changelog/v1.9.0.rst
  components/api.rst
  components/display/max7219.rst
  conf.py
  github.py
  guides/contributing.rst
  images/bedjet.png
  images/radon_eye_logo.png
  index.rst
Labels: current

#2875 [Ethernet] ksz8081rna support
  components/ethernet.rst
Labels: has-parent, next, not-stale

#3050 2023.6.5
  Doxygen
  Makefile
  _static/version
  changelog/2023.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3043 Add documentation for new Zio Ultrasonic Distance Sensor component
  components/sensor/images/zio_ultrasonic.jpg
  components/sensor/zio_ultrasonic.rst
  images/zio_ultrasonic.jpg
  index.rst
Labels: has-parent, next

#2278 Add documentation for Alpha3 Pump component
  components/sensor/alpha3.rst
  images/alpha3.jpg
  index.rst
Labels: has-parent, next, not-stale

#3007 airthings_wave: Document battery-voltage sensors.
  components/sensor/airthings_ble.rst
Labels: has-parent, next

#2906 grove TB6612FNG
  components/grove-tb6612fng.rst
  components/images/grove_tb6612fng.jpg
  images/grove_tb6612fng.jpg
  images/motor.png
  index.rst
Labels: has-parent, next

#3055 Add 12MHz option to canbus docs.
  components/canbus.rst
Labels: has-parent, next

#3002 Add ATM90E26 documentation
  components/sensor/atm90e26.rst
  images/atm90e26.jpg
  index.rst
Labels: has-parent, next

#3056 Fix caution and search style in dark mode
  _static/custom.css
Labels: current

#3059 fix naming
  components/grove_tb6612fng.rst
  index.rst
Labels: has-parent, next

#3049 New duty_time sensor
  components/sensor/duty_time.rst
  components/sensor/index.rst
  images/timer-play-outline.svg
  index.rst
Labels: has-parent, next

#3062 Fix tip on dark mode
  _static/custom.css
Labels: current

#3065 Addition
  components/vbus.rst
Labels: current

#3066 Update remote_transmitter.rst
  components/remote_transmitter.rst
Labels: current

#3070 Remove restore_state from template switch
  components/switch/template.rst
Labels: has-parent, next

#3072 Add section for ADC pins on esp32
  components/sensor/adc.rst
Labels: has-parent, next

#3068 Add timeout filter documentation
  components/sensor/index.rst
Labels: has-parent, next

#3073 2023.7.0b2
  Doxygen
  Makefile
  _static/custom.css
  _static/version
  changelog/2023.7.0.rst
  components/remote_transmitter.rst
  components/sensor/adc.rst
  components/sensor/index.rst
  components/switch/template.rst
  components/vbus.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3076 Update automations.rst doc page
  guides/automations.rst
Labels: current

#3079 2023.7.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2023.7.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3040 fix issues and note only away/home
  components/alarm_control_panel/index.rst
  components/alarm_control_panel/template.rst
Labels: has-parent, current

#3082 Remove message saying dashboard wont work on windows
  guides/getting_started_command_line.rst
Labels: has-parent, next

#3083 Add block about component operation warning to changelog
  changelog/2023.7.0.rst
Labels: current

#3081 Specify web_server ota configuration variable is not compatible with esp-idf
  components/web_server.rst
Labels: current

#3078 Fix for schema 2023.7
  components/sensor/atm90e26.rst
  components/speaker/index.rst
  components/touchscreen/tt21100.rst
Labels: current

#3084 Fix issue link
  changelog/2023.7.0.rst
Labels: current

#3085 Small Improvements to FS3000 Documentation
  components/sensor/fs3000.rst
Labels: current

#3071 Coolix IR protocol improvements
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3088 Fix typo
  components/light/index.rst
Labels: current

#3091 Update FAQ to speifically mention OpenWrt and pfSense for mDNS
  guides/faq.rst
Labels: current

#3033 climate triggers Climate and ClimateCall references
  components/climate/index.rst
Labels: has-parent, next

#3039 Add 'map_linear' and 'clamp' sensor filters
  components/sensor/images/sensor_filter_calibrate_linear.png
  components/sensor/index.rst
Labels: has-parent, next

#3092 Adding Inkplate 6 v2 Documentation
  components/display/inkplate6.rst
Labels: has-parent, next
