Repository esphome/esphome-docs, pull requests merged in 2023-01, with the labels that each got.

#2573 Update rotary_encoder.rst
  components/sensor/rotary_encoder.rst
Labels: current

#2425 Documentation for `matrix_keypad` component
  components/matrix_keypad.rst
  images/matrix_keypad.jpg
  index.rst
Labels: has-parent, next

#2578 http_request: document new parameter `duration_ms` in `on_response` handler
  components/http_request.rst
Labels: has-parent, next

#2541 Add X9C potentiometer docs
  components/output/images/x9c.jpg
  components/output/x9c.rst
  images/x9c.jpg
  index.rst
Labels: has-parent, next

#2580 Add framework workaround to the config example
  components/rp2040.rst
Labels: current

#2585 Add note explaining what to do in set_action
  components/select/template.rst
Labels: current

#2586 Fix API reference link for ESP32 Camera Web Server
  components/esp32_camera_web_server.rst
Labels: current

#2590 Update automations.rst
  guides/automations.rst
Labels: current

#2525 Note ID is not used by Home Assistant
  guides/configuration-types.rst
Labels: current

#2594 Spelling mistake public/publish
  components/switch/template.rst
Labels: current

#2426 Documentation for `key_collector` component
  components/key_collector.rst
  components/matrix_keypad.rst
Labels: has-parent, next

#2600 add "actual_gain" information
  components/sensor/tsl2591.rst
Labels: has-parent, next

#2241 Add support for EE895, HTE501 and TEE501 sensors
  components/sensor/ee895.rst
  components/sensor/hte501.rst
  components/sensor/images/EE895.png
  components/sensor/images/HTE501.png
  components/sensor/images/TEE501.png
  components/sensor/tee501.rst
  cookbook/iaq_board.rst
  images/EE895.png
  images/HTE501.png
  images/TEE501.png
  index.rst
Labels: has-parent, next

#2325 Updated documentation for pca9685
  components/output/pca9685.rst
Labels: next, not-stale

#2500 Documentation for `sigma_delta_output` component
  components/output/images/sigma-delta-example.png
  components/output/sigma_delta.rst
  components/output/slow_pwm.rst
  images/sigma-delta.svg
  index.rst
Labels: has-parent, next

#2424 Documentation for `wiegand` component
  components/wiegand.rst
  images/wiegand.jpg
  index.rst
Labels: has-parent, next

#2603 Fix link to mqtt base component config
  components/mqtt.rst
Labels: current

#2595 Added power negative filter example - very useful
  components/sensor/ina226.rst
Labels: current

#2604 Revert "Added power negative filter example - very useful"
  components/sensor/ina226.rst
Labels: current

#2587 Fix esp32-arduino_framework ref
  components/esp32.rst
Labels: current

#2593 addded: BME680 IAQ Class
  components/sensor/bme680_bsec.rst
Labels: current

#2606 2022.12.4
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2608 Update pcf8574.rst
  components/pcf8574.rst
Labels: current

#2613 2022.12.5
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2612 Update ethernet.rst
  components/ethernet.rst
Labels: current

#2616 2022.12.6
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2615 Fix order
  components/ethernet.rst
Labels: current

#2617 Move password to bottom of list and add deprecated label
  components/api.rst
Labels: current

#2618 Fix display font and static text ref
  changelog/2022.4.0.rst
  components/display/index.rst
Labels: current

#2614 Add missing font: component to example.
  components/display/st7789v.rst
Labels: has-parent, current

#2461 Format-fixes-202211
  components/climate/bedjet.rst
  components/display_menu/index.rst
  components/display_menu/lcd_menu.rst
  components/ezo_pmp.rst
  components/sensor/ble_client.rst
  components/sensor/ezo.rst
  components/sensor/mpl3115a2.rst
  components/sensor/ufire_ec.rst
  components/sensor/ufire_ise.rst
  components/touchscreen/xpt2046.rst
  schema_doc.py
Labels: stale, current

#2619 Add note to container changes
  changelog/2022.12.0.rst
Labels: current

#2621 Redirect 2022.12.4 to 2022.12.0 changelog
  _redirects
Labels: current

#2605 Add documentation for MiCS 4514
  components/sensor/mics_4514.rst
  images/mics_4514.jpg
  index.rst
Labels: has-parent, next

#2620 Add improv serial next_url
  components/improv_serial.rst
  guides/creators.rst
Labels: has-parent, next

#2623 2022.12.7
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#2581 Added documentation in order to use ADS1015
  components/sensor/ads1115.rst
Labels: has-parent, next

#2625 2022.12.8
  Doxygen
  Makefile
  _static/version
  changelog/2022.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current
