Repository esphome/esphome-docs, pull requests merged in 2024-02, with the labels that each got.

#3587 Update power_supply.rst
  components/power_supply.rst
Labels: current

#3588 Update logger.rst
  components/logger.rst
Labels: current

#3593 Fixed wikipedia link
  cookbook/power_meter.rst
Labels: current

#3594 Updates links to device class list
  components/binary_sensor/index.rst
  components/button/index.rst
  components/cover/index.rst
  components/number/index.rst
  components/sensor/index.rst
  components/switch/index.rst
Labels: current

#3590 add is_wrgb to esp32_rmt_led_strip
  components/light/esp32_rmt_led_strip.rst
Labels: has-parent, next

#3592 Add All other options from Light
  components/light/esp32_rmt_led_strip.rst
  components/light/rp2040_pio_led_strip.rst
Labels: current

#3601 [touchscreen] Add a note to the update_interval
  components/touchscreen/index.rst
Labels: current

#3451 Fix ili9xxx docs, specifically example configs.
  components/display/ili9xxx.rst
Labels: stale, has-parent, next

#3602 Documentation for 6190 & 6193 (WLED Sync fix and BK72XX support)
  components/light/index.rst
Labels: has-parent, next

#3603 Micro Wake Word docs
  components/micro_wake_word.rst
Labels: has-parent, next

#3609 microWakeWord - cutoff probability is a percentage
  components/micro_wake_word.rst
Labels: has-parent, next

#3612 microWakeWord: Add minimum_esphome_version as optional field
  components/micro_wake_word.rst
Labels: has-parent, next

#3608 INA226 - new options added for ADC configuration; Fixed improper work with signed values
  components/sensor/ina226.rst
Labels: has-parent, next

#3613 2024.2.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.2.0.rst
  components/micro_wake_word.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3615 Flip configuration and command in example
  guides/migrate_sonoff_tasmota.rst
Labels: current

#3123 New component: ADE7880 voltage/current/power/energy sensor
  components/sensor/ade7880.rst
  images/ade7880.svg
  index.rst
Labels: has-parent, next

#3572 Update VA docs to add on_idle action
  components/voice_assistant.rst
Labels: has-parent, next

#3617 2024.2.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.2.0.rst
  components/voice_assistant.rst
  conf.py
  guides/migrate_sonoff_tasmota.rst
  guides/supporters.rst
Labels: beta

#3585 LTR390 - Multiple fixes (sensor name, descriptions and notes)
  components/sensor/ltr390.rst
Labels: has-parent, next

#3619 Migrate ready-made projects to ESP Web Tools 10
  projects/installer.html
Labels: current

#3623 Point to new microWakeWord specific firmware
  projects/installer.html
Labels: has-parent, current

#3381 Add documentation for uponor_smatrix component
  components/uponor_smatrix.rst
  images/uponor.svg
  index.rst
Labels: has-parent, next

#3493 MCP9600 change minimum bus speed to 10kHz
  components/sensor/mcp9600.rst
Labels: stale, current

#3629 Add some details to the 2024.2.0 release notes
  changelog/2024.2.0.rst
Labels: current

#3630 Build Docker image for arm64
  .github/workflows/docker.yml
Labels: current

#3633 output is optional
  components/fan/speed.rst
Labels: has-parent, next

#3638 Fix typo liquit to liquid
  components/sensor/ufire_ise.rst
Labels: current

#3639 2024.2.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.2.0.rst
  components/fan/speed.rst
  conf.py
  guides/supporters.rst
Labels: current

#3472 Delete devices directory
  components/light/sonoff_d1.rst
  components/output/my9231.rst
  cookbook/arduino_port_extender.rst
  cookbook/sonoff-fishpond-pump.rst
  devices/images/nodemcu_esp32-full.jpg
  devices/images/nodemcu_esp8266-full.jpg
  devices/images/sonoff_4ch_buttons.jpg
  devices/images/sonoff_4ch_header.jpg
  devices/images/sonoff_4ch_mcu.jpg
  devices/images/sonoff_4ch_result.png
  devices/images/sonoff_4ch_top.jpg
  devices/images/sonoff_4ch_uart.jpg
  devices/images/sonoff_4ch_upload.png
  devices/images/sonoff_basic-full.jpg
  devices/images/sonoff_s20_header.jpg
  devices/images/sonoff_s20_parts.jpg
  devices/images/sonoff_s20_pcb.jpg
  devices/images/sonoff_s20_result.png
  devices/images/sonoff_s20_screws.jpg
  devices/images/sonoff_s20_uart.jpg
  devices/images/sonoff_s20_upload.png
  devices/images/sonoff_t1_uk_3g_back_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_backplate_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_plate_off_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_touchpads_v1.1.jpg
  devices/images/sonoff_t1_uk_3g_v1.1.jpg
  devices/images/sonoff_t3_eu_3g_back_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_backplate_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_plate_off_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_touchpads_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_uart_v1.0.jpg
  devices/images/sonoff_t3_eu_3g_v1.0.jpg
  devices/index.rst
  devices/nodemcu_esp32.rst
  devices/nodemcu_esp8266.rst
  devices/sonoff.rst
  devices/sonoff_4ch.rst
  devices/sonoff_4ch.yaml
  devices/sonoff_basic.rst
  devices/sonoff_s20.rst
  devices/sonoff_s20.yaml
  devices/sonoff_t1_uk_3gang_v1.1.rst
  devices/sonoff_t1_uk_3gang_v1.1.yaml
  devices/sonoff_t3_eu_3gang_v1.0.rst
  devices/sonoff_t3_eu_3gang_v1.0.yaml
  devices/teckin.yaml
  devices/teckin_sp20_us.yaml
  index.rst
Labels: current, not-stale

#3515 Remove dead inkplate link
  components/display/inkplate6.rst
Labels: current

#3183 Update esphome.rst docs for ESPHOME_BUILD_PATH environment variable
  components/esphome.rst
Labels: stale, has-parent, next

#3599 Add device class support to text sensor
  components/text_sensor/index.rst
Labels: has-parent, next

#3641 Update bme280_environment.rst
  cookbook/bme280_environment.rst
Labels: current

#3621 Docs should specify that PSRAM is required
  components/micro_wake_word.rst
Labels: current

#3502 Add info about work-around for ble_tracker and wifi use on single core
  components/esp32_ble_tracker.rst
Labels: stale, current

#3234 Document new parameter `min_ipv6_addr_count` and sub sensors for wifi_info and ethernet_info
  components/network.rst
  components/text_sensor/ethernet_info.rst
  components/text_sensor/wifi_info.rst
Labels: has-parent, next

#3645 Update index.rst to add explanation how to check for a specific value of the select
  components/select/index.rst
Labels: current

#3644 [RTTTL] add Gain volume control
  components/rtttl.rst
Labels: has-parent, next

#3637 Update description to 2.9in V2 display variant
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3648 FAQ: unavailable entities during deep sleep
  components/deep_sleep.rst
  guides/faq.rst
Labels: current

#3647 Add docs for esphome->project->on_update
  components/esphome.rst
Labels: has-parent, next

#3643 CSE7766 Apparent Power & Power Factor calculations
  components/sensor/cse7766.rst
Labels: has-parent, next
