Repository esphome/esphome-docs, pull requests merged in 2024-08, with the labels that each got.

#4080 RMT documentation clarification and refactoring
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/rf_bridge.rst
  guides/setting_up_rmt_devices.rst
  index.rst
Labels: current

#4104 [api] Update ``service`` -> ``action``
  changelog/v1.12.0.rst
  components/api.rst
  components/ble_client.rst
  components/dfplayer.rst
  components/display/nextion.rst
  components/fingerprint_grow.rst
  components/rf_bridge.rst
  components/rtttl.rst
  components/sensor/ld2410.rst
  components/sensor/mhz19.rst
  components/sensor/pulse_counter.rst
  components/sensor/pulse_meter.rst
  components/sensor/scd4x.rst
  components/sim800l.rst
  components/sprinkler.rst
  components/tm1651.rst
  cookbook/infostrip.rst
  cookbook/power_meter.rst
  custom/custom_component.rst
  guides/configuration-types.rst
  guides/index.rst
Labels: has-parent, next

#4085 Add docs for `round_to_multiple_of` filter
  components/sensor/index.rst
Labels: has-parent, next

#4068 Fix 11db attenuation
  components/display/inkplate6.rst
  components/sensor/adc.rst
Labels: has-parent, current

#4109 Update esp32 board link to current version used
  components/esp32.rst
Labels: current

#4107 MQTT enabled Alarm Control Panel
  components/alarm_control_panel/index.rst
Labels: has-parent, next

#4095 Break out packages + substitutions docs
  changelog/v1.10.0.rst
  components/index.rst
  components/packages/index.rst
  components/substitutions/index.rst
  guides/configuration-types.rst
  guides/faq.rst
  index.rst
Labels: current

#4101 Split display widgets documentation
  components/animation.rst
  components/display/index.rst
  components/fonts.rst
  components/graph.rst
  components/images.rst
  components/images/display_rendering_graph.png
  components/qr_code.rst
  images/chart-line.svg
  images/image-multiple-outline.svg
  images/image-outline.svg
  index.rst
  lint.py
Labels: current

#4112 Move packages and substitutions out of folders
  changelog/v1.10.0.rst
  components/index.rst
  components/packages.rst
  components/substitutions.rst
  guides/faq.rst
  index.rst
Labels: current

#4113 ``service`` -> ``action`` take 2
  components/packages.rst
Labels: next

#4114 Rename files to match component name
  components/font.rst
  components/image.rst
  index.rst
  lint.py
Labels: current

#2076 Add online_image documentation
  components/display/index.rst
  components/image.rst
  components/online_image.rst
  images/image-sync-outline.svg
  index.rst
Labels: has-parent, next, not-stale

#3678 Initial LVGL doc for ESPHome
  components/binary_sensor/lvgl.rst
  components/display/index.rst
  components/font.rst
  components/index.rst
  components/key_collector.rst
  components/light/lvgl.rst
  components/lvgl/images/lvgl_align.png
  components/lvgl/images/lvgl_animimg.gif
  components/lvgl/images/lvgl_arc.png
  components/lvgl/images/lvgl_bar.png
  components/lvgl/images/lvgl_baseobj.png
  components/lvgl/images/lvgl_boxmodel.png
  components/lvgl/images/lvgl_button.png
  components/lvgl/images/lvgl_buttonmatrix.png
  components/lvgl/images/lvgl_checkbox.png
  components/lvgl/images/lvgl_dropdown.png
  components/lvgl/images/lvgl_image.png
  components/lvgl/images/lvgl_keyboard.png
  components/lvgl/images/lvgl_label.png
  components/lvgl/images/lvgl_led.png
  components/lvgl/images/lvgl_line.png
  components/lvgl/images/lvgl_main_screenshot.png
  components/lvgl/images/lvgl_meter.png
  components/lvgl/images/lvgl_msgbox.png
  components/lvgl/images/lvgl_roller.png
  components/lvgl/images/lvgl_slider.png
  components/lvgl/images/lvgl_spinbox.png
  components/lvgl/images/lvgl_spinner.gif
  components/lvgl/images/lvgl_switch.png
  components/lvgl/images/lvgl_symbols.png
  components/lvgl/images/lvgl_tabview.png
  components/lvgl/images/lvgl_textarea.png
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/number/lvgl.rst
  components/select/lvgl.rst
  components/sensor/lvgl.rst
  components/switch/lvgl.rst
  components/text/lvgl.rst
  components/text_sensor/lvgl.rst
  images/lvgl.png
  images/lvgl_c_bns.png
  images/lvgl_c_lig.png
  images/lvgl_c_num.png
  images/lvgl_c_sel.png
  images/lvgl_c_swi.png
  images/lvgl_c_txt.png
  index.rst
Labels: has-parent, next

#4125 Feature improv serial project identity
  components/improv_serial.rst
Labels: has-parent, next

#4018 [bme68x_bsec2_i2c] Add docs
  components/sensor/bme680_bsec.rst
  components/sensor/bme68x_bsec2.rst
  index.rst
Labels: has-parent, next

#4046 Add Xiaomi LYWSD02MMC
  components/sensor/xiaomi_ble.rst
Labels: has-parent, next

#4130 Add redirect from /components/images to /components/image
  _redirects
Labels: current

#4100 fixed default *bits_per_sample* value
  components/microphone/i2s_audio.rst
Labels: current

#4075 Correct ENS160 default address
  components/sensor/ens160.rst
Labels: current

#4102 [online_image] Add placeholder documentation
  components/online_image.rst
Labels: has-parent, next

#4128 [lvgl] Document `initial_focus` for encoders
  components/lvgl/index.rst
Labels: has-parent, next

#3984 Updated documentation for Light dim_relative min/max brightness feature PR
  components/light/index.rst
Labels: has-parent, next

#4151 [switch] Tidy up name/id
  components/switch/ble_client.rst
  components/switch/factory_reset.rst
  components/switch/index.rst
  components/switch/modbus_controller.rst
  components/switch/nextion.rst
  components/switch/output.rst
  components/switch/restart.rst
  components/switch/safe_mode.rst
  components/switch/shutdown.rst
  components/switch/template.rst
  components/switch/tuya.rst
  components/switch/uart.rst
Labels: current

#4155 [components] Tidy up name/id
  components/copy.rst
  components/fingerprint_grow.rst
  components/gps.rst
  components/remote_receiver.rst
  components/sim800l.rst
  components/sun.rst
  components/touchscreen/index.rst
Labels: current

#4154 [valve] Tidy up name/id
  components/valve/index.rst
  components/valve/template.rst
Labels: current

#4006 Add docu for Homeassistant Switch
  components/switch/homeassistant.rst
  index.rst
Labels: has-parent, next

#4153 [update] Tidy up name/id
  components/update/index.rst
Labels: current

#3942 Documentation for Home Assistant Number
  components/number/home_assistant.rst
Labels: has-parent, next

#4132 [lvgl] Document `update_on_release` for number
  components/number/lvgl.rst
Labels: has-parent, next

#4136 Document `color_filter_opa` style property
  components/lvgl/index.rst
Labels: has-parent, next

#3110 support illuminance for airthings wave plus device
  components/sensor/airthings_ble.rst
Labels: stale, has-parent, next

#4149 [select] Tidy up name/id
  components/select/index.rst
  components/select/modbus_controller.rst
  components/select/template.rst
  components/select/tuya.rst
Labels: current

#4148 [number] Tidy up name/id
  components/number/index.rst
  components/number/modbus_controller.rst
  components/number/template.rst
  components/number/tuya.rst
Labels: current

#4152 [text_sensor] Tidy up name/id
  components/text_sensor/ble_client.rst
  components/text_sensor/ble_scanner.rst
  components/text_sensor/homeassistant.rst
  components/text_sensor/index.rst
  components/text_sensor/modbus_controller.rst
  components/text_sensor/mqtt_subscribe.rst
  components/text_sensor/nextion.rst
  components/text_sensor/template.rst
  components/text_sensor/tuya.rst
  components/text_sensor/version.rst
Labels: current

#4147 [media_player] Tidy up name/id
  components/media_player/index.rst
Labels: current

#4146 [lock] Tidy up name/id
  components/lock/index.rst
  components/lock/output.rst
  components/lock/template.rst
Labels: current

#4140 [climate] Tidy up name/id
  components/climate/anova.rst
  components/climate/bedjet.rst
  components/climate/climate_ir.rst
  components/climate/haier.rst
  components/climate/index.rst
  components/climate/midea.rst
  components/climate/pid.rst
  components/climate/tuya.rst
Labels: current

#4145 [light] Tidy up name/id
  components/light/binary.rst
  components/light/color_temperature.rst
  components/light/cwww.rst
  components/light/fastled.rst
  components/light/hbridge.rst
  components/light/index.rst
  components/light/monochromatic.rst
  components/light/neopixelbus.rst
  components/light/partition.rst
  components/light/rgb.rst
  components/light/rgbct.rst
  components/light/rgbw.rst
  components/light/rgbww.rst
  components/light/shelly_dimmer.rst
  components/light/sonoff_d1.rst
  components/light/spi_led_strip.rst
  components/light/status_led.rst
  components/light/tuya.rst
Labels: current

#4143 [event] Tidy up name/id
  components/event/index.rst
Labels: current

#4144 [fan] Tidy up name/id
  components/fan/binary.rst
  components/fan/hbridge.rst
  components/fan/index.rst
  components/fan/speed.rst
  components/fan/template.rst
  components/fan/tuya.rst
Labels: current

#4142 [datetime] Tidy up name/id
  components/datetime/index.rst
Labels: current

#4141 [cover] Tidy up name/id
  components/cover/am43.rst
  components/cover/current_based.rst
  components/cover/endstop.rst
  components/cover/feedback.rst
  components/cover/index.rst
  components/cover/template.rst
  components/cover/time_based.rst
  components/cover/tuya.rst
Labels: current

#4139 [button] Tidy up name/id
  components/button/factory_reset.rst
  components/button/index.rst
  components/button/output.rst
  components/button/restart.rst
  components/button/safe_mode.rst
  components/button/shutdown.rst
  components/button/template.rst
  components/button/uart.rst
  components/button/wake_on_lan.rst
Labels: current

#4138 [binary_sensor] Tidy up name/id
  components/binary_sensor/analog_threshold.rst
  components/binary_sensor/ble_presence.rst
  components/binary_sensor/cap1188.rst
  components/binary_sensor/esp32_touch.rst
  components/binary_sensor/gpio.rst
  components/binary_sensor/homeassistant.rst
  components/binary_sensor/hydreon_rgxx.rst
  components/binary_sensor/index.rst
  components/binary_sensor/modbus_controller.rst
  components/binary_sensor/mpr121.rst
  components/binary_sensor/nextion.rst
  components/binary_sensor/pn532.rst
  components/binary_sensor/rc522.rst
  components/binary_sensor/rdm6300.rst
  components/binary_sensor/status.rst
  components/binary_sensor/template.rst
  components/binary_sensor/ttp229.rst
  components/binary_sensor/tuya.rst
Labels: current

#4137 [alarm_control_panel] Tidy up name/id
  components/alarm_control_panel/index.rst
Labels: current

#3953 Add new Action and Condition.
  components/speaker/index.rst
Labels: has-parent, next

#4160 2024.8.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.8.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4165 [lvgl] Update layout docs
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: has-parent, next

#4169 2024.8.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.8.0.rst
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4177 2024.8.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.8.0.rst
  components/sensor/total_daily_energy.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4182 Fix homeassistant number page
  components/number/homeassistant.rst
  index.rst
Labels: current

#4175 Add output source priority "hybrid"
  components/pipsolar.rst
Labels: has-parent, next

#3992 Enable verbose mode from env ESPHOME_VERBOSE or --verbose
  guides/cli.rst
Labels: has-parent, next

#4010 Tuya number: added description of new datapoint_hidden yaml key
  components/number/tuya.rst
  components/tuya.rst
Labels: has-parent, next

#4187 Update lambda_magic.rst
  cookbook/lambda_magic.rst
Labels: current

#4192 Fix formatting of lvgl.is.idle example
  components/lvgl/index.rst
Labels: current

#4195 `scale` -> `zoom` correction in lvgl `image` widget
  components/lvgl/widgets.rst
Labels: current

#4126 bl0942: Add address and line_frequency options
  components/sensor/bl0942.rst
Labels: has-parent, next

#4194 Esp32_rmt_led_strip_reset
  components/light/esp32_rmt_led_strip.rst
Labels: has-parent, next

#4188 Update contributing.rst
  guides/contributing.rst
  guides/images/update_branch.png
Labels: current

#4190 [ili9xxx] Document that `invert_colors` is now required.
  components/display/ili9xxx.rst
Labels: has-parent, next

#4193 Add WS2811 to esp32_rmt_led_strip
  components/light/esp32_rmt_led_strip.rst
Labels: has-parent, next

#4172 [lvgl] Document `lvgl.widget.focus`
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: has-parent, next

#4204 Fix syntax for `datetime.date.set` lambda
  components/datetime/index.rst
Labels: current

#4196 Add BL0906 documentation
  components/sensor/bl0906.rst
  components/sensor/images/athom-em2.png
  components/sensor/images/athom-em6.png
  images/bl0906.png
  index.rst
Labels: has-parent, next

#4206 [gt911] Document reset pin
  components/touchscreen/gt911.rst
Labels: has-parent, next

#4189 [st7701s] Document delay feature
  components/display/st7701s.rst
Labels: has-parent, next

#4199 update documentation for esp32_can
  components/canbus/esp32_can.rst
Labels: has-parent, next

#4191 Tuya Number: description of the new restore_value key for hidden datapoints
  components/number/tuya.rst
Labels: has-parent, next

#3918 Document UDP component
  components/binary_sensor/udp.rst
  components/sensor/udp.rst
  components/udp.rst
  images/udp.svg
  index.rst
Labels: has-parent, next

#4181 Update ble_presence.rst
  components/binary_sensor/ble_presence.rst
Labels: has-parent, current

#4184 Update bme68x_bsec2.rst
  components/sensor/bme68x_bsec2.rst
Labels: current

#4170 Update getting_started_hassio.rst
  guides/getting_started_hassio.rst
Labels: current
