Repository esphome/esphome-docs, pull requests merged in 2024-04, with the labels that each got.

#3726 Update ethernet.rst. Added more details.
  components/ethernet.rst
Labels: current

#3728 Energy instead of voltage in energy value
  components/sensor/bl0942.rst
Labels: current

#3729 ESP Touch raw values access documentation
  components/binary_sensor/esp32_touch.rst
Labels: has-parent, current

#3730 Add temperature for QMC5883L
  components/sensor/qmc5883l.rst
Labels: has-parent, next

#3737 2024.3.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3746 Internal temperature: Support Beken platform
  components/sensor/internal_temperature.rst
Labels: has-parent, next

#3465 added documentation for the pink version of miflora sensor
  components/sensor/images/xiaomi_hhccjcy10.jpg
  components/sensor/xiaomi_hhccjcy10.rst
  images/xiaomi_hhccjcy10.jpg
  index.rst
Labels: has-parent, next

#2778 Add timeout option on i2c.rst (esphome/issues#4340)
  components/i2c.rst
Labels: has-parent, next, not-stale

#2844 Add ABB-Welcome / Busch-Welcome Door Intercom Protocol
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, not-stale

#3748 Add docs for time entities
  components/datetime/index.rst
  components/datetime/template.rst
Labels: has-parent, next

#3745 Update for rmt_channel on receiver and transmitter
  components/light/esp32_rmt_led_strip.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3744 Added tlc5971 documentation
  components/output/images/tlc5971.jpg
  components/output/tlc5971.rst
  images/tlc5971.jpg
  index.rst
Labels: has-parent, next

#3749 Add documentation for Dooya RF
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3751 2024.4.0b1
  Doxygen
  Makefile
  _static/changelog-2024.4.0.png
  _static/version
  changelog/2024.4.0.rst
  components/at581x.rst
  components/climate/climate_ir.rst
  components/climate/tuya.rst
  components/datetime/index.rst
  components/datetime/template.rst
  components/display/index.rst
  components/i2c.rst
  components/images/sun_gtil2_controller_board.png
  components/images/sun_gtil2_display_board.png
  components/images/sun_gtil2_schematic.png
  components/light/esp32_rmt_led_strip.rst
  components/output/images/tlc5971.jpg
  components/output/ledc.rst
  components/output/sm2135.rst
  components/output/tlc5971.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/images/jsn-sr04t-v3-mode-select-pads.jpg
  components/sensor/images/jsn-sr04t-v3.jpg
  components/sensor/images/xiaomi_hhccjcy10.jpg
  components/sensor/internal_temperature.rst
  components/sensor/jsn_sr04t.rst
  components/sensor/qmc5883l.rst
  components/sensor/sht3xd.rst
  components/sensor/xiaomi_hhccjcy10.rst
  components/sun_gtil2.rst
  components/wireguard.rst
  conf.py
  guides/supporters.rst
  images/at581x.png
  images/jsn-sr04t-v3.jpg
  images/sun_1000g2.png
  images/tlc5971.jpg
  images/xiaomi_hhccjcy10.jpg
  index.rst
Labels: has-parent, beta

#3756 2024.4.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.4.0.rst
  changelog/index.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3721 Add DNS sensor
  components/text_sensor/ethernet_info.rst
Labels: has-parent, next

#3600 Remove unnecessary lambda from example
  components/sensor/index.rst
Labels: stale, current

#3747 Update xiaomi_ble: Bluetooth Proxy supports stock firmware, too
  components/sensor/xiaomi_ble.rst
Labels: current

#3434 Add esphome-gdo link
  guides/diy.rst
Labels: current

#3717 Esphome flasher deprecated
  changelog/v1.9.0.rst
  guides/faq.rst
  guides/getting_started_command_line.rst
  guides/images/esphomeflasher-ui.png
  guides/physical_device_connection.rst
Labels: current

#3738 Display rendering engine screenshots
  components/display/images/display_rendering_colors.png
  components/display/images/display_rendering_graph.png
  components/display/images/display_rendering_line.png
  components/display/images/display_rendering_shapes.png
  components/display/images/display_rendering_text.png
  components/display/images/graph_dualtrace.png
  components/display/images/graph_screen.png
  components/display/index.rst
Labels: current

#3758 Made for ESPHome: Specify adopted configs must compile
  guides/made_for_esphome.rst
Labels: current

#3760 2024.4.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.4.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3759 Remove 404 link
  guides/diy.rst
Labels: current

#3765 2024.4.0
  Doxygen
  Makefile
  _static/changelog-2024.4.0.png
  _static/version
  changelog/2024.4.0.rst
  changelog/index.rst
  components/at581x.rst
  components/climate/climate_ir.rst
  components/climate/tuya.rst
  components/datetime/index.rst
  components/datetime/template.rst
  components/display/index.rst
  components/i2c.rst
  components/images/sun_gtil2_controller_board.png
  components/images/sun_gtil2_display_board.png
  components/images/sun_gtil2_schematic.png
  components/light/esp32_rmt_led_strip.rst
  components/output/images/tlc5971.jpg
  components/output/ledc.rst
  components/output/sm2135.rst
  components/output/tlc5971.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/images/jsn-sr04t-v3-mode-select-pads.jpg
  components/sensor/images/jsn-sr04t-v3.jpg
  components/sensor/images/xiaomi_hhccjcy10.jpg
  components/sensor/internal_temperature.rst
  components/sensor/jsn_sr04t.rst
  components/sensor/qmc5883l.rst
  components/sensor/sht3xd.rst
  components/sensor/xiaomi_hhccjcy10.rst
  components/sun_gtil2.rst
  components/wireguard.rst
  conf.py
  guides/supporters.rst
  images/at581x.png
  images/jsn-sr04t-v3.jpg
  images/sun_1000g2.png
  images/tlc5971.jpg
  images/xiaomi_hhccjcy10.jpg
  index.rst
Labels: has-parent, current

#3768 Update status_led.rst
  components/status_led.rst
Labels: current

#3783 2024.4.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3785 Update Dockerfile
  Dockerfile
Labels: current

#3786 Add fosstodon verification tag
  _templates/layout.html
Labels: current

#3788 Remove "Required Home Assistant XXXX.X" messages for older versions
  components/binary_sensor/homeassistant.rst
  components/binary_sensor/index.rst
  components/bluetooth_proxy.rst
  components/climate/index.rst
  components/cover/index.rst
  components/datetime/index.rst
  components/esp32_camera.rst
  components/fan/index.rst
  components/light/index.rst
  components/lock/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/homeassistant.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text_sensor/index.rst
Labels: current

#3763 Add documentation for valve component
  components/index.rst
  components/valve/images/valve-ui.png
  components/valve/index.rst
  components/valve/template.rst
  index.rst
Labels: has-parent, next

#3787 [sn74hc595] Update documentation for type and spi_id
  components/sn74hc595.rst
Labels: has-parent, next

#3789 Organize main page better
  index.rst
Labels: current

#3113 Add WeiKai component documentation
  components/images/DFR0627.jpg
  components/weikai.rst
  images/wk2168.jpg
  index.rst
Labels: has-parent, next

#3722 Event components
  components/event/index.rst
  components/event/template.rst
  components/index.rst
  index.rst
  schema_doc.py
Labels: has-parent, next

#2767 Include roomba ir in docs
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, not-stale

#3798 Fix Docker build
  Dockerfile
  guides/contributing.rst
Labels: current

#3784 Add DateTime datetime type entities to docs
  components/datetime/index.rst
  components/datetime/template.rst
Labels: has-parent, next

#3796 Update description about showing the Color Test Card.
  components/display/images/test_card.jpg
  components/display/index.rst
Labels: has-parent, next

#3780 waveshare_epaper: Add 2.90in-dke
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3631 Redo the homeassistant service call API setup instructions
  _static/custom.css
  components/api.rst
Labels: stale, current

#3775 Add transition_length to strobe effect.
  components/light/index.rst
Labels: has-parent, next

#3804 2024.4.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.4.0.rst
  conf.py
  guides/supporters.rst
Labels: current
