Repository esphome/esphome-docs, pull requests merged in 2024-06, with the labels that each got.

#3889 Wireguard support for bk72
  components/wireguard.rst
Labels: has-parent, next

#3893 Document host platform
  components/host.rst
  images/host.svg
  index.rst
Labels: current

#3732 Update i2s_microphone data value
  components/microphone/index.rst
Labels: stale, has-parent, current

#3899 Make pagefind work in docker
  .gitignore
  Dockerfile
  Makefile
  pagefind.yml
Labels: current

#3900 Remove debug code from last PR
  Dockerfile
Labels: current

#3884 Rename last_operation() to get_last_operation() & warn about bug http…
  components/cover/time_based.rst
Labels: has-parent, current

#3887 Add Ethernet MAC address to ethernet_info
  components/text_sensor/ethernet_info.rst
Labels: has-parent, next

#3909 Document host time
  components/host.rst
  components/time/host.rst
Labels: has-parent, next

#3910 Fix host icon in dark mode
  index.rst
Labels: current

#3583 Set SN74HC165's clock_inhibit_pin as optional
  components/sn74hc165.rst
Labels: current

#3903 Update to Addressable Color Wipe Example
  components/light/index.rst
Labels: current

#3720 Update ens160.rst to add missing ens160_air_quality_index
  components/sensor/ens160.rst
Labels: stale, current

#3824 doc: wifi reboot_timeout disabled if ap enabled
  components/wifi.rst
Labels: current

#3762 Fix doc for template cover regarding position_action and has_position
  components/cover/template.rst
Labels: current

#3771 Include note about Daylight Savings Time duplication/skipping
  components/time/index.rst
Labels: current

#3767 Reorder and reference the mirdea_ir variant example.
  components/climate/climate_ir.rst
Labels: current

#3556 Improve SGP30 humidity compensation documentation
  components/sensor/sgp30.rst
Labels: current

#3446 Add Seeed Studio XIAO ESP32S3 Sense pins to esp32_camera.rst
  components/esp32_camera.rst
Labels: current

#3901 Install pagefind in devcontainer
  .devcontainer/devcontainer.json
  .devcontainer/postCreate.sh
  lint.py
Labels: current

#3916 2024.5.5
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3886 [ethernet] Adds documentation for setting PHY register values
  components/ethernet.rst
Labels: has-parent, next

#3859 transmit_aeha carrier frequency now adjustable
  components/remote_transmitter.rst
Labels: has-parent, next

#3497 Tuya cover invert position report
  components/cover/tuya.rst
Labels: stale, has-parent, next

#3906 Document file: scheme for external component via git
  components/external_components.rst
Labels: has-parent, next

#3291 OTA Update via HTTP Request documentation
  components/ota.rst
  components/ota_http_request.rst
  index.rst
Labels: has-parent, next

#3921 SHT3xd component - Provide example i2c configuration for >50-100Khz i2c frequencies on IDF
  components/sensor/sht3xd.rst
Labels: current

#3919 Documentation updates for ``http_request`` component refactor
  components/http_request.rst
  components/ota.rst
  components/ota_http_request.rst
Labels: has-parent, next

#3926 New branding for ESPHome
  _static/apple-touch-icon.png
  _static/browserconfig.xml
  _static/custom.css
  _static/favicon-128x128.png
  _static/favicon-16x16.png
  _static/favicon-192x192.png
  _static/favicon-256x256.png
  _static/favicon-32x32.png
  _static/favicon-512x512.png
  _static/favicon.ico
  _static/made-for-esphome-black-on-transparent.png
  _static/made-for-esphome-black-on-transparent.svg
  _static/made-for-esphome-black-on-white.png
  _static/made-for-esphome-black-on-white.svg
  _static/made-for-esphome-white-on-black.png
  _static/made-for-esphome-white-on-black.svg
  _static/made-for-esphome-white-on-transparent.png
  _static/made-for-esphome-white-on-transparent.svg
  _static/mstile-150x150.png
  _static/safari-pinned-tab.svg
  _static/site.webmanifest
  _templates/layout.html
  images/logo-core.svg
  images/logo-docs.svg
  images/logo-release.svg
  images/logo-text.svg
Labels: current

#3932 Blue ESPHome logo
  _static/custom.css
  _static/logo-text-on-dark.svg
  _static/logo-text-on-light.svg
  _templates/layout.html
  images/logo.svg
  index.rst
Labels: current

#3928 Fix-navigation-spacing
  _static/custom.css
  _templates/layout.html
Labels: current

#3936 Run svg2png
  svg2png/alarm-panel.png
  svg2png/analog_threshold.png
  svg2png/content-copy.png
  svg2png/dac7678.png
  svg2png/ektf2232.png
  svg2png/feedback_cover.png
  svg2png/format-font.png
  svg2png/garage-variant.png
  svg2png/gcja5.png
  svg2png/gp8403.png
  svg2png/haier.png
  svg2png/head-lightbulb-outline.png
  svg2png/high-voltage-warning.png
  svg2png/home-assistant.png
  svg2png/host.png
  svg2png/i2s_audio.png
  svg2png/ili9341.png
  svg2png/ili9342.png
  svg2png/ili9481.png
  svg2png/ili9488.png
  svg2png/kamstrup_kmp_holder.png
  svg2png/kamstrup_kmp_sch.png
  svg2png/lcd_gpio.png
  svg2png/libretiny.png
  svg2png/logo-docs.png
  svg2png/logo-text.png
  svg2png/logo.png
  svg2png/made-for-esphome-black-on-transparent.png
  svg2png/made-for-esphome-black-on-white.png
  svg2png/made-for-esphome-white-on-black.png
  svg2png/made-for-esphome-white-on-transparent.png
  svg2png/max44009.png
  svg2png/mcp47a1.png
  svg2png/microphone.png
  svg2png/pca6416a.png
  svg2png/pellet.png
  svg2png/psram.png
  svg2png/qr-code.png
  svg2png/radio-tower.png
  svg2png/rp2040.png
  svg2png/rtl87xx.png
  svg2png/sigma-delta.png
  svg2png/sm2235.png
  svg2png/sm2335.png
  svg2png/sml.png
  svg2png/speaker.png
  svg2png/sprinkler-variant.png
  svg2png/st7796.png
  svg2png/thermometer.png
  svg2png/timer-play-outline.png
  svg2png/uponor.png
  svg2png/voice-assistant.png
  svg2png/water-drop.png
  svg2png/wireguard_custom_logo.png
  svg2png/xl9535.png
Labels: current

#3935 [core] Update Entities documentation
  components/index.rst
  components/ota_http_request.rst
  components/update/http_request.rst
  components/update/index.rst
  index.rst
Labels: has-parent, next

#3925 [CI] Make action to generate component images
  .github/workflows/component-image.yml
Labels: current

#3940 Add vim swp files to gitignore
  .gitignore
Labels: current

#3719 Add line for 13.3in-k in waveshare_epaper component
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3930 [safe_mode] Allow user-defined interval for successful boot
  components/safe_mode.rst
Labels: has-parent, next

#3911 docs for one-wire platform change
  components/images/dallas-log.png
  components/one_wire.rst
  components/sensor/dallas.rst
  components/sensor/dallas_temp.rst
  components/sensor/images/dallas-log.png
  components/sensor/images/dallas-wired.jpg
  components/sensor/index.rst
  components/sensor/max31855.rst
  components/sensor/max31856.rst
  components/sensor/max31865.rst
  components/sensor/max6675.rst
  images/one-wire.svg
  index.rst
Labels: has-parent, next

#3880 Document sdl driver
  components/display/sdl.rst
  components/touchscreen/sdl.rst
  images/sdl.png
  index.rst
Labels: has-parent, next

#3888 Add st7735 to ili9xxx
  components/display/ili9xxx.rst
  components/display/st7735.rst
Labels: has-parent, next

#3929 Add links to the Open Home Foundation
  _templates/contact.html
  guides/supporters.rst
Labels: current

#3939 Added documentation for new option operation_speed for X9C Digital Potentiometer
  components/output/x9c.rst
Labels: has-parent, next

#3947 2024.6.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3949 Update ``json::parse_json`` examples
  components/http_request.rst
  cookbook/http_request_sensor.rst
Labels: has-parent, next

#3954 Update TYPO in pipsolar.rst
  components/pipsolar.rst
Labels: current

#3923 Update documentation for dashboard command
  guides/cli.rst
Labels: current

#3962 Update a couple docs for esphome/esphome#6922
  components/ota_http_request.rst
  guides/migrate_sonoff_tasmota.rst
Labels: has-parent, next

#3961 2024.6.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  components/ota_http_request.rst
  conf.py
  guides/migrate_sonoff_tasmota.rst
  guides/supporters.rst
Labels: beta

#3955 Add another project to diy.rst
  guides/diy.rst
Labels: current

#3958 Fix GPIO pins of 2nd and 3rd hardware UART
  components/logger.rst
Labels: current

#3793 Add state class and fix typo in bme680 example
  components/sensor/bme680.rst
Labels: current

#3902 [ft5x06] Add interrupt pin
  components/touchscreen/ft5x06.rst
Labels: has-parent, next

#3964 corrected indentation
  guides/configuration-types.rst
Labels: current

#3966 2024.6.0b5
  .github/workflows/docker.yml
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  components/logger.rst
  components/sensor/bme680.rst
  components/touchscreen/ft5x06.rst
  conf.py
  guides/configuration-types.rst
  guides/diy.rst
  guides/supporters.rst
Labels: beta

#3970 Fix 2024.6.0 changelog social image
  _static/changelog-2024.6.0.png
  changelog/2024.6.0.rst
Labels: current

#3971 2024.6.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3972 Fix missing platform for one_wire in changelog
  changelog/2024.6.0.rst
Labels: current

#3976 [ota] Add component page, various tweaks
  _redirects
  changelog/v1.9.0.rst
  components/bluetooth_proxy.rst
  components/index.rst
  components/ota/esphome.rst
  components/ota/http_request.rst
  components/ota/index.rst
  components/safe_mode.rst
  components/update/http_request.rst
  components/update/index.rst
  components/wifi.rst
  guides/getting_started_hassio.rst
  guides/physical_device_connection.rst
  index.rst
Labels: current

#3977 Update the climate UI screenshot
  components/climate/images/climate-ui.png
Labels: current

#3985 Fix the invalid URL for data sheet in gdk101.rst
  components/sensor/gdk101.rst
Labels: current

#3934 Add stevebaxter to supporters.rst
  guides/supporters.rst
Labels: current

#3988 2024.6.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3989 Add a bunch of missing supporters
  guides/supporters.rst
Labels: current

#3983 Add esphome platform to OTA sections in docs
  components/bluetooth_proxy.rst
  components/display/inkplate6.rst
  components/light/sonoff_d1.rst
  components/output/my9231.rst
  components/output/sm16716.rst
  cookbook/arduino_port_extender.rst
  cookbook/leak-detector-m5stickC.rst
  cookbook/sonoff-fishpond-pump.rst
  guides/creators.rst
Labels: current

#3975 Bump HeatpumpIR and IRremoteESP8266
  components/climate/climate_ir.rst
Labels: has-parent, next

#3995 2024.6.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3957 Break apart automations doc
  all_automations.json
  automations/actions.rst
  automations/all_actions.rst
  automations/all_conditions.rst
  automations/index.rst
  automations/templates.rst
  build_automations_pages.py
  components/button/template.rst
  components/event/template.rst
  components/globals.rst
  components/interval.rst
  components/lock/template.rst
  components/script.rst
  components/switch/template.rst
  cookbook/garage-door.rst
  guides/automations.rst
  index.rst
  schema_doc.py
Labels: has-parent, current

#3994 [modbus_text_sensor] new default ANSI encoding type
  components/text_sensor/modbus_controller.rst
Labels: has-parent, next

#3998 2024.6.4
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3999 Fix script link
  components/script.rst
  index.rst
Labels: current

#4000 "Temperature" to "Pressure" correction
  components/sensor/bmp280.rst
Labels: current
