Repository esphome/esphome-docs, pull requests merged in 2024-03, with the labels that each got.

#2843 Document W5500 support
  components/ethernet.rst
Labels: has-parent, next, not-stale

#3551 Add regular polygon shapes to display component
  components/display/index.rst
Labels: has-parent, next

#1974 Support for MS8607 PHT (Pressure Humidity Temperature) sensor
  components/sensor/images/ms8607-full.jpg
  components/sensor/ms8607.rst
  images/ms8607.jpg
  index.rst
Labels: has-parent, next, not-stale

#3628 Help for additional haier climete sensors added
  components/binary_sensor/haier.rst
  components/binary_sensor/images/haier-climate.jpg
  components/climate/haier.rst
  components/sensor/haier.rst
  components/sensor/images/haier-climate.jpg
Labels: has-parent, next

#3658 Add toggle command to cover REST API commands
  web-api/index.rst
Labels: has-parent, next

#3651 Add docs for passing the used wake word to the voice_assistant
  components/micro_wake_word.rst
  components/voice_assistant.rst
Labels: has-parent, next

#3654 optional output is temporary
  components/fan/speed.rst
Labels: has-parent, next

#3660 2024.2.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.2.0.rst
  components/fan/speed.rst
  components/micro_wake_word.rst
  components/voice_assistant.rst
  conf.py
  guides/supporters.rst
Labels: current

#3662 Update pca9554.rst to fix typo
  components/pca9554.rst
Labels: current

#3595 add doc for datetime component
  components/datetime/index.rst
  components/datetime/template.rst
  components/index.rst
  index.rst
Labels: has-parent, next

#3527 Add AGS10 Sensor
  components/sensor/ags10.rst
  components/sensor/images/ags10.jpg
  images/ags10.jpg
  index.rst
Labels: has-parent, next

#3606 Add documentation for ADS1118
  components/sensor/ads1118.rst
  components/sensor/images/ads1118-full.jpg
  images/ads1118.jpg
  index.rst
Labels: has-parent, next

#3655 document template fan and fan triggers
  components/fan/index.rst
  components/fan/speed.rst
  components/fan/template.rst
  index.rst
Labels: has-parent, next

#3558 [Fingerprint_grow] Add description for Sleep Mode Feature
  components/fingerprint_grow.rst
  components/images/fingeprint_grow-sleep_mode_wiring.jpg
Labels: has-parent, next

#3666 Add IRK support to allow tracking of devices with random MAC addresses
  components/binary_sensor/ble_presence.rst
Labels: has-parent, next

#3673 Update ili9xxx documentation in regards of SPI settings
  components/display/ili9xxx.rst
Labels: has-parent, current

#3635 feat(MQTT): Add QoS option for each MQTT component
  components/mqtt.rst
Labels: has-parent, next

#3459 Add CST816 touchscreen docs
  components/touchscreen/cst816.rst
  components/touchscreen/images/cst816.jpg
  images/cst816.jpg
  index.rst
Labels: has-parent, next

#3625 Add AM2315C docs
  components/sensor/am2315c.rst
  components/sensor/images/am2315c-full.jpg
  images/am2315c.jpg
  index.rst
Labels: has-parent, next

#3500 Add docs for ble_presence timeout
  components/binary_sensor/ble_presence.rst
Labels: has-parent, next

#3577 Add Cst226 touchscreen docs
  components/touchscreen/cst226.rst
  components/touchscreen/images/t4-s3.jpg
  images/t4-s3.jpg
  index.rst
Labels: has-parent, next

#3596 Font: document new font features
  components/display/fonts.rst
  components/display/index.rst
  images/format-font.svg
  index.rst
Labels: has-parent, next

#3604 Add MHZ-19 warmup time
  components/sensor/mhz19.rst
Labels: has-parent, next

#3573 ATM90E32 advanced features
  components/sensor/atm90e32.rst
Labels: has-parent, next

#3675 Add note about fake RP2040 unsupported
  components/rp2040.rst
Labels: current

#2353 Mitsubishi update
  components/climate/climate_ir.rst
Labels: has-parent, next, not-stale

#3546 Add st7701s and rpi_dpi_rgb docs
  components/display/images/indicator.jpg
  components/display/images/waveshare_touch-s3.jpg
  components/display/rpi_dpi_rgb.rst
  components/display/st7701s.rst
  images/waveshare_touch-s3.jpg
  index.rst
Labels: has-parent, next

#3529 hydreon_rgxx - add resolution option
  components/sensor/hydreon_rgxx.rst
Labels: stale, has-parent, next

#3676 Update quad spi docs
  components/spi.rst
Labels: has-parent, next

#3525 VEML7700 and VEML6030 light sensors
  components/sensor/images/veml7700-full.jpg
  components/sensor/images/veml7700-spectral.png
  components/sensor/images/veml7700-ui.png
  components/sensor/veml7700.rst
  images/veml6030.jpg
  images/veml7700.jpg
  index.rst
Labels: has-parent, next

#3383 Add Seeed Studio mmWave Sensor MR24HPC1 document
  components/images/seeed-mr24hpc1-card.png
  components/images/seeed-mr24hpc1-mmwave-kit.png
  components/images/seeed-mr24hpc1.jpg
  components/seeed_mr24hpc1.rst
  images/seeed-mr24hpc1.jpg
  index.rst
Labels: next, not-stale

#3261 add docs for load font from url
  components/display/fonts.rst
Labels: stale, has-parent, next

#3677 Document quad SPI AMOLED displays
  components/display/images/t-display-amoled.jpg
  components/display/images/t4-s3.jpg
  components/display/qspi_amoled.rst
  index.rst
Labels: has-parent, next

#3656 ADE7953: Add the ability to use accumulating energy registers, more precise power reporting
  components/sensor/ade7953.rst
Labels: has-parent, next

#3397 feat: Add HTU31D Documentation
  components/sensor/htu31d.rst
  components/sensor/images/htu31d.jpg
  images/htu31d.jpg
  index.rst
Labels: has-parent, next

#3109 Add Emmeti platform to climate_ir.rst
  components/climate/climate_ir.rst
Labels: has-parent, next, not-stale

#3513 Kamstrup KMP
  components/sensor/images/kamstrup_kmp.jpg
  components/sensor/images/kamstrup_kmp_holder.svg
  components/sensor/images/kamstrup_kmp_sch.svg
  components/sensor/kamstrup_kmp.rst
  images/kamstrup_kmp.jpg
  index.rst
Labels: has-parent, next

#3661 add possibility to provide different conversion times for Bus Voltage…
  components/sensor/ina226.rst
Labels: has-parent, next

#3670 Fix indentation for SGP4x
  components/sensor/sgp4x.rst
Labels: current

#3653 Update diy.rst
  guides/diy.rst
Labels: current

#3581 Update bme280_environment.rst to reference bme280_i2c
  cookbook/bme280_environment.rst
Labels: current

#3548 Append project to diy.rst
  guides/diy.rst
Labels: current

#3442 Change the URL of the YAML repository for media player
  projects/installer.html
Labels: current

#3684 2024.3.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.3.0.rst
  components/select/index.rst
  components/sensor/sgp4x.rst
  conf.py
  cookbook/bme280_environment.rst
  guides/diy.rst
  guides/supporters.rst
  projects/installer.html
Labels: beta

#3685 typo
  _templates/layout.html
Labels: current

#3687 Add documentation for line_at_angle
  components/display/index.rst
Labels: has-parent, next

#3691 Title Fix Update diy.rst
  guides/diy.rst
Labels: current

#3693 2024.3.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.3.0.rst
  conf.py
  guides/diy.rst
  guides/supporters.rst
Labels: beta

#3695 2024.3.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2024.3.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3044 Pronto protocol customize delta
  components/remote_receiver.rst
Labels: has-parent, next, not-stale

#3671 add phase_angle to ledc component
  components/output/ledc.rst
Labels: has-parent, next

#3579 sm2135: add separate_modes option
  components/output/sm2135.rst
Labels: has-parent, next

#3697 fix(ina219): typo
  components/sensor/ina219.rst
Labels: has-parent, current

#3700 Add thank you note to release notes
  changelog/2024.3.0.rst
Labels: current

#3701 Correct example config for T-Display S3 Amoled
  components/display/qspi_amoled.rst
Labels: current

#3096 Update Tuya Climate for new esphome PR
  components/climate/tuya.rst
Labels: has-parent, next

#3005 Add sun_gtil2 component
  components/images/sun_gtil2_controller_board.png
  components/images/sun_gtil2_display_board.png
  components/images/sun_gtil2_schematic.png
  components/sun_gtil2.rst
  images/sun_1000g2.png
  index.rst
Labels: has-parent, next

#3704 doc: describe the IPv6 address generation
  components/network.rst
Labels: current

#3708 WireGuard for esp8266
  components/wireguard.rst
Labels: has-parent, next

#3646 Add documentation for AT581x Radar component
  components/at581x.rst
  images/at581x.png
  index.rst
Labels: has-parent, next

#3501 Documentation for JSN-SR04T Ultrasonic Sensor
  components/sensor/images/jsn-sr04t-v3-mode-select-pads.jpg
  components/sensor/images/jsn-sr04t-v3.jpg
  components/sensor/jsn_sr04t.rst
  images/jsn-sr04t-v3.jpg
  index.rst
Labels: has-parent, next, not-stale

#3715 2024.3.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3709 add doc for daikin_arc
  components/climate/climate_ir.rst
Labels: has-parent, next

#3711 Add example for get_size()
  components/display/index.rst
Labels: has-parent, next

#3703 Update for SHT85 support
  components/sensor/sht3xd.rst
Labels: has-parent, next

#3718 Guide on creating and including sound clips to be played by the i2s Speaker component.
  components/speaker/index.rst
  guides/audio_clips_for_i2s.rst
  guides/images/save_as_wav.png
Labels: current

#3584 Wireguard: add netmask caveat note
  components/wireguard.rst
Labels: stale, current
