Repository esphome/esphome-docs, pull requests merged in 2024-12, with the labels that each got.

#4233 Add docs for H-Bridge Switch
  components/switch/hbridge.rst
  components/switch/images/hbridge-relay.png
  images/hbridge-relay.jpg
  index.rst
Labels: has-parent, next

#4452 Updated docs for esphome#7768
  components/mqtt.rst
Labels: wrong-base-branch, has-parent, next

#4477 Docs for ble name
  components/esp32_ble.rst
Labels: has-parent, next

#4492 2024.11.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4483 Create guide for using an ESP devboard with USB_UART bridge chip as serial adapter
  guides/devboard_as_flasher.rst
  guides/images/devboard-as-flasher-pi.jpg
  guides/images/devboard-as-flasher.png
  guides/physical_device_connection.rst
Labels: current

#4478 vbus component: fix for Deltasol CS Plus
  components/vbus.rst
Labels: current

#4333 Add: Seeed Studio MR60BHA2 Document
  components/images/seeed_mr60bha2.jpg
  components/seeed_mr60bha2.rst
  images/seeed_mr60bha2.jpg
  index.rst
Labels: has-parent, next

#4495 Update index.rst - typo
  components/lvgl/index.rst
Labels: current

#4496 [lvgl] Document `on_change` trigger
  components/lvgl/widgets.rst
Labels: has-parent, next

#4497 Add note about retiring `armv7`
  changelog/2024.11.0.rst
Labels: current

#4500 2024.12.0b1
  Doxygen
  Makefile
  _static/changelog-2024.12.0.png
  _static/version
  changelog/2024.11.0.rst
  changelog/2024.12.0.rst
  changelog/index.rst
  components/binary_sensor/nextion.rst
  components/binary_sensor/switch.rst
  components/display/nextion.rst
  components/display/waveshare_epaper.rst
  components/esp32_ble.rst
  components/images/seeed_mr60bha2.jpg
  components/images/seeed_mr60fda2.jpg
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/matrix_keypad.rst
  components/mqtt.rst
  components/seeed_mr60bha2.rst
  components/seeed_mr60fda2.rst
  components/sensor/nextion.rst
  components/switch/hbridge.rst
  components/switch/images/hbridge-relay.png
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
  components/vbus.rst
  components/wifi.rst
  conf.py
  guides/contributing.rst
  guides/devboard_as_flasher.rst
  guides/images/devboard-as-flasher-pi.jpg
  guides/images/devboard-as-flasher.png
  guides/images/gha_checks.jpg
  guides/physical_device_connection.rst
  guides/supporters.rst
  images/hbridge-relay.jpg
  images/seeed_mr60bha2.jpg
  images/seeed_mr60fda2.jpg
  index.rst
Labels: beta

#4504 2024.12.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  components/lvgl/index.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4487 Added description for OpenTherm new features
  components/opentherm.rst
Labels: has-parent, next

#4507 Update display example
  components/display/index.rst
Labels: current

#4508 2024.12.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4437 [Midea] Update follow me action with Fahrenheit support
  components/climate/midea.rst
Labels: has-parent, next

#4509 2024.12.0
  Doxygen
  Makefile
  _static/changelog-2024.12.0.png
  _static/version
  changelog/2024.12.0.rst
  changelog/index.rst
  components/binary_sensor/nextion.rst
  components/binary_sensor/switch.rst
  components/display/nextion.rst
  components/display/waveshare_epaper.rst
  components/esp32_ble.rst
  components/images/seeed_mr60bha2.jpg
  components/images/seeed_mr60fda2.jpg
  components/lvgl/widgets.rst
  components/matrix_keypad.rst
  components/mqtt.rst
  components/seeed_mr60bha2.rst
  components/seeed_mr60fda2.rst
  components/sensor/nextion.rst
  components/switch/hbridge.rst
  components/switch/images/hbridge-relay.png
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
  components/wifi.rst
  conf.py
  guides/supporters.rst
  images/hbridge-relay.jpg
  images/seeed_mr60bha2.jpg
  images/seeed_mr60fda2.jpg
  index.rst
Labels: current

#4512 [esp32_improv] Remove ``false`` as valid value for authorizer
  components/esp32_improv.rst
Labels: current

#4480 [esp32_rmt] Updates for IDF 5+ changes
  components/light/esp32_rmt_led_strip.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#4514 document QSPI changes
  components/display/qspi_dbi.rst
Labels: has-parent, next

#4515 2024.12.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4519 [lvgl] Clarify getting started
  components/lvgl/index.rst
Labels: current

#4520 Fixed a typo in ld2420 docs.
  components/sensor/ld2420.rst
Labels: current

#4523 Update devboard_as_flasher.rst to additionally include ESP32 S series
  guides/devboard_as_flasher.rst
Labels: current

#4524 2024.12.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4543 Correction to `http_request` example
  components/http_request.rst
Labels: current

#4544 Update font renderer example to avoid number to string ambiguity
  components/font.rst
Labels: current

#4545 [lvgl] Document `disp_bg_image` and `disp_bg_opa` changes
  components/lvgl/index.rst
Labels: has-parent, next

#4266 Add use_psram param description to esp32_rmt_led_strip.rst
  components/light/esp32_rmt_led_strip.rst
Labels: stale, has-parent, current
