Repository esphome/esphome-docs, pull requests merged in 2024-07, with the labels that each got.

#4009 Update dallas_temp.rst
  components/sensor/dallas_temp.rst
Labels: current

#3990 fix ota example
  components/ota/esphome.rst
Labels: current

#3869 Note about alternative wind sensors due to deprecation by manufacturer
  components/sensor/tx20.rst
Labels: current

#4013 Fix components.json generation
  changelog/v1.9.0.rst
  components/globals.rst
  components/interval.rst
  components/script.rst
  cookbook/http_request_sensor.rst
Labels: current

#4014 [uptime] Add sensor types
  components/sensor/uptime.rst
Labels: has-parent, next

#3811 remote_receiver: document using multiple with receiver_id
  components/remote_receiver.rst
Labels: stale, current

#4016 2024.6.5
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4017 2024.6.6
  Doxygen
  Makefile
  _static/version
  changelog/2024.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4020 Update of Haier component documentation to support new features and settings
  components/climate/haier.rst
Labels: has-parent, next

#4021 Update SGP30 documentation to fix typos
  components/sensor/sgp30.rst
Labels: current

#4031 [M4E] Requirements tweak
  guides/made_for_esphome.rst
Labels: current

#4015 [micro_wake_word] Version 2 Documentation
  components/micro_wake_word.rst
Labels: has-parent, next

#4004 Information about UART component in host platform added
  components/uart.rst
Labels: has-parent, next

#4035 2024.7.0b1
  .github/workflows/component-image.yml
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  components/api.rst
  components/climate/climate_ir.rst
  components/climate/haier.rst
  components/micro_wake_word.rst
  components/output/x9c.rst
  components/sensor/sgp30.rst
  components/sensor/uptime.rst
  components/text_sensor/modbus_controller.rst
  components/uart.rst
  conf.py
  guides/made_for_esphome.rst
  guides/supporters.rst
Labels: beta

#4036 Change average_throttle to throttle_average in power_meter.rst
  cookbook/power_meter.rst
Labels: current

#4029 Add yac1fb9 model for the gree climate_ir component
  components/climate/climate_ir.rst
Labels: has-parent, next

#4022 jsn_sr04t: Added options for AJ_SR04M sensor types
  components/sensor/jsn_sr04t.rst
Labels: has-parent, next

#4044 Update globals.rst: Added globals.set Action Lambda Example
  components/globals.rst
Labels: current

#4040 Remove `esp8266_restore_from_flash` note
  components/cover/time_based.rst
Labels: current

#4041 Remove `esp8266_restore_from_flash` reference
  components/globals.rst
Labels: current

#4042 Remove `esp8266_restore_from_flash` reference
  components/light/index.rst
Labels: current

#4043 Remove `esp8266_restore_from_flash` reference
  components/sensor/rotary_encoder.rst
Labels: current

#3996 Bump HeatpumpIR - add protocols
  components/climate/climate_ir.rst
Labels: has-parent, next

#4012 LTR390 separate ALS and UV gain and resolution
  components/sensor/ltr390.rst
Labels: has-parent, next

#4045 2024.7.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  components/climate/climate_ir.rst
  components/cover/time_based.rst
  components/globals.rst
  components/light/index.rst
  components/sensor/ltr390.rst
  components/sensor/rotary_encoder.rst
  conf.py
  cookbook/power_meter.rst
  guides/supporters.rst
Labels: beta

#4049 [http_request] fix response
  components/http_request.rst
Labels: current

#4050 Replace mac addresses in docs with XX:XX:XX:XX:XX:XX
  components/binary_sensor/ble_presence.rst
  components/ble_client.rst
  components/button/wake_on_lan.rst
  components/climate/anova.rst
  components/climate/bedjet.rst
  components/cover/am43.rst
  components/display/pvvx_mithermometer.rst
  components/esp32_ble_tracker.rst
  components/output/ble_client.rst
  components/sensor/airthings_ble.rst
  components/sensor/am43.rst
  components/sensor/b_parasite.rst
  components/sensor/ble_client.rst
  components/sensor/ble_rssi.rst
  components/sensor/inkbird_ibsth1_mini.rst
  components/sensor/mopeka_pro_check.rst
  components/sensor/mopeka_std_check.rst
  components/sensor/radon_eye_ble.rst
  components/sensor/ruuvitag.rst
  components/sensor/xiaomi_ble.rst
  components/sensor/xiaomi_hhccjcy10.rst
  components/sensor/xiaomi_miscale.rst
  components/switch/ble_client.rst
  components/text_sensor/ble_client.rst
  components/text_sensor/ble_scanner.rst
Labels: current

#4038 [canbus] Break out platforms
  components/canbus.rst
  components/canbus/esp32_can.rst
  components/canbus/images/canbus_esp32_3v3.png
  components/canbus/images/canbus_esp32_5v.png
  components/canbus/images/canbus_mcp2515_resistor.png
  components/canbus/images/canbus_mcp2515_txs0108e.png
  components/canbus/index.rst
  components/canbus/mcp2515.rst
  components/index.rst
  images/mcp2515.svg
  index.rst
Labels: current

#4053 [i2s_audio] Microphone i2s mode
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#4057 2024.7.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4058 Update host-related docs
  components/display/sdl.rst
  components/host.rst
Labels: current

#4059 2024.7.0
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  components/climate/climate_ir.rst
  components/climate/haier.rst
  components/micro_wake_word.rst
  components/microphone/i2s_audio.rst
  components/output/x9c.rst
  components/sensor/ltr390.rst
  components/sensor/uptime.rst
  components/text_sensor/modbus_controller.rst
  components/uart.rst
  conf.py
  guides/supporters.rst
Labels: current

#4026 Update esphome.rst: Add Removing a Password section
  components/ota/esphome.rst
Labels: current

#4051 Component TOF10120: Fix broken link to datasheet
  components/sensor/tof10120.rst
Labels: current

#4047 Update actions.rst
  automations/actions.rst
Labels: current

#4037 Fix Modbus Example Server doc
  components/modbus_controller.rst
Labels: current

#4060 Add mWW breaking change note
  changelog/2024.7.0.rst
Labels: current

#3987 Add `on_response Trigger` lambda example
  components/http_request.rst
Labels: current

#4024 Corrected an incidence of "servo" to "stepper motor"
  components/stepper/index.rst
Labels: current

#4001 [web_server] v3-features
  components/images/web_server/number-slider-popup-input-field.png
  components/images/web_server/number-slider-popup.png
  components/images/web_server/sensor-history-graph.png
  components/images/web_server/tab-header-expand-cloapsed.png
  components/images/web_server/tab-header-expand-controls-expanded.png
  components/images/web_server/tab-header-expand-logs-expanded.png
  components/web_server.rst
Labels: current

#3982 update board information
  components/esp32.rst
Labels: current

#3764 Fix default address in qmc5883l
  components/sensor/qmc5883l.rst
Labels: current

#3878 Update documentation about `restore_mode` for valves
  components/valve/template.rst
Labels: current

#4062 Update changelog redirect
  changelog/index.rst
Labels: current

#4066 Update Datasheet URL
  components/sensor/scd4x.rst
Labels: current

#4067 Update datasheet ref
  components/sensor/ens160.rst
Labels: current

#3922 Fix example for overriding libraries
  components/esphome.rst
Labels: current

#3809 update MQTT docs to include discover_ip option
  components/mqtt.rst
  guides/cli.rst
Labels: has-parent, next

#3866 Document m5angle8 input device
  components/sensor/images/m5stack_8angle.jpg
  components/sensor/m5stack_8angle.rst
  images/m5stack_8angle.png
  index.rst
Labels: has-parent, next

#4039 [modbus_controller] on command sent trigger
  components/modbus_controller.rst
Labels: has-parent, next

#4071 2024.7.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3826 APDS9306 Ambient Light Sensor Documentation
  components/images/apds9306.png
  components/sensor/apds9306.rst
  components/sensor/images/apds9306.png
  images/apds9306.png
  index.rst
Labels: has-parent, next

#4076 [http_request] Simplify component examples
  components/http_request.rst
  cookbook/http_request_sensor.rst
Labels: current

#4077 [http_request] Change default timeout to 4.5s
  components/http_request.rst
Labels: has-parent, next

#4078 [http_request] Allow configure buffer size on ESP-IDF
  components/http_request.rst
Labels: has-parent, next

#4079 2024.7.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  components/http_request.rst
  conf.py
  guides/supporters.rst
Labels: current

#3873 Added Electrolux AC into supported list
  components/climate/climate_ir.rst
Labels: stale, current

#4088 Fix for Mitsubishi units that only support cooling
  components/climate/climate_ir.rst
Labels: has-parent, next

#4072 [touchscreen] Add ``pages`` config item
  components/touchscreen/index.rst
Labels: has-parent, next

#3883 Add deprecation notice for ESP32 Hall sensor
  components/sensor/esp32_hall.rst
Labels: next

#4096 Fix example YAML for Haier climate component
  components/climate/haier.rst
Labels: current

#4087 fix pipsolar example
  components/pipsolar.rst
Labels: current

#4094 fix SMS example
  components/sim800l.rst
Labels: current

#3892 add chrisns/childrens-clock to diy.rst
  guides/diy.rst
Labels: stale, current

#4097 [micro_wake_word] Update documentation to discuss how voice activity is detected
  components/micro_wake_word.rst
Labels: has-parent, next

#4098 [update] Add automation documentation
  components/update/index.rst
Labels: has-parent, next

#4103 2024.7.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.7.0.rst
  components/climate/climate_ir.rst
  components/micro_wake_word.rst
  conf.py
  guides/supporters.rst
Labels: current
