Repository esphome/esphome-docs, pull requests merged in 2024-09, with the labels that each got.

#4214 Fix component image generator filenames
  .github/workflows/component-image.yml
Labels: current

#4210 Documentation for CH422G I/O Expander
  components/ch422g.rst
  images/ch422g.svg
  index.rst
Labels: has-parent, next

#4212 Add enable_pin to RPI_DPI_RGB Display Driver doc
  components/display/rpi_dpi_rgb.rst
Labels: has-parent, next

#4161 Add Gree model YX1FF
  components/climate/climate_ir.rst
Labels: has-parent, next

#4203 [modbus_controller] Pref to allow duplicate commands
  components/modbus_controller.rst
Labels: has-parent, next

#4220 2024.8.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.8.0.rst
  conf.py
Labels: current

#4213 Voice assist improvement docs - conversation_timeout
  components/voice_assistant.rst
Labels: has-parent, next

#4163 Add calibration values for BL0942
  components/sensor/bl0942.rst
Labels: has-parent, next

#3802 Add documentation for StatsD component
  components/statsd.rst
  index.rst
Labels: has-parent, next

#4215 Add supported domains for HA switch
  components/switch/homeassistant.rst
Labels: has-parent, next

#4064 Add BMP280 SPI Component
  components/sensor/bmp280.rst
Labels: has-parent, next

#4209 [lvgl] Document msgbox changes
  components/lvgl/widgets.rst
Labels: next

#3616 Support for light sensors LTR-501, LTR-301, LTR-558
  components/sensor/images/ltr501-full.jpg
  components/sensor/images/ltr501-ui.png
  components/sensor/ltr501.rst
  images/ltr501.jpg
  index.rst
Labels: has-parent, next

#4239 spell: Update lvgl.rst
  components/sensor/lvgl.rst
Labels: current

#4240 spell: Update host.rst
  components/host.rst
Labels: current

#4241 spell: Update atm90e32.rst
  components/sensor/atm90e32.rst
Labels: current

#4226 [bme280] Update configuration variables list
  components/sensor/bme280.rst
Labels: current

#4238 update jsn_sr04t page
  components/sensor/jsn_sr04t.rst
Labels: current

#4237 [bl0942] Update docs for accuracy fixes in esphome/esphome#7428
  components/sensor/bl0942.rst
Labels: has-parent, next

#4236 [LVGL] documentation for gradients and meter parts.
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: has-parent, next

#3890 [dsmr] Add internal 'telegram' text_sensor to support bridging
  components/sensor/dsmr.rst
Labels: has-parent, next

#4157 Add ATM90E32 Offset calibration
  components/sensor/atm90e32.rst
Labels: has-parent, next

#4119 Update max31856 docs to support thermocouple type selection
  components/sensor/max31856.rst
Labels: has-parent, next

#4166 [i2s_audio] Add more options to speakers and microphones
  components/microphone/i2s_audio.rst
  components/speaker/i2s_audio.rst
Labels: has-parent, next

#4202 [Modbus Controller] Added preference to change command retries
  components/modbus_controller.rst
Labels: has-parent, next

#4229 [contributing] Various additions & some minor copy fixes/tweaks
  guides/contributing.rst
  guides/images/update_branch.png
Labels: current

#4227 Described new esp32_camera frame buffer option.
  components/esp32_camera.rst
Labels: has-parent, next

#4243 2024.9.0b1
  Doxygen
  Makefile
  _static/changelog-2024.9.0.png
  _static/version
  changelog/2024.9.0.rst
  changelog/index.rst
  components/binary_sensor/udp.rst
  components/canbus/esp32_can.rst
  components/ch422g.rst
  components/climate/climate_ir.rst
  components/display/ili9xxx.rst
  components/display/rpi_dpi_rgb.rst
  components/display/st7701s.rst
  components/esp32_camera.rst
  components/host.rst
  components/light/esp32_rmt_led_strip.rst
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/microphone/i2s_audio.rst
  components/modbus_controller.rst
  components/number/tuya.rst
  components/pipsolar.rst
  components/sensor/atm90e32.rst
  components/sensor/bl0906.rst
  components/sensor/bl0942.rst
  components/sensor/bme280.rst
  components/sensor/bmp280.rst
  components/sensor/dsmr.rst
  components/sensor/images/athom-em2.png
  components/sensor/images/athom-em6.png
  components/sensor/images/ltr501-full.jpg
  components/sensor/images/ltr501-ui.png
  components/sensor/jsn_sr04t.rst
  components/sensor/ltr501.rst
  components/sensor/lvgl.rst
  components/sensor/max31856.rst
  components/sensor/udp.rst
  components/speaker/i2s_audio.rst
  components/statsd.rst
  components/switch/homeassistant.rst
  components/touchscreen/gt911.rst
  components/tuya.rst
  components/udp.rst
  components/voice_assistant.rst
  conf.py
  guides/cli.rst
  guides/contributing.rst
  guides/images/update_branch.png
  guides/supporters.rst
  images/bl0906.png
  images/ch422g.svg
  images/ltr501.jpg
  images/udp.svg
  index.rst
Labels: has-parent, beta

#4244 Add note about service -> action change
  components/api.rst
Labels: current

#4183 Update ble_presence.rst to include information about Manufacturer ID
  components/binary_sensor/ble_presence.rst
Labels: has-parent, next

#4247 Add a section about custom component deprecation
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/light/custom.rst
  components/output/custom.rst
  components/sensor/bmi160.rst
  components/sensor/custom.rst
  components/sensor/mpu6050.rst
  components/sensor/mpu6886.rst
  components/switch/custom.rst
  components/text_sensor/custom.rst
  custom/custom_component.rst
  custom/i2c.rst
  custom/spi.rst
  custom/uart.rst
  guides/contributing.rst
  index.rst
Labels: current

#4110 LVGL cookbook
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  cookbook/images/lvgl_cook_animimg_batt.gif
  cookbook/images/lvgl_cook_climate.png
  cookbook/images/lvgl_cook_clock.png
  cookbook/images/lvgl_cook_cover.png
  cookbook/images/lvgl_cook_flex_layout.png
  cookbook/images/lvgl_cook_font_batt.png
  cookbook/images/lvgl_cook_font_binstat.png
  cookbook/images/lvgl_cook_font_roboto_mdi.png
  cookbook/images/lvgl_cook_gauge.png
  cookbook/images/lvgl_cook_gradient_styles.png
  cookbook/images/lvgl_cook_keypad.png
  cookbook/images/lvgl_cook_pagenav.png
  cookbook/images/lvgl_cook_remligbut.png
  cookbook/images/lvgl_cook_statico.png
  cookbook/images/lvgl_cook_thermometer.png
  cookbook/images/lvgl_cook_thermometer_gauge.png
  cookbook/images/lvgl_cook_titlebar.png
  cookbook/images/lvgl_cook_volume.png
  cookbook/images/lvgl_cook_weather.png
  cookbook/lvgl.rst
  index.rst
  lint.py
Labels: next

#4251 2024.9.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.9.0.rst
  components/api.rst
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/light/custom.rst
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/output/custom.rst
  components/sensor/bmi160.rst
  components/sensor/custom.rst
  components/sensor/mpu6050.rst
  components/sensor/mpu6886.rst
  components/switch/custom.rst
  components/text_sensor/custom.rst
  conf.py
  cookbook/images/lvgl_cook_animimg_batt.gif
  cookbook/images/lvgl_cook_climate.png
  cookbook/images/lvgl_cook_clock.png
  cookbook/images/lvgl_cook_cover.png
  cookbook/images/lvgl_cook_flex_layout.png
  cookbook/images/lvgl_cook_font_batt.png
  cookbook/images/lvgl_cook_font_binstat.png
  cookbook/images/lvgl_cook_font_roboto_mdi.png
  cookbook/images/lvgl_cook_gauge.png
  cookbook/images/lvgl_cook_gradient_styles.png
  cookbook/images/lvgl_cook_keypad.png
  cookbook/images/lvgl_cook_pagenav.png
  cookbook/images/lvgl_cook_remligbut.png
  cookbook/images/lvgl_cook_statico.png
  cookbook/images/lvgl_cook_thermometer.png
  cookbook/images/lvgl_cook_thermometer_gauge.png
  cookbook/images/lvgl_cook_titlebar.png
  cookbook/images/lvgl_cook_volume.png
  cookbook/images/lvgl_cook_weather.png
  cookbook/lvgl.rst
  custom/custom_component.rst
  custom/i2c.rst
  custom/spi.rst
  custom/uart.rst
  guides/contributing.rst
  guides/supporters.rst
  index.rst
  lint.py
Labels: beta

#4254 2024.9.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.9.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4249 [ili9xxx] Add cs_pin config option
  components/display/ili9xxx.rst
  components/display/index.rst
  components/display/st7701s.rst
Labels: current

#4258 2024.9.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.9.0.rst
  components/display/ili9xxx.rst
  components/display/index.rst
  components/display/st7701s.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4259 Minor phrasing change
  guides/contributing.rst
Labels: current

#4007 Add openeth type to Ethernet controller
  components/ethernet.rst
Labels: has-parent, current

#3951 [nextion] add `skip_connection_handshake` attribute
  components/display/nextion.rst
Labels: has-parent, next

#4228 Haier climate documentation updated to reflect new code changes
  components/climate/haier.rst
  components/switch/haier.rst
Labels: has-parent, next

#4250 I2s comm fmt
  components/speaker/i2s_audio.rst
Labels: has-parent, next

#4253 [lvgl] Enhancements
  components/lvgl/index.rst
Labels: has-parent, next

#4089 Added TCA9555 driver docs
  components/tca9555.rst
Labels: has-parent, next

#4263 Fix minor grammatical error
  components/text_sensor/homeassistant.rst
Labels: current

#3822 Add on_announcement trigger to media_player doc
  components/media_player/index.rst
Labels: has-parent, current

#4269 fix typo 'post' to 'port'
  components/statsd.rst
Labels: current

#4272 2024.9.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.9.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4274 More ``homeassistant`` platform notes
  components/binary_sensor/homeassistant.rst
  components/number/homeassistant.rst
  components/sensor/homeassistant.rst
  components/switch/homeassistant.rst
  components/text_sensor/homeassistant.rst
  components/time/homeassistant.rst
  guides/getting_started_hassio.rst
Labels: current

#4256 [esp32_improv] Doc updates for esphome/esphome#7461
  components/esp32_improv.rst
Labels: has-parent, next

#4129 add reactive power to cse7766
  components/sensor/cse7766.rst
Labels: has-parent, next

#4277 Pylontech mostempr
  components/pylontech.rst
Labels: current

#4061 Added "and/or brightness (e.g. monochromatic)" to the Random Effect description
  components/light/index.rst
Labels: stale, current

#4276 Update inkplate6.rst
  components/display/inkplate6.rst
Labels: has-parent, next

#4275 Add remote transmitter triggers to support auto tx on/off
  components/remote_transmitter.rst
Labels: has-parent, next

#4261 [ch422g] Document additional pin support
  components/ch422g.rst
Labels: has-parent, next

#4280 Add clean_session as configurable option to the MQTT component
  components/mqtt.rst
Labels: has-parent, current

#4282 Revert "Add clean_session as configurable option to the MQTT component"
  components/mqtt.rst
Labels: current

#4284 Add clean_session as configurable option to the MQTT component
  components/mqtt.rst
Labels: has-parent, next

#3492 Add docs for Sharp GP2Y1010AU0F PM2.5 sensor
  components/sensor/gp2y1010au0f.rst
  images/gp2y1010au0f.png
  index.rst
Labels: has-parent, next

#4234 Make time dependency optional
  components/datetime/index.rst
Labels: has-parent, next

#4287 Make images consistent on home page
  changelog/2023.11.0.rst
  components/binary_sensor/gpio.rst
  components/output/gpio.rst
  components/switch/gpio.rst
  github.py
  images/ade7880.svg
  images/ade7953.svg
  images/bk72xx.svg
  images/bp1658cj.svg
  images/bp5758d.svg
  images/canbus.svg
  images/ch422g.svg
  images/cse7761.svg
  images/cse7766.svg
  images/dac.svg
  images/dac7678.svg
  images/dsmr.svg
  images/ektf2232.svg
  images/esp32.svg
  images/esp8266.svg
  images/gcja5.svg
  images/gp8403.svg
  images/gpio.svg
  images/hlw8012.svg
  images/http.svg
  images/i2s_audio.svg
  images/ili9341.svg
  images/ili9342.svg
  images/ili9481.svg
  images/ili9486.svg
  images/ili9488.svg
  images/libretiny.svg
  images/max44009.svg
  images/mcp230xx.svg
  images/mcp23sxx.svg
  images/mcp2515.svg
  images/mcp47a1.svg
  images/micronova.svg
  images/my9231.svg
  images/pca6416a.svg
  images/pellet.svg
  images/pin.svg
  images/pmsx003.svg
  images/psram.svg
  images/pzem004t.svg
  images/rp2040.svg
  images/rtl87xx.svg
  images/servo.svg
  images/sm16716.svg
  images/sm2135.svg
  images/sm2235.svg
  images/sm2335.svg
  images/sml.svg
  images/spi.svg
  images/st7796.svg
  images/stepper.svg
  images/uart.svg
  images/xl9535.svg
  index.rst
Labels: current

#4290 [m4e] Add note to create PR in esphome/esphome-devices
  guides/made_for_esphome.rst
Labels: current
