Repository esphome/esphome-docs, pull requests merged in 2024-05, with the labels that each got.

#2797 Remote receiver improvements
  components/remote_receiver.rst
Labels: has-parent, next, not-stale

#3801 bmp3xx SPI support added
  components/sensor/bmp3xx.rst
Labels: has-parent, next

#3532 Update time_based.rst - handle with last operation
  components/cover/time_based.rst
Labels: has-parent, next

#3626 web_server: Update documentation for changes in PR #6269
  web-api/index.rst
Labels: stale, has-parent, next

#3813 Order of esphome parameters corrected
  guides/getting_started_command_line.rst
Labels: current

#3816 Order of esphome parameters corrected II
  components/mqtt.rst
  guides/migrate_espeasy.rst
  guides/migrate_espurna.rst
Labels: current

#3815 External components: add documentation about path for git source
  components/external_components.rst
Labels: has-parent, next

#3818 Update bme680_bsec licence url
  components/sensor/bme680_bsec.rst
Labels: current

#3814 Update getting_started_command_line.rst
  guides/getting_started_command_line.rst
Labels: current

#3776 datetime typo
  components/datetime/index.rst
Labels: current

#3823 2024.5.0b1
  Doxygen
  Makefile
  _static/changelog-2024.5.0.png
  _static/version
  changelog/2024.5.0.rst
  changelog/index.rst
  components/cover/time_based.rst
  components/datetime/index.rst
  components/datetime/template.rst
  components/display/images/test_card.jpg
  components/display/index.rst
  components/display/waveshare_epaper.rst
  components/event/index.rst
  components/event/template.rst
  components/external_components.rst
  components/images/DFR0627.jpg
  components/index.rst
  components/light/index.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/bmp3xx.rst
  components/sensor/htu21d.rst
  components/sn74hc595.rst
  components/text_sensor/ethernet_info.rst
  components/valve/images/valve-ui.png
  components/valve/index.rst
  components/valve/template.rst
  components/weikai.rst
  conf.py
  guides/supporters.rst
  images/wk2168.jpg
  index.rst
  schema_doc.py
  web-api/index.rst
Labels: beta

#3707 Add IRK support to RSSI tracking with randomized MAC addresses
  components/sensor/ble_rssi.rst
Labels: has-parent, next

#3825 2024.5.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3827 2024.5.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3522 Update ota.rst - added OTA port for Beken chips
  components/ota.rst
Labels: current, not-stale

#2853 GDK101 support
  components/sensor/gdk101.rst
  components/sensor/images/gdk101.jpg
  images/gdk101.jpg
  index.rst
Labels: has-parent, next, not-stale

#3831 [CST816] Add support for Hynitron Microelectronics CST826 capacitive touch
  components/touchscreen/cst816.rst
Labels: has-parent, next

#3834 2024.5.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  components/ota.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3835 2024.5.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#3702 Use GPIOXX in sample configs
  components/cover/he60r.rst
  components/dfrobot_sen0395.rst
  components/micronova.rst
  components/output/my9231.rst
  components/output/sm16716.rst
  components/sensor/ld2410.rst
  components/touchscreen/cst226.rst
  components/touchscreen/cst816.rst
  components/touchscreen/gt911.rst
  components/touchscreen/lilygo_t5_47.rst
  components/touchscreen/xpt2046.rst
Labels: has-parent, current

#3837 [adc] Change 11dB references to 12dB
  components/sensor/adc.rst
Labels: has-parent, next

#3839 2024.5.0
  Doxygen
  Makefile
  _static/changelog-2024.5.0.png
  _static/version
  changelog/2024.5.0.rst
  changelog/index.rst
  components/cover/time_based.rst
  components/datetime/index.rst
  components/datetime/template.rst
  components/display/images/test_card.jpg
  components/display/index.rst
  components/display/waveshare_epaper.rst
  components/event/index.rst
  components/event/template.rst
  components/external_components.rst
  components/images/DFR0627.jpg
  components/index.rst
  components/light/index.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/adc.rst
  components/sensor/bmp3xx.rst
  components/sensor/htu21d.rst
  components/sn74hc595.rst
  components/text_sensor/ethernet_info.rst
  components/valve/images/valve-ui.png
  components/valve/index.rst
  components/valve/template.rst
  components/weikai.rst
  conf.py
  guides/supporters.rst
  images/wk2168.jpg
  index.rst
  schema_doc.py
  web-api/index.rst
Labels: current

#3799 [bedjet] Update docs for esphome/esphome#6633
  components/climate/bedjet.rst
Labels: has-parent, next

#3755 Add beken_spi_led_strip component
  components/light/beken_spi_led_strip.rst
  index.rst
Labels: has-parent, next

#3740 Mirage protocol
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#3714 docs: update wifi
  components/wifi.rst
Labels: has-parent, next

#3782 OTA docs update for esphome/esphome#6459
  components/ota.rst
Labels: has-parent, next

#3664 Add ADC multisampling
  components/sensor/adc.rst
Labels: has-parent, next

#3683 ENS160 I2C and SPI support
  components/sensor/ens160.rst
Labels: has-parent, next

#3571 INA228/INA229, INA238/INA239, INA237 power/energy/charge monitor (I2C, SPI) - Documentation
  components/sensor/images/ina228-full.jpg
  components/sensor/ina2xx.rst
  images/ina228.jpg
  images/ina2xx.jpg
  index.rst
Labels: has-parent, next

#3842 Update pca9685.rst
  components/output/pca9685.rst
Labels: current

#3553 add `touch_timeout` config option.
  components/touchscreen/index.rst
  components/touchscreen/lilygo_t5_47.rst
Labels: stale, has-parent, current

#3549 Update esp32_camera.rst with aspect ratios
  components/esp32_camera.rst
Labels: stale, current

#3186 Replace Sphinx search with Pagefind
  .github/workflows/docker.yml
  .github/workflows/lint.yml
  Makefile
  _static/custom.css
  _templates/layout.html
  _templates/search.html
  _templates/searchbox.html
  conf.py
  pagefind.yml
Labels: current, not-stale

#3850 2024.5.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3836 [ili9xxx] Document pixel_mode and init_sequence
  components/display/ili9xxx.rst
Labels: has-parent, next

#3852 2024.5.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3828 Add note that the PWM and RS485 versions of the A02YYUW are not supported
  components/sensor/a02yyuw.rst
Labels: current

#3841 Safe mode documentation and updates
  components/button/safe_mode.rst
  components/ota.rst
  components/safe_mode.rst
  components/switch/safe_mode.rst
  index.rst
Labels: has-parent, next

#3856 Fix typos in time-based cover documentation
  components/cover/time_based.rst
Labels: current

#3705 Fixed issues with text
  components/sensor/kamstrup_kmp.rst
Labels: stale, current

#3332 Document the modbus server feature
  components/modbus.rst
  components/modbus_controller.rst
Labels: has-parent, next, not-stale

#3857 Add on_safe_mode trigger to docs
  components/safe_mode.rst
  guides/automations.rst
Labels: has-parent, next

#3853 Allow output open drain
  components/sx1509.rst
Labels: has-parent, next

#3851 Documentation added for button and text_sensor components of Haier integration
  components/binary_sensor/haier.rst
  components/button/haier.rst
  components/climate/haier.rst
  components/text_sensor/haier.rst
Labels: has-parent, next

#3845 MPR121 gpio
  components/binary_sensor/mpr121.rst
Labels: has-parent, next

#3867 2024.5.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3868 Fixed attenuation values
  components/sensor/adc.rst
Labels: current

#3871 Fix incorrect naming of the AdaFruit MagTag display.
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3876 2024.5.4
  Doxygen
  Makefile
  _static/version
  changelog/2024.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3881 Webserver-mention-v3
  components/web_server.rst
Labels: current

#3777 Change datetime id names in examples
  components/datetime/index.rst
  components/datetime/template.rst
Labels: current

#3858 Make search results appear in a fixed window;
  _static/custom.css
  _templates/layout.html
  _templates/searchbox.html
Labels: current

#3877 [voice_assistant] Timer triggers
  components/voice_assistant.rst
Labels: has-parent, next

#3741 Webserver entity sorting
  components/alarm_control_panel/index.rst
  components/binary_sensor/index.rst
  components/button/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/datetime/index.rst
  components/fan/index.rst
  components/images/web_server-v3.png
  components/light/index.rst
  components/lock/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text/index.rst
  components/text_sensor/index.rst
  components/web_server.rst
Labels: has-parent, next

#3528 Series of Lite-On Light (ALS) and Proximity(PS) sensors - LTR-303, LTR-329, LTR-553, LTR-556, LTR-659, some others
  components/sensor/images/ltr303-full.jpg
  components/sensor/images/ltr303-spectral.png
  components/sensor/images/ltr303-ui.png
  components/sensor/ltr_als_ps.rst
  images/ltr-ps.jpg
  images/ltr303.jpg
  images/ltr329.jpg
  images/ltr559.jpg
  index.rst
Labels: has-parent, next

#3885 ancient version mentions removed + version sensor screenshot update
  components/climate/bang_bang.rst
  components/display/index.rst
  components/ethernet.rst
  components/text_sensor/images/version-ui.png
  components/text_sensor/version.rst
  components/wifi.rst
  guides/configuration-types.rst
  web-api/index.rst
Labels: current

#3891 The event type is accesible using the event_type variable.
  components/event/index.rst
Labels: current
