Repository esphome/esphome-docs, pull requests merged in 2024-11, with the labels that each got.

#4414 [spi_device] Rename mode to spi_mode
  components/spi.rst
Labels: has-parent, next

#4408 feat(MQTT): Add `enable`, `disable` and `enable_on_boot`
  components/mqtt.rst
Labels: has-parent, next

#4349 Add documentation for json component
  components/http_request.rst
  components/json.rst
  images/json.svg
  index.rst
Labels: current

#4413 [lvgl] Document multiple instance configs
  components/lvgl/index.rst
Labels: has-parent, next

#4416 Move pad_column to layout
  cookbook/lvgl.rst
Labels: current

#4417 2024.10.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4257 Update bme280 description humidity
  components/sensor/bme280.rst
Labels: current

#4412 Clarify MQTT docs when logging is disabled
  components/mqtt.rst
Labels: has-parent, current

#4406 Renames from ade7953 to ade7953_i2c
  components/cover/current_based.rst
Labels: current

#4421 Simplified bulky formulation about sensor filters
  components/sensor/index.rst
Labels: current

#3920 Change PWM image
  images/pwm.png
Labels: current, not-stale

#4346 Image path CANBUS update to absolute paths
  components/canbus/esp32_can.rst
  components/canbus/mcp2515.rst
Labels: current

#4224 Add SPI bus to spi_led_strip example
  components/light/spi_led_strip.rst
Labels: current

#4289 Update OtaUrl for migration from tasmota
  guides/migrate_sonoff_tasmota.rst
Labels: current

#3772 Link to blinds and water/gas meter projects
  guides/diy.rst
Labels: current

#4300 Update lvgl.rst - Prevent burn-in of LCD recipe fix
  cookbook/lvgl.rst
Labels: current

#3433 Add factory reset after 5 reboots example to cookbook
  cookbook/lambda_magic.rst
Labels: has-parent, current, not-stale

#4418 Document filter changes
  components/sensor/index.rst
Labels: has-parent, next

#4423 [http_request] Fix indentation
  components/http_request.rst
Labels: next

#4422 Update user manual links for HLK-LD2410 variants
  components/sensor/ld2410.rst
Labels: current

#3773 Move extensions to their own folder
  _extensions/components.py
  _extensions/github.py
  _extensions/seo.py
  _extensions/sitemap.py
  conf.py
Labels: stale, current

#4429 Split sphinx extensions up a little
  _extensions/apiref.py
  _extensions/github.py
  _extensions/tables.py
  conf.py
Labels: current

#3800 Documentation for new OpenTherm component
  components/images/opentherm-shield.png
  components/opentherm.rst
  images/opentherm.png
  index.rst
Labels: has-parent, next

#4430 Clean up some external links
  components/binary_sensor/rc522.rst
  components/display/ili9xxx.rst
  components/display/st7567.rst
  components/sensor/as3935.rst
  components/sensor/atm90e32.rst
  components/tm1651.rst
  components/weikai.rst
  cookbook/leak-detector-m5stickC.rst
Labels: current

#4431 Add note about referral links
  guides/contributing.rst
Labels: current

#4426 [i2s_audio] Document I2S speaker disable timeout option
  components/speaker/i2s_audio.rst
Labels: has-parent, next

#4231 [Modbus Controller] Document new automations `on_online` and `on_offline`
  components/modbus_controller.rst
Labels: has-parent, next, not-stale

#4438 2024.11.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4271 fixed i2c multiple bus sample code, adding missing "sensor:" sensor line. sample code will now validate.
  components/i2c.rst
Labels: current

#4392 Add 'always' as a valid time refresh value
  guides/configuration-types.rst
Labels: current

#4439 Update bme280.rst with CSB pin hint
  components/sensor/bme280.rst
Labels: current

#4436 Update link note
  guides/contributing.rst
Labels: current

#3689 Added info and link about host networking driver
  guides/faq.rst
Labels: stale, current

#4446 Add deadline for custom components
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/light/custom.rst
  components/output/custom.rst
  components/sensor/custom.rst
  components/switch/custom.rst
  components/text_sensor/custom.rst
  custom/custom_component.rst
  custom/i2c.rst
  custom/spi.rst
  custom/uart.rst
  guides/contributing.rst
Labels: current

#4450 2024.11.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/i2c.rst
  components/light/custom.rst
  components/output/custom.rst
  components/sensor/bme280.rst
  components/sensor/custom.rst
  components/switch/custom.rst
  components/text_sensor/custom.rst
  conf.py
  custom/custom_component.rst
  custom/i2c.rst
  custom/spi.rst
  custom/uart.rst
  guides/configuration-types.rst
  guides/contributing.rst
  guides/faq.rst
  guides/supporters.rst
Labels: beta

#4454 2024.11.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4442 [nextion] New trigger `on_buffer_overflow`
  components/display/nextion.rst
Labels: has-parent, next

#4459 2024.11.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4368 Add publish Action for Nextion components
  components/binary_sensor/nextion.rst
  components/sensor/nextion.rst
  components/switch/nextion.rst
  components/text_sensor/nextion.rst
Labels: has-parent, next

#4186 feat(WiFi): Add wifi.configure action
  components/wifi.rst
Labels: has-parent, next

#4466 Fix a bunch of broken links
  _redirects
  changelog/2022.1.0.rst
  changelog/2023.12.0.rst
  changelog/2023.9.0.rst
  changelog/v1.12.0.rst
  changelog/v1.13.0.rst
  changelog/v1.14.0.rst
  changelog/v1.15.0.rst
  guides/contributing.rst
  guides/diy.rst
Labels: current

#4465 docs for new switch binary sensor
  components/binary_sensor/switch.rst
  index.rst
Labels: has-parent, next

#4025 Waveshare 1.54in V2 B Display support
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4394 added Waveshare BWR Mode for the 7.5in Display
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4467 document new key trigger
  components/matrix_keypad.rst
Labels: has-parent, next

#4330 Add: Seeed Studio MR60FDA2 mmWave Sensor document
  components/images/seeed_mr60fda2.jpg
  components/seeed_mr60fda2.rst
  images/seeed_mr60fda2.jpg
  index.rst
Labels: has-parent, next

#4461 fix typo
  components/opentherm.rst
Labels: current

#4460 Alphabetize front page
  index.rst
Labels: current

#4262 Fix dashboard command in getting_started_command_line.rst
  guides/getting_started_command_line.rst
Labels: current

#4475 Clarify position in template cover docs
  components/cover/template.rst
Labels: current

#4476 2024.11.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.11.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4481 Update spi.rst - typo
  components/spi.rst
Labels: current

#4484 Update packages.rst (Fixed garage doors example)
  components/packages.rst
Labels: current
