Repository esphome/esphome-docs, pull requests merged in 2024-10, with the labels that each got.

#4291 [rp2040] Update note on platform version
  components/rp2040.rst
Labels: has-parent, next

#4292 2024.9.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.9.0.rst
  components/rp2040.rst
  conf.py
  guides/supporters.rst
Labels: current

#4297 [esp32] Update doc for new ``ignore_efuse_custom_mac`` config var
  components/esp32.rst
Labels: has-parent, next

#4308 even parity is required for CSE7766
  components/sensor/cse7766.rst
Labels: has-parent, current

#4286 [audio_dac] [aic3204] Add new component + platform docs
  components/audio_dac/aic3204.rst
  components/audio_dac/index.rst
  components/index.rst
  images/aic3204.svg
  images/audio_dac.svg
  index.rst
Labels: has-parent, next

#4305 Document meter changes
  components/lvgl/widgets.rst
Labels: has-parent, next

#2598 Add docs for Grove Multichannel Gas Sensor V2
  components/sensor/grove_gas_mc_v2.rst
  images/grove-gas-mc-v2.png
  index.rst
Labels: has-parent, next

#4310 [lvgl] Update dropdown and encoder docs
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: has-parent, next

#3905 [web_server] grouping
  components/alarm_control_panel/index.rst
  components/binary_sensor/index.rst
  components/button/index.rst
  components/climate/index.rst
  components/cover/index.rst
  components/datetime/index.rst
  components/fan/index.rst
  components/light/index.rst
  components/lock/index.rst
  components/number/index.rst
  components/select/index.rst
  components/sensor/index.rst
  components/switch/index.rst
  components/text/index.rst
  components/text_sensor/index.rst
  components/update/index.rst
  components/valve/index.rst
  components/web_server.rst
Labels: has-parent, next

#4105 Initial NPI-19 pressure sensor documentation
  components/sensor/images/npi19.jpg
  components/sensor/npi19.rst
  images/npi19.jpg
  index.rst
Labels: has-parent, next

#4092 Add NAU7802 docs
  components/sensor/images/nau7802.png
  components/sensor/nau7802.rst
  images/nau7802.jpg
  index.rst
Labels: has-parent, next

#4312 [cst816] document skip_probe option
  components/touchscreen/cst816.rst
Labels: has-parent, next

#4315 Document `condition:` config for binary sensor
  components/binary_sensor/template.rst
Labels: has-parent, next

#4320 Add tca9555 to index
  images/tca9555.svg
  index.rst
Labels: next

#4324 Update midea.rst
  components/climate/midea.rst
Labels: current

#4317 Document `pillow` requirements change
  components/font.rst
Labels: has-parent, next

#4326 Remove outdated limitation
  components/sensor/max31856.rst
Labels: current

#4328 [udp] Delete http_request_sensor.rst
  cookbook/http_request_sensor.rst
Labels: has-parent, current

#4302 update: actions.rst typo
  automations/actions.rst
Labels: current

#4329 Update color_temperature.rst
  components/light/color_temperature.rst
Labels: current

#4332 [web_server] event component grouping
  components/event/index.rst
Labels: has-parent, next

#4338 2024.10.0b2
  .github/workflows/component-image.yml
  Doxygen
  Makefile
  _static/version
  automations/actions.rst
  changelog/2024.10.0.rst
  components/climate/midea.rst
  components/event/index.rst
  components/light/color_temperature.rst
  components/sensor/max31856.rst
  conf.py
  cookbook/http_request_sensor.rst
  guides/supporters.rst
Labels: beta

#4339 Update ltr501.rst
  components/sensor/ltr501.rst
Labels: current

#4316 Document new conditions shortcuts
  automations/actions.rst
Labels: has-parent, next

#4255 Add documentation for TC74
  components/sensor/images/tc74-full.jpg
  components/sensor/tc74.rst
  images/tc74.jpg
  index.rst
Labels: has-parent, next

#4235 Added ring and gauge basic shapes
  components/display/index.rst
Labels: has-parent, next

#4336 [lvgl] Document draw_rounding
  components/lvgl/index.rst
Labels: has-parent, next

#4335 [qspi_dbi] Rename from qspi_amoled
  _redirects
  components/display/qspi_dbi.rst
  index.rst
Labels: has-parent, next

#4299 Documentation for Analog Devices MAX17043 battery fuel gauge
  components/sensor/images/max17043.jpg
  components/sensor/max17043.rst
  images/max17043.jpg
  index.rst
Labels: has-parent, next

#4331 [light] Add ``initial_state`` documentation
  components/light/index.rst
Labels: has-parent, next

#4343 Document Speaker volume set action
  automations/all_actions.rst
  components/speaker/index.rst
Labels: has-parent, next

#4334 [axs15231] Add AXS15231 touchscreen
  components/touchscreen/axs15231.rst
  images/axs15231.svg
  index.rst
Labels: has-parent, next

#4344 [lvgl] Document selection by text for roller and dropdown
  components/lvgl/widgets.rst
Labels: has-parent, next

#4348 Corrected incorrect descriptions
  components/number/modbus_controller.rst
Labels: current

#4350 Update tca9555.rst fix link
  components/tca9555.rst
Labels: current

#4357 Add some breaking change text to 2024.10.0 changelog
  changelog/2024.10.0.rst
Labels: current

#4264 bump sphinx
  requirements.txt
Labels: current

#4225 Add Sphinx collapsible and tab plugins
  _static/custom.css
  conf.py
  requirements.txt
Labels: current

#4359 add collapse and tab examples to guides/contributing.rst
  guides/contributing.rst
Labels: current

#4358 Update documentation for custom MAC support on Arduino
  components/esp32.rst
Labels: has-parent, next

#4364 Fix typo in esp32.rst
  components/esp32.rst
Labels: next

#4366 2024.10.1
  Doxygen
  Makefile
  _static/version
  changelog/2024.10.0.rst
  components/esp32.rst
  conf.py
  guides/supporters.rst
Labels: current

#4365 Update changelog for custom MAC address support
  changelog/2024.10.0.rst
Labels: current

#4363 feat(MQTT): Add subscribe QoS to discovery
  components/mqtt.rst
Labels: has-parent, next

#4367 Tabs label CSS dark mode fix
  _static/custom.css
Labels: current

#4356 Update i2c.rst
  components/i2c.rst
  components/i2c_device.rst
Labels: has-parent, current

#4370 Revert "Update i2c.rst"
  components/i2c.rst
  components/i2c_device.rst
Labels: current

#4371 I2c device docs
  components/i2c.rst
  components/i2c_device.rst
Labels: has-parent, next

#4372 Try add ref to rebase/force push box
  guides/contributing.rst
Labels: current

#4373 Allow binary packages installed in dockerfile
  Dockerfile
Labels: current

#4374 Build docker image on PRs that touch the docker files
  .github/workflows/docker.yml
Labels: current

#4375 Use python 3.12 on Netlify and CI
  .github/workflows/lint.yml
  netlify.toml
Labels: current

#4377 2024.10.2
  Doxygen
  Makefile
  _static/version
  changelog/2024.10.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4378 [speaker] Document mute actions and audio dac support
  components/speaker/i2s_audio.rst
  components/speaker/index.rst
Labels: has-parent, next

#4376 Set up dependabot to monitor python packages
  .github/dependabot.yml
Labels: current

#4386 [M4E] Add `id` requirement
  components/packages.rst
  guides/made_for_esphome.rst
Labels: current

#4388 Fix typo in contributing.rst
  guides/contributing.rst
Labels: current

#4390 Update HA getting started to use ESPHome Device Compiler name
  guides/getting_started_hassio.rst
Labels: next

#4387 [media_player] Document paused and announcing conditions
  components/media_player/index.rst
Labels: has-parent, next

#4393 Search improvements
  Makefile
  _templates/searchbox.html
  pagefind.yml
Labels: current

#4395 Be less aggressive in maintaining focus on search box
  _templates/searchbox.html
Labels: current

#4396 [media_player] add new conditions to all conditions list
  automations/all_conditions.rst
Labels: has-parent, next

#4347 add `qrcode` lvgl widget
  components/lvgl/widgets.rst
Labels: has-parent, next

#4397 [http_request] Add status_code note
  components/http_request.rst
Labels: has-parent, next

#4389 Add polling_interval and its usage to ethernet.rst
  components/ethernet.rst
Labels: has-parent, next

#4281 Update Mopeka docs to include new optional sensors and configuration
  components/sensor/mopeka_pro_check.rst
Labels: has-parent, next

#4401 [http_request] Document on_error trigger
  components/http_request.rst
Labels: has-parent, next

#4400 [es8311]] Document new ES8311 component
  components/audio_dac/es8311.rst
  images/es8311.svg
  index.rst
Labels: has-parent, next

#4403 Document touchscreen changes
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
Labels: has-parent, next

#4245 [font] Add documentation for glyphsets
  components/font.rst
Labels: has-parent, next

#4405 Update ld2410.rst
  components/sensor/ld2410.rst
Labels: current
