Repository esphome/esphome-docs, pull requests merged in 2024-01, with the labels that each got.

#3508 Update AHT10 docs to show support for AHT30 sensor
  components/sensor/aht10.rst
Labels: has-parent, current

#3506 medisana scale
  guides/diy.rst
Labels: current

#3487 Update the touchscreen document's
  components/touchscreen/index.rst
  components/touchscreen/xpt2046.rst
Labels: has-parent, current

#3518 Update pulse_meter.rst
  components/sensor/pulse_meter.rst
Labels: current

#3521 Hint for using 433Mhz transmitter
  components/remote_transmitter.rst
Labels: current

#3516 Add questionmark to default glyphs.
  components/display/index.rst
Labels: has-parent, next

#3519 pylontech: document voltage_low and voltage_high correctly
  components/pylontech.rst
Labels: has-parent, current

#3496 Extends UART change at runtime to ESP8266
  components/uart.rst
Labels: has-parent, next

#3517 Extend i2s config options
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#3524 removed spelling error in neopixelbus documentation, line 16
  components/light/neopixelbus.rst
Labels: current

#3273 Add BME280 SPI Component
  components/sensor/bme280.rst
Labels: has-parent, next

#3342 Documentation for WireGuard actions and conditions
  components/wireguard.rst
  guides/automations.rst
Labels: has-parent, next

#3530 Update ota.rst
  components/ota.rst
Labels: current

#3536 Update ili9xxx.rst
  components/display/ili9xxx.rst
Labels: current

#3538 clarify the use of "on_update" and some other small textual updates.
  components/touchscreen/index.rst
Labels: current

#3539 document cse7766 changes
  components/sensor/cse7766.rst
Labels: has-parent, next

#3541 2023.12.6
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3542 add new display model and option to set 18Bit color mode.
  components/display/ili9xxx.rst
  index.rst
Labels: has-parent, next

#3544 Add triangle shapes to display component
  components/display/index.rst
Labels: has-parent, next

#3490 [Fingerprint_grow] Add description for on_finger_scan_misplaced and on_finger_scan_start triggers
  components/fingerprint_grow.rst
Labels: has-parent, next

#3537 document continuous option
  components/display/index.rst
Labels: has-parent, next

#3526 Add NFC binary sensor platform doc
  components/binary_sensor/nfc.rst
  components/images/pn7150-full.jpg
  components/images/pn716x-full.jpg
  components/pn7150.rst
  components/pn7160.rst
  images/nfc.png
  index.rst
Labels: has-parent, next

#3547 2023.12.7
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3471 Add docs for VEML3235 lux sensor
  components/sensor/images/veml3235.jpg
  components/sensor/veml3235.rst
  images/veml3235.jpg
  index.rst
Labels: has-parent, next

#3387 Add documentation for MQTT X.509 client certificates.
  components/mqtt.rst
Labels: has-parent, next

#3357 Add doc for Honeywell HumidIcon (I2C HIH series) Temperature & Humidity sensor
  components/sensor/honeywell_hih_i2c.rst
  components/sensor/images/honeywellhih.jpg
  images/honeywellhih.jpg
  index.rst
Labels: has-parent, next

#3216 Add documentation for combination sensor
  components/sensor/combination.rst
  components/sensor/kalman_combinator.rst
  index.rst
Labels: has-parent, next

#3557 bluetooth_proxy.rst: Fix typo
  components/bluetooth_proxy.rst
Labels: current

#3454 Document quad spi config
  components/spi.rst
Labels: has-parent, next

#3559 Add AM2120 model to dht
  components/sensor/dht.rst
Labels: has-parent, next

#3171 Add Waveshare epd2.13v3
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3552 OTA version documentation
  components/ota.rst
Labels: has-parent, next

#3560 2023.12.8
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3561 remove serial command text
  components/sensor/pm1006.rst
Labels: has-parent, current

#3564 Update MCP3008 Formatting & Readability
  components/sensor/mcp3008.rst
Labels: current

#3565 2023.12.9
  Doxygen
  Makefile
  _static/version
  changelog/2023.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#3563 Document Pico-ResTouch-LCD-3.5 support for ili9xxx component
  components/display/ili9xxx.rst
Labels: has-parent, next

#3567 Made for ESPHome doc updates
  guides/made_for_esphome.rst
Labels: current

#3576 Olimex POE WROVER uses GPIO0 for clock
  components/ethernet.rst
Labels: current

#3578 Update inkplate6.rst
  components/display/inkplate6.rst
Labels: current

#3580 waveshare_eink_color: add 2.7inch B and V2
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3582 Update pulse_meter.rst
  components/sensor/pulse_meter.rst
Labels: current

#3478 Brush up modbus docs
  components/binary_sensor/modbus_controller.rst
  components/modbus.rst
  components/modbus_controller.rst
  components/number/modbus_controller.rst
  components/output/modbus_controller.rst
  components/select/modbus_controller.rst
  components/sensor/modbus_controller.rst
  components/switch/modbus_controller.rst
  components/text_sensor/modbus_controller.rst
Labels: current
