Repository esphome/esphome-docs, pull requests merged in 2025-01, with the labels that each got.

#4549 Fix invalid link
  components/sensor/as7341.rst
Labels: current

#4553 fix dashboard start command
  guides/getting_started_command_line.rst
Labels: current

#4557 esphome.rst: Show on_boot/on_Shutdown priority as list item
  components/esphome.rst
Labels: current

#4542 Update remote_receiver.rst
  components/remote_receiver.rst
Labels: current

#4564 Easier to find Devices Database
  index.rst
Labels: current

#4565 Fix typo in endstop.rst
  components/cover/endstop.rst
Labels: current

#4527 Rename 'no2' to 'nitrogen_dioxide' in Grove Gas MC V2 docs
  components/sensor/grove_gas_mc_v2.rst
Labels: current

#4559 [lvgl] Remove default state
  components/lvgl/widgets.rst
Labels: has-parent, next

#4570 [lvgl] Document `lvgl.page.is_showing`
  components/lvgl/index.rst
Labels: has-parent, next

#4522 [lvgl] Document auto_clear_enabled changes
  components/display/index.rst
  components/display/pvvx_mithermometer.rst
  components/display/qspi_dbi.rst
  components/display/rpi_dpi_rgb.rst
  components/display/st7701s.rst
Labels: has-parent, next

#4341 Log level
  guides/getting_started_command_line.rst
Labels: has-parent, next

#4578 Getting started guide updates
  guides/getting_started_command_line.rst
  guides/getting_started_hassio.rst
  guides/images/addon.png
  guides/images/dashboard_empty.png
  guides/images/dashboard_states.png
  guides/images/hassio_addon.png
Labels: current

#4550 [nextion] Add ``set_brightness`` action + various copy fixes
  components/display/nextion.rst
Labels: has-parent, next

#4506 Document image changes
  components/animation.rst
  components/image.rst
  components/lvgl/widgets.rst
  cookbook/lvgl.rst
Labels: has-parent, next

#4517 Adds Alarm Control Panel REST API documentation
  web-api/index.rst
Labels: has-parent, next

#4580 Update i2c.rst
  components/i2c.rst
Labels: has-parent, current

#4548 [uptime] Document text_sensor
  components/sensor/uptime.rst
  components/text_sensor/uptime.rst
Labels: has-parent, next

#4582 Inkplate 10
  components/display/inkplate6.rst
Labels: current

#4581 Document ili9xxx changes
  components/display/ili9xxx.rst
Labels: has-parent, next

#4534 Document new es7210 ADC component
  components/es7210.rst
  images/es7210.svg
  index.rst
Labels: has-parent, next

#4587 2024.12.3
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4589 2024.12.4
  Doxygen
  Makefile
  _static/version
  changelog/2024.12.0.rst
  conf.py
Labels: current

#4399 Update send_wait_time text to reflect modbus timing changes
  components/modbus.rst
Labels: stale, has-parent, next

#4595 [image] Rename "use_transparency" to "transparency"
  components/animation.rst
  components/image.rst
  components/online_image.rst
Labels: has-parent, next

#4593 FAQ updates/rewrite
  guides/faq.rst
  guides/getting_started_hassio.rst
Labels: current

#4588 [audio_adc] Add/update docs for new component
  components/audio_adc/es7210.rst
  components/audio_adc/index.rst
  components/index.rst
  images/audio_adc.svg
  index.rst
Labels: has-parent, next

#4590 uptime text sensor docs
  components/text_sensor/uptime.rst
Labels: has-parent, next

#4583 [es8156] Add docs for ES8156 audio DAC
  components/audio_dac/es8156.rst
  components/audio_dac/index.rst
  images/es8156.svg
  index.rst
Labels: has-parent, next

#4596 Update api.rst - lambda example for condition connected
  components/api.rst
Labels: current

#4598 [custom] Remove platforms
  _redirects
  changelog/v1.14.0.rst
  components/binary_sensor/custom.rst
  components/climate/custom.rst
  components/cover/custom.rst
  components/esphome.rst
  components/light/custom.rst
  components/output/custom.rst
  components/sensor/custom.rst
  components/sensor/misc/custom-empty.h
  components/switch/custom.rst
  components/text_sensor/custom.rst
  cookbook/lambda_magic.rst
  custom/custom_component.rst
  custom/i2c.rst
  custom/index.rst
  custom/spi.rst
  custom/uart.rst
  guides/contributing.rst
  guides/diy.rst
  index.rst
  schema_doc.py
Labels: has-parent, next

#4535 Add: Human Presence and Target Count to the Seeed Studio MR60BHA2
  components/seeed_mr60bha2.rst
Labels: has-parent, next

#4597 [es7243e] Add docs for ES7243E audio ADC
  components/audio_adc/es7243e.rst
  images/es7243e.svg
  index.rst
Labels: has-parent, next

#4599 [esp32] Set logger default interface for C6
  components/logger.rst
Labels: has-parent, next

#4591 [ads1115] Add sample rate control
  components/sensor/ads1115.rst
Labels: has-parent, next

#4600 [online_image] Binary BMP support
  components/online_image.rst
Labels: has-parent, next

#4445 Add useful template examples for both text and numerical sensors
  components/sensor/template.rst
  components/text_sensor/template.rst
Labels: stale, has-parent, current

#4002 [esp32_ble_server] Create custom BLE services, characteristics and descriptors
  components/esp32_ble_server.rst
Labels: has-parent, next

#4516 Mac local installation update
  guides/installing_esphome.rst
Labels: current

#4625 fix spelling
  components/sensor/kamstrup_kmp.rst
Labels: current
