Repository esphome/esphome-docs, pull requests merged in 2025-05, with the labels that each got.

#4858 [micro_wake_word] Document new microWakeWord features
  components/micro_wake_word.rst
Labels: has-parent, next

#4860 [voice_assistant] document micro_wake_word configuration option
  components/voice_assistant.rst
Labels: has-parent, next

#4232 [climate] Add gree model `YAG`
  components/climate/climate_ir.rst
Labels: has-parent, next, not-stale

#4734 Vl53l0x timing budget
  components/sensor/vl53l0x.rst
Labels: has-parent, current

#4865 Add workflow to check mismatching labels
  .github/workflows/check-labels.yml
Labels: current

#4864 Vl53l0x timing budget (#4734)
  components/sensor/vl53l0x.rst
Labels: has-parent, next

#4485 Added docs for new `to_ntc_*` sensor filter
  components/sensor/index.rst
  components/sensor/sensor-filter-to_ntc_resistance.rst
  components/sensor/sensor-filter-to_ntc_temperature.rst
  conf.py
Labels: has-parent, next, awaiting-parent, not-stale

#4812 Document cpu_frequency config and debug
  components/debug.rst
  components/esp32.rst
Labels: has-parent, next

#4869 Add GDEY0583T81 support
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4878 Uppercase `H` in `Hz`
  components/ethernet.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/sensor/ld2420.rst
  components/sensor/mcp9600.rst
  components/sensor/sht3xd.rst
Labels: current

#4643 Document packet_transport and udp changes
  components/binary_sensor/packet_transport.rst
  components/index.rst
  components/packet_transport/index.rst
  components/sensor/packet_transport.rst
  components/udp.rst
  images/packet_transport.svg
Labels: has-parent, next

#4857 Update diy.rst
  guides/diy.rst
Labels: current

#4827 sort esp32 variants alphabetically
  components/canbus/esp32_can.rst
  components/light/esp32_rmt_led_strip.rst
  components/light/neopixelbus.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
  components/uart.rst
Labels: current

#4828 add `test.esp32-s3-{ard,idf}.yaml` files to required tests
  guides/contributing.rst
Labels: current

#4750 Update title to reflect sensor capabilities
  components/sensor/ens160.rst
Labels: current

#4526 Use ESPHome logo on readme page according to theme (light/dark)
  README.md
  images/logo-docs-on-dark.svg
Labels: current

#4871 [esp32_ble_server] Document appearance field
  components/esp32_ble_server.rst
Labels: has-parent, next

#4883 [packages] Document revised syntax
  components/packages.rst
Labels: has-parent, next

#4876 [lvgl] document lvgl.widget.refresh
  components/lvgl/index.rst
Labels: has-parent, next

#4877 [image] Document MDIL and Memory icons
  components/image.rst
Labels: has-parent, next

#4645 document UART packet transport
  components/packet_transport/index.rst
  components/packet_transport/uart.rst
  components/packet_transport/udp.rst
  components/uart.rst
  components/udp.rst
Labels: has-parent, next

#4743 Document cst226 binary sensor
  components/touchscreen/cst226.rst
Labels: has-parent, next

#4499 [nextion] Adds a command pacer with `command_spacing` attribute
  components/display/nextion.rst
Labels: has-parent, next, not-stale

#4886 scd4x: new datasheet location
  components/sensor/scd4x.rst
Labels: current

#4735 Store documents for sensor filters in separate files and sort entries
  changelog/v1.14.0.rst
  components/sensor/index.rst
  components/sensor/sensor-filter-calibrate_linear.rst
  components/sensor/sensor-filter-calibrate_polynomial.rst
  components/sensor/sensor-filter-clamp.rst
  components/sensor/sensor-filter-debounce.rst
  components/sensor/sensor-filter-delta.rst
  components/sensor/sensor-filter-exponential_moving_average.rst
  components/sensor/sensor-filter-filter_out.rst
  components/sensor/sensor-filter-heartbeat.rst
  components/sensor/sensor-filter-lambda.rst
  components/sensor/sensor-filter-max.rst
  components/sensor/sensor-filter-median.rst
  components/sensor/sensor-filter-min.rst
  components/sensor/sensor-filter-multiply.rst
  components/sensor/sensor-filter-offset.rst
  components/sensor/sensor-filter-or.rst
  components/sensor/sensor-filter-quantile.rst
  components/sensor/sensor-filter-round.rst
  components/sensor/sensor-filter-round_to_multiple_of.rst
  components/sensor/sensor-filter-skip_initial.rst
  components/sensor/sensor-filter-sliding_window_moving_average.rst
  components/sensor/sensor-filter-throttle.rst
  components/sensor/sensor-filter-throttle_average.rst
  components/sensor/sensor-filter-timeout.rst
  conf.py
Labels: current

#4890 Move contributing page to developers.esphome.io
  _redirects
  changelog/2025.2.0.rst
  changelog/v1.13.0.rst
  components/external_components.rst
  components/index.rst
  components/sensor/ade7953.rst
  components/sensor/bl0940.rst
  components/sensor/pzem004t.rst
  components/sensor/pzemac.rst
  components/sensor/pzemdc.rst
  guides/contributing.rst
  guides/faq.rst
  guides/installing_esphome.rst
  index.rst
Labels: current

#4737 Fix typo for PCF8563 and PCF85063
  components/time/pcf85063.rst
  components/time/pcf8563.rst
Labels: stale, current

#4732 Clarify the time unit that a template should return
  components/deep_sleep.rst
Labels: current

#4896 Fix burger menu icon open state
  _static/index.css
Labels: current

#4894 Fix some formatting
  changelog/2021.11.0.rst
  changelog/2021.12.0.rst
  changelog/v1.8.0.rst
  components/binary_sensor/status.rst
  components/canbus/index.rst
  components/climate/haier.rst
  components/logger.rst
  components/lvgl/index.rst
  components/modbus_controller.rst
  components/mqtt.rst
  components/output/ledc.rst
  components/power_supply.rst
  components/sensor/dsmr.rst
  components/sensor/index.rst
  components/sensor/ld2420.rst
  components/sensor/ltr501.rst
  components/sensor/ltr_als_ps.rst
  components/sensor/npi19.rst
  components/sensor/pulse_counter.rst
  components/sensor/pulse_meter.rst
  components/sensor/sen5x.rst
  components/sensor/ultrasonic.rst
  components/sprinkler.rst
  components/text_sensor/index.rst
  components/wifi.rst
  guides/configuration-types.rst
  guides/getting_started_command_line.rst
  index.rst
Labels: current

#4881 Document software_coexistence for esp32_ble_tracker
  components/esp32_ble_tracker.rst
Labels: has-parent, next

#4810 ATM90E32 Semi-automatic Calibration & Status Fields
  components/sensor/atm90e32.rst
Labels: has-parent, next

#4898 [sound_level] Document new sound level sensor
  components/index.rst
  components/sensor/sound_level.rst
Labels: has-parent, next

#4900 2025.4.2
  Doxygen
  Makefile
  _static/version
  changelog/2025.4.0.rst
  components/lvgl/widgets.rst
  conf.py
  guides/supporters.rst
Labels: current

#4540 MQTT: Added fan direction support
  components/fan/index.rst
Labels: has-parent, next

#4901 Regenerate 2025.4.0 changelog with new dependency section
  changelog/2025.4.0.rst
Labels: current

#4902 [i2s_audio] Document new DC offset correction option
  components/microphone/i2s_audio.rst
Labels: has-parent, next

#4882 [gps] document hdop and update_interval (#3140)
  components/gps.rst
Labels: has-parent, next

#4749 Tuya Select - Add int_datapoint option
  components/select/tuya.rst
Labels: has-parent, next

#4903 Fix URL error in adc.rst
  components/sensor/adc.rst
Labels: current

#4905 Update ac_dimmer.rst
  components/output/ac_dimmer.rst
Labels: current

#4907 [online_image] BMP 24-bit support
  components/online_image.rst
Labels: has-parent, next

#4745 [mipi_spi] Add docs
  components/display/mipi_spi.rst
  components/index.rst
Labels: has-parent, next

#4908 Update devcontainer
  .devcontainer/devcontainer.json
Labels: current

#4910 2025.5.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2025.5.0.rst
  conf.py
Labels: beta

#4164 [max7219digit] add actions for the common display functions.
  components/display/max7219digit.rst
Labels: has-parent, next, not-stale

#4912 Sensor docs Required -> Optional
  components/sensor/ccs811.rst
  components/sensor/dps310.rst
  components/sensor/ee895.rst
  components/sensor/ens160.rst
  components/sensor/hte501.rst
  components/sensor/hyt271.rst
  components/sensor/mhz19.rst
  components/sensor/ms5611.rst
  components/sensor/ms8607.rst
  components/sensor/senseair.rst
  components/sensor/sgp30.rst
  components/sensor/shtcx.rst
  components/sensor/t6615.rst
Labels: has-parent, next

#4859 Fix strftime example
  components/time/index.rst
Labels: current

#4918 Schema 2025 5
  components/esphome.rst
  schema_doc.py
Labels: next

#4919 2025.5.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2025.5.0.rst
  components/esphome.rst
  components/sensor/as3935.rst
  components/sensor/ens210.rst
  components/time/index.rst
  conf.py
  guides/supporters.rst
  schema_doc.py
Labels: beta

#4923 2025.5.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2025.5.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4924 2025.5.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2025.5.0.rst
  conf.py
Labels: beta

#4926 Remove doxygen api docs from main website
  Dockerfile
  Makefile
  _extensions/apiref.py
  _redirects
  components/binary_sensor/modbus_controller.rst
  netlify.toml
  script/bump-version.py
Labels: current

#4697 CUBIC CM1106 Single Beam NDIR CO2 Sensor Module
  components/index.rst
  components/sensor/cm1106.rst
  components/sensor/images/cm1106.png
  images/cm1106.png
Labels: has-parent, next

#4930 Remove atom lite from recommended bluetooth proxy
  projects/installer.html
Labels: current

#4914 [lvgl] update buffer_size docs
  components/lvgl/index.rst
Labels: has-parent, next

#4916 [lvgl] Add content styling to tabview
  components/lvgl/widgets.rst
Labels: has-parent, next

#4724 [usb_uart] Document USB Host mode UART
  components/index.rst
  components/usb_host.rst
  components/usb_uart.rst
  images/usb.svg
Labels: has-parent, next

#4931 Add ready made project: HA Voice PE
  _static/projects/voice-assistant/home-assistant-voice.png
  projects/installer.html
Labels: current

#4933 [modbus_controller] add assumed_state option to switch (Fix 6613)
  components/switch/modbus_controller.rst
Labels: has-parent, next

#4937 Update ready-made projects links to right YAML
  projects/installer.html
Labels: current

#4943 [esp32] Add c5, c6 and p4 to docs
  components/esp32.rst
  components/logger.rst
Labels: next

#4756 [sx1509] add docs for key support
  components/sx1509.rst
Labels: has-parent, next

#4951 [lvgl] Add missing style properties
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: current

#4949 2025.5.1
  Makefile
  _static/version
  changelog/2025.5.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4779 [cookbook/lvgl] Fix lingering references to use_transparency for images
  components/lvgl/widgets.rst
  cookbook/lvgl.rst
Labels: stale, has-parent, current

#4950 Fix RP2040 (Pico W) chip documentation (CYW43455 -> CYW43439)
  components/rp2040.rst
Labels: current

#4913 [esp32_ble_server] Fix broken code examples
  components/esp32_ble_server.rst
Labels: current

#4873 Add note to clarify publish_state() method
  components/switch/index.rst
Labels: current

#4897 Broken links in See Also
  components/json.rst
Labels: current

#4301 Web_server-detail-all
  web-api/index.rst
Labels: has-parent, current, not-stale

#4953 Update speaker icon for dark mode
  components/index.rst
Labels: current

#4915 [ac_dimmer] Add notice about pin schema for zero cross pin reuse
  components/output/ac_dimmer.rst
Labels: current

#4775 Update packages.rst
  components/packages.rst
Labels: current

#4945 [speaker mediaplayer] add option for initial volume
  components/media_player/speaker.rst
Labels: has-parent, next

#4817 Improve Sensirion SPS30 documentation
  components/sensor/images/sps30-wiring.png
  components/sensor/sps30.rst
Labels: current

#4656 Update tm1637.rst
  components/display/tm1637.rst
Labels: current

#4689 Remove `rmt_channel` from esp32_rmt_led_strip example
  components/light/esp32_rmt_led_strip.rst
Labels: current, awaiting-feedback, integration: esp32_rmt_led_strip

#4842 Update index.rst Solar inverters section
  components/index.rst
Labels: current

#4799 modbus_controller: fix skip_updates interval description
  components/binary_sensor/modbus_controller.rst
  components/number/modbus_controller.rst
  components/select/modbus_controller.rst
  components/sensor/modbus_controller.rst
  components/switch/modbus_controller.rst
  components/text_sensor/modbus_controller.rst
Labels: current

#4911 [alarm_control_panel] Document new `auto_bypass` option for template alarm control panel binary sensors
  components/alarm_control_panel/template.rst
Labels: has-parent, next

#4488 Added flip x and y for inkplate6
  components/display/inkplate6.rst
Labels: has-parent, next
