Repository esphome/esphome-docs, pull requests merged in 2025-08, with the labels that each got.

#5156 [image] Update schema docs
  components/image.rst
Labels: next

#5164 [nrf52] adc doc
  components/sensor/adc.rst
Labels: component: adc, has-parent, next, component: nrf52, component: zephyr

#4086 Add documentation for the new espnow component
  components/espnow.rst
  components/index.rst
  images/esp-now.svg
Labels: has-parent, next, not-stale, component: espnow

#5180 [esp32] Add option to enable execution from PSRAM
  components/esp32.rst
Labels: component: debug, has-parent, next, component: esp32, component: psram, component: lvgl, component: mipi_spi

#5195 [ld2450] fix syntax error
  components/sensor/ld2450.rst
Labels: current

#5030 [ld2450] Add timeout clarification
  components/sensor/ld2450.rst
Labels: current

#5093 ms5611: Remove 404 link and added datasheet
  components/sensor/ms5611.rst
Labels: current

#5200 Add ESP32 Arduino to ESP-IDF migration guide
  guides/esp32_arduino_to_idf.rst
Labels: has-parent, next, component: esp32

#5206 2025.7.5
  Makefile
  _static/version
  changelog/2025.7.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#5203 [remote_transmitter] Add digital_write automation
  components/remote_transmitter.rst
  components/sx127x.rst
Labels: component: remote_transmitter, has-parent, next

#5192 Document multiple device address support in CLI commands
  guides/cli.rst
Labels: component: api, has-parent, next

#5208 Document max_notifications configuration option for esp32_ble component
  components/esp32_ble.rst
Labels: component: esp32_ble_tracker, has-parent, next, component: esp32_ble

#5201 [ld2410] Update docs for removal of ``throttle``, other clean-up
  components/sensor/ld2410.rst
Labels: has-parent, next, component: ld2410

#5209 Document esp32_ble advertising configuration option
  components/esp32_ble.rst
Labels: component: esp32_ble_beacon, has-parent, next, component: esp32_ble, component: esp32_ble_server

#5217 Remove mentions of rmt_channel from esp32_rmt_led_strip
  components/light/esp32_rmt_led_strip.rst
Labels: current

#5211 [switch] Add `switch.control` automation action
  components/switch/index.rst
Labels: component: switch, has-parent, next

#5197 [lvgl] Update lambda color usage
  components/lvgl/index.rst
Labels: has-parent, next

#5212 [switch] Add trigger `on_state`
  components/switch/index.rst
Labels: component: switch, has-parent, next

#5219 [esp32] Add IDF log_level option
  components/esp32.rst
Labels: has-parent, next, component: esp32, component: lvgl

#5213 [sensor] Extend timeout filter with option to return last value received
  components/sensor/sensor-filter-timeout.rst
Labels: component: sensor, has-parent, next

#5227 [ld2410] Fix typo
  components/sensor/ld2410.rst
Labels: next

#5224 raise log level for one component
  components/logger.rst
Labels: current

#5204 [host platform] add hint about firewall settings on local host computer
  components/host.rst
Labels: current

#5205 Update ld2450.rst - high perfromance typo fix
  components/sensor/ld2450.rst
Labels: current

#5193 Update globals.rst
  components/globals.rst
Labels: current

#5226 [ld2450] Update docs for removal of ``throttle``
  components/sensor/ld2450.rst
Labels: has-parent, next, component: ld2450

#4987 Update installing_esphome.rst to mention git for extern. components
  guides/installing_esphome.rst
Labels: current

#5218 Fix parameter names of touchscreen::TouchPoint
  components/touchscreen/index.rst
Labels: current

#5238 [remote_transmitter] add missing underline
  components/remote_transmitter.rst
Labels: current

#5265 Restore webapp in Ready Made Projects
  content/projects/_index.md
  static/projects/bluetooth-proxy/esp32_generic.png
  static/projects/bluetooth-proxy/gl-s10.png
  static/projects/bluetooth-proxy/header.png
  static/projects/bluetooth-proxy/lilygo-eth-poe.png
  static/projects/bluetooth-proxy/m5stack_atom_lite.png
  static/projects/bluetooth-proxy/olimex_esp32_poe_iso.png
  static/projects/bluetooth-proxy/wt32-eth01.png
  static/projects/empty/espressif.png
  static/projects/empty/pico-w.png
  static/projects/media-player/atom_echo.png
  static/projects/media-player/atom_speaker_kit.png
  static/projects/media-player/esp_muse_luxe.png
  static/projects/media-player/esp_muse_proto.png
  static/projects/voice-assistant/esp32-s3-box-3.png
  static/projects/voice-assistant/home-assistant-voice.png
  themes/esphome-theme/layouts/_default/projects.html
Labels: current

#5269 [guides/yaml] 4→2 space indent
  content/guides/yaml.md
Labels: current

#5266 [graph] Add missing documentation for legend feature
  content/components/graph.md
Labels: current

#5272 fix white on white text in getting-started-heading
  content/components/nrf52.md
  themes/esphome-theme/assets/css/main.css
  themes/esphome-theme/layouts/_default/baseof.html
Labels: current

#5278 Changes from user feedback
  content/components/_index.md
  content/components/light/monochromatic.md
  script/md_anchors.py
  themes/esphome-theme/layouts/shortcodes/imgtable.html
Labels: current

#5290 remove `throttle` from [ld2450] component config example
  content/components/sensor/ld2450.md
Labels: current

#5287 2025.8.1
  content/changelog/2025.8.0.md
  content/guides/supporters.md
  data/version.yaml
Labels: current

#5291 Update _index.md to mention nRF52
  content/_index.md
Labels: current

#5304 2025.8.2
  content/changelog/2025.8.0.md
  content/guides/supporters.md
  data/version.yaml
Labels: current

#5263 [lvgl] Document change in spinbox config
  content/components/lvgl/widgets.md
Labels: has-parent, next, component: lvgl

#5307 Add LVGL Hello image
  content/components/lvgl/_index.md
  content/images/lvgl-hello.png
Labels: has-parent, next, component: lvgl

#5276 [sntp]: document change in behaviour for ESP8266 and ESP32
  content/components/time/_index.md
  content/components/time/sntp.md
Labels: component: sntp, has-parent, next

#5305 Update wording on nrf support
  content/changelog/2025.8.0.md
Labels: current

#5117 [nrf52] dfu
  content/components/nrf52.md
Labels: has-parent, next, component: nrf52
