Repository esphome/esphome-docs, pull requests merged in 2025-03, with the labels that each got.

#4730 Restore lost items
  components/index.rst
Labels: next

#4729 2025.2.2
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4736 Fixes logo to embed light mode / dark mode within
  _static/custom.css
  _templates/search.html
  _templates/searchbox.html
  components/index.rst
  conf.py
  guides/contributing.rst
  images/index.rst
  images/logo-docs.svg
  images/logo-text.svg
  index.rst
  web-api/index.rst
Labels: current

#4698 allow touchscreen binary_sensor to use raw touch values
  components/touchscreen/index.rst
Labels: has-parent, next

#4740 [cst816] remove binary sensor config docs
  components/touchscreen/cst816.rst
  components/touchscreen/index.rst
Labels: has-parent, next

#4747 2025.3.0b1
  Doxygen
  Makefile
  _static/changelog-2025.3.0.png
  _static/custom.css
  _static/version
  _templates/search.html
  _templates/searchbox.html
  changelog/2025.3.0.rst
  changelog/index.rst
  components/climate/climate_ir.rst
  components/cover/images/tormatic.png
  components/cover/tormatic.rst
  components/display/ili9xxx.rst
  components/index.rst
  components/packages.rst
  components/remote_transmitter.rst
  components/sensor/images/ld2450.png
  components/sensor/images/mlx90393-resolution.svg
  components/sensor/images/msa311-full.jpg
  components/sensor/images/msa3xx-ui.png
  components/sensor/ld2450.rst
  components/sensor/ltr501.rst
  components/sensor/mlx90393.rst
  components/sensor/msa3xx.rst
  components/touchscreen/chsc6x.rst
  components/touchscreen/cst816.rst
  components/touchscreen/images/chsc6x.png
  components/touchscreen/index.rst
  conf.py
  guides/contributing.rst
  guides/supporters.rst
  images/chsc6x.png
  images/index.rst
  images/ld2450.png
  images/logo-docs.svg
  images/logo-text.svg
  images/msa301.jpg
  images/msa311.jpg
  images/tormatic.png
  index.rst
  web-api/index.rst
Labels: beta

#4752 2025.3.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  conf.py
Labels: beta

#4758 2025.3.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4763 2025.3.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4765 2025.3.0
  Doxygen
  Makefile
  _static/changelog-2025.3.0.png
  _static/version
  changelog/2025.3.0.rst
  changelog/index.rst
  components/climate/climate_ir.rst
  components/cover/images/tormatic.png
  components/cover/tormatic.rst
  components/display/ili9xxx.rst
  components/index.rst
  components/packages.rst
  components/remote_transmitter.rst
  components/sensor/images/ld2450.png
  components/sensor/images/mlx90393-resolution.svg
  components/sensor/images/msa311-full.jpg
  components/sensor/images/msa3xx-ui.png
  components/sensor/ld2450.rst
  components/sensor/ltr501.rst
  components/sensor/mlx90393.rst
  components/sensor/msa3xx.rst
  components/touchscreen/chsc6x.rst
  components/touchscreen/cst816.rst
  components/touchscreen/images/chsc6x.png
  components/touchscreen/index.rst
  conf.py
  guides/contributing.rst
  guides/supporters.rst
  images/chsc6x.png
  images/ld2450.png
  images/msa301.jpg
  images/msa311.jpg
  images/tormatic.png
Labels: current

#4741 [cli] Document new `--reset` and `--upload_speed` options
  components/logger.rst
  guides/cli.rst
Labels: has-parent, next

#4767 2025.3.1
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4766 [font] Update size and bpp docs
  components/font.rst
Labels: has-parent, next

#4772 2025.3.2
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  components/font.rst
  conf.py
  guides/supporters.rst
Labels: current

#4774 [esp32_can] update docs for can tx enqueue timeout
  components/canbus/esp32_can.rst
Labels: has-parent, next

#4641 [scheduler] document debug_scheduler flag
  components/esphome.rst
Labels: has-parent, next

#4776 [psram] Doc updates
  components/psram.rst
Labels: has-parent, next

#4785 2025.3.3
  Doxygen
  Makefile
  _static/version
  changelog/2025.3.0.rst
  conf.py
  guides/supporters.rst
Labels: current
