Repository esphome/esphome-docs, pull requests merged in 2025-07, with the labels that each got.

#5054 Document web_server OTA platform
  components/ota/index.rst
  components/ota/web_server.rst
  components/web_server.rst
Labels: has-parent, next

#5056 Delete unused Doxygen file
  Doxygen
Labels: current

#5057 2025.6.3
  Makefile
  _static/version
  changelog/2025.6.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4955 [Packet transport] Ping timeout sensor
  components/binary_sensor/packet_transport.rst
  components/packet_transport/index.rst
Labels: has-parent, next

#5058 Document batch_delay: 0 option for immediate state updates with IR remotes
  components/api.rst
  components/remote_receiver.rst
Labels: has-parent, next

#4278 [sx127x] Add sx127x component
  components/images/sx127x-full.png
  components/index.rst
  components/packet_transport/index.rst
  components/packet_transport/sx127x.rst
  components/sx127x.rst
  images/sx127x.png
Labels: has-parent, next

#5060 Add initial documentation for new camera platform
  components/camera/index.rst
  components/index.rst
Labels: has-parent, next

#5077 [nextion] Add optional device info storage configuration
  components/display/nextion.rst
Labels: has-parent, next

#5075 [nextion] Review `touch_sleep_timeout`
  components/display/nextion.rst
Labels: has-parent, next

#5072 Add note and links in BSEC2 section
  changelog/2025.6.0.rst
Labels: current

#5065 [image] Document `byte_order` config option
  components/image.rst
Labels: has-parent, next

#4340 lps22: add docs
  components/index.rst
  components/sensor/images/lps22.jpg
  components/sensor/lps22.rst
  images/lps22.jpg
Labels: has-parent, next, not-stale

#5092 2025.7.0b2
  .gitattributes
  Makefile
  _static/version
  changelog/2025.7.0.rst
  components/index.rst
  components/sensor/images/lps22.avif
  components/sensor/lps22.rst
  conf.py
  guides/supporters.rst
  images/lps22.avif
  lint.py
Labels: beta

#5101 [online_image] Document byte_order
  components/online_image.rst
Labels: has-parent, next

#5102 Enable website issues
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issues.yml
Labels: current

#5105 2025.7.0b5
  Makefile
  _static/version
  changelog/2025.7.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4111 nrf52 core based on zephyr
  components/index.rst
  components/nrf52.rst
  images/nrf52.svg
Labels: stale, has-parent, next

#4502 [adc] Use new library with ESP-IDF v5
  components/sensor/adc.rst
Labels: has-parent, next

#5091 Document custom_services configuration option for API component
  components/api.rst
Labels: has-parent, next

#5097 [adc] Add ESP32-C5 support
  components/sensor/adc.rst
Labels: has-parent, next

#5120 [CI] Delete check labels workflow
  .github/workflows/check-labels.yml
Labels: current

#5126 [CI] auto label - Use expression to get input
  .github/workflows/auto-label-pr.yml
Labels: current

#5132 [gpio] Document LibreTiny interrupt mode default behavior
  components/binary_sensor/gpio.rst
Labels: component: gpio, has-parent, next

#5135 2025.7.2
  Makefile
  _static/version
  changelog/2025.7.0.rst
  components/binary_sensor/gpio.rst
  conf.py
  guides/supporters.rst
Labels: current

#5143 [esp32_rmt] Improve rmt_symbols docs
  components/light/esp32_rmt_led_strip.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: current

#5141 [esp32_rmt_led_strip] Remove rmt_channel
  components/light/esp32_rmt_led_strip.rst
Labels: current

#5089 [sx127x] Update preamble_size docs
  components/sx127x.rst
Labels: current

#5137 [gpio] Update binary sensor docs for allow_other_uses interrupt handling
  components/binary_sensor/gpio.rst
Labels: has-parent, next

#5159 2025.7.3
  Makefile
  _static/version
  changelog/2025.7.0.rst
  components/binary_sensor/gpio.rst
  conf.py
  guides/supporters.rst
Labels: current

#5144 [remote_receiver] Fix idle time for newer ESP32 variants
  components/remote_receiver.rst
Labels: component: remote_receiver, has-parent, next

#5168 [esp32_camera] Fix broken external_component reference
  components/esp32_camera.rst
Labels: current

#5171 [mipi_spi] Docs for display driver
  components/display/mipi_dsi.rst
  components/index.rst
  images/tab5.jpg
Labels: has-parent, next, component: mipi_dsi, component: mipi, component: mipi_rgb

#5177 [api] Document homeassistant_states option
  components/api.rst
Labels: component: api, component: homeassistant, has-parent, next

#5181 Remove auto issue closing workflow job
  .github/workflows/stale.yml
Labels: current

#5178 [api] Add homeassistant_services configuration option
  components/api.rst
Labels: component: api, component: homeassistant, has-parent, next

#5183 2025.7.4
  Makefile
  _static/version
  changelog/2025.7.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4957 [output] Add `set_min_power` & `set_max_power` actions for `FloatOutput`
  components/output/index.rst
Labels: has-parent, next

#5162 [time] Document update interval
  components/time/index.rst
Labels: current
