Repository esphome/esphome-docs, pull requests merged in 2025-04, with the labels that each got.

#4636 Add documentation MCP4461 quad i2c digipot/rheostat component
  components/index.rst
  components/output/mcp4461.rst
  images/mcp4461.jpg
Labels: has-parent, next

#4791 Change Nabu Casa to Open Home Foundation
  CODE_OF_CONDUCT.md
  _templates/contact.html
  _templates/layout.html
  conf.py
  guides/faq.rst
  guides/made_for_esphome.rst
  guides/supporters.rst
Labels: current

#4739 Document BLE connection slot limits and options
  components/bluetooth_proxy.rst
  components/esp32_ble_tracker.rst
Labels: has-parent, next

#4803 [ble_server] Add entry in index.rst
  components/index.rst
Labels: current

#4797 [psram] Document use of experimental 120MHz octal mode
  components/esp32.rst
  components/psram.rst
Labels: has-parent, next

#4787 [lvgl] add `on_boot` docs.
  components/lvgl/index.rst
  components/lvgl/widgets.rst
Labels: has-parent, next

#4788 [lvgl] Update line widget docs
  components/lvgl/widgets.rst
Labels: has-parent, next

#4754 [spi] Document octal mode
  components/spi.rst
Labels: has-parent, next

#4807 [lvgl] Document lvgl.style.update
  components/lvgl/index.rst
Labels: has-parent, next

#4808 2025.4.0b1
  CODE_OF_CONDUCT.md
  Doxygen
  Makefile
  _static/version
  _templates/contact.html
  _templates/layout.html
  changelog/2025.4.0.rst
  changelog/index.rst
  components/bluetooth_proxy.rst
  components/canbus/esp32_can.rst
  components/esp32.rst
  components/esp32_ble_tracker.rst
  components/esphome.rst
  components/index.rst
  components/logger.rst
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/output/mcp4461.rst
  components/psram.rst
  components/spi.rst
  conf.py
  guides/cli.rst
  guides/faq.rst
  guides/made_for_esphome.rst
  guides/supporters.rst
  images/mcp4461.jpg
Labels: beta

#4790 [lvgl] document canvas widget
  components/lvgl/images/canvas.png
  components/lvgl/widgets.rst
Labels: has-parent, next

#4786 [lvgl] Document restore_value for select
  components/number/lvgl.rst
  components/select/lvgl.rst
Labels: has-parent, next

#4822 2025.4.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2025.4.0.rst
  components/lvgl/images/canvas.png
  components/lvgl/widgets.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4820 Fix typo
  components/sensor/smt100.rst
Labels: current

#4824 2025.4.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2025.4.0.rst
  components/sensor/smt100.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4829 2025.4.0
  Doxygen
  Makefile
  _static/changelog-2025.4.0.png
  _static/version
  changelog/2025.4.0.rst
  changelog/index.rst
  components/bluetooth_proxy.rst
  components/canbus/esp32_can.rst
  components/esp32.rst
  components/esp32_ble_tracker.rst
  components/esphome.rst
  components/index.rst
  components/logger.rst
  components/lvgl/images/canvas.png
  components/lvgl/index.rst
  components/lvgl/widgets.rst
  components/output/mcp4461.rst
  components/psram.rst
  components/spi.rst
  conf.py
  guides/cli.rst
  guides/supporters.rst
  images/mcp4461.jpg
Labels: current

#4668 [prometheus] Update docs with list of supported components
  components/prometheus.rst
Labels: has-parent, next, awaiting-parent

#4823 Update docs for optional API encryption key
  components/api.rst
Labels: has-parent, next

#4690 [esp32_rmt_led_strip] Add use_dma option for S3
  components/light/esp32_rmt_led_strip.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#4696 CUBIC PM2005/PM2105 Laser Particle Sensor Module
  components/index.rst
  components/sensor/images/pm2005.png
  components/sensor/pm2005.rst
  images/pm2005.png
Labels: has-parent, next

#4703 [uptime] Document text_sensor separator
  components/text_sensor/uptime.rst
Labels: has-parent, next

#4726 Document mapping component
  components/index.rst
  components/mapping.rst
  images/mapping.svg
Labels: has-parent, next

#4768 [analog_threshold] Document templatable thresholds
  components/binary_sensor/analog_threshold.rst
Labels: has-parent, next

#4831 Update 2025.4.0.rst
  changelog/2025.4.0.rst
Labels: current

#4826 Add a helpful nudge to set a `friendly_name`
  components/esphome.rst
Labels: current

#4677 Clarify LVGL widget update properties
  components/lvgl/widgets.rst
Labels: has-parent, next

#4654 http_request can get response headers
  components/http_request.rst
Labels: has-parent, next

#4835 [http_request] Add host platform docs
  components/http_request.rst
Labels: has-parent, next

#4836 Make certain MDNS config options templatable
  components/mdns.rst
Labels: has-parent, next

#4846 [ld2450] Copy fixes
  components/sensor/ld2450.rst
Labels: current

#4707 Update remote_receiver.rst, B&O Beo4 IR protocol added
  all_automations.json
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next, not-stale

#4851 Synchronise all_automations.json with latest dev
  all_automations.json
Labels: next

#4809 Update buffer size docs
  components/lvgl/index.rst
Labels: has-parent, next

#4311 Add documentation for Gobox protocol sending/receiving.
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#4638 Support for new i2s audio driver
  components/i2s_audio.rst
  components/microphone/i2s_audio.rst
  components/speaker/i2s_audio.rst
Labels: has-parent, next

#4715 add `ADC` pins for `ESP32-C2`, `ESP32-C6`, `ESP32-H2`
  components/sensor/adc.rst
Labels: has-parent, next

#4806 Restore link on logo in searchbar
  _templates/searchbox.html
Labels: current

#4789 Move sidebar logo into its own file
  _templates/_logo_svg.html
  _templates/searchbox.html
Labels: current

#4852 Make sidebar logo navigate to home or component index based on current page
  _templates/logo-components.html
  _templates/logo.html
  _templates/searchbox.html
  conf.py
Labels: current

#4848 [microphone] Document Microphone Source
  components/microphone/index.rst
Labels: has-parent, next

#4849 [micro_wake_word, voice_assistant] Use microphone source class
  components/micro_wake_word.rst
  components/voice_assistant.rst
Labels: has-parent, next

#4853 [i2s_audio] Document mclk_multiple and bits_per_sample vs bits_per_channel on IDF5 driver
  components/microphone/i2s_audio.rst
  components/speaker/i2s_audio.rst
Labels: has-parent, next

#4855 Rework home page
  _static/index.css
  _static/index.js
  index.rst
Labels: current

#4862 Add quick links near top, minor copy tweaks
  index.rst
Labels: current
