Repository esphome/esphome-docs, pull requests merged in 2025-09, with the labels that each got.

#5325 [schema-doc] Update parsing md for better doc extraction
  script/schema_doc.py
Labels: next

#5260 [mipi_rgb] Document new display driver
  content/components/_index.md
  content/components/display/_index.md
  content/components/display/ili9xxx.md
  content/components/display/mipi_rgb.md
  content/components/display/qspi_dbi.md
  content/components/display/rpi_dpi_rgb.md
  content/components/display/st7735.md
Labels: has-parent, next, component: mipi, component: mipi_rgb

#5319 [mcp2515] add section about limitations
  content/components/canbus/esp32_can.md
  content/components/canbus/mcp2515.md
Labels: current

#5329 [thermostat] Documentation updates for esphome/esphome#10561
  content/components/climate/thermostat.md
Labels: next

#5340 [bl0940] document new configuration options
  content/components/_index.md
  content/components/sensor/bl0940.md
  content/components/sensor/images/bl0940-cal.png
Labels: has-parent, next, component: bl0940

#5345 2025.8.4
  content/changelog/2025.8.0.md
  content/guides/supporters.md
  data/version.yaml
Labels: current

#5374 Update docs for Arduino as a Component
  content/components/esp32.md
  content/components/logger.md
  content/components/media_player/speaker.md
  content/guides/esp32_arduino_to_idf.md
Labels: has-parent, next

#5380 [zwave_proxy] Add docs
  content/components/_index.md
  content/components/images/z-wave.svg
  content/components/zwave_proxy.md
Labels: component: api, has-parent, next, component: zwave_proxy

#5385 [zwave_proxy] Copy fixes
  content/components/zwave_proxy.md
Labels: next

#5358 [ektf2232] Rename `rts_pin` to `reset_pin`
  content/components/touchscreen/ektf2232.md
Labels: has-parent, next, component: ektf2232

#5386 2025.9.1
  content/changelog/2025.9.0.md
  content/guides/supporters.md
  data/version.yaml
Labels: current

#5381 substitutions: Document !literal tag
  content/components/substitutions.md
Labels: component: substitutions, has-parent, next

#5352 [uart] Multiple ESP32 features and fixes
  content/components/uart.md
Labels: component: uart, has-parent, next

#5379 Remove Arduino-specific BLE limitations from documentation
  content/components/bluetooth_proxy.md
  content/components/esp32_ble.md
  content/components/esp32_ble_tracker.md
Labels: has-parent, next

#5375 Mapping: Fix typo
  content/components/mapping.md
Labels: current

#5366 [deep_sleep] removed extra spaces
  content/components/deep_sleep.md
Labels: current

#5356 [binary_sensor] Remove deprecated config item `publish_initial_state`
  content/components/binary_sensor/_index.md
Labels: current

#5364 Update sx126x.md - Minor typo, heirachy of heading
  content/components/sx126x.md
Labels: current

#5344 ld2420 max_gate_distance description
  content/components/sensor/ld2420.md
Labels: current

#5295 Remove redundant newlines in documentation
  content/components/display/st7701s.md
Labels: current

#5391 [deep_sleep] Update possible modes for esp32_ext1_wakeup
  content/components/deep_sleep.md
Labels: current

#5365 Update debug.md - remove logger level debug, add note about monitorin…
  content/components/debug.md
Labels: wrong-base-branch, component: debug, has-parent, current

#5402 Fix some HA "my" buttons
  content/components/api.md
  content/guides/getting_started_hassio.md
Labels: current

#5403 Remove button shortcode
  README.md
  script/convert_rst_to_md.py
  themes/esphome-theme/layouts/shortcodes/button.html
Labels: current

#5405 Lint script
  script/convert_rst_to_md.py
Labels: current

#5408 Fix footer discord link
  hugo.yaml
Labels: current

#5430 Auto generate "all changelogs" list
  content/changelog/2021.10.0.md
  content/changelog/2021.11.0.md
  content/changelog/2021.12.0.md
  content/changelog/2021.8.0.md
  content/changelog/2021.9.0.md
  content/changelog/2022.1.0.md
  content/changelog/2022.10.0.md
  content/changelog/2022.11.0.md
  content/changelog/2022.12.0.md
  content/changelog/2022.2.0.md
  content/changelog/2022.3.0.md
  content/changelog/2022.4.0.md
  content/changelog/2022.5.0.md
  content/changelog/2022.6.0.md
  content/changelog/2022.8.0.md
  content/changelog/2022.9.0.md
  content/changelog/2023.10.0.md
  content/changelog/2023.11.0.md
  content/changelog/2023.12.0.md
  content/changelog/2023.2.0.md
  content/changelog/2023.3.0.md
  content/changelog/2023.4.0.md
  content/changelog/2023.5.0.md
  content/changelog/2023.6.0.md
  content/changelog/2023.7.0.md
  content/changelog/2023.8.0.md
  content/changelog/2023.9.0.md
  content/changelog/2024.10.0.md
  content/changelog/2024.11.0.md
  content/changelog/2024.12.0.md
  content/changelog/2024.2.0.md
  content/changelog/2024.3.0.md
  content/changelog/2024.4.0.md
  content/changelog/2024.5.0.md
  content/changelog/2024.6.0.md
  content/changelog/2024.7.0.md
  content/changelog/2024.8.0.md
  content/changelog/2024.9.0.md
  content/changelog/2025.2.0.md
  content/changelog/2025.3.0.md
  content/changelog/2025.4.0.md
  content/changelog/2025.5.0.md
  content/changelog/2025.6.0.md
  content/changelog/2025.7.0.md
  content/changelog/2025.8.0.md
  content/changelog/2025.9.0.md
  content/changelog/v1.10.0.md
  content/changelog/v1.11.0.md
  content/changelog/v1.12.0.md
  content/changelog/v1.13.0.md
  content/changelog/v1.14.0.md
  content/changelog/v1.15.0.md
  content/changelog/v1.16.0.md
  content/changelog/v1.17.0.md
  content/changelog/v1.18.0.md
  content/changelog/v1.19.0.md
  content/changelog/v1.20.0.md
  content/changelog/v1.8.0.md
  content/changelog/v1.9.0.md
  themes/esphome-theme/layouts/shortcodes/changelogs.html
Labels: current

#5398 Ethernet fixed mac
  content/components/ethernet.md
Labels: next

#5424 [sx126x] Add additional FSK CRC options
  content/components/sx126x.md
Labels: has-parent, next, component: sx126x

#5432 Add sample code snippet for MEMS Microphone ICS-43434
  content/components/microphone/i2s_audio.md
Labels: current
