Repository esphome/esphome-docs, pull requests merged in 2025-02, with the labels that each got.

#4611 feat(core): Add support for <...> includes
  components/esphome.rst
Labels: has-parent, next

#4628 [resampler] Media Player Components Docs PR1
  components/speaker/resampler.rst
  images/waveform.svg
  index.rst
Labels: has-parent, next

#4639 [lvgl] Document swipe gestures
  components/lvgl/widgets.rst
Labels: has-parent, next

#4640 Add xxtea docs
  components/xxtea.rst
  images/xxtea.svg
  index.rst
Labels: has-parent, next

#4642 Preferences update docs
  components/esphome.rst
Labels: has-parent, next

#4435 Update manual for uponor_smatrix component (esphome#7745)
  components/uponor_smatrix.rst
Labels: has-parent, next

#4644 Add docs for SDL binary sensor
  components/binary_sensor/sdl.rst
  components/display/sdl.rst
  index.rst
Labels: has-parent, next

#4633 Add documentation for Toto remote transmitter/receiver protocol
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: has-parent, next

#4518 Fix example: wrong pin for the S3 Box 3 and specify channel
  components/audio_dac/es8311.rst
Labels: current

#4629 [mixer] Media Player Components Docs PR2
  automations/all_actions.rst
  components/speaker/mixer.rst
  images/mixer.svg
  index.rst
Labels: has-parent, next

#4649 Document logger changes
  components/logger.rst
  components/select/logger.rst
Labels: has-parent, next

#4601 add adc/sampling_mode doc
  components/sensor/adc.rst
Labels: has-parent, next

#4630 [speaker] Media Player Components Docs PR3
  automations/all_actions.rst
  components/media_player/index.rst
  components/media_player/speaker.rst
  index.rst
Labels: has-parent, next

#4627 add partial update of GDEW029T5 e-paper display
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4428 Added Waveshare e-paper display model "7.50inv2p" to the waveshare_epaper component.
  components/display/waveshare_epaper.rst
Labels: stale, has-parent, next

#4529 added Waveshare BWR Mode for the 4.2in Display
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4617 [online_image] Document JPEG support
  components/online_image.rst
Labels: has-parent, next

#4493 Add GDEY029T94 support
  components/display/waveshare_epaper.rst
Labels: stale, has-parent, next

#4574 GDEY042T81 e-paper displays support
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#3806 Adding doc for the Waveshare 7.3" ACeP 7-Color display
  components/display/images/waveshare_epaper_7color_acep-full.jpg
  components/display/waveshare_epaper.rst
Labels: has-parent, next

#4530 Add sphinx_copybutton to code-blocks
  conf.py
  requirements.txt
Labels: current

#4662 Add changelog text
  changelog/2025.2.0.rst
Labels: next

#4665 2025.2.0b2
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  conf.py
  guides/supporters.rst
  requirements.txt
Labels: beta

#4664 Add note about not using ``sstream``
  guides/contributing.rst
Labels: next

#4552 Update esp32_dac.rst
  components/output/esp32_dac.rst
Labels: has-parent, next

#4634 [esp32_rmt] Enable pullup and od mode based on pin scheme
  components/remote_transmitter.rst
Labels: has-parent, next

#4666 bme280 Documentation correction
  components/sensor/bme280.rst
Labels: current

#4667 2025.2.0b3
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  components/output/esp32_dac.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4615 Fix typo in max17043.rst added "out"
  components/sensor/max17043.rst
Labels: current

#4660 Fix rtttl component documentation typo
  components/rtttl.rst
Labels: current

#4658 [speaker] Document enqueue parameter and add a troubleshooting section
  components/media_player/speaker.rst
Labels: has-parent, next

#4670 Add wire color codes for RJ45 to pylontech.rst
  components/pylontech.rst
Labels: current

#4653 Fixes broken links on the remote_receiver page
  components/remote_receiver.rst
Labels: current

#4650 Fixed typo in nextion.rst
  components/display/nextion.rst
Labels: current

#4646 Removed duplicate pm10 from Panasonic SN-GCJA5 Particulate Matter Sensor
  components/sensor/gcja5.rst
Labels: current

#4556 Update xl9535.rst - fixed dead datasheet link
  components/xl9535.rst
Labels: current

#4635 add `rmt_channel` options for C6 and H2
  components/light/esp32_rmt_led_strip.rst
  components/remote_receiver.rst
  components/remote_transmitter.rst
Labels: current

#4669 Add tests section to contributing guide
  guides/contributing.rst
Labels: current

#4657 Add arg to strftime in TM1637
  components/display/tm1637.rst
Labels: current

#4637 add avialiable range to measurement interval of SCD30
  components/sensor/scd30.rst
Labels: has-parent, next

#4673 Add pullup resistor documentation for DHT component
  components/sensor/dht.rst
Labels: has-parent, next, awaiting-parent

#4676 2025.2.0b4
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  components/remote_transmitter.rst
  components/sensor/dht.rst
  components/sensor/scd30.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4674 Add link to 'the existing code' for mpu6050
  components/sensor/mpu6050.rst
Labels: current

#4678 DateTime fix typo in lambda example
  components/datetime/index.rst
Labels: current

#4680 Updated SCD40/41 data sheet
  components/sensor/scd4x.rst
Labels: current

#4682 2025.2.0b5
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  components/datetime/index.rst
  components/sensor/mpu6050.rst
  components/sensor/scd4x.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4683 Update default frame interval for Toto infrared protocol
  components/remote_transmitter.rst
Labels: has-parent, next, awaiting-parent

#4684 2025.2.0b6
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  conf.py
  guides/supporters.rst
Labels: beta

#4681 Updated platformio to pioarduino in esp32.rst
  components/esp32.rst
Labels: current

#3327 Add ld2450 document
  components/sensor/images/ld2450.png
  components/sensor/ld2450.rst
  images/ld2450.png
  index.rst
Labels: has-parent, next

#4691 Clarified the correct model for Pimoroni Badger in waveshare_epaper.rst
  components/display/waveshare_epaper.rst
Labels: current

#4692 Remove removed old-style options.
  components/esphome.rst
Labels: current

#4695 Update sprinkler.rst to new style esp32 platform
  components/sprinkler.rst
Labels: current

#4699 [il9xxx] Add notes about psram and 8 bit changes
  changelog/2025.2.0.rst
  components/display/ili9xxx.rst
Labels: current

#4693 More details for ARMv7
  changelog/2025.2.0.rst
Labels: current

#4701 [image] Add missing option and clarify transparency
  changelog/2025.2.0.rst
  components/image.rst
Labels: current

#4702 Add GC9D01N model to ili9xxx
  components/display/ili9xxx.rst
Labels: has-parent, next

#4700 Adding documentation about chsc6x touch screen controller
  components/touchscreen/chsc6x.rst
  components/touchscreen/images/chsc6x.png
  images/chsc6x.png
  index.rst
Labels: has-parent, next

#4713 2025.2.1
  Doxygen
  Makefile
  _static/version
  changelog/2025.2.0.rst
  conf.py
  guides/supporters.rst
Labels: current

#4706 Move docs off of main page
  components/index.rst
  guides/contributing.rst
  images/xiaomi_lywsd03mmc.jpg
  index.rst
Labels: current

#4718 Update PR template to match new table location
  .github/PULL_REQUEST_TEMPLATE.md
Labels: current

#4716 Update PR template to move code PR to new line
  .github/PULL_REQUEST_TEMPLATE.md
Labels: current

#4719 Remove sidebar from homepage
  conf.py
Labels: current

#4722 Adding protocol Panasonic EKE from arduino-heatpumpir 1.0.32 in climate_ir
  components/climate/climate_ir.rst
Labels: has-parent, next

#3865 MSA311 and MSA301 accelerometer supportmsa3xx
  components/index.rst
  components/sensor/images/msa311-full.jpg
  components/sensor/images/msa3xx-ui.png
  components/sensor/msa3xx.rst
  images/msa301.jpg
  images/msa311.jpg
Labels: stale, has-parent, next

#4353 [mlx90393] Fix default values, gain and resolution settings
  components/sensor/images/mlx90393-resolution.svg
  components/sensor/mlx90393.rst
Labels: has-parent, next

#3458 Document new component for Tormatic/Novoferm garage door drives
  components/cover/images/tormatic.png
  components/cover/tormatic.rst
  components/index.rst
  images/tormatic.png
Labels: has-parent, next, not-stale
